Repository woocommerce/woocommerce-admin, pull requests merged in 2018-08, with the labels that each got.

#251 Update/table component
  client/analytics/report/mock-data.js
  client/analytics/report/revenue.js
  client/components/table/README.md
  client/components/table/index.js
  client/components/table/style.scss
  client/components/table/summary.js
  client/components/table/table.js
  client/stylesheets/_variables.scss
Labels: Analytics, [Status] Ready to Merge

#267 Fix for gutenberg 3.4
  client/dashboard/store-performance/index.js
  client/layout/activity-panel/panels/orders.js
  client/layout/header/index.js
  lib/client-assets.php
  package-lock.json
Labels: [Status] Needs Review

#253 Pagination: Fix page input bug.
  client/components/pagination/index.js
Labels: Analytics, [Status] Needs Review

#249 add theming to Gutenberg components'
  client/components/dropdown-button/style.scss
  client/stylesheets/_gutenberg-components.scss
  client/stylesheets/_mixins.scss
  client/stylesheets/_variables.scss
  client/stylesheets/_wpadmin-reset.scss
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
Labels: [Status] Ready to Merge

#274 Move non-reset SCSS to new files, add folder structure
  client/embedded.js
  client/index.js
  client/layout/activity-panel/style.scss
  client/stylesheets/README.md
  client/stylesheets/_embedded.scss
  client/stylesheets/_index.scss
  client/stylesheets/_wpadmin-reset.scss
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_global.scss
  client/stylesheets/shared/_gutenberg-components.scss
  client/stylesheets/shared/_reset.scss
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#275 Table: Add "required"/"sortable" meta to headers/columns
  client/analytics/report/revenue.js
  client/components/table/README.md
  client/components/table/index.js
  client/components/table/table.js
Labels: Analytics, Components, [Status] Ready to Merge

#278 Fix warning: update compose import
  client/analytics/report/orders/index.js
Labels: [Status] Ready to Merge, [Type] Bug

#281 Orders Panel: Add default prop object.
  client/layout/activity-panel/panels/orders.js
Labels: [Status] Needs Review, [Type] Bug

#280 Header: Set z-index greater than popover
  client/layout/header/style.scss
Labels: [Status] Needs Review, [Type] Bug

#279 Overview: Add Columns
  client/dashboard/index.js
  client/dashboard/style.scss
Labels: Dashboard

#282 Layout: Add the 40px side gutters on 1100px+ screens
  client/dashboard/style.scss
  client/layout/header/style.scss
  client/layout/style.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_global.scss
Labels: [Status] Ready to Merge

#270 D3 Chart Component: split example and index
  client/components/chart/charts.js
  client/components/chart/d3-base/index.js
  client/components/chart/example.js
  client/components/chart/index.js
  client/components/chart/legend.js
  client/components/chart/style.scss
  client/components/chart/test/utils.js
  client/components/chart/utils.js
  client/dashboard/index.js
  client/stylesheets/abstracts/_variables.scss
  package-lock.json
Labels: Analytics, Dashboard, [Status] Needs Review

#288 SummaryNumber: Update style of dropdown on smaller screens
  client/components/summary/index.js
  client/components/summary/item.js
  client/components/summary/style.scss
Labels: Components, [Status] Ready to Merge

#289 Table: Update style to match design
  client/analytics/report/revenue.js
  client/components/filter-picker/style.scss
  client/components/table/README.md
  client/components/table/style.scss
  client/components/table/table.js
  client/stylesheets/shared/_global.scss
Labels: Components, [Status] Ready to Merge

#296 Fix Column Toggle Error
  client/components/table/table.js
Labels: [Status] Needs Review

#293 Add Revenue Report API/data-layer
  client/lib/nav-utils/index.js
  client/store/constants.js
  client/store/index.js
  client/store/reports/index.js
  client/store/reports/revenue/index.js
  client/store/reports/revenue/stats/actions.js
  client/store/reports/revenue/stats/index.js
  client/store/reports/revenue/stats/reducer.js
  client/store/reports/revenue/stats/resolvers.js
  client/store/reports/revenue/stats/selectors.js
  client/store/reports/revenue/stats/test/reducer.js
  client/store/reports/revenue/stats/test/resolvers.js
  client/store/reports/revenue/stats/test/selectors.js
  package-lock.json
  package.json
Labels: [Tests] Includes Tests

#300 Table Component: Apply scope only to the row headers
  client/components/table/table.js
Labels: Accessibility, Components, [Status] Ready to Merge

#303 Dashboard: Use isNumeric in Top Selling Products.
  client/dashboard/top-selling-products/index.js
Labels: Dashboard, [Status] Needs Review

#304 Analytics: Add Chart to Revenue Report
  client/analytics/report/revenue/data.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/mock-data.js
Labels: Analytics

#297 Components: Export reusable components to a separate file + global
  client/analytics/report/example.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/index.js
  client/components/README.md
  client/components/card/index.js
  client/components/chart/example.js
  client/components/filters/date/content.js
  client/components/filters/date/index.js
  client/components/filters/filter/index.js
  client/components/index.js
  client/components/rating/index.js
  client/components/rating/product.js
  client/components/rating/review.js
  client/components/rating/test/index.js
  client/dashboard/index.js
  client/dashboard/store-performance/index.js
  client/dashboard/top-selling-products/index.js
  client/index.js
  client/layout/activity-panel/activity-card/test/index.js
  client/layout/activity-panel/activity-header/index.js
  client/layout/activity-panel/activity-outbound-link/index.js
  client/layout/activity-panel/panels/orders.js
  client/layout/activity-panel/panels/reviews.js
  client/layout/header/index.js
  lib/client-assets.php
  tests/js/jest.config.json
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, Components, [Status] Ready to Merge

#298 Extensions: Add filter to allow third-party registration of reports
  client/analytics/report/README.md
  client/analytics/report/example.js
  client/analytics/report/index.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/index.js
  lib/admin.php
Labels: Build, Extensibility, [Status] Ready to Merge

#306 Revenue Report: Use href on SummaryNumber components.
  client/analytics/report/revenue/index.js
Labels: Analytics, [Status] Ready to Merge

#309 Remove apiRequest in favor of apiFetch
  client/store/orders/actions.js
  client/store/orders/resolvers.js
  client/store/reports/revenue/stats/resolvers.js
  package-lock.json
  package.json
  webpack.config.js
Labels: [Status] Ready to Merge

#308 Filters: Add path & query back to filter props
  client/components/filters/README.md
  client/components/filters/advanced/README.md
  client/components/filters/advanced/index.js
  client/components/filters/date/README.md
  client/components/filters/date/index.js
  client/components/filters/filter/README.md
  client/components/filters/filter/index.js
  client/components/filters/index.js
  client/lib/nav-utils/index.js
Labels: [Status] Ready to Merge

#314 Updated dropdown button styles
  client/components/dropdown-button/style.scss
Labels: Design, [Status] Needs Review

#307 Store: Add generic reports stats support.
  client/store/reports/index.js
  client/store/reports/stats/actions.js
  client/store/reports/stats/index.js
  client/store/reports/stats/reducer.js
  client/store/reports/stats/resolvers.js
  client/store/reports/stats/selectors.js
  client/store/reports/stats/test/reducer.js
  client/store/reports/stats/test/resolvers.js
  client/store/reports/stats/test/selectors.js
  client/store/util.js
Labels: Analytics, [Status] Needs Review

#313 Fix the summaryNumber display when in toggle-button state
  client/components/summary/style.scss
Labels: [Status] Ready to Merge

#317 Animation mixin + add `prefers-reduced-motion` support to existing animations
  client/components/animation-slider/style.scss
  client/components/dropdown-button/style.scss
  client/components/summary/style.scss
  client/stylesheets/abstracts/_mixins.scss
Labels: Accessibility, [Status] Ready to Merge

#318 Updates to presets / custom toggle and segmented selection
  client/components/filters/date/style.scss
  client/components/segmented-selection/style.scss
  client/stylesheets/abstracts/_variables.scss
Labels: Design, [Status] Ready to Merge

#321 Store: Add product API + state handlers
  client/store/index.js
  client/store/products/actions.js
  client/store/products/index.js
  client/store/products/reducer.js
  client/store/products/resolvers.js
  client/store/products/selectors.js
  client/store/products/test/reducer.js
  client/store/products/test/resolvers.js
  client/store/products/test/selectors.js
  client/store/util.js
Labels: [Status] Ready to Merge

#322 Components: Add a search component based on Autocomplete
  client/analytics/index.js
  client/components/index.js
  client/components/search/README.md
  client/components/search/autocomplete.js
  client/components/search/autocompleters/index.js
  client/components/search/autocompleters/product.js
  client/components/search/index.js
  client/components/search/style.scss
  client/components/tag/README.md
  client/components/tag/index.js
  client/components/tag/style.scss
Labels: Components, [Status] Ready to Merge

#323 Connect TopSellingProducts with the API
  client/dashboard/top-selling-products/__mocks__/mock-data.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
  client/store/reports/stats/resolvers.js
Labels: Dashboard, [Status] Ready to Merge, [Tests] Includes Tests

#327 Segmented-selection: remove focus outline in favor of inset box-shadow
  client/components/filters/date/index.js
  client/components/segmented-selection/style.scss
Labels: [Status] Needs Review

#324 DaptePicker: fix erorr message popover
  client/components/calendar/style.scss
  client/components/filters/date/style.scss
Labels: [Status] Ready to Merge

#325 DatePicker: Fix Error message positioning on non-mobile widths
  client/components/filters/date/style.scss
Labels: [Status] Ready to Merge

#332 updating datepicker styles
  client/components/calendar/style.scss
  client/components/filters/style.scss
Labels: Design, [Status] Needs Review

#338 Create TablePlaceholder component to be used when table contents are loading
  client/components/index.js
  client/components/table/README.md
  client/components/table/index.js
  client/components/table/placeholder.js
  client/components/table/style.scss
  client/components/table/table.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
Labels: Dashboard, [Status] Needs Review

#335 Update Card Component Styles on Mobile
  client/components/card/style.scss
Labels: Design, [Status] Needs Review

#334 Docs Project: Component cleanup
  client/components/calendar/README.md
  client/components/calendar/index.js
  client/components/card/index.js
  client/components/ellipsis-menu/README.md
  client/components/ellipsis-menu/index.js
  client/components/filters/date/content.js
  client/components/filters/index.js
  client/components/index.js
  client/components/summary/README.md
  client/components/summary/index.js
  client/components/table/index.js
  client/lib/proptype-validator.js
Labels: Documentation, [Status] Ready to Merge

#336 Docs Project: Add documentation parser + inline documentation
  .eslintignore
  bin/generate-docs/index.js
  bin/generate-docs/lib/file-system.js
  bin/generate-docs/lib/formatting.js
  client/components/animation-slider/index.js
  client/components/calendar/index.js
  client/components/card/index.js
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/legend.js
  client/components/count/index.js
  client/components/dropdown-button/index.js
  client/components/ellipsis-menu/index.js
  client/components/ellipsis-menu/menu-item.js
  client/components/ellipsis-menu/menu-title.js
  client/components/filters/advanced/index.js
  client/components/filters/date/index.js
  client/components/filters/filter/index.js
  client/components/filters/index.js
  client/components/flag/index.js
  client/components/gravatar/README.md
  client/components/gravatar/index.js
  client/components/index.js
  client/components/link/index.js
  client/components/order-status/index.js
  client/components/pagination/index.js
  client/components/product-image/index.js
  client/components/rating/index.js
  client/components/rating/product.js
  client/components/rating/review.js
  client/components/search/index.js
  client/components/segmented-selection/index.js
  client/components/split-button/index.js
  client/components/summary/index.js
  client/components/summary/item.js
  client/components/table/index.js
  client/components/table/summary.js
  client/components/table/table.js
  client/components/tag/index.js
  package-lock.json
  package.json
Labels: Documentation, [Status] Needs Review

#337 Docs Project: Add markdown files, docsify to render site
  bin/generate-docs/index.js
  bin/generate-docs/lib/formatting.js
  docs/.nojekyll
  docs/README.md
  docs/_sidebar.md
  docs/components/animation-slider.md
  docs/components/calendar.md
  docs/components/card.md
  docs/components/chart.md
  docs/components/count.md
  docs/components/dropdown-button.md
  docs/components/ellipsis-menu.md
  docs/components/filters.md
  docs/components/flag.md
  docs/components/gravatar.md
  docs/components/link.md
  docs/components/order-status.md
  docs/components/pagination.md
  docs/components/product-image.md
  docs/components/rating.md
  docs/components/search.md
  docs/components/segmented-selection.md
  docs/components/split-button.md
  docs/components/summary.md
  docs/components/table.md
  docs/components/tag.md
  docs/index.html
  package-lock.json
  package.json
Labels: Documentation, [Status] Ready to Merge
