Repository woocommerce/woocommerce-admin, pull requests merged in 2018-11, with the labels that each got.

#731 Fix charts redirecting to previous path when changing interval value
  client/analytics/components/report-chart/index.js
  client/analytics/report/orders/chart.js
  client/analytics/report/orders/config.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/chart.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/chart.js
  client/analytics/report/revenue/index.js
  client/components/chart/index.js
Labels: Analytics, Components, [Status] Ready to Merge

#741 Adds Jest Snapshot update command
  package.json
Labels: [Status] Ready to Merge

#752 IE11: Fix table header actions layout
  client/components/table/style.scss
Labels: Components, [Status] Ready to Merge

#750 Add error message to Top Selling Products table
  client/analytics/components/report-error/index.js
  client/components/empty-content/index.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/style.scss
Labels: Components, Dashboard, [Status] Ready to Merge

#748 Add markdown docs with details on contributing
  CONTRIBUTING.md
  README.md
Labels: [Status] Ready to Merge

#733 Makes stylelint config match prettier settings
  .stylelintrc.json
  client/components/card/style.scss
  client/components/chart/style.scss
  client/components/table/style.scss
  client/header/activity-panel/style.scss
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_variables.scss
Labels: [Status] Ready to Merge

#747 Run dbdelta on init, at least as long as this is a separate plugin
  wc-admin.php
Labels: [Status] Ready to Merge

#761 Switch to using `@wordpress/viewport` for responsive screen layouts
  client/components/calendar/index.js
  client/components/chart/utils.js
  client/components/filters/style.scss
  client/components/summary/index.js
  client/components/summary/placeholder.js
  client/components/summary/style.scss
  client/components/table/style.scss
  client/dashboard/style.scss
  client/devdocs/style.scss
  client/header/activity-panel/style.scss
  client/header/style.scss
  client/layout/style.scss
  client/lib/ui.js
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_global.scss
  package-lock.json
  package.json
Labels: [Status] Ready to Merge, [Type] Try

#755 Build: Switch react imports to use core packages
  client/components/section-header/test/index.js
  client/components/table/download-icon.js
  client/header/index.js
  client/store/index.js
  client/store/reports/index.js
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#735 Adds css linting to the main lint command to be run in ci
  package.json
Labels: [Status] Ready to Merge

#759 Persist time queries when clicking on breadcrumbs links
  client/header/index.js
  client/lib/nav-utils/index.js
  client/lib/nav-utils/test/index.js
Labels: Analytics, [Status] Ready to Merge

#773 Do not attempt to run table setup without dependency check first
  wc-admin.php
Labels: [Status] Needs Review

#768 Add command to build release zip
  bin/build-plugin-zip.sh
  package.json
Labels: [Status] Ready to Merge

#763 Build: Move `lib/nav-utils` and `lib/history` to `@woocommerce/navigation`
  client/analytics/components/report-error/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/table.js
  client/components/chart/index.js
  client/components/filters/advanced/index.js
  client/components/filters/compare/index.js
  client/components/filters/date/index.js
  client/components/filters/filter/index.js
  client/components/link/index.js
  client/components/search/autocompleters/coupons.js
  client/components/search/autocompleters/product-cat.js
  client/components/search/autocompleters/product.js
  client/components/table/index.js
  client/dashboard/top-selling-products/index.js
  client/header/index.js
  client/layout/controller.js
  client/layout/index.js
  client/lib/async-requests/index.js
  client/lib/nav-utils/README.md
  client/store/notes/resolvers.js
  client/store/orders/resolvers.js
  client/store/reports/stats/resolvers.js
  lib/client-assets.php
  package.json
  packages/navigation/.npmrc
  packages/navigation/README.md
  packages/navigation/package.json
  packages/navigation/src/history.js
  packages/navigation/src/index.js
  packages/navigation/src/test/index.js
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, [Status] Needs Review

#782 i18n: Inject translations when the i18n lib is included
  lib/client-assets.php
Labels: Build, [Status] Needs Review

#742 Add/variations autocompleter
  client/analytics/report/products/config.js
  client/components/filters/advanced/index.js
  client/components/filters/advanced/search-filter.js
  client/components/filters/compare/index.js
  client/components/filters/filter/index.js
  client/components/search/autocompleters/index.js
  client/components/search/autocompleters/variations.js
  client/components/search/index.js
  client/lib/async-requests/index.js
  package-lock.json
Labels: [Status] Needs Review

#783 Update @wordpress/data for 3.x
  client/store/notes/resolvers.js
  client/store/notes/test/resolvers.js
  client/store/orders/resolvers.js
  client/store/orders/test/resolvers.js
  client/store/products/resolvers.js
  client/store/products/test/resolvers.js
  client/store/reports/stats/resolvers.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#753 Extensibility: Add activity panel inbox tutorial
  docs/_sidebar.md
  docs/examples/README.md
  docs/examples/_sidebar.md
  docs/examples/activity-panel-inbox.md
  docs/examples/images/activity-panel-inbox.png
  docs/examples/images/activity-panel-store-alerts.png
Labels: [Status] Ready to Merge

#756 Build: Move `lib/csv` to packages
  client/components/table/index.js
  client/components/table/test/index.js
  lib/client-assets.php
  package.json
  packages/csv-export/.npmrc
  packages/csv-export/README.md
  packages/csv-export/package.json
  packages/csv-export/src/__mocks__/mock-csv-data.js
  packages/csv-export/src/__mocks__/mock-headers.js
  packages/csv-export/src/__mocks__/mock-rows.js
  packages/csv-export/src/index.js
  packages/csv-export/src/test/index.js
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#693 Activity Panel: Inbox: Add Woo Extension Subscription / Connection Notes
  includes/class-wc-admin-note.php
  includes/class-wc-admin-notes-new-sales-record.php
  includes/class-wc-admin-notes-woo-subscriptions-notes.php
  includes/data-stores/class-wc-admin-notes-data-store.php
  wc-admin.php
Labels: [Status] Ready to Merge

#793 Moves charts to config to delete chart.js
  client/analytics/report/orders/chart.js
  client/analytics/report/orders/config.js
  client/analytics/report/orders/index.js
Labels: [Status] Needs Review

#794 Creates a helper function to get selected chart
  client/analytics/report/orders/index.js
  client/lib/get-selected-chart/index.js
Labels: [Status] Needs Review

#774 Allow WC-Admin to activate on WP 5 without Gutenberg plugin active
  README.md
  lib/client-assets.php
  wc-admin.php
Labels: [Status] Ready to Merge

#798 Updates docs
  docs/components/search.md
Labels: [Status] Ready to Merge

#803 Build: Move filter code to the navigation package
  client/components/filters/advanced/index.js
  client/components/filters/advanced/select-filter.js
  client/components/filters/filter/index.js
  client/components/filters/filter/utils.js
  client/store/reports/utils.js
  packages/navigation/README.md
  packages/navigation/src/filters.js
  packages/navigation/src/index.js
  packages/navigation/src/test/filters.js
Labels: Build, [Status] Ready to Merge

#817 Update table gradient code to be more similar to chart legend gradient code
  client/components/table/style.scss
  client/components/table/table.js
Labels: Components, [Status] Ready to Merge

#816 Update comparison chart design and show it on the Product report
  client/analytics/components/report-chart/index.js
  client/analytics/report/products/index.js
  client/components/chart/index.js
  client/components/chart/legend.js
  client/components/chart/legend.scss
  client/components/chart/style.scss
  client/components/chart/test/legend.js
Labels: Analytics, Components, [Status] Needs Design Review, [Status] Needs Review

#821 Adds Card Snapshot
  client/components/card/test/__snapshots__/index.js.snap
  client/components/card/test/index.js
Labels: [Status] Needs Review

#819 Add snapshotting to Animation Slider
  client/components/animation-slider/test/__snapshots__/index.js.snap
  client/components/animation-slider/test/index.js
Labels: [Status] Needs Review

#820 Remove unneeded leading whitespace
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#785 Component - chart: more than 9 weeks of ticks change xFormat to months & x2Format to yrs
  client/components/chart/utils.js
  packages/date/src/index.js
Labels: Analytics, Components, Dashboard, [Status] Needs Design Review, [Status] Ready to Merge

#830 Adds a test snapshot for count
  client/components/count/test/__snapshots__/index.js.snap
  client/components/count/test/index.js
Labels: [Status] Needs Review

#832 Add image to variations autocompleter
  client/components/product-image/index.js
  client/components/product-image/test/__snapshots__/index.js.snap
  client/components/product-image/test/index.js
  client/components/search/autocompleters/variations.js
  docs/components/product-image.md
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#823 Apply onQueryChange to more than just 'filter'
  client/analytics/report/products/config.js
  client/analytics/report/products/table.js
  client/components/table/index.js
  package-lock.json
  packages/navigation/src/index.js
Labels: [Status] Ready to Merge

#808 Remove the SCRIPT_DEBUG:true requirement
  README.md
  wc-admin.php
Labels: [Status] Ready to Merge

#758 PHPUnit testing improvements
  .travis.yml
  bin/install-wp-tests.sh
  bin/js_lint_test.sh
  bin/phpcs.sh
  bin/phpunit.sh
  bin/travis.sh
  composer.json
  composer.lock
  tests/bootstrap.php
  tests/reports/class-wc-tests-reports-orders.php
  tests/reports/class-wc-tests-reports-revenue-stats.php
Labels: REST API, [Status] In Progress, [Status] Ready to Merge, [Type] Bug, [Type] Enhancement

#843 Adds basic snapshot for dropdown button
  client/components/dropdown-button/index.js
  client/components/dropdown-button/test/__snapshots__/index.js.snap
  client/components/dropdown-button/test/index.js
Labels: [Status] Ready to Merge

#850 Fixes code comments on return value type
  client/store/products/selectors.js
Labels: [Status] Ready to Merge

#779 Adds UI wiring for Taxes chart and summary
  client/analytics/report/index.js
  client/analytics/report/taxes/config.js
  client/analytics/report/taxes/index.js
  client/store/constants.js
  client/store/reports/stats/resolvers.js
  client/store/reports/utils.js
  lib/admin.php
Labels: [Status] Ready to Merge

#858 Added zero padding to hours in unit tests.
  tests/reports/class-wc-tests-reports-orders.php
  tests/reports/class-wc-tests-reports-revenue-stats.php
Labels: [Status] Needs Review

#868 Minor fixes to stores
  client/store/orders/index.js
  client/store/orders/selectors.js
  client/store/orders/test/selectors.js
  client/store/products/resolvers.js
  client/store/products/selectors.js
  client/store/products/test/selectors.js
  client/store/reports/stats/index.js
  client/store/reports/stats/selectors.js
  client/store/reports/stats/test/selectors.js
Labels: Analytics, [Status] Ready to Merge

#867 Add Coupons report table
  client/analytics/report/coupons/index.js
  client/analytics/report/coupons/table.js
  client/analytics/report/orders/table.js
  client/store/coupons/actions.js
  client/store/coupons/index.js
  client/store/coupons/reducer.js
  client/store/coupons/resolvers.js
  client/store/coupons/selectors.js
  client/store/coupons/test/reducer.js
  client/store/coupons/test/resolvers.js
  client/store/coupons/test/selectors.js
  client/store/index.js
  client/store/reports/stats/resolvers.js
  lib/admin.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#725 Adds UI wiring for Catgories chart and summary
  client/analytics/report/categories/config.js
  client/analytics/report/categories/index.js
  client/analytics/report/index.js
  client/store/reports/stats/resolvers.js
  client/store/reports/utils.js
  lib/admin.php
Labels: [Status] Ready to Merge

#724 Adds UI wiring for Coupons chart and summary
  client/analytics/report/coupons/config.js
  client/analytics/report/coupons/index.js
  lib/admin.php
Labels: [Status] Ready to Merge

#876 Packages: Remove imports from file that doesn’t exist in packages
  packages/components/src/search/autocompleters/coupons.js
  packages/components/src/search/autocompleters/product-cat.js
  packages/components/src/search/autocompleters/product.js
  packages/components/src/search/autocompleters/variations.js
  packages/date/src/index.js
Labels: Build, [Status] Ready to Merge

#878 Remove duplicated 'Coupons' menu item and reorder them
  lib/admin.php
Labels: Analytics, [Status] Ready to Merge

#881 Add Taxes report table
  client/analytics/report/taxes/index.js
  client/analytics/report/taxes/table.js
  client/store/index.js
  client/store/taxes/actions.js
  client/store/taxes/index.js
  client/store/taxes/reducer.js
  client/store/taxes/resolvers.js
  client/store/taxes/selectors.js
  client/store/taxes/test/reducer.js
  client/store/taxes/test/resolvers.js
  client/store/taxes/test/selectors.js
  packages/components/src/search/autocompleters/index.js
  packages/components/src/search/autocompleters/taxes.js
  packages/components/src/search/index.js
Labels: Analytics, [Status] Needs Review, [Tests] Includes Tests

#841 Chart: Persist interval and chart type
  client/analytics/components/report-chart/index.js
  client/analytics/report/products/table.js
  client/components/chart/index.js
  client/header/index.js
  client/layout/controller.js
  packages/components/src/filters/filter/index.js
  packages/date/src/index.js
  packages/date/test/index.js
  packages/navigation/src/index.js
  packages/navigation/src/test/index.js
Labels: Analytics, [Status] Ready to Merge

#824 Add/product detail link
  client/analytics/report/products/config.js
  client/analytics/report/products/table.js
  packages/components/src/filters/filter/index.js
Labels: [Status] Ready to Merge

#884 Add chartMode property to filters configuration
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-chart/test/index.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  docs/components/chart.md
  docs/components/filters.md
  packages/components/src/filters/filter/index.js
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#898 Update uses of Gutenberg popover for content sizing
  packages/components/src/filters/date/content.js
  packages/components/src/filters/date/index.js
  packages/components/src/filters/filter/index.js
  packages/components/src/search/autocomplete.js
  packages/components/src/search/index.js
  packages/components/src/search/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#818 Try: chart component as a package part 1
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-chart/test/index.js
  client/components/chart/example-hour.js
  client/components/chart/example.js
  client/components/chart/index.js
  client/components/chart/style.scss
  client/components/d3chart/d3-base/README.md
  client/components/d3chart/d3-base/index.js
  client/components/d3chart/d3-base/style.scss
  client/components/d3chart/d3-base/test/index.js
  client/components/d3chart/example.md
  client/components/d3chart/index.js
  client/components/d3chart/legend.js
  client/components/d3chart/legend.scss
  client/components/d3chart/style.scss
  client/components/d3chart/test/fixtures/dummy-hour.js
  client/components/d3chart/test/fixtures/dummy.js
  client/components/d3chart/test/legend.js
  client/components/d3chart/test/utils.js
  client/components/d3chart/utils.js
  client/components/index.js
  client/store/reports/utils.js
  docs/components/chart.md
  package-lock.json
  packages/date/src/index.js
Labels: Components, Packages, [Status] Needs Review, [Type] Try

#901 Chart: Persist orderedKeys between state changes
  client/components/chart/index.js
Labels: Analytics, [Status] Ready to Merge, [Type] Enhancement

#883 Update coupon report summary numbers to match design
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  package-lock.json
Labels: Analytics, Components, Design, [Status] Ready to Merge

#905 Default charts to 'time-comparison'
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-chart/test/index.js
  client/components/chart/index.js
  client/components/d3chart/index.js
Labels: Components, [Status] Needs Review

#909 Remove unnecessary IF clause in reports/utils.js
  client/store/reports/utils.js
Labels: [Status] Ready to Merge

#896 Merge table stores
  client/analytics/report/coupons/table.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/taxes/table.js
  client/store/coupons/actions.js
  client/store/coupons/reducer.js
  client/store/coupons/resolvers.js
  client/store/coupons/selectors.js
  client/store/coupons/test/reducer.js
  client/store/coupons/test/resolvers.js
  client/store/coupons/test/selectors.js
  client/store/index.js
  client/store/products/actions.js
  client/store/products/index.js
  client/store/products/reducer.js
  client/store/products/resolvers.js
  client/store/products/selectors.js
  client/store/products/test/reducer.js
  client/store/products/test/resolvers.js
  client/store/reports/index.js
  client/store/reports/items/actions.js
  client/store/reports/items/index.js
  client/store/reports/items/reducer.js
  client/store/reports/items/resolvers.js
  client/store/reports/items/selectors.js
  client/store/reports/items/test/reducer.js
  client/store/reports/items/test/resolvers.js
  client/store/reports/items/test/selectors.js
  client/store/reports/stats/selectors.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
  client/store/taxes/actions.js
  client/store/taxes/index.js
  client/store/taxes/reducer.js
  client/store/taxes/resolvers.js
  client/store/taxes/selectors.js
  client/store/taxes/test/reducer.js
  client/store/taxes/test/resolvers.js
  client/store/taxes/test/selectors.js
  client/store/variations/actions.js
  client/store/variations/index.js
  client/store/variations/resolvers.js
  client/store/variations/selectors.js
  client/store/variations/test/reducer.js
  client/store/variations/test/resolvers.js
  client/store/variations/test/selectors.js
Labels: Analytics, [Status] Needs Review, [Tests] Includes Tests

#908 Make ChartPlaceholder have the same height than the resulting Chart
  client/components/chart/index.js
  client/components/chart/placeholder.js
  client/components/chart/style.scss
  client/components/d3chart/index.js
  docs/components/chart.md
  docs/components/d3chart.md
Labels: Components, [Status] Ready to Merge

#913 Use numberFormat() to format all non-currency numbers in tables
  client/analytics/report/coupons/table.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/table.js
  client/analytics/report/taxes/table.js
Labels: Analytics, [Status] Needs Review

#904 Add Summary to Products table
  client/analytics/report/products/table.js
Labels: Analytics, [Status] Needs Review

#928 Merge report tables
  client/analytics/components/report-table/index.js
  client/analytics/report/coupons/table.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/taxes/table.js
  packages/components/src/table/table.js
Labels: Analytics, [Status] Needs Review

#891 Adds snapshots for the Split Button component
  packages/components/src/split-button/test/__snapshots__/index.js.snap
  packages/components/src/split-button/test/index.js
Labels: Components, Packages, [Status] Ready to Merge

#910 Bug: noticed a new NaN error caused by attempt to draw chart with empty data
  client/components/d3chart/index.js
Labels: Analytics, Components, [Status] Ready to Merge, [Type] Bug

#938 Call wp_set_script_translations when possible
  lib/client-assets.php
Labels: [Status] Ready to Merge

#903 Categories table
  client/analytics/report/categories/index.js
  client/analytics/report/categories/table.js
Labels: Analytics, [Status] Needs Review

#939 Components: Remove import from local files
  packages/components/src/search/autocompleters/taxes.js
Labels: Components, [Status] Ready to Merge

#877 Tag component snapshots
  packages/components/src/tag/test/__snapshots__/index.js.snap
  packages/components/src/tag/test/index.js
Labels: Components, Packages, [Status] Ready to Merge

#955 Fix false positives in Reports stats resolvers tests
  client/store/reports/stats/test/resolvers.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#932 Hide selected items from autocomplete dropdown
  packages/components/src/search/autocomplete.js
  packages/components/src/search/index.js
  packages/components/src/search/test/autocomplete.js
Labels: Components, [Status] Ready to Merge, [Tests] Includes Tests

#951 Remove order statuses "wc-" prefix
  lib/client-assets.php
  packages/components/src/order-status/index.js
  tests/js/setup-globals.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#946 Roll version to 0.2.0
  package.json
  wc-admin.php
Labels: [Status] Needs Review

#952 Use X-WP-Total header to set the total number of items in tables
  client/analytics/components/report-table/index.js
  client/analytics/report/categories/table.js
  client/analytics/report/coupons/table.js
  client/analytics/report/products/table.js
  client/analytics/report/taxes/table.js
  client/store/reports/items/actions.js
  client/store/reports/items/reducer.js
  client/store/reports/items/resolvers.js
  client/store/reports/items/selectors.js
  client/store/reports/items/test/reducer.js
  client/store/reports/items/test/resolvers.js
  client/store/reports/items/test/selectors.js
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#833 Add wc-api and "Fresh Data"
  client/analytics/report/orders/table.js
  client/index.js
  client/wc-api/constants.js
  client/wc-api/orders/index.js
  client/wc-api/orders/operations.js
  client/wc-api/orders/selectors.js
  client/wc-api/utils.js
  client/wc-api/wc-api-spec.js
  client/wc-api/with-select.js
  client/wc-api/wp-data-store/create-api-client.js
  client/wc-api/wp-data-store/create-store.js
  client/wc-api/wp-data-store/index.js
  client/wc-api/wp-data-store/reducer.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#949 Packages: Add changelogs and documentation
  packages/README.md
  packages/components/CHANGELOG.md
  packages/csv-export/CHANGELOG.md
  packages/currency/CHANGELOG.md
  packages/date/CHANGELOG.md
  packages/navigation/CHANGELOG.md
Labels: Documentation, Packages, [Status] Ready to Merge

#958 Update/summary number focus
  packages/components/src/summary/style.scss
Labels: Accessibility, Analytics, [Status] Ready to Merge, [Type] Enhancement

#959 Don't encode search text in autocompleters before stringifying it
  packages/components/src/search/autocompleters/coupons.js
  packages/components/src/search/autocompleters/product-cat.js
  packages/components/src/search/autocompleters/product.js
  packages/components/src/search/autocompleters/taxes.js
  packages/components/src/search/autocompleters/variations.js
Labels: [Status] Needs Review

#961 Make sure D3Base always updates when width changes
  client/components/d3chart/d3-base/index.js
  client/components/d3chart/d3-base/test/index.js
  client/components/d3chart/index.js
Labels: Components, [Status] Needs Review

#962 Packages – Components: Move proptype-validator utility into src
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/card/index.js
  packages/components/src/lib/proptype-validator.js
  packages/components/src/section-header/index.js
Labels: Packages, [Status] Ready to Merge, [Type] Bug

#964 Add screen reader labels to table headers
  client/analytics/report/categories/table.js
  client/analytics/report/coupons/table.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  docs/components/table.md
  packages/components/src/table/table.js
Labels: Accessibility, Analytics, Components, [Status] Ready to Merge
