Repository woocommerce/woocommerce-admin, pull requests merged in 2018-07, with the labels that each got.

#195 Update travis to run npm test
  .travis.yml
  client/lib/date/test/index.js
  tests/js/setup-globals.js
Labels: [Status] Needs Review

#186 Fixes some display issues on embedded/classic WC pages
  client/layout/activity-panel/wordpress-notices.js
  client/layout/header/style.scss
  client/stylesheets/_wpadmin-reset.scss
  lib/admin.php
Labels: [Status] Ready to Merge

#182 ActivityPanel: Update semantics for screen reader navigation
  client/layout/activity-panel/index.js
Labels: Activity Panel, [Status] Ready to Merge

#196 Datepicker: fix getCurrentDates to always reflect defaults
  client/components/date-picker/index.js
  client/lib/date/index.js
  client/lib/date/test/index.js
Labels: [Status] Ready to Merge

#203 Update ActivityCard to latest hifi designs
  client/layout/activity-panel/activity-card/README.md
  client/layout/activity-panel/activity-card/index.js
  client/layout/activity-panel/activity-card/style.scss
  client/layout/activity-panel/activity-card/test/__snapshots__/index.js.snap
  client/layout/activity-panel/activity-card/test/index.js
  client/layout/activity-panel/orders.js
  client/layout/activity-panel/style.scss
  client/stylesheets/_colors.scss
  client/stylesheets/_variables.scss
  client/stylesheets/_wpadmin-reset.scss
  webpack.config.js
Labels: Activity Panel, [Status] Ready to Merge, [Tests] Includes Tests

#212 Activity Panel: Add a "first draft" of Inbox items
  client/layout/activity-panel/inbox.js
  client/layout/activity-panel/index.js
  client/layout/activity-panel/panels/inbox.js
  client/layout/activity-panel/panels/orders.js
  client/layout/activity-panel/panels/reviews.js
  client/layout/activity-panel/panels/stock.js
  client/layout/activity-panel/style.scss
Labels: [Status] Needs Design Review, [Status] Needs Review

#211 Add "in progress" banner to readme
  README.md
Labels: [Status] Ready to Merge

#217 Fix ActivityPanel Slide Animation
  client/layout/activity-panel/index.js
Labels: Activity Panel, [Status] Ready to Merge

#216 Remove Agenda Widget
  client/dashboard/index.js
  client/dashboard/widgets/agenda/README.md
  client/dashboard/widgets/agenda/header.js
  client/dashboard/widgets/agenda/index.js
  client/dashboard/widgets/agenda/item.js
  client/dashboard/widgets/agenda/style.scss
Labels: Dashboard, [Status] Ready to Merge

#221 Fix key prop warning in FilterPicker
  client/components/filter-picker/index.js
Labels: [Status] Ready to Merge

#213 Activity Panel Outbound Link
  client/components/gravatar/README.md
  client/components/link/README.md
  client/components/link/index.js
  client/layout/activity-panel/activity-header/README.md
  client/layout/activity-panel/activity-outbound-link/README.md
  client/layout/activity-panel/activity-outbound-link/index.js
  client/layout/activity-panel/activity-outbound-link/style.scss
  client/layout/activity-panel/panels/orders.js
  client/layout/activity-panel/style.scss
  client/layout/header/index.js
  client/stylesheets/_colors.scss
Labels: Activity Panel, [Status] Needs Design Review, [Status] Needs Review

#230 Update `react-world-flags` package
  .travis.yml
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#220 Activity Panel: Add loading placeholder for ActivityCard, using Inbox as demo
  client/layout/activity-panel/activity-card/README.md
  client/layout/activity-panel/activity-card/index.js
  client/layout/activity-panel/activity-card/placeholder.js
  client/layout/activity-panel/activity-card/style.scss
  client/layout/activity-panel/activity-card/test/__snapshots__/placeholder.js.snap
  client/layout/activity-panel/activity-card/test/index.js
  client/layout/activity-panel/activity-card/test/placeholder.js
  client/layout/activity-panel/panels/inbox.js
  client/layout/activity-panel/panels/orders.js
  client/stylesheets/_mixins.scss
  client/stylesheets/_wpadmin-reset.scss
Labels: Activity Panel, [Status] Ready to Merge

#226 Components: Filter picker: Add animation
  client/components/animation-slider/README.md
  client/components/animation-slider/index.js
  client/components/animation-slider/style.scss
  client/components/filter-picker/index.js
  client/components/filter-picker/style.scss
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#234 Update to Gutenberg 3.3 – remove `gutenberg` dependency
  .babelrc
  client/components/ellipsis-menu/menu-item.js
  client/dashboard/store-performance/index.js
  client/layout/activity-panel/panels/orders.js
  client/layout/header/index.js
  lib/client-assets.php
  package-lock.json
  package.json
  tests/js/jest.config.json
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#232 Fade in activity panel tabs during page transition
  client/stylesheets/_wpadmin-reset.scss
Labels: Activity Panel, [Status] Needs Review

#189 D3 Chart: legend component and integration
  .babelrc
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/d3-base/README.md
  client/components/chart/d3-base/index.js
  client/components/chart/d3-base/style.scss
  client/components/chart/d3-base/test/index.js
  client/components/chart/index.js
  client/components/chart/legend.js
  client/components/chart/style.scss
  client/components/chart/test/fixtures/dummy.js
  client/components/chart/test/utils.js
  client/components/chart/utils.js
  client/components/d3/base/index.js
  client/components/d3/charts/README.md
  client/components/d3/charts/style.scss
  client/components/segmented-selection/index.js
  client/dashboard/charts.js
  client/dashboard/index.js
  package-lock.json
Labels: Analytics, [Status] Needs Review

#238 Fix WP Notices Tabbing
  client/stylesheets/_wpadmin-reset.scss
Labels: Activity Panel, [Status] Ready to Merge

#240 Adds the full range of WooCommerce purples
  client/stylesheets/_colors.scss
Labels: Design, [Status] Ready to Merge

#241 Update ActivityCard Mobile Styles
  client/layout/activity-panel/activity-card/style.scss
Labels: Activity Panel, [Status] Ready to Merge

#235 Add custom Datepicker styles and validation
  client/components/calendar/index.js
  client/components/calendar/input.js
  client/components/calendar/style.scss
  client/components/date-picker/content.js
  client/components/date-picker/index.js
  client/components/date-picker/style.scss
  client/lib/date/index.js
  client/lib/date/test/index.js
  package-lock.json
Labels: [Status] Ready to Merge

#244 Add CSS autoprefixer
  .browserslistrc
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
Labels: [Status] Ready to Merge

#237 SummaryNumber Component: Update to latest hifi design
  client/analytics/report/example.js
  client/components/card/style.scss
  client/components/summary/README.md
  client/components/summary/index.js
  client/components/summary/item.js
  client/components/summary/style.scss
  client/dashboard/store-performance/index.js
  client/dashboard/store-performance/style.scss
  client/layout/style.scss
  client/stylesheets/_breakpoints.scss
Labels: Analytics, [Status] Ready to Merge

#250 Remove debug code logging screen ID
  lib/client-assets.php
Labels: [Status] Ready to Merge

#239 Datepicker: Refactor Calendar to fully controlled component
  client/analytics/report/products/index.js
  client/analytics/report/revenue.js
  client/components/calendar/index.js
  client/components/date-picker/README.md
  client/components/date-picker/content.js
  client/components/date-picker/index.js
  client/lib/date/index.js
  client/lib/date/test/index.js
Labels: [Status] Ready to Merge
