Repository woocommerce/woocommerce-admin, pull requests merged in 2018-09, with the labels that each got.

#326 Add CSV download to Revenue table
  client/analytics/report/revenue/__mocks__/mock-csv.js
  client/analytics/report/revenue/__mocks__/mock-data.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/test/index.js
  client/lib/csv/__mocks__/mock-csv-data.js
  client/lib/csv/__mocks__/mock-headers.js
  client/lib/csv/__mocks__/mock-rows.js
  client/lib/csv/index.js
  client/lib/csv/test/index.js
  package-lock.json
  package.json
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#345 IE11: fix Activity Panel tab icons missing and wrong alignment
  client/layout/activity-panel/style.scss
Labels: Activity Panel, [Status] Ready to Merge

#346 Proposal: use native Array.isArray() instead of lodash function
  client/components/table/index.js
  client/layout/activity-panel/activity-card/index.js
  client/layout/header/index.js
Labels: [Status] Ready to Merge

#344 Search Component: Move `selected` to props
  client/analytics/index.js
  client/analytics/report/orders/constants.js
  client/components/filters/advanced/index.js
  client/components/search/README.md
  client/components/search/index.js
Labels: [Status] Needs Review

#351 Fix TopSellingProducts table not correctly loading data
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
  client/store/reports/stats/reducer.js
Labels: Dashboard, [Status] Ready to Merge

#348 Add EmptyContent Component and revenue error/empty states.
  client/analytics/report/revenue/index.js
  client/components/empty-content/index.js
  client/components/empty-content/style.scss
  client/components/image-asset/index.js
  client/components/index.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
  client/stylesheets/shared/_global.scss
  images/empty-content.svg
  lib/client-assets.php
Labels: [Status] Ready to Merge

#347 Add loading indicators to the revenue report.
  client/analytics/report/index.js
  client/analytics/report/revenue/index.js
  client/analytics/report/style.scss
  client/components/chart/placeholder.js
  client/components/chart/style.scss
  client/components/empty-content/index.js
  client/components/empty-content/style.scss
  client/components/image-asset/index.js
  client/components/index.js
  client/components/summary/item.js
  client/components/summary/placeholder.js
  client/components/summary/style.scss
  client/components/table/placeholder.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
  client/stylesheets/shared/_global.scss
  images/empty-content.svg
  lib/client-assets.php
Labels: Analytics, [Status] Ready to Merge

#352 Fix wp-admin navigation active state
  client/layout/controller.js
Labels: [Status] Ready to Merge

#355 Remove test code/examples and disable the inbox activity panel.
  client/analytics/index.js
  client/analytics/report/example.js
  client/analytics/report/index.js
  client/dashboard/index.js
  client/layout/activity-panel/index.js
  lib/admin.php
Labels: [Status] Ready to Merge

#353 IE11: fix CSS grid in Summary
  client/components/summary/style.scss
  client/stylesheets/abstracts/_mixins.scss
  package-lock.json
  package.json
  postcss.config.js
Labels: [Status] Ready to Merge

#360 Chart Component: Add/chart intervals
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/example-hour.js
  client/components/chart/index.js
  client/components/chart/test/fixtures/dummy-hour.js
  client/components/chart/test/fixtures/dummy.js
  client/components/chart/test/utils.js
  client/components/chart/utils.js
  client/dashboard/index.js
Labels: [Status] Needs Review

#366 IE11: Fix Date filters grid not displaying correctly
  client/components/filters/date/style.scss
  client/components/segmented-selection/index.js
  client/components/segmented-selection/style.scss
Labels: Analytics, [Status] Ready to Merge

#350 Chart Component: chart design feedback and updates
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/legend.js
  client/components/chart/style.scss
  client/components/chart/test/utils.js
  client/components/chart/utils.js
  client/dashboard/index.js
  client/lib/currency/index.js
  package-lock.json
Labels: [Status] Ready to Merge

#369 Add w.js when wc_tracker is enabled.
  lib/client-assets.php
Labels: [Status] Ready to Merge

#370 IE11: fix Card layout broken because it was using CSS grid
  client/components/card/index.js
  client/components/card/style.scss
Labels: [Status] Ready to Merge

#368 Component – Filters: Add "comparison" card
  client/analytics/report/products/constants.js
  client/components/filters/compare/index.js
  client/components/filters/index.js
Labels: Analytics, Components, [Status] Ready to Merge

#380 Chart Component: standard vs comparison legend layout
  client/components/chart/index.js
Labels: Analytics, Dashboard, [Status] Needs Design Review, [Status] Needs Review

#381 Chart Component: remove chart legend ordering for layout=standard and color scales
  client/analytics/report/revenue/index.js
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/example.js
  client/components/chart/index.js
  client/components/chart/test/utils.js
  client/components/chart/utils.js
Labels: Analytics, Components, Dashboard, [Status] Ready to Merge

#372 IE11: Add fallback gutter for browsers that don't support CSS Custom properties
  client/layout/activity-panel/activity-card/style.scss
  client/layout/activity-panel/activity-outbound-link/style.scss
  client/layout/header/style.scss
  client/layout/style.scss
  client/stylesheets/abstracts/_variables.scss
Labels: [Status] Ready to Merge

#356 IE11: Add required polyfills so react-dates works in Internet Explorer 11
  client/components/calendar/index.js
Labels: Components, [Status] Ready to Merge

#363 Chart Component: add iconbuttons to toggle master - missing gridicons?
  client/components/chart/charts.js
  client/components/chart/d3-base/index.js
  client/components/chart/index.js
  client/components/chart/style.scss
  package-lock.json
  package.json
Labels: [Status] In Progress

#390 Fix Gutenberg 3.7 compatibility: Remove APIProvider
  client/embedded.js
  client/index.js
  lib/client-assets.php
Labels: Build, [Status] Ready to Merge

#359 Add interval selection to the revenue report
  client/analytics/report/revenue/index.js
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/style.scss
  client/lib/date/index.js
  client/lib/date/test/index.js
Labels: [Status] Ready to Merge

#349 Advanced Filters: Add url support
  client/analytics/report/orders/constants.js
  client/components/filters/advanced/index.js
  client/components/filters/advanced/search-filter.js
  client/components/filters/advanced/select-filter.js
  client/components/filters/advanced/style.scss
  client/components/filters/advanced/test/utils.js
  client/components/filters/advanced/utils.js
  client/components/filters/index.js
  client/components/search/index.js
  client/lib/nav-utils/index.js
  client/stylesheets/shared/_global.scss
Labels: [Status] Needs Review

#365 Add empty state message to Top Selling Products card
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/style.scss
  client/dashboard/top-selling-products/test/index.js
Labels: Dashboard, [Status] Needs Design Review, [Status] Needs Review, [Tests] Includes Tests

#392 Advanced Filters: Filter button improvements
  client/components/filters/advanced/index.js
  client/components/filters/advanced/style.scss
Labels: [Status] Ready to Merge

#394 Make Top Selling Products table to have the same height in all states
  client/components/table/style.scss
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/style.scss
  client/dashboard/top-selling-products/test/index.js
Labels: Dashboard, [Status] Ready to Merge

#396 Dropdown: fix positioning
  client/components/filters/advanced/index.js
  client/components/filters/advanced/style.scss
Labels: [Status] Ready to Merge

#386 Advanced Filters: Add api fetch for Search results
  client/analytics/report/orders/config.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  client/components/filters/advanced/index.js
  client/components/filters/advanced/search-filter.js
  client/components/filters/advanced/test/utils.js
  client/components/filters/advanced/utils.js
  client/components/filters/index.js
Labels: [Status] Needs Design Review, [Status] Ready to Merge

#393 Revenue Report: align date formats for the chart
  client/analytics/report/revenue/index.js
  client/components/chart/index.js
  client/components/chart/style.scss
  client/components/chart/utils.js
  client/lib/date/index.js
  package-lock.json
  package.json
Labels: Analytics, [Status] Needs Review

#399 Make it possible to navigate charts with the keyboard
  client/components/chart/utils.js
Labels: Analytics, [Status] Ready to Merge

#411 IE11: fix dates overlapping in Custom filter
  client/components/calendar/style.scss
Labels: [Status] Ready to Merge

#408 Chart: Add styling needed to not be wrapped by card.
  client/analytics/report/revenue/index.js
  client/components/chart/style.scss
Labels: Analytics, [Status] Needs Review

#398 Component - Chart: factorial spacing of x-axis ticks
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/utils.js
Labels: Analytics, Components, Dashboard, [Status] Needs Design Review, [Status] Needs Review

#413 Component - Chart: check if second x axis tick required
  client/components/chart/utils.js
  package-lock.json
  package.json
Labels: Analytics, Components, Dashboard, [Status] Ready to Merge

#387 Add mock product report, helper functions
  client/analytics/report/products/__mocks__/data.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/index.js
  client/lib/nav-utils/index.js
Labels: Analytics, [Status] Ready to Merge

#427 Don't allow unselecting all items in chart legends
  client/components/chart/legend.js
  client/components/chart/style.scss
  client/components/chart/test/legend.js
Labels: Analytics, [Status] Needs Review, [Tests] Includes Tests

#422 Make buttons to switch between bar and line chart accessible
  client/components/chart/index.js
Labels: Accessibility, [Status] Ready to Merge

#420 Added reporting REST API extensions to wc-admin.
  includes/api/class-wc-admin-rest-reports-categories-controller.php
  includes/api/class-wc-admin-rest-reports-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-stats-controller.php
  includes/api/class-wc-admin-rest-reports-customers-controller.php
  includes/api/class-wc-admin-rest-reports-downloads-controller.php
  includes/api/class-wc-admin-rest-reports-downloads-files-controller.php
  includes/api/class-wc-admin-rest-reports-downloads-stats-controller.php
  includes/api/class-wc-admin-rest-reports-orders-stats-controller.php
  includes/api/class-wc-admin-rest-reports-products-controller.php
  includes/api/class-wc-admin-rest-reports-products-stats-controller.php
  includes/api/class-wc-admin-rest-reports-revenue-stats-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-stats-controller.php
  includes/api/class-wc-admin-rest-system-status-tools-controller.php
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-order-stats-background-process.php
  includes/class-wc-admin-reports-categories-query.php
  includes/class-wc-admin-reports-interval.php
  includes/class-wc-admin-reports-orders-stats-query.php
  includes/class-wc-admin-reports-products-query.php
  includes/class-wc-admin-reports-products-stats-query.php
  includes/class-wc-admin-reports-query.php
  includes/class-wc-admin-reports-revenue-query.php
  includes/data-stores/class-wc-admin-reports-categories-data-store.php
  includes/data-stores/class-wc-admin-reports-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  includes/data-stores/class-wc-admin-reports-products-data-store.php
  includes/data-stores/class-wc-admin-reports-products-stats-data-store.php
  includes/interfaces/class-wc-admin-reports-data-store-interface.php
  includes/wc-admin-order-functions.php
  wc-admin.php
Labels: REST API, [Status] In Progress

#434 Build: Update packages
  bin/pre-commit-hook.js
  client/layout/activity-panel/activity-card/test/__snapshots__/index.js.snap
  docs/_sidebar.md
  docs/components/chart.md
  docs/components/empty-content.md
  docs/components/image-asset.md
  docs/components/search.md
  docs/components/summary.md
  docs/components/table.md
  package-lock.json
  package.json
Labels: Build, [Status] Needs Review

#425 Advanced Filters: add match param to url
  client/components/filters/advanced/index.js
Labels: [Status] Needs Review

#435 Minor padding tweaks to ellipsis menu items
  client/components/ellipsis-menu/style.scss
Labels: Analytics, Components, Design

#426 Chart Legend: Update checkbox styles to outline when unchecked and add focus state
  client/components/chart/legend.js
  client/components/chart/style.scss
Labels: Accessibility, Analytics, [Status] Ready to Merge

#431 Compare Filter: Wrap up compare card functionality
  client/analytics/report/products/config.js
  client/components/filters/compare/button.js
  client/components/filters/compare/index.js
  client/components/filters/style.scss
  client/components/search/index.js
  client/components/search/style.scss
  client/components/table/index.js
Labels: Analytics, Components, [Status] Ready to Merge

#445 Docs: Remove REST API feature branch requirement.
  README.md
  docs/README.md
Labels: [Status] Needs Review

#294 Datepicker: resize dropdown on tab switch
  client/components/filters/date/content.js
  client/components/filters/date/index.js
Labels: [Status] Ready to Merge

#459 Change default date format for chart tooltips
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/index.js
Labels: Analytics, [Status] Needs Review

#460 Increase contrast of the tooltip title color
  client/components/chart/style.scss
Labels: Accessibility, [Status] Needs Review

#458 Update tooltip title and labels in standard graphs
  client/analytics/report/revenue/index.js
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/test/fixtures/dummy-hour.js
  client/components/chart/test/fixtures/dummy.js
  client/components/chart/utils.js
  client/lib/date/index.js
Labels: Analytics, [Status] Needs Review

#441 Use WooCommerce's database prefix
  includes/class-wc-admin-api-init.php
  includes/data-stores/class-wc-admin-reports-categories-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  includes/data-stores/class-wc-admin-reports-products-data-store.php
  includes/wc-admin-order-functions.php
Labels: [Status] Needs Review

#466 Remove opacity property from chart tooltip title styles
  client/components/chart/style.scss
Labels: Accessibility, Analytics, [Status] Ready to Merge

#467 Transpose and update format of chart tooltip dates
  client/analytics/report/revenue/index.js
  client/components/chart/README.md
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/utils.js
  client/lib/date/index.js
Labels: Analytics, [Status] Needs Review

#470 Add visual component docs from markdown examples
  client/components/animation-slider/README.md
  client/components/animation-slider/example.md
  client/components/calendar/README.md
  client/components/calendar/example.md
  client/components/card/README.md
  client/components/card/example.md
  client/components/chart/README.md
  client/components/chart/example.md
  client/components/count/README.md
  client/components/count/example.md
  client/components/dropdown-button/README.md
  client/components/dropdown-button/example.md
  client/components/ellipsis-menu/README.md
  client/components/ellipsis-menu/example.md
  client/components/empty-content/example.md
  client/components/filters/README.md
  client/components/filters/example.md
  client/components/flag/README.md
  client/components/flag/example.md
  client/components/gravatar/README.md
  client/components/gravatar/example.md
  client/components/image-asset/example.md
  client/components/index.js
  client/components/link/README.md
  client/components/link/example.md
  client/components/order-status/README.md
  client/components/order-status/example.md
  client/components/pagination/README.md
  client/components/pagination/example.md
  client/components/product-image/README.md
  client/components/product-image/example.md
  client/components/rating/README.md
  client/components/rating/example.md
  client/components/search/README.md
  client/components/search/example.md
  client/components/section/example.md
  client/components/segmented-selection/README.md
  client/components/segmented-selection/example.md
  client/components/split-button/example.md
  client/components/summary/README.md
  client/components/summary/example.md
  client/components/table/README.md
  client/components/table/example.md
  client/components/tag/README.md
  client/components/tag/example.md
  client/devdocs/docs.js
  client/devdocs/example.js
  client/devdocs/examples.json
  client/devdocs/index.js
  client/devdocs/style.scss
  client/layout/controller.js
  lib/admin.php
  package-lock.json
  package.json
  webpack.config.js
Labels: Documentation, [Status] Ready to Merge

#454 AdvancedFilters: Add request for orders statuses
  client/analytics/report/orders/config.js
  client/components/filters/advanced/index.js
  client/components/filters/advanced/select-filter.js
  client/components/filters/advanced/style.scss
  client/components/filters/advanced/utils.js
  package-lock.json
Labels: [Status] Needs Review

#421 Improve charts accessibility
  client/analytics/report/revenue/index.js
  client/components/chart/charts.js
  client/components/chart/index.js
  client/components/chart/utils.js
Labels: Accessibility, Analytics, [Status] Needs Review

#472 Fix: chart legend was not visible at 1340px width
  client/components/chart/index.js
Labels: Analytics, [Status] Ready to Merge

#478 Fix activity panel tabs misaligned in Chrome and Safari
  client/header/activity-panel/style.scss
Labels: Activity Panel, [Status] Ready to Merge

#473 Build: Add `cross-env` to allow building on Windows
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#471 Make tooltip position be relative to the hovered elements instead of the mouse
  client/components/chart/style.scss
  client/components/chart/utils.js
Labels: Analytics, [Status] Ready to Merge

#476 Update chart header layout according to design
  client/components/chart/style.scss
Labels: Analytics, [Status] Ready to Merge

#484 Components – Search: Pass through aria label props
  client/components/search/example.md
  client/components/search/index.js
Labels: Components, [Status] Ready to Merge

#461 Casted numeric values to floats before performing arithmetic operations.
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
Labels: REST API, [Status] Needs Review

#462 Added PHP tests
  .gitignore
  .travis.yml
  bin/install-wp-tests.sh
  bin/phpcs.sh
  bin/phpunit.sh
  bin/travis.sh
  composer.json
  composer.lock
  includes/class-wc-admin-api-init.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  phpcs.xml.dist
  phpunit.xml.dist
  tests/api/reports-categories.php
  tests/api/reports-interval.php
  tests/api/reports-orders-stats.php
  tests/api/reports-products-stats.php
  tests/api/reports-products.php
  tests/api/reports-revenue-stats.php
  tests/bootstrap.php
  tests/framework/helpers/class-wc-helper-reports.php
  tests/reports/class-wc-tests-reports-orders.php
  tests/reports/class-wc-tests-reports-products.php
  tests/reports/class-wc-tests-reports-revenue-stats.php
  wc-admin.php
Labels: REST API, [Status] Needs Review

#487 Update chart interval select alignment
  client/components/chart/style.scss
Labels: Analytics, Components, Design, [Status] Ready to Merge, [Type] Enhancement

#490 Update Empty Content SVG
  images/empty-content.svg
Labels: Analytics, Components, Design

#464 Admin Notes: Add CRUD and Data Stores
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-note.php
  includes/class-wc-admin-notes.php
  includes/data-stores/class-wc-admin-notes-data-store.php
Labels: [Status] Needs Review
