Repository woocommerce/woocommerce-admin, pull requests merged in 2018-10, with the labels that each got.

#483 Make tabular data independent of chart interval
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/test/index.js
  client/components/table/placeholder.js
  client/lib/date/index.js
  client/store/reports/stats/actions.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
Labels: [Status] Needs Review

#495 TableCard: Add search to table header
  client/analytics/report/products/index.js
  client/components/filters/compare/button.js
  client/components/search/index.js
  client/components/search/style.scss
  client/components/table/index.js
  client/components/table/style.scss
Labels: Components, [Status] Ready to Merge

#500 TableCard Fix: Add a default value to `labels` to prevent warning
  client/components/table/index.js
Labels: [Status] Needs Review, [Type] Bug

#493 Orders table
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/index.js
  client/components/table/style.scss
  client/components/table/table.js
  client/dashboard/top-selling-products/index.js
  client/lib/csv/__mocks__/mock-csv-data.js
  client/lib/csv/__mocks__/mock-headers.js
  client/lib/csv/__mocks__/mock-rows.js
  client/lib/csv/index.js
  client/store/orders/reducer.js
  client/store/orders/selectors.js
Labels: Analytics, [Status] Needs Review

#498 Adds GitHub templates to ensure good issue and PR descriptions
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Ready to Merge

#497 Refactors code to vanilla js and removes jQuery
  .eslintrc
  client/layout/controller.js
  webpack.config.js
Labels: [Status] Needs Review

#506 Reports: Update summary number label based on selected compare interval
  client/analytics/report/revenue/index.js
Labels: Analytics, [Status] Ready to Merge

#504 Adds Orders Summary and Orders Graph
  client/analytics/report/orders/index.js
Labels: [Status] Needs Review

#515 Round average orders in order summary
  client/analytics/report/orders/index.js
Labels: [Status] Needs Review

#520 Fix y-axis tick labels
  client/components/chart/charts.js
  client/components/chart/index.js
Labels: Analytics, Components, [Status] Needs Review, [Type] Bug

#503 Create ViewMoreList component
  client/analytics/report/orders/table.js
  client/components/index.js
  client/components/table/style.scss
  client/components/tag/example.md
  client/components/tag/index.js
  client/components/tag/style.scss
  client/components/view-more-list/example.md
  client/components/view-more-list/index.js
  client/components/view-more-list/style.scss
  client/devdocs/examples.json
  docs/components/view-more-list.md
Labels: Components, [Status] Needs Review

#512 Tag: use label in removeLabel
  client/components/search/index.js
  client/components/tag/index.js
Labels: [Status] Ready to Merge

#501 DatePicker: update selected tab to reflect update to TabPanel component
  client/components/filters/date/content.js
Labels: [Status] Ready to Merge, [Type] Bug

#522 Rename 'mock-data' files so they don't have the same file name
  client/analytics/report/revenue/__mocks__/revenue-mock-csv.js
  client/analytics/report/revenue/__mocks__/revenue-mock-data.js
  client/analytics/report/revenue/test/index.js
  client/dashboard/top-selling-products/__mocks__/top-selling-products-mock-data.js
  client/dashboard/top-selling-products/test/index.js
Labels: [Status] Needs Review

#457 i18n: Advanced Filters strings
  client/analytics/report/orders/config.js
  client/components/filters/advanced/index.js
  client/components/filters/advanced/search-filter.js
  client/components/filters/advanced/select-filter.js
  client/components/filters/advanced/style.scss
  client/components/filters/index.js
  client/components/filters/style.scss
  client/components/search/index.js
  package.json
Labels: [Status] Ready to Merge

#514 Advanced Filters: fix README
  client/components/filters/advanced/README.md
Labels: [Status] Needs Review

#519 Send params with Orders table API calls
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/store/orders/actions.js
  client/store/orders/reducer.js
  client/store/orders/resolvers.js
  client/store/orders/selectors.js
  client/store/orders/test/reducer.js
  client/store/orders/test/resolvers.js
  client/store/orders/test/selectors.js
  client/store/reports/stats/selectors.js
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#517 Refactors out summary and graph
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/orders/chart.js
  client/analytics/report/orders/index.js
Labels: [Status] Ready to Merge

#523 Update/refactor revenue report using chart components
  client/analytics/report/revenue/chart.js
  client/analytics/report/revenue/index.js
Labels: [Status] Ready to Merge

#544 Dashboard: Remove Chart Example
  client/dashboard/index.js
Labels: Dashboard, [Status] Needs Review

#525 Hide day from X axis when the time period is too long
  client/analytics/components/report-chart/index.js
  client/components/chart/charts.js
  client/components/chart/utils.js
  client/lib/date/index.js
Labels: Analytics, [Status] Ready to Merge

#551 Change toggle background color to woocommerce purple
  client/components/ellipsis-menu/style.scss
Labels: Design, [Status] Needs Review

#549 Reposition chevron icon for first column in tables
  client/components/table/style.scss
Labels: [Status] Ready to Merge

#541 Fix pagination alignment/451
  client/components/pagination/style.scss
Labels: [Status] Ready to Merge

#542 Create appendTimestamp() utils function
  client/analytics/report/orders/index.js
  client/analytics/report/revenue/index.js
  client/lib/date/index.js
  client/lib/date/test/index.js
  client/store/reports/utils.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#468 Component - Chart: focus data points on hover with tooltip
  client/components/chart/charts.js
  client/components/chart/style.scss
  client/components/chart/test/utils.js
  client/components/chart/utils.js
Labels: Analytics, Dashboard, [Status] Needs Review

#543 Adds report error component
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-error/index.js
  client/analytics/components/report-summary/index.js
Labels: [Status] Ready to Merge

#553 Removes unwanted orders report filters
  client/analytics/report/orders/config.js
Labels: [Status] Ready to Merge

#546 Add table shadow element to tables
  client/components/table/style.scss
  client/components/table/table.js
Labels: [Status] Ready to Merge

#560 Modify table download button styling
  client/components/table/download-icon.js
  client/components/table/index.js
  client/components/table/style.scss
Labels: Design, [Status] Ready to Merge

#563 Change componentDidUnmount to componentWillUnmount
  client/components/table/table.js
Labels: [Status] Ready to Merge, [Type] Bug

#539 Align status indicator to the right in Orders table
  client/analytics/report/orders/style.scss
  client/analytics/report/orders/table.js
Labels: Analytics, [Status] Ready to Merge

#569 Remove unnecessary opacity values from charts code
  client/components/chart/utils.js
Labels: Analytics, [Status] Ready to Merge

#491 Fixed textdomain
  includes/api/class-wc-admin-rest-reports-categories-controller.php
  includes/api/class-wc-admin-rest-reports-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-stats-controller.php
  includes/api/class-wc-admin-rest-reports-customers-controller.php
  includes/api/class-wc-admin-rest-reports-orders-stats-controller.php
  includes/api/class-wc-admin-rest-reports-products-controller.php
  includes/api/class-wc-admin-rest-reports-products-stats-controller.php
  includes/api/class-wc-admin-rest-reports-revenue-stats-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-stats-controller.php
  includes/api/class-wc-admin-rest-system-status-tools-controller.php
  includes/class-wc-admin-reports-query.php
  includes/data-stores/class-wc-admin-reports-categories-data-store.php
  includes/data-stores/class-wc-admin-reports-products-data-store.php
  includes/data-stores/class-wc-admin-reports-products-stats-data-store.php
Labels: [Status] Ready to Merge

#488 Imported dev files from WooCommerce and updated pre-commit hook
  .gitignore
  Gruntfile.js
  bin/pre-commit-hook.js
  package-lock.json
  package.json
  phpcs.xml.dist
Labels: [Status] Ready to Merge

#570 Change link focus area in table links
  client/components/table/style.scss
Labels: Design, [Status] Needs Design Review

#548 Add products report Chart and Summary
  client/analytics/report/products/chart.js
  client/analytics/report/products/index.js
Labels: [Status] Ready to Merge

#530 Deactivate plugin if dependencies not met
  wc-admin.php
Labels: [Status] Needs Review

#571 Update sorted column background color
  client/components/table/style.scss
  client/components/table/table.js
Labels: Design, [Status] Needs Review

#538 Add/filters search
  client/analytics/report/products/config.js
  client/components/filters/compare/index.js
  client/components/filters/filter/index.js
  client/components/filters/style.scss
Labels: [Status] Needs Review

#565 Reports: create queries for data requests in one place
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/orders/index.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
Labels: [Status] Needs Review, [Status] Ready to Merge

#547 Update the order of orders report summary numbers
  client/analytics/components/report-summary/index.js
  client/analytics/report/orders/chart.js
Labels: Analytics, Components, [Status] Needs Review, [Type] Enhancement

#580 Orders Report: Fix key prop warning.
  client/analytics/report/orders/table.js
Labels: Analytics, [Status] Needs Review

#583 ChartData: fix typo in primary/secondary data
  client/analytics/components/report-chart/index.js
Labels: [Status] Ready to Merge

#507 Activity Panel: Inbox: Add REST API (GETters only)
  includes/api/class-wc-admin-rest-admin-notes-controller.php
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-note.php
  includes/class-wc-admin-notes.php
  includes/data-stores/class-wc-admin-notes-data-store.php
Labels: [Status] Ready to Merge

#602 IE11: fix tooltip not correctly positioned in charts
  client/components/chart/utils.js
Labels: [Status] Ready to Merge

#603 IE11: fix table header misalignment
  client/components/card/style.scss
  client/components/table/style.scss
Labels: [Status] Ready to Merge

#606 Temporary fix for dev docs while react-live is fixed
  client/devdocs/example.js
Labels: [Status] Needs Review

#608 Fixes React Live by pinning buble version
  client/devdocs/example.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#513 Activity Panel: Inbox: Add Store, Enable Inbox
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox.js
  client/lib/sanitize-html/index.js
  client/lib/sanitize-html/test/index.js
  client/store/index.js
  client/store/notes/actions.js
  client/store/notes/index.js
  client/store/notes/reducer.js
  client/store/notes/resolvers.js
  client/store/notes/selectors.js
  client/store/notes/test/reducer.js
  client/store/notes/test/resolvers.js
  client/store/notes/test/selectors.js
  package.json
Labels: [Status] Ready to Merge

#605 Create EmptyTable component
  client/components/index.js
  client/components/table/empty.js
  client/components/table/example.md
  client/components/table/style.scss
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/style.scss
  client/dashboard/top-selling-products/test/index.js
Labels: Components, [Status] Needs Review

#581 Add default report data if empty product data is returned
  includes/api/class-wc-admin-rest-reports-products-stats-controller.php
Labels: REST API, [Status] Ready to Merge, [Type] Bug

#561 Update/track usage logic
  client/lib/tracks.js
  lib/client-assets.php
Labels: [Status] Needs Review

#611 Uses PHPCBF to autofix warnings and errors
  includes/api/class-wc-admin-rest-admin-notes-controller.php
  includes/api/class-wc-admin-rest-reports-controller.php
  includes/api/class-wc-admin-rest-reports-customers-controller.php
  includes/api/class-wc-admin-rest-reports-products-controller.php
  includes/api/class-wc-admin-rest-reports-products-stats-controller.php
  includes/api/class-wc-admin-rest-system-status-tools-controller.php
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-reports-categories-query.php
  includes/class-wc-admin-reports-interval.php
  includes/class-wc-admin-reports-orders-stats-query.php
  includes/class-wc-admin-reports-products-query.php
  includes/class-wc-admin-reports-products-stats-query.php
  includes/class-wc-admin-reports-revenue-query.php
  includes/data-stores/class-wc-admin-notes-data-store.php
  includes/data-stores/class-wc-admin-reports-categories-data-store.php
  includes/data-stores/class-wc-admin-reports-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  includes/data-stores/class-wc-admin-reports-products-data-store.php
  includes/data-stores/class-wc-admin-reports-products-stats-data-store.php
  lib/admin.php
  lib/common.php
  tests/api/reports-products-stats.php
  tests/reports/class-wc-tests-reports-orders.php
  tests/reports/class-wc-tests-reports-products.php
  tests/reports/class-wc-tests-reports-revenue-stats.php
Labels: [Status] Needs Review

#627 Activity Panel: Inbox: Correctly define admin notes REST API schema
  includes/api/class-wc-admin-rest-admin-notes-controller.php
Labels: [Status] Ready to Merge

#620 Make Orders placeholder table have the correct sorted column
  client/analytics/report/orders/table.js
Labels: Analytics, [Status] Ready to Merge

#623 Move Revenue table to its own component
  client/analytics/report/revenue/chart.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/table.js
  client/analytics/report/revenue/test/table.js
Labels: Analytics, [Status] Ready to Merge

#640 Removes phpcs from npm run lint
  package.json
Labels: [Status] Needs Review

#628 Add file doc block to fix linting issue
  includes/wc-admin-order-functions.php
Labels: [Status] Ready to Merge

#641 Fix errors in lib/common.php
  lib/common.php
Labels: [Status] Needs Review

#645 Fixes PHP 5.2 compatibility issues
  includes/class-wc-admin-reports-orders-stats-query.php
Labels: [Status] Ready to Merge

#647 Fixes PHP 5.2 compatibility issues
  includes/class-wc-admin-reports-products-stats-query.php
Labels: [Status] Ready to Merge

#646 Fixes PHP 5.2 compatibility issues
  includes/class-wc-admin-reports-products-query.php
Labels: [Status] Ready to Merge

#642 Fix linting errors in tests/test-sample.php
  tests/test-sample.php
Labels: [Status] Ready to Merge

#643 Fixes lints in class-wc-admin-reports-data-store
  includes/class-wc-admin-reports-interval.php
  includes/data-stores/class-wc-admin-reports-data-store.php
Labels: [Status] Needs Review

#644 Fixes lints in lib/admin.php
  lib/admin.php
Labels: [Status] Ready to Merge

#650 Fixes PHP errors caused by linting fixes
  lib/common.php
Labels: [Status] Ready to Merge

#568 Fix/date params persistence
  client/layout/controller.js
  client/lib/date/index.js
  client/lib/date/test/index.js
  client/lib/nav-utils/index.js
Labels: [Status] Ready to Merge

#652 Move Download table logic inside the TableCard component
  client/analytics/report/orders/table.js
  client/analytics/report/revenue/__mocks__/revenue-mock-csv.js
  client/analytics/report/revenue/__mocks__/revenue-mock-data.js
  client/analytics/report/revenue/table.js
  client/analytics/report/revenue/test/table.js
  client/components/table/__mocks__/table-mock-csv.js
  client/components/table/__mocks__/table-mock-data.js
  client/components/table/__mocks__/table-mock-headers.js
  client/components/table/index.js
  client/components/table/test/index.js
  client/lib/csv/index.js
  client/lib/csv/test/index.js
Labels: Components, [Status] Ready to Merge, [Tests] Includes Tests

#619 Products table
  client/analytics/report/orders/table.js
  client/analytics/report/products/__mocks__/data.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/components/table/index.js
  client/components/table/placeholder.js
  client/store/products/reducer.js
  client/store/products/resolvers.js
  client/store/products/selectors.js
  client/store/products/test/reducer.js
  client/store/products/test/resolvers.js
  client/store/products/test/selectors.js
  lib/client-assets.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#639 Chart: remove year from x2-axis tick if present in previous tick
  client/components/chart/test/utils.js
  client/components/chart/utils.js
Labels: Analytics, Components, Dashboard, [Status] Needs Design Review

#618 Adds php compatibility range for phpcs
  phpcs.xml.dist
Labels: [Status] Ready to Merge

#665 Move margin of screen options/help up a little bit
  client/header/style.scss
Labels: Design, [Status] Ready to Merge, [Type] Enhancement

#653 Fixes PHP 5.2 compatibility issues
  includes/class-wc-admin-reports-revenue-query.php
Labels: [Status] Ready to Merge

#677 Build: Update babel config
  .babelrc
  babel.config.js
  package.json
Labels: Build, [Status] Needs Review

#656 Updates wc-admin menu order and entries #624
  lib/admin.php
Labels: [Status] Needs Review

#635 Chart: remove last x-axis tick in an uneven series
  client/components/chart/utils.js
Labels: Analytics, Components, Dashboard, [Status] Ready to Merge

#671 Persist date params in Products table link
  client/analytics/report/products/table.js
  client/components/filters/filter/index.js
  client/layout/controller.js
  client/lib/nav-utils/index.js
  client/lib/nav-utils/test/index.js
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#649 Activity Panel: Inbox: When the user updates WooCommerce, add a note alerting that the store notice setting has moved
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/panels/inbox.js
  includes/api/class-wc-admin-rest-admin-notes-controller.php
  includes/class-wc-admin-notes-new-sales-record.php
  includes/class-wc-admin-notes-settings-notes.php
  wc-admin.php
Labels: [Status] Ready to Merge

#688 remove rounded corners from activity bar icon buttons
  client/header/activity-panel/style.scss
Labels: Activity Panel, Components, Design, [Status] Ready to Merge

#679 Dashboard: Add DatePicker
  client/dashboard/index.js
  package-lock.json
Labels: [Status] Ready to Merge

#540 Component - chart: adjust chart height and dots
  client/components/chart/index.js
  client/components/chart/utils.js
Labels: Analytics, Dashboard, [Status] Ready to Merge

#686 Create QUERY_DEFAULTS object with default values for queries
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/table.js
  client/header/activity-panel/panels/inbox.js
  client/lib/date/index.js
  client/store/constants.js
Labels: [Status] Ready to Merge

#684 Bug: ensure duplicate parts of date removed from x2 ticks
  client/components/chart/utils.js
Labels: Analytics, Components, Dashboard, [Status] Ready to Merge, [Type] Bug

#701 Reverse the order highlighted points are rendered in charts
  client/components/chart/utils.js
Labels: Components, [Status] Ready to Merge

#706 Fixes hover background on first column in tables
  client/components/table/style.scss
Labels: [Status] Needs Review

#658 Updates default analytics menu
  client/analytics/report/index.js
  client/layout/controller.js
  lib/admin.php
Labels: [Status] Ready to Merge

#591 Add/filter params to queries
  client/analytics/report/orders/config.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/components/filters/filter/index.js
  client/components/filters/filter/utils.js
  client/store/reports/test/utils.js
  client/store/reports/utils.js
  package-lock.json
  tests/js/setup-globals.js
Labels: [Status] Needs Review

#713 Add isLoading prop to TableCard
  client/analytics/report/orders/table.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/table.js
  client/components/table/index.js
  client/components/table/placeholder.js
  client/components/table/test/index.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
Labels: Analytics, Components, [Status] Ready to Merge, [Tests] Includes Tests

#707 Move withSelect() inside table components
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/table.js
  client/components/table/index.js
  client/components/table/placeholder.js
  client/components/table/test/index.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
Labels: Analytics, [Status] Ready to Merge

#702 Simplified compound expression to fix code for older PHP versions.
  includes/data-stores/class-wc-admin-reports-data-store.php
Labels: REST API, [Status] Ready to Merge

#717 Fix: date params were no longer persisted when navigating pages
  client/layout/controller.js
Labels: [Status] Needs Review

#720 Fix automattically fixable php lint warnings
  includes/api/class-wc-admin-rest-reports-products-stats-controller.php
Labels: [Status] Ready to Merge

#723 Fix code comment
  client/store/products/selectors.js
Labels: [Status] Needs Review

#730 Adds PHPCS autofixer command to npm scripts
  package.json
Labels: [Status] Ready to Merge

#728 Add stylelint
  .stylelintrc.json
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#729 Stylelint autofixes
  client/components/calendar/style.scss
  client/components/chart/style.scss
  client/components/count/style.scss
  client/components/ellipsis-menu/style.scss
  client/components/split-button/style.scss
  client/components/table/style.scss
  client/header/activity-panel/style.scss
  client/header/style.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/shared/_reset.scss
Labels: [Status] Ready to Merge

#737 Fix spelling of "average" in "average order value" in orders report
  client/analytics/report/orders/chart.js
Labels: Analytics, Components

#687 Added zero-padding to hours coming from the db.
  includes/class-wc-admin-reports-interval.php
Labels: REST API, [Status] Ready to Merge

#710 Return correct object for REST products controller.
  includes/data-stores/class-wc-admin-reports-products-data-store.php
Labels: REST API, [Status] Ready to Merge

#716 Move tooltip below the chart when there is limited horizontal space
  client/components/chart/index.js
  client/components/chart/style.scss
  client/components/chart/utils.js
Labels: Components, [Status] Needs Design Review, [Status] Ready to Merge

#678 Try: Add Lerna to split out utility packages
  .gitignore
  .travis.yml
  bin/packages/build.js
  bin/packages/get-babel-config.js
  bin/packages/get-packages.js
  bin/packages/post-css-config.js
  bin/packages/watch.js
  bin/pre-commit-hook.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/table.js
  client/components/calendar/index.js
  client/components/chart/legend.js
  client/components/chart/utils.js
  client/components/filters/date/compare-periods.js
  client/components/filters/date/index.js
  client/components/filters/date/preset-periods.js
  client/dashboard/top-selling-products/index.js
  client/dashboard/top-selling-products/test/index.js
  client/header/activity-panel/panels/orders.js
  client/store/reports/utils.js
  includes/data-stores/class-wc-admin-reports-data-store.php
  lerna.json
  lib/client-assets.php
  package-lock.json
  package.json
  packages/currency/.npmrc
  packages/currency/README.md
  packages/currency/package.json
  packages/currency/src/index.js
  packages/currency/test/index.js
  packages/date/.npmrc
  packages/date/README.md
  packages/date/package.json
  packages/date/src/index.js
  packages/date/test/index.js
  tests/js/jest.config.json
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, Extensibility, [Status] Ready to Merge

#689 Adds Section Header component
  client/components/card/index.js
  client/components/index.js
  client/components/section-header/example.md
  client/components/section-header/index.js
  client/components/section-header/style.scss
  client/components/section-header/test/__snapshots__/index.js.snap
  client/components/section-header/test/index.js
  client/components/table/style.scss
  client/dashboard/store-performance/index.js
Labels: [Status] Needs Review

#736 Hide Clear filter button when no filters are selected
  client/components/filters/advanced/index.js
  client/components/filters/compare/index.js
Labels: Analytics, [Status] Ready to Merge

#613 Update order summary in Orders report
  client/analytics/report/orders/table.js
  client/components/table/index.js
  client/components/table/style.scss
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-reports-orders-stats-query.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  tests/reports/class-wc-tests-reports-orders.php
  tests/reports/class-wc-tests-reports-revenue-stats.php
Labels: REST API, [Status] In Progress
