Repository woocommerce/woocommerce-admin, pull requests merged in 2019-09, with the labels that each got.

#2857 Onboarding: Add "Customize Appearance" task
  client/dashboard/task-list/index.js
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/appearance.js
  client/wc-api/constants.js
  client/wc-api/onboarding/constants.js
  client/wc-api/onboarding/operations.js
  client/wc-api/options/index.js
  client/wc-api/options/mutations.js
  client/wc-api/options/operations.js
  client/wc-api/options/selectors.js
  client/wc-api/wc-api-spec.js
  src/API/Init.php
  src/API/Options.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Needs Design Review, [Status] Ready to Merge

#2862 Onboarding: Add task list toggle option
  client/dashboard/index.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2863 Onboarding - add quick testing links for Calypso flows
  src/API/OnboardingPlugins.php
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2799 scroll import action to import section of settings page
  client/analytics/settings/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/scroll-to/index.js
  src/Notes/WC_Admin_Notes_Historical_Data.php
Labels: Activity Panel, Components, Inbox, Packages, [Status] Ready to Merge, [Type] Tweak

#2845 Fix Report Column and Indicator Labels
  client/analytics/components/leaderboard/test/index.js
  client/analytics/report/categories/config.js
  client/analytics/report/categories/table.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/config.js
  client/analytics/report/taxes/config.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/store-performance/index.js
  src/API/Reports/Coupons/Stats/Controller.php
  src/API/Reports/Downloads/Stats/Controller.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/PerformanceIndicators/Controller.php
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Revenue/Stats/Controller.php
  tests/api/reports-performance-indicators.php
Labels: Design, [Status] Ready to Merge, [Type] Task

#2832 Queue customer lookup updates.
  src/API/Reports/Customers/DataStore.php
  src/ReportsSync.php
  tests/api/reports-customers.php
  tests/api/reports-downloads-stats.php
  tests/api/reports-downloads.php
  tests/api/reports-import.php
  tests/framework/helpers/class-wc-helper-queue.php
Labels: [Status] Ready to Merge, [Type] Tweak

#2874 use correct path for NAMESPACE import in task-list
  client/dashboard/task-list/tasks/connect.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#2881 Fix: persist date_last_active for customer reports
  src/API/Reports/Customers/DataStore.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#2871 Fix chart type buttons misalignment
  packages/components/src/chart/style.scss
Labels: Components, Packages, [Status] Ready to Merge, [Type] Bug

#2868 Onboarding: Add "Import products" step
  client/dashboard/task-list/tasks/appearance.js
  src/API/Init.php
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
  tests/api/onboarding-tasks.php
Labels: Onboarding, [Status] Ready to Merge

#2870 Use upstream webpack-rtl-plugin
  package.json
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#2889 Onboarding: Add create homepage logic to "Customize Appearance" step
  client/dashboard/task-list/index.js
  client/dashboard/task-list/tasks/appearance.js
  client/wc-api/options/mutations.js
  client/wc-api/options/operations.js
  client/wc-api/options/selectors.js
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
  tests/api/onboarding-tasks.php
Labels: Onboarding, [Status] Needs Review

#2922 Fix variable name typo
  src/ReportsSync.php
  tests/batch-queue.php
Labels: [Status] Ready to Merge

#2898 indent cleanup, remove blank line before class closing brace
  src/API/Coupons.php
  src/API/Data.php
  src/API/DataCountries.php
  src/API/ProductCategories.php
  src/API/Reports/Categories/Controller.php
  src/API/Reports/Categories/DataStore.php
  src/API/Reports/Categories/Query.php
  src/API/Reports/Customers/DataStore.php
  src/API/Reports/Customers/Query.php
  src/API/Reports/Customers/Stats/Query.php
  src/API/Reports/DataStore.php
  src/API/Reports/Downloads/DataStore.php
  src/API/Reports/Downloads/Query.php
  src/API/Reports/Downloads/Stats/DataStore.php
  src/API/Reports/Downloads/Stats/Query.php
  src/API/Reports/Orders/DataStore.php
  src/API/Reports/Orders/Query.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/Orders/Stats/Query.php
  src/API/Reports/Products/Query.php
  src/API/Reports/Products/Stats/DataStore.php
  src/API/Reports/Query.php
  src/API/Reports/Revenue/Query.php
  src/API/Reports/Stock/Stats/Query.php
  src/API/Reports/Taxes/Query.php
  src/API/Reports/Taxes/Stats/DataStore.php
  src/API/Reports/Taxes/Stats/Query.php
  src/API/Reports/Variations/DataStore.php
  src/API/Reports/Variations/Query.php
  src/API/SettingOptions.php
  src/Notes/DataStore.php
  src/Notes/NoteTraits.php
Labels: [Status] Ready to Merge, [Type] Dev

#2916 Removed extra semicolon and line end whitespaces
  src/FeaturePlugin.php
Labels: [Status] Needs Review

#2819 Add filter to notes datastore where clauses
  src/Notes/DataStore.php
Labels: [Status] Ready to Merge, [Type] Dev

#2941 Only build pushes to master branch.
  .travis.yml
Labels: Build, [Status] Needs Review, [Type] Dev

#2917 Refactor: Alternative approach to implementing extendable settings from the server
  client/analytics/components/report-table/index.js
  client/analytics/report/customers/config.js
  client/analytics/report/customers/table.js
  client/analytics/report/index.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/stock/index.js
  client/analytics/report/stock/table.js
  client/analytics/settings/config.js
  client/analytics/settings/index.js
  client/dashboard/components/settings/general/store-address.js
  client/dashboard/leaderboards/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/store-performance/index.js
  client/dashboard/task-list/index.js
  client/dashboard/task-list/tasks/shipping/rates.js
  client/devdocs/example.js
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/unread-indicators.js
  client/settings/fallbacks.js
  client/settings/index.js
  packages/components/src/advanced-filters/docs/example.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/chart/index.js
  packages/components/src/filters/docs/example.js
  packages/currency/src/index.js
  packages/currency/test/index.js
  packages/date/src/index.js
  packages/date/test/index.js
  packages/number/src/index.js
  packages/number/src/test/index.js
  src/Features/ActivityPanels.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Loader.php
  tests/js/jest.config.json
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, Components, Packages, [Status] In Progress, [Status] Needs Review, [Type] Enhancement

#2944 Fix pull request branch detection on CI (try #2)
  bin/install-wp-tests.sh
Labels: Build, [Status] Needs Review, [Type] Dev

#2945 Fix pull request branch detection on CI (try #3)
  bin/install-wp-tests.sh
Labels: Build, [Status] Ready to Merge, [Type] Dev

#2933 Reduce size of bundled JS, and overall plugin file size.
  client/embedded.js
  client/index.js
  client/stylesheets/_embedded.scss
  client/stylesheets/_index.scss
  src/Loader.php
  webpack.config.js
Labels: Build, [Status] Ready to Merge, [Type] Performance

#2950 Fix plugin installation when working from a push instead of a pull request.
  bin/install-wp-tests.sh
Labels: Build, [Status] Needs Review, [Type] Dev

#2940 Add GitHub pages deploy step to Travis config.
  .travis.yml
Labels: Build, Documentation, [Status] Ready to Merge, [Type] Dev

#2948 Leaderboards: fix rename from getSettings
  client/dashboard/leaderboards/index.js
Labels: [Status] Ready to Merge

#2873 add DevDocs for ScrollTo component
  client/devdocs/examples.json
  docs/components/_sidebar.md
  packages/components/src/scroll-to/docs/example.js
Labels: Components, Packages, [Status] Needs feedback

#2952 Copy component READMEs to docs folder before GH page deploy.
  .travis.yml
Labels: Build, [Status] Ready to Merge, [Type] Dev

#2846 Fix conflict with Blocks 2.4
  src/Loader.php
  src/PageController.php
Labels: [Status] Ready to Merge, [Type] Bug

#2907 Fix vendor scripts not autoloading
  bin/travis.sh
  includes/core-functions.php
  tests/api/reports-downloads.php
  tests/bootstrap.php
Labels: Build, [Status] Ready to Merge, [Type] Bug

#2962 Fix DevDocs example render.
  client/devdocs/example.js
  packages/components/src/advanced-filters/docs/example.js
Labels: Components, Documentation, Packages, [Status] Needs Review, [Type] Dev

#2963 Update README.md and CONTRIBUTING.md (moving and adding)
  CONTRIBUTING.md
  README.md
Labels: Documentation, [Status] Ready to Merge

#2967 Ignore filename rules for PSR-4 classes.
  phpcs.xml.dist
Labels: Build, [Status] Needs Review, [Type] Dev

#2946 0.19.0 release changes
  package-lock.json
  package.json
  packages/components/src/scroll-to/README.md
  readme.txt
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, Components, Packages, [Status] Needs Review

#2899 Add ability to receive an emailed download link to report export endpoint.
  includes/emails/html-admin-report-export-download.php
  includes/emails/plain-admin-report-export-download.php
  src/API/Reports/Export/Controller.php
  src/ReportCSVEmail.php
  src/ReportExporter.php
Labels: Analytics, REST API, [Status] Needs Review, [Type] Enhancement

#2964 Fix `npm run build` resulting in non functional app.
  package.json
Labels: Build, [Type] Bug

#2971 Remove unnecessary duplicate logic
  client/settings/fallbacks.js
Labels: [Status] Ready to Merge, [Type] Bug

#2920 Simplified intervals_missing method of DataStore class
  src/API/Reports/DataStore.php
Labels: [Status] Ready to Merge

#2919 Simplified intervals_missing method of TimeInterval class
  src/API/Reports/TimeInterval.php
Labels: [Status] Ready to Merge

#2974 wcSettings: fix countries getSettings
  client/analytics/report/customers/config.js
  client/analytics/report/customers/table.js
  client/dashboard/components/settings/general/store-address.js
Labels: [Status] Needs Review
