Repository woocommerce/woocommerce-admin, pull requests merged in 2019-06, with the labels that each got.

#2368 Misspelling at update config.jp
  client/analytics/report/customers/config.js
Labels: [Type] Fix

#2369 Double space at 191 row
  client/analytics/report/customers/config.js
Labels: [Type] Fix

#2191 Low stock handling inconsistencies with WooCommerce 3.6+
  client/analytics/report/stock/table.js
  client/analytics/report/stock/utils.js
  includes/api/class-wc-admin-rest-products-controller.php
  includes/api/class-wc-admin-rest-reports-stock-controller.php
  includes/data-stores/class-wc-admin-reports-stock-stats-data-store.php
Labels: [Status] Ready to Merge

#2362 Remove second beta warning from readme
  readme.txt
Labels: [Status] Ready to Merge, [Type] Task

#2378 Don't create Notices tab in Activity Panel if notices HTML element was removed by a plugin
  client/header/activity-panel/index.js
Labels: [Status] Needs Review, [Type] Bug

#2352 Fix wrong average numbers in chart legends
  client/analytics/components/report-chart/index.js
  docs/examples/extensions/dashboard-section/js/global-prices.js
  packages/components/CHANGELOG.md
  packages/components/src/chart/index.js
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Type] Bug

#2312 Add progress bars to Historical Data Import screen
  client/analytics/settings/historical-data/actions.js
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/historical-data/layout.js
  client/analytics/settings/historical-data/progress.js
  client/analytics/settings/historical-data/status.js
  client/analytics/settings/historical-data/style.scss
  client/analytics/settings/historical-data/test/utils.js
  client/analytics/settings/historical-data/utils.js
  client/wc-api/imports/operations.js
  client/wc-api/imports/selectors.js
  includes/api/class-wc-admin-rest-reports-import-controller.php
  includes/class-wc-admin-reports-sync.php
  tests/api/reports-import.php
Labels: [Status] Needs Design Review, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#2227 Notes: Add filters to disable milestone and sales record notes.
  includes/notes/class-wc-admin-notes-new-sales-record.php
  includes/notes/class-wc-admin-notes-order-milestones.php
Labels: [Status] Ready to Merge

#2193 Add tracks to import jobs
  includes/class-wc-admin-reports-sync.php
Labels: [Status] Ready to Merge

#2292 Settings: Add default date settings
  client/analytics/settings/config.js
  client/analytics/settings/default-date.js
  client/analytics/settings/index.js
  client/analytics/settings/setting.js
  client/analytics/settings/setting.scss
  includes/class-wc-admin-loader.php
  packages/components/CHANGELOG.md
  packages/components/src/filters/date/index.js
  packages/components/src/filters/index.js
  packages/date/src/index.js
  tests/js/setup-globals.js
Labels: Components, Dashboard, Packages, [Type] Enhancement

#2347 Add onbaording step 7 - Business Details
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Needs Review

#2086 Add date_created_gmt property to orders endpoint
  includes/api/class-wc-admin-rest-reports-orders-controller.php
  includes/class-wc-admin-install.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php
  tests/api/reports-orders.php
Labels: Activity Panel, [Status] Ready to Merge

#2325 Trigger an action server side when admin note actions are clicked
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/panels/inbox.js
  client/layout/store-alerts/index.js
  client/wc-api/notes/mutations.js
  client/wc-api/notes/operations.js
  includes/api/class-wc-admin-rest-admin-note-action-controller.php
  includes/api/class-wc-admin-rest-admin-notes-controller.php
  includes/class-wc-admin-api-init.php
  includes/data-stores/class-wc-admin-notes-data-store.php
  includes/notes/class-wc-admin-note.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#2399 Remove table data on plugin uninstall
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-install.php
  includes/notes/class-wc-admin-notes.php
  uninstall.php
  woocommerce-admin.php
Labels: [Status] Ready to Merge, [Type] Bug

#2402 Add uninstall file to release ZIP
  bin/build-plugin-zip.sh
Labels: Build, [Status] Ready to Merge

#2401 Cancel all scheduled actions on plugin deactivation
  uninstall.php
  woocommerce-admin.php
Labels: [Status] Ready to Merge, [Type] Bug

#2387 Improve hidden tab suppression/fix rapid requests
  client/wc-api/wc-api-spec.js
  client/wc-api/wp-data-store/create-api-client.js
Labels: [Status] Needs Review, [Type] Bug

#2397 Notes: update sales record link
  includes/class-wc-admin-events.php
  includes/notes/class-wc-admin-notes-new-sales-record.php
Labels: [Status] Ready to Merge, [Type] Fix, [Type] Tweak

#2405 Fix Activity Panel layout on mobile
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/panels/inbox.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/panels/reviews.js
  client/header/activity-panel/panels/stock/card.js
  client/header/activity-panel/panels/stock/index.js
Labels: Activity Panel, [Status] Ready to Merge

#2385 Fix some data not to being imported when 'skip_existing' option is enabled
  includes/class-wc-admin-reports-sync.php
Labels: [Status] Needs feedback, [Status] Ready to Merge, [Type] Bug

#2409 Release 0.13.0
  docs/components/_sidebar.md
  docs/components/analytics/report-chart.md
  docs/components/analytics/report-summary.md
  docs/components/packages/card.md
  docs/components/packages/chart.md
  docs/components/packages/filters.md
  docs/components/packages/spinner.md
  docs/components/packages/stepper.md
  package-lock.json
  package.json
  readme.txt
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#2420 Tag Version 0.13.2 for release
  package-lock.json
  package.json
  readme.txt
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#2414 Prevent multiple imports from running simultaneously
  includes/class-wc-admin-reports-sync.php
  tests/api/reports-import.php
Labels: REST API, [Status] Ready to Merge, [Type] Bug

#2384 Fix search bar in Orders page not being tapable on mobile
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_reset.scss
Labels: [Status] Ready to Merge, [Type] Bug

#2407 Update Amount of Orders to Number of Orders throughout
  includes/api/class-wc-admin-rest-reports-categories-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-controller.php
  includes/api/class-wc-admin-rest-reports-coupons-stats-controller.php
  includes/api/class-wc-admin-rest-reports-orders-stats-controller.php
  includes/api/class-wc-admin-rest-reports-revenue-stats-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-controller.php
  includes/api/class-wc-admin-rest-reports-taxes-stats-controller.php
  tests/api/reports-performance-indicators.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#2422 Table queries: remove befor/after from no interval endpoints
  client/wc-api/reports/utils.js
Labels: [Status] Ready to Merge

#2412 Add changelog script
  bin/changelog.js
  package-lock.json
  package.json
Labels: Build, [Status] Needs Review

#2417 Fix revenue and orders charts using the wrong endpoint in the Dashboard
  client/dashboard/dashboard-charts/config.js
Labels: Dashboard, [Status] Ready to Merge

#2423 Performance indicators - bail whenever an internal API request fails.
  includes/api/class-wc-admin-rest-reports-performance-indicators-controller.php
  includes/class-wc-admin-loader.php
Labels: Dashboard, [Status] Ready to Merge, [Type] Fix

#2431 Fix conflicts with WordPress.com toolbar
  client/header/style.scss
  client/stylesheets/shared/_reset.scss
Labels: Activity Panel, [Status] Ready to Merge

#2432 Remove unnecessary WP style dependencies.
  includes/class-wc-admin-loader.php
Labels: Components, [Status] Ready to Merge, [Type] Tweak

#2429 Update Dashboard Charts naming and order
  client/dashboard/dashboard-charts/block.js
  client/dashboard/dashboard-charts/config.js
  client/dashboard/dashboard-charts/index.js
Labels: Dashboard, [Status] Ready to Merge

#2433 Changelog: Omit unmerged pull requests
  bin/changelog.js
Labels: Build, [Status] Ready to Merge, [Type] Fix

#2438 Remove test menu from Orders panel
  client/header/activity-panel/panels/orders.js
Labels: Activity Panel, [Status] Ready to Merge, [Type] Task

#2228 add match=any support for advanced orders table filter
  includes/api/class-wc-admin-rest-reports-orders-controller.php
  includes/class-wc-admin-reports-orders-query.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
Labels: [Status] Ready to Merge, [Type] Bug

#2424 Add test to catch missing version updates.
  bin/update-version.php
  tests/plugin-version.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Tweak

#2425 Action Scheduler: fix potential endless sync
  includes/class-wc-admin-reports-sync.php
  includes/data-stores/class-wc-admin-reports-coupons-data-store.php
  includes/data-stores/class-wc-admin-reports-taxes-data-store.php
Labels: [Status] Ready to Merge

#2446 Fix Activity Panel being overlapped by editor toolbar
  client/header/style.scss
Labels: Activity Panel, [Status] Ready to Merge

#2437 Changelog script: Use PR author note, if supplied
  .github/PULL_REQUEST_TEMPLATE.md
  bin/changelog.js
Labels: Build, [Status] Ready to Merge

#2447 Allow keyboard interaction in Stock Activity Panel form
  client/header/activity-panel/panels/stock/card.js
Labels: Accessibility, Activity Panel, [Status] Ready to Merge

#2418 Refactor customer name retrieval
  includes/class-wc-admin-order-refund.php
  includes/class-wc-admin-order.php
  includes/data-stores/class-wc-admin-reports-customers-data-store.php
  tests/api/reports-customers.php
  tests/api/reports-import.php
Labels: [Status] Ready to Merge, [Type] Bug

#2428 Prevent duplicate customer imports
  includes/data-stores/class-wc-admin-reports-customers-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php
Labels: [Status] Needs Review, [Type] Bug

#2440 Report Tables: Add example extension
  client/analytics/components/report-table/index.js
  docs/examples/extensions/table-column/js/index.js
  docs/examples/extensions/table-column/woocommerce-admin-table-column.php
  packages/components/src/rating/style.scss
Labels: Build, Components, Extensibility, Packages, [Status] Ready to Merge, [Type] Enhancement

#2460 Add wp-api-fetch script to dependencies
  includes/class-wc-admin-loader.php
Labels: [Status] Ready to Merge, [Type] Dev

#2457 fix type in readme changelog for 0.13.0
  readme.txt
Labels: Documentation, [Type] Fix

#2464 Check for good WC_Orders before using instance methods.
  includes/class-wc-admin-order-refund.php
  includes/data-stores/class-wc-admin-reports-customers-data-store.php
  includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php
  tests/api/orders.php
  tests/api/reports-customers.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug, [Type] Fix

#2472 Fix mobile onboarding stepper positioning
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#2468 Update onboarding track setting
  client/dashboard/profile-wizard/steps/start/index.js
Labels: Onboarding

#2467 Onboarding: Pull dynamic prices for product types
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Enhancement

#2441 Remove the "wpClosedMenu" page setting
  client/layout/controller.js
Labels: Build, [Status] Ready to Merge

#2488 Table extension: fix page error and jsDoc
  client/analytics/components/report-table/index.js
  docs/examples/extensions/table-column/js/index.js
Labels: [Status] Ready to Merge

#2498 Activity Panels: Add track event when panels are opened.
  client/header/activity-panel/index.js
  client/lib/tracks.js
  package-lock.json
  package.json
Labels: Build, [Status] Needs Review

#2493 Onboarding: Add theme step and theme browser
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
  client/dashboard/profile-wizard/style.scss
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Needs Review

#2502 Add Reports CSV Exporter Class
  includes/api/class-wc-admin-rest-reports-orders-controller.php
  includes/api/class-wc-admin-rest-reports-products-controller.php
  includes/export/class-wc-admin-report-csv-exporter.php
  tests/reports/class-wc-tests-reports-coupons.php
  woocommerce-admin.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#2492 Add a filter to allow other extensions to register new WC-Admin-powered pages
  client/layout/controller.js
  client/layout/index.js
Labels: Build, [Status] Needs Review

#2521 Fix batch queue range bug.
  includes/class-wc-admin-reports-sync.php
  tests/batch-queue.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#2442 Remove updated stock products from Activity Panel
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/panels/stock/card.js
  client/wc-api/items/mutations.js
  client/wc-api/items/operations.js
  client/wc-api/wc-api-spec.js
  includes/api/class-wc-admin-rest-products-controller.php
  includes/class-wc-admin-loader.php
Labels: Activity Panel, [Status] Ready to Merge, [Type] Enhancement

#2462 open external note action links in a new tab
  client/header/activity-panel/panels/inbox.js
Labels: Activity Panel, Inbox, [Status] Ready to Merge

#2507 release 0.14.0
  package-lock.json
  package.json
  readme.txt
  woocommerce-admin.php
Labels: [Status] Ready to Merge

#2532 Tracks: Fix double wcadmin_ prefix.
  client/header/activity-panel/index.js
  client/lib/tracks.js
Labels: [Status] Needs Review

#2503 Add installed themes and WooCommerce support to theme browser
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2529 Remove hover on Card component
  packages/components/src/card/style.scss
Labels: Components, Onboarding, Packages, [Status] Ready to Merge

#2519 remove double slash from image urls, use string for download ID
  tests/api/data.php
  tests/api/reports-downloads-stats.php
  tests/api/reports-downloads.php
  tests/api/reports-performance-indicators.php
Labels: [Status] Ready to Merge, [Type] Dev

#2496 Test that REST controllers work with their default parameters.
  includes/api/class-wc-admin-rest-orders-controller.php
  includes/api/class-wc-admin-rest-reports-performance-indicators-controller.php
  tests/api/report-controllers.php
  tests/bootstrap.php
Labels: REST API, [Status] Ready to Merge, [Tests] Includes Tests

#2487 Remove style that causes incorrect margins for certain notices
  client/stylesheets/shared/_embed.scss
Labels: [Status] Ready to Merge, [Type] Fix

#2539 Always return columns in ‘posts_fields’ filters.
  includes/api/class-wc-admin-rest-products-controller.php
Labels: REST API, [Status] Ready to Merge, [Type] Bug

#2537 Fixes issue with alerts on mobile
  client/layout/store-alerts/style.scss
  package-lock.json
Labels: [Status] Needs Review, [Type] Fix

#2463 Add State alongside City (and other customer info).
  client/analytics/report/customers/table.js
  includes/api/class-wc-admin-rest-reports-customers-controller.php
  includes/class-wc-admin-install.php
  includes/data-stores/class-wc-admin-reports-customers-data-store.php
  tests/api/reports-customers.php
Labels: Analytics, [Status] Ready to Merge, [Type] Enhancement

#2525 Advanced Filters: Add Tracks events
  client/analytics/components/report-filters/index.js
  client/analytics/report/categories/index.js
  client/analytics/report/coupons/index.js
  client/analytics/report/customers/index.js
  client/analytics/report/downloads/index.js
  client/analytics/report/orders/index.js
  client/analytics/report/products/index.js
  client/analytics/report/revenue/index.js
  client/analytics/report/stock/index.js
  client/analytics/report/taxes/index.js
  client/lib/tracks.js
  packages/components/src/filters/advanced/index.js
  packages/components/src/filters/filter/index.js
  packages/components/src/filters/index.js
Labels: Components, Packages, [Status] Ready to Merge
