Repository woocommerce/woocommerce-admin, pull requests merged in 2019-07, with the labels that each got.

#2531 Onboarding - Profile Wizard: Add tracks events
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/steps/theme/index.js
Labels: [Status] Ready to Merge

#2548 Customizable dashboard: handle turned off feature flag
  client/dashboard/index.js
Labels: [Status] Ready to Merge

#2546 Stock notifs: fix low_stock_amount for variations
  includes/api/class-wc-admin-rest-products-controller.php
Labels: [Status] Ready to Merge, [Type] Fix

#2550 Dashboard: Add Tracks events
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/leaderboards/index.js
  client/dashboard/store-performance/index.js
Labels: Dashboard, [Status] Ready to Merge

#2543 Add error checking for failed remote gets
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#2554 Examples: Update README
  docs/examples/extensions/README.md
Labels: [Status] Needs Review

#2552 Ignore empty wp notice elements.
  client/header/activity-panel/wordpress-notices.js
Labels: [Status] Ready to Merge

#2560 Send tracks event for snoozing store alerts.
  client/layout/store-alerts/index.js
Labels: [Status] Ready to Merge, [Type] Task

#2559 Add tracks event to Store Alert and Inbox Notification action clicks
  includes/api/class-wc-admin-rest-admin-note-action-controller.php
  includes/class-wc-admin-reports-sync.php
  includes/core-functions.php
Labels: [Status] Ready to Merge, [Type] Task

#2544 Settings: Better structure to settings page, and protect form changes
  client/analytics/settings/historical-data/layout.js
  client/analytics/settings/index.js
  package-lock.json
Labels: [Status] Needs Design Review, [Status] Needs Review

#2444 Route handling: Remove hash in favor of path parameter
  client/dashboard/dashboard-charts/block.js
  client/header/activity-panel/panels/orders.js
  client/layout/controller.js
  client/layout/index.js
  client/layout/test/index.js
  docs/README.md
  docs/documentation.md
  includes/api/class-wc-admin-rest-leaderboards-controller.php
  includes/api/class-wc-admin-rest-onboarding-plugins-controller.php
  includes/class-wc-admin-loader.php
  includes/core-functions.php
  includes/notes/class-wc-admin-notes-historical-data.php
  includes/notes/class-wc-admin-notes-new-sales-record.php
  includes/notes/class-wc-admin-notes-order-milestones.php
  includes/page-controller/class-wc-admin-page-controller.php
  packages/components/src/link/index.js
  packages/navigation/CHANGELOG.md
  packages/navigation/src/history.js
  packages/navigation/src/index.js
  tests/api/leaderboards.php
Labels: Components, Packages, [Status] Ready to Merge

#2557 Tracks: Add chart and table events
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/categories/index.js
Labels: [Status] Ready to Merge, [Type] Task

#2534 Set default values for onboarding select dropdowns
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#2526 Add Report CSV Export Endpoint
  docs/examples/extensions/table-column/woocommerce-admin-table-column.php
  includes/api/class-wc-admin-rest-reports-export-controller.php
  includes/class-wc-admin-api-init.php
  includes/export/class-wc-admin-report-csv-exporter.php
  includes/export/class-wc-admin-report-exporter.php
  tests/api/reports-export.php
  tests/bootstrap.php
  woocommerce-admin.php
Labels: Analytics, REST API, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#2561 Remove placeholder "learn more" link from excluded status setting.
  client/analytics/settings/config.js
Labels: [Status] Ready to Merge, [Type] Task

#2524 Packages: prepare for release
  packages/README.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/csv-export/CHANGELOG.md
  packages/csv-export/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/number/CHANGELOG.md
  packages/number/package.json
Labels: Build, Components, Packages, [Status] Ready to Merge

#2556 Onboarding: Update theme order and sorting
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2575 Update color-studio to 1.0.5
  package-lock.json
  package.json
Labels: Build, Packages, [Status] Ready to Merge

#2569 Add countLabel prop to SearchListItem
  packages/components/CHANGELOG.md
  packages/components/src/search-list-control/item.js
  packages/components/src/search-list-control/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#2551 Onboarding - Add business extension recommendations
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/start/style.scss
  client/dashboard/profile-wizard/style.scss
  images/onboarding/facebook.png
  images/onboarding/mailchimp.png
  includes/api/class-wc-admin-rest-onboarding-profile-controller.php
  tests/api/onboarding-profile.php
Labels: Onboarding, [Status] Ready to Merge

#2562 Header: Adjust sizes at all breakpoints
  client/analytics/components/report-table/style.scss
  client/header/activity-panel/style.scss
  client/header/style.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_embed.scss
Labels: [Status] Ready to Merge

#2568 Add a theme REST API to allow uploading themes
  includes/api/class-wc-admin-rest-themes-controller.php
  includes/class-wc-admin-api-init.php
  includes/class-wc-admin-theme-upgrader-skin.php
  includes/class-wc-admin-theme-upgrader.php
  includes/features/onboarding/class-wc-admin-onboarding.php
  tests/api/themes.php
Labels: Onboarding, REST API, [Status] Needs Review

#2491 Allow each page to specify their breadcrumbs without having to render the Header component
  client/analytics/index.js
  client/analytics/report/index.js
  client/analytics/settings/index.js
  client/dashboard/index.js
  client/devdocs/index.js
  client/embedded.js
  client/header/README.md
  client/header/index.js
  client/index.js
  client/layout/controller.js
  client/layout/index.js
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#2597 Update components package 3.1.0
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/csv-export/CHANGELOG.md
  packages/currency/CHANGELOG.md
  packages/date/CHANGELOG.md
  packages/navigation/CHANGELOG.md
  packages/number/CHANGELOG.md
Labels: Build, Components, Packages, [Status] Ready to Merge

#2577 Settings: Fix wsod when no actionable statuses are set.
  client/analytics/settings/config.js
  includes/class-wc-admin-loader.php
Labels: [Status] Ready to Merge

#2571 ReportTable: Add back in ids array generation.
  client/analytics/components/report-table/index.js
Labels: [Status] Needs Review

#2580 Onboarding: Add theme uploader component
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
  client/dashboard/profile-wizard/steps/theme/uploader.js
  includes/api/class-wc-admin-rest-themes-controller.php
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Needs Design Review, [Status] Needs Review

#2596 Update to new Snackbar component and notice store
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/index.js
  client/analytics/settings/setting.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/embedded.js
  client/index.js
  client/layout/transient-notices/index.js
  client/layout/transient-notices/style.scss
  client/layout/transient-notices/transient-notice.js
  client/store/index.js
  client/store/notices/actions.js
  client/store/notices/index.js
  client/store/notices/reducers.js
  client/store/notices/selectors.js
  client/store/notices/test/fixtures/index.js
  client/store/notices/test/index.js
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_gutenberg-components.scss
  client/wc-api/items/mutations.js
  package-lock.json
  package.json
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  webpack.config.js
Labels: Build, Onboarding, [Status] Needs Review

#2602 restore devdocs URLs after hash removal
  client/devdocs/index.js
Labels: Documentation, [Status] Ready to Merge

#2593 Notes: Only check for scheduled snooze action hourly
  includes/notes/class-wc-admin-notes.php
Labels: [Status] In Progress

#2573 Notes: Type cast is_snoozeable on insert.
  includes/data-stores/class-wc-admin-notes-data-store.php
  tests/api/admin-notes.php
  tests/framework/helpers/class-wc-helper-admin-notes.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#2484 use summary query to total coupons per order
  includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php
  tests/reports/class-wc-tests-reports-orders-stats.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests

#2607 Fix: propType validation warnings on embedded pages
  client/layout/index.js
Labels: [Status] Ready to Merge

#2594 Tracks: Fix Link onclick
  client/analytics/components/report-filters/index.js
  packages/components/src/filters/advanced/index.js
  packages/components/src/link/index.js
Labels: Components, Packages, [Status] Ready to Merge

#2610 Append '(optional)' to address line 2 label
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Onboarding, [Status] Ready to Merge

#2611 Fix margin around onboarding inputs
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#2612 exclude old WC auto-draft orders from import
  client/analytics/settings/historical-data/layout.js
  includes/class-wc-admin-reports-sync.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#2616 Add list component to packages.
  client/devdocs/examples.json
  docs/components/_sidebar.md
  docs/components/packages/list.md
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/list/example.md
  packages/components/src/list/index.js
  packages/components/src/list/style.scss
  packages/components/src/style.scss
Labels: Components, Onboarding, Packages, [Status] Needs Review

#2619 show example extension list as list in readme
  docs/examples/extensions/README.md
Labels: Documentation, [Status] Ready to Merge, [Type] Dev

#2618 Add instructions for translating to contributing docs.
  CONTRIBUTING.md
  README.md
  languages/README.md
Labels: Documentation, [Status] Ready to Merge, [Type] Task

#2621 Onboarding: Change margins on industry intro paragraph.
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/style.scss
Labels: [Status] Needs Design Review, [Status] Needs Review

#2630 Onboarding: Fix checkbox group label color
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#2629 Fix margin between theme price and buttons
  client/dashboard/profile-wizard/steps/theme/style.scss
Labels: Onboarding, [Status] Ready to Merge

#2634 Revert "Update to new Snackbar component and notice store"
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/index.js
  client/analytics/settings/setting.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/embedded.js
  client/index.js
  client/layout/transient-notices/index.js
  client/layout/transient-notices/style.scss
  client/layout/transient-notices/transient-notice.js
  client/store/index.js
  client/store/notices/actions.js
  client/store/notices/index.js
  client/store/notices/reducers.js
  client/store/notices/selectors.js
  client/store/notices/test/fixtures/index.js
  client/store/notices/test/index.js
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_gutenberg-components.scss
  client/wc-api/items/mutations.js
  package-lock.json
  package.json
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  webpack.config.js
Labels: Build, [Status] Needs Review

#2637 Fix "page" parameter collision between routing and table pagination.
  client/analytics/report/revenue/table.js
  client/layout/controller.js
  client/wc-api/reports/utils.js
  packages/components/src/table/index.js
Labels: Analytics, Components, Packages, Release Blocker, [Status] Ready to Merge, [Type] Bug

#2645 Disable placeholder animation when prefers-reduced-motion is set
  client/stylesheets/abstracts/_mixins.scss
Labels: Accessibility, [Status] Ready to Merge, [Type] Fix

#2633 Add priority 2 Tracks events
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-table/index.js
  client/header/index.js
  packages/components/CHANGELOG.md
  packages/components/src/filters/advanced/index.js
  packages/components/src/table/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Task

#2640 Tests setup: bring in Woo Core dependencies
  bin/install-wp-tests.sh
Labels: Build, [Status] Needs Review

#2646 Chart: Remove z-index from empty message
  packages/components/CHANGELOG.md
  packages/components/src/chart/d3chart/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#2641 Prep for release 0.15.0
  docs/components/analytics/report-summary.md
  docs/components/packages/filters.md
  docs/components/packages/list.md
  docs/components/packages/search-list-control.md
  package.json
  readme.txt
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#2617 Update onboarding form validation
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#2631 Update padding for checkbox group cards
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Needs Design Review, [Status] Ready to Merge

#2655 Replace 'stringifyQuery' with 'addQueryArgs'
  client/analytics/settings/historical-data/index.js
  client/lib/async-requests/index.js
  client/wc-api/imports/operations.js
  client/wc-api/items/operations.js
  client/wc-api/notes/operations.js
  client/wc-api/reports/items/operations.js
  client/wc-api/reports/stats/operations.js
  client/wc-api/reviews/operations.js
  package.json
  packages/components/src/search/autocompleters/categories.js
  packages/components/src/search/autocompleters/coupons.js
  packages/components/src/search/autocompleters/customers.js
  packages/components/src/search/autocompleters/download-ips.js
  packages/components/src/search/autocompleters/emails.js
  packages/components/src/search/autocompleters/orders.js
  packages/components/src/search/autocompleters/product.js
  packages/components/src/search/autocompleters/taxes.js
  packages/components/src/search/autocompleters/usernames.js
  packages/components/src/search/autocompleters/variations.js
  packages/navigation/CHANGELOG.md
  packages/navigation/README.md
  packages/navigation/src/index.js
Labels: Build, Components, Packages, [Status] Ready to Merge, [Type] Dev

#2638 Add priority 3 Tracks events
  client/analytics/components/report-table/index.js
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/index.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/index.js
  packages/components/src/pagination/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Task

#2658 Onboarding: Update help tab with reset onboarding link
  includes/core-functions.php
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2661 Nav: Hide nav on block editor.
  includes/page-controller/class-wc-admin-page-controller.php
Labels: [Status] Ready to Merge

#2662 Activity Panels: Fix notification indicator css.
  client/header/activity-panel/style.scss
Labels: [Status] Needs Design Review, [Status] Ready to Merge

#2598 Implement "Simple" Select Component
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/style.scss
  client/devdocs/examples.json
  docs/components/_sidebar.md
  docs/components/packages/simple-select-control.md
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/simple-select-control/example.md
  packages/components/src/simple-select-control/index.js
  packages/components/src/simple-select-control/style.scss
  packages/components/src/spinner/example.md
  packages/components/src/style.scss
Labels: Components, Onboarding, Packages, [Status] Needs Review

#2654 Onboarding: Add the task list dashboard
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/style.scss
  client/dashboard/style.scss
  client/dashboard/task-list/index.js
  client/dashboard/task-list/style.scss
  client/stylesheets/abstracts/_variables.scss
  includes/class-wc-admin-loader.php
  packages/components/src/list/style.scss
  packages/date/test/index.js
Labels: Components, Onboarding, Packages, [Status] Needs Design Review, [Status] Needs Review

#2659 Reduce order status change delay in Orders Panel.
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/unread-indicators.js
  includes/api/class-wc-admin-rest-reports-orders-controller.php
  includes/data-stores/class-wc-admin-reports-orders-data-store.php
Labels: Activity Panel, REST API, [Status] Ready to Merge, [Type] Task

#2663 Webpack: Use wp.url instead of bundling package
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#2667 Onboarding: Add products task
  client/dashboard/index.js
  client/dashboard/task-list/index.js
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/products.js
  includes/features/onboarding/class-wc-admin-onboarding-tasks.php
  includes/features/onboarding/class-wc-admin-onboarding.php
  packages/components/src/list/index.js
  packages/components/src/list/style.scss
Labels: Components, Onboarding, Packages, [Status] Needs Review

#2678 update assertisWPError calls to assertWPError in unit tests
  tests/api/reports-interval.php
Labels: [Status] Ready to Merge, [Type] Dev

#2673 Fix flash of unstyled content for onboarding pages
  client/dashboard/profile-wizard/index.js
  client/dashboard/style.scss
  client/layout/style.scss
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#2676 Fix missing nav on connected admin pages.
  includes/features/onboarding/class-wc-admin-onboarding.php
  includes/page-controller/class-wc-admin-page-controller.php
Labels: [Status] Ready to Merge, [Type] Bug

#2660 Settings: Fix notice shown after save.
  client/wc-api/settings/selectors.js
Labels: [Status] Ready to Merge

#2677 Notice: Update feedback notice verbiage and action.
  includes/notes/class-wc-admin-notes-giving-feedback-notes.php
Labels: [Status] Ready to Merge

#2674 Remove path from URL in root/dashboard page
  packages/navigation/src/index.js
Labels: Onboarding, Packages, [Status] Needs Review, [Type] Bug

#2643 Revert "Revert "Update to new Snackbar component and notice store""
  README.md
  bin/install-wp-tests.sh
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/index.js
  client/analytics/settings/setting.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/uploader.js
  client/embedded.js
  client/index.js
  client/layout/transient-notices/index.js
  client/layout/transient-notices/style.scss
  client/layout/transient-notices/transient-notice.js
  client/store/index.js
  client/store/notices/actions.js
  client/store/notices/index.js
  client/store/notices/reducers.js
  client/store/notices/selectors.js
  client/store/notices/test/fixtures/index.js
  client/store/notices/test/index.js
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_gutenberg-components.scss
  client/wc-api/items/mutations.js
  package-lock.json
  package.json
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  readme.txt
  webpack.config.js
  woocommerce-admin.php
Labels: Build, [Status] Needs Review, [Type] Task

#2689 add filter to feature config array
  woocommerce-admin.php
Labels: [Status] Ready to Merge, [Type] Dev

#2687 Only apply current submenu CSS reset on non-embed pages.
  client/stylesheets/_index.scss
  client/stylesheets/shared/_reset.scss
Labels: [Status] Ready to Merge, [Type] Bug

#2698 Fix react-spring breaking IE11.
  webpack.config.js
Labels: Build, Release Blocker, [Status] Ready to Merge, [Type] Bug

#2701 Prevent onboarding from running on non-admin pages
  includes/features/onboarding/class-wc-admin-onboarding.php
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#2703 Automate pre-release tasks
  bin/changelog.js
  bin/pre-release.sh
  package.json
Labels: Build, [Status] Needs Review

#2705 Fix vertical centering in onboarding theme step
  client/dashboard/profile-wizard/steps/theme/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#2699 Ensure content to wrapper alignment during Activity Panel transitions
  client/header/activity-panel/index.js
  client/header/activity-panel/style.scss
Labels: [Status] Ready to Merge

#2708 Fix groupby for category segmentation in reports.
  includes/class-wc-admin-reports-coupons-stats-segmenting.php
  includes/class-wc-admin-reports-orders-stats-segmenting.php
  includes/class-wc-admin-reports-products-stats-segmenting.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#2715 Add theme demo track events
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/preview.js
Labels: Onboarding, [Status] Ready to Merge
