Repository woocommerce/woocommerce-admin, pull requests merged in 2019-12, with the labels that each got.

#3325 Packages: Prep for release.
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/csv-export/CHANGELOG.md
  packages/csv-export/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/number/CHANGELOG.md
  packages/number/package.json
Labels: Build, Components, Packages, [Priority] High, [Status] Needs Review

#3302 Remove Newspack Dependency
  client/analytics/settings/historical-data/style.scss
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/product-types.js
  client/dashboard/profile-wizard/steps/start/index.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/preview.js
  client/dashboard/profile-wizard/steps/theme/style.scss
  client/dashboard/profile-wizard/steps/usage-modal.js
  client/dashboard/profile-wizard/style.scss
  client/dashboard/style.scss
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/appearance.js
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/klarna.js
  client/dashboard/task-list/tasks/payments/paypal.js
  client/dashboard/task-list/tasks/payments/square.js
  client/dashboard/task-list/tasks/payments/stripe.js
  client/dashboard/task-list/tasks/shipping/rates.js
  client/dashboard/task-list/tasks/steps/connect.js
  client/dashboard/task-list/tasks/steps/location.js
  client/dashboard/task-list/tasks/steps/plugins.js
  client/dashboard/task-list/tasks/tax.js
  client/devdocs/examples.json
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_global.scss
  docs/components/_sidebar.md
  package-lock.json
  package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/image-upload/README.md
  packages/components/src/image-upload/docs/example.js
  packages/components/src/image-upload/index.js
  packages/components/src/image-upload/style.scss
  packages/components/src/image-upload/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
  packages/components/src/text-control/style.scss
  tests/js/jest.config.json
  webpack.config.js
Labels: [Status] Ready to Merge

#3332 Onboarding: Update getCurrencyFormatString import to use wc-admin lib
  client/dashboard/task-list/tasks/shipping/rates.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3321 Onboarding: Update appearance task completion criteria
  client/dashboard/task-list/tasks.js
  client/dashboard/task-list/tasks/appearance.js
Labels: Onboarding, [Status] Ready to Merge

#3323 Onboarding: Allow logo to be removed via customize appearance task
  client/dashboard/task-list/tasks/appearance.js
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#3316 Onboarding: Format product count ranges numbers without decimals
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3331 Onboarding: Redirect to task list after shipping step connection
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/steps/connect.js
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#3324 Onboarding: Update global currency settings on address change
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/lib/currency-format.js
  packages/currency/src/index.js
Labels: Onboarding, Packages, [Type] Bug

#3337 Fix button margin on plugins screen
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#3336 Remove extra debug information for onboarding plugins install
  src/API/OnboardingPlugins.php
Labels: Onboarding

#3333 account for time change when calculating next day start
  src/API/Reports/TimeInterval.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3350 add filter to allow WC Admin to be disabled
  src/FeaturePlugin.php
Labels: On Merge to WC Core, [Status] Ready to Merge, [Type] Enhancement

#3362 Fix JS error on DevDocs
  client/lib/date.js
  packages/components/src/date-range-filter-picker/docs/example.js
  packages/components/src/filters/docs/example.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Bug

#3328 Add currency extension
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/revenue/table.js
  client/dashboard/customizable.js
  client/wc-api/reports/utils.js
  docs/examples/extensions/sql-modification/js/index.js
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
  package-lock.json
  packages/navigation/CHANGELOG.md
  packages/navigation/src/index.js
  src/API/Reports/Coupons/Stats/Query.php
Labels: Packages, [Status] Ready to Merge

#3339 Stardardize hooks
  CONTRIBUTING.md
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
  src/API/NoteActions.php
  src/API/Notes.php
  src/API/OnboardingProfile.php
  src/API/Reports/Categories/DataStore.php
  src/API/Reports/Categories/Query.php
  src/API/Reports/Coupons/DataStore.php
  src/API/Reports/Coupons/Query.php
  src/API/Reports/Coupons/Stats/Query.php
  src/API/Reports/Customers/DataStore.php
  src/API/Reports/Customers/Query.php
  src/API/Reports/Customers/Stats/Query.php
  src/API/Reports/DataStore.php
  src/API/Reports/Downloads/Query.php
  src/API/Reports/Downloads/Stats/DataStore.php
  src/API/Reports/Downloads/Stats/Query.php
  src/API/Reports/Orders/Query.php
  src/API/Reports/Orders/Stats/DataStore.php
  src/API/Reports/Orders/Stats/Query.php
  src/API/Reports/PerformanceIndicators/Controller.php
  src/API/Reports/Products/DataStore.php
  src/API/Reports/Products/Query.php
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Products/Stats/DataStore.php
  src/API/Reports/Products/Stats/Query.php
  src/API/Reports/Revenue/Query.php
  src/API/Reports/SqlQuery.php
  src/API/Reports/Stock/Stats/Query.php
  src/API/Reports/Taxes/DataStore.php
  src/API/Reports/Taxes/Query.php
  src/API/Reports/Taxes/Stats/Controller.php
  src/API/Reports/Taxes/Stats/DataStore.php
  src/API/Reports/Taxes/Stats/Query.php
  src/API/Reports/Variations/Query.php
  src/FeaturePlugin.php
  src/Features/Analytics.php
  src/Install.php
  src/Loader.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Note.php
  src/PageController.php
  src/ReportsSync.php
  tests/api/onboarding-profile.php
Labels: On Merge to WC Core, [Status] Needs Review, [Type] Dev

#3361 Add/disable plugin filter
  src/FeaturePlugin.php
Labels: [Status] Ready to Merge, [Type] Tweak

#3245 Onboarding: Update check for TOS accepted in tax step
  client/dashboard/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3371 Release 0.23.0 changes
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3395 Release/0.23.1
  package.json
  src/FeaturePlugin.php
  src/Features/Onboarding.php
  src/Package.php
  woocommerce-admin.php
Labels: Build

#3397 Onboarding: Reduce number of queries needed to update logo
  client/dashboard/task-list/tasks/appearance.js
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge

#3398 Onboarding: Update the tracking usage modal copy
  client/dashboard/profile-wizard/steps/usage-modal.js
Labels: Onboarding, [Status] Ready to Merge

#3359 make report filter date props optional
  packages/components/src/filters/index.js
Labels: Components, Extensibility, Packages, [Status] Ready to Merge, [estimate] 1

#3386 don't load analytics dashboard for users without needed capability
  src/Loader.php
Labels: Activity Panel, [Status] Ready to Merge, [Type] Bug

#3358 Fix revenue question translation with currency conversion
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/utils.js
  packages/currency/src/index.js
Labels: Onboarding, Packages, [Status] Ready to Merge

#3402 Onboarding - Add button to continue setup after importing products
  client/dashboard/task-list/tasks/products.js
  client/wp-admin-scripts/onboarding-product-import-notice/index.js
  src/Features/OnboardingTasks.php
  webpack.config.js
Labels: Build, Onboarding

#3347 Default the Calypso environment to production
  src/API/OnboardingPlugins.php
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3400 Onboarding: Update shipping task button text
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/shipping/rates.js
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#3340 Onboarding: Fix error if product types are missing
  client/dashboard/index.js
  client/dashboard/profile-wizard/steps/theme/index.js
Labels: Onboarding, [Type] Bug

#3388 update customer rest controller for last active date in local time
  src/API/Reports/Customers/Controller.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3389 Fix missing header on core pages.
  includes/connect-existing-pages.php
Labels: Activity Panel, [Status] Ready to Merge, [Type] Fix

#3338 Add autocomplete props to address fields in onboarding and adjust country/state matching
  client/dashboard/components/settings/general/store-address.js
Labels: Onboarding, [Status] Ready to Merge

#3417 Install latest stable WC for running builds.
  bin/install-wp-tests.sh
Labels: Build, [Status] Ready to Merge, [Type] Fix

#3393 Bump minimum WP version to 5.3
  README.md
  bin/install-wp-tests.sh
  docs/README.md
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3357 Fix WC-Admin component styles for WP 5.3
  client/analytics/components/report-table/index.js
  client/layout/store-alerts/index.js
  client/layout/store-alerts/style.scss
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/shared/_global.scss
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/style.scss
  packages/components/src/dropdown-button/style.scss
  packages/components/src/ellipsis-menu/style.scss
  packages/components/src/pagination/style.scss
  packages/components/src/search/style.scss
  packages/components/src/split-button/index.js
  packages/components/src/split-button/style.scss
  packages/components/src/split-button/test/__snapshots__/index.js.snap
  packages/components/src/table/style.scss
  packages/components/src/text-control-with-affixes/README.md
  packages/components/src/text-control-with-affixes/docs/example.js
  packages/components/src/text-control-with-affixes/index.js
  packages/components/src/text-control-with-affixes/style.scss
Labels: Build, Components, Design, Packages, [Status] Ready to Merge, [Type] Fix

#3403 Add starter pack script
  bin/starter-pack/._gitignore
  bin/starter-pack/_README.md
  bin/starter-pack/_main.php
  bin/starter-pack/_package.json
  bin/starter-pack/_webpack.config.js
  bin/starter-pack/src/index.js
  bin/starter-pack/src/index.scss
  bin/starter-pack/starter-pack.js
  package.json
Labels: Build, [Status] Ready to Merge

#3421 Fix CompareFilter selected value format.
  packages/components/CHANGELOG.md
  packages/components/src/compare-filter/index.js
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Type] Bug

#3418 AssetDataRegistry: update SQL example
  docs/examples/extensions/README.md
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
Labels: [Status] Needs Review

#3404 Documentation: Add base directory and files
  docs/woocommerce.com/README.md
  docs/woocommerce.com/analytics-basics.md
  docs/woocommerce.com/analytics-categories-report.md
  docs/woocommerce.com/analytics-coupons-report.md
  docs/woocommerce.com/analytics-customers-report.md
  docs/woocommerce.com/analytics-downloads-report.md
  docs/woocommerce.com/analytics-historical-data-import.md
  docs/woocommerce.com/analytics-orders-report.md
  docs/woocommerce.com/analytics-products-report.md
  docs/woocommerce.com/analytics-revenue-report.md
  docs/woocommerce.com/analytics-settings.md
  docs/woocommerce.com/analytics-stock-report.md
  docs/woocommerce.com/analytics-taxes-report.md
Labels: Documentation, [Status] Ready to Merge

#3427 Fix the "is this card useful" prompt display
  client/dashboard/task-list/index.js
  client/dashboard/task-list/style.scss
Labels: Onboarding, [Status] Ready to Merge

#3429 Add moment dependency to script registration.
  src/Loader.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3428 Fix user data fields filter name.
  src/Features/ActivityPanels.php
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
Labels: Dashboard, [Status] Ready to Merge, [Type] Bug

#3390 scroll to notices when made visible while scrolled down
  client/header/activity-panel/wordpress-notices.js
Labels: Activity Panel, [Status] Ready to Merge, [Type] Tweak

#3434 Allow report caching layer to be filtered off.
  src/API/Reports/DataStore.php
  tests/reports/class-wc-tests-reports-orders-stats.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#3391 Add filters to WP notice collapsing behavior.
  client/header/activity-panel/style.scss
  client/header/activity-panel/wordpress-notices.js
  docs/examples/extensions/important-admin-notice/js/index.js
  docs/examples/extensions/important-admin-notice/woocommerce-admin-important-admin-notice-example.php
Labels: Activity Panel, Extensibility, [Status] Ready to Merge, [Type] Enhancement

#3454 Prompt user for branch/commit to base releases on.
  bin/pre-release.sh
Labels: Build, [Status] Ready to Merge

#3453 Bump version to 0.23.2.
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge, [Type] Task

#3443 Update instructions for documenting new components.
  docs/documentation.md
Labels: Components, Documentation, [Status] Ready to Merge, [Type] Dev

#3444 Add purchase modal at the end of the profile wizard
  client/dashboard/index.js
  client/dashboard/profile-wizard/cart-modal.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/style.scss
  client/dashboard/utils.js
  client/wc-api/onboarding/selectors.js
  src/Features/Onboarding.php
Labels: Onboarding

#3459 Show pending review regardless of comment moderation settings
  client/header/activity-panel/panels/reviews.js
  client/header/activity-panel/unread-indicators.js
Labels: Activity Panel, [Status] Ready to Merge, [Type] Fix

#3473 Fix errant DB migrations.
  src/Install.php
Labels: [Many] Large, [Status] Ready to Merge, [Type] Bug

#3419 DataStores: normalize contexts to plural
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
  src/API/Reports/Coupons/Stats/DataStore.php
  src/API/Reports/Customers/Stats/DataStore.php
  src/API/Reports/Downloads/Stats/DataStore.php
  src/API/Reports/Orders/Stats/DataStore.php
  src/API/Reports/Products/Stats/DataStore.php
  src/API/Reports/Taxes/Stats/DataStore.php
Labels: [Status] Ready to Merge

#3465 Invalidate cache on settings change
  src/API/SettingOptions.php
Labels: Analytics, REST API, Settings, [Status] Ready to Merge, [Type] Fix

#3483 Onboarding: Add in tracks for failed plugin installation
  src/API/OnboardingPlugins.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3485 Onboarding: Don't show skip link if no plugins exist to skip
  client/dashboard/profile-wizard/steps/start/index.js
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#3486 Onboarding: Skip Shipping connect step if Jetpack is already connected
  client/dashboard/task-list/tasks/shipping/index.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3471 Onboarding: Add another option to platforms.
  client/dashboard/profile-wizard/steps/business-details.js
  src/API/OnboardingProfile.php
Labels: Onboarding, [Status] Needs Review

#3482 Onboarding: Add theme install and activation endpoints
  src/API/Init.php
  src/API/OnboardingPlugins.php
  src/API/OnboardingThemes.php
  src/Features/Onboarding.php
  tests/api/onboarding-plugins.php
  tests/api/onboarding-themes.php
Labels: Onboarding, REST API, [Status] Ready to Merge, [Tests] Includes Tests

#3484 Onboarding: Install free themes during profiler
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/utils.js
  src/API/OnboardingThemes.php
Labels: Onboarding, [Status] Needs Review

#3433 update i18n scripts for making JSON files
  CONTRIBUTING.md
  babel.config.js
  bin/combine-pot-files.php
  bin/make-i18n-json.sh
  languages/README.md
  package.json
Labels: Build, [Status] Ready to Merge, [Type] Dev

#3489 Fix button color when no demo present.
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
Labels: [Status] Ready to Merge, [Type] Fix

#3494 Onboarding: Add error styling and text to country state dropdown
  client/dashboard/components/settings/general/store-address.js
  client/dashboard/style.scss
  packages/components/src/select-control/control.js
  packages/components/src/select-control/index.js
Labels: Components, Onboarding, Packages, [Status] Ready to Merge, [Type] Bug

#3492 Onboarding: Fix disabled button hover state
  client/dashboard/style.scss
  client/stylesheets/shared/_global.scss
Labels: Onboarding, [Status] Ready to Merge

#3472 Onboarding: Add purchase products task list item
  client/dashboard/components/cart-modal.js
  client/dashboard/customizable.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/task-list/index.js
  client/dashboard/task-list/tasks.js
  client/dashboard/utils.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3475 Tag version 0.23.3
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3490 Onboarding: Add Skip Step link on Themes Step
  client/dashboard/profile-wizard/steps/theme/index.js
Labels: Onboarding, [Status] Ready to Merge
