Repository woocommerce/woocommerce-admin, pull requests merged in 2020-06, with the labels that each got.

#4462 Fix error handling for plugins on server error
  packages/components/src/plugins/index.js
  packages/components/src/plugins/test/index.js
  packages/data/src/plugins/actions.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Bug

#4386 Inbox notification: add client unit tests
  client/header/activity-panel/panels/inbox/test/index.js
  tests/api/admin-notes.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#4474 SelectControl: Select search result options by clicking on item text or icon in Firefox and Safari
  packages/components/src/select-control/list.js
Labels: Components, Packages, [Status] Ready to Merge

#4458 Filters: Fix static query parameters
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/customers/config.js
  client/analytics/report/downloads/config.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/config.js
  client/analytics/report/stock/config.js
  client/analytics/report/taxes/config.js
  client/layout/controller.js
Labels: [Status] Needs feedback, [Status] Ready to Merge

#4451 Add WooCommerce Subscriptions note
  src/Events.php
  src/Notes/WC_Admin_Notes_WooCommerce_Subscriptions.php
Labels: [Status] Ready to Merge

#4218 Inbox notification: layout changes
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-header/index.js
  client/header/activity-panel/activity-header/style.scss
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/inbox/placeholder.js
  client/header/activity-panel/panels/inbox/style.scss
  client/header/activity-panel/panels/inbox/test/index.js
  client/header/activity-panel/panels/inbox/utils.js
  client/stylesheets/abstracts/_colors.scss
  client/wc-api/notes/mutations.js
  client/wc-api/notes/operations.js
  client/wc-api/notes/selectors.js
  client/wc-api/wc-api-spec.js
  docs/examples/activity-panel-inbox.md
  src/API/NoteActions.php
  src/API/Notes.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
  src/Notes/WC_Admin_Notes_Draw_Attention.php
  src/Notes/WC_Admin_Notes_EU_VAT_Number.php
  src/Notes/WC_Admin_Notes_Giving_Feedback_Notes.php
  src/Notes/WC_Admin_Notes_Historical_Data.php
  src/Notes/WC_Admin_Notes_Install_JP_And_WCS_Plugins.php
  src/Notes/WC_Admin_Notes_Marketing.php
  src/Notes/WC_Admin_Notes_Migrate_From_Shopify.php
  src/Notes/WC_Admin_Notes_Mobile_App.php
  src/Notes/WC_Admin_Notes_New_Sales_Record.php
  src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php
  src/Notes/WC_Admin_Notes_Onboarding_Payments.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/Notes/WC_Admin_Notes_Order_Milestones.php
  src/Notes/WC_Admin_Notes_Personalize_Store.php
  src/Notes/WC_Admin_Notes_Tracking_Opt_In.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
  src/Notes/WC_Admin_Notes_Woo_Subscriptions_Notes.php
  tests/api/admin-notes.php
  tests/framework/helpers/class-wc-helper-admin-notes.php
  tests/notes/class-wc-tests-marketing-notes.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: [Status] Ready to Merge

#4179 Add scrollable styling to left side of Table, and keep updated
  packages/components/src/table/style.scss
  packages/components/src/table/table.js
Labels: Components, Packages

#4450 Homescreen: Add option to disable
  client/dashboard/index.js
  client/layout/controller.js
  client/layout/index.js
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Loader.php
Labels: [Status] Ready to Merge

#4345 Fix the WCPay method not appearing as recommended sometimes
  client/task-list/tasks/payments/index.js
Labels: [Status] Ready to Merge

#4481 Jetpack stats on home page
  client/dashboard/store-performance/index.js
  client/dashboard/store-performance/utils.js
  client/homepage/stats-overview/defaults.js
  client/homepage/stats-overview/stats-list.js
  packages/components/src/summary/number.js
  src/API/Reports/PerformanceIndicators/Controller.php
Labels: Components, Packages, [Status] Needs Review

#4143 Remote inbox notification delivery
  config/core.json
  config/development.json
  config/plugin.json
  src/DateTimeProvider/CurrentDateTimeProvider.php
  src/DateTimeProvider/DateTimeProviderInterface.php
  src/Events.php
  src/FeaturePlugin.php
  src/Install.php
  src/Notes/WC_Admin_Note.php
  src/PluginsProvider/PluginsProvider.php
  src/PluginsProvider/PluginsProviderInterface.php
  src/RemoteInboxNotifications/DataSourcePoller.php
  src/RemoteInboxNotifications/EvaluateAndGetStatus.php
  src/RemoteInboxNotifications/FailRuleProcessor.php
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/NotRuleProcessor.php
  src/RemoteInboxNotifications/OrRuleProcessor.php
  src/RemoteInboxNotifications/PassRuleProcessor.php
  src/RemoteInboxNotifications/PluginVersionRuleProcessor.php
  src/RemoteInboxNotifications/PluginsActivatedRuleProcessor.php
  src/RemoteInboxNotifications/PublishAfterTimeRuleProcessor.php
  src/RemoteInboxNotifications/PublishBeforeTimeRuleProcessor.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
  src/RemoteInboxNotifications/RuleEvaluator.php
  src/RemoteInboxNotifications/RuleProcessorInterface.php
  src/RemoteInboxNotifications/SpecRunner.php
  tests/remote-inbox-notifications/evaluate-and-get-status.php
  tests/remote-inbox-notifications/failing-rule-evaluator.php
  tests/remote-inbox-notifications/get-rule-processor.php
  tests/remote-inbox-notifications/mock-date-time-provider.php
  tests/remote-inbox-notifications/mock-get-rule-processor.php
  tests/remote-inbox-notifications/mock-plugins-provider.php
  tests/remote-inbox-notifications/not-rule-processor.php
  tests/remote-inbox-notifications/or-rule-processor.php
  tests/remote-inbox-notifications/passing-rule-evaluator.php
  tests/remote-inbox-notifications/plugin-version-rule-processor.php
  tests/remote-inbox-notifications/plugins-activated-rule-processor.php
  tests/remote-inbox-notifications/publish-after-time-rule-processor.php
  tests/remote-inbox-notifications/publish-before-time-rule-processor.php
Labels: [Status] Needs Review

#4490 Correctly set parent path when a wc-admin registered page is used as a breadcrumb parent
  src/PageController.php
  tests/page-controller.php
Labels: Marketing, [Status] Needs Review, [Tests] Includes Tests, [Type] Enhancement

#4501 Usage of URLSearchParams breaks in IE11
  client/header/activity-panel/panels/inbox/card.js
  client/layout/controller.js
  client/utils/README.md
  client/utils/index.js
  client/utils/test/index.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#4496 Inbox panel on the home screen
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/inbox/style.scss
  client/homepage/layout.js
  client/homepage/test/index.js
Labels: Home Screen, [Status] Ready to Merge

#4511 Home Screen: Only show "Store management" (Quick Links) card if "Store setup" (Task List) card is not shown.
  client/homepage/layout.js
Labels: Home Screen, [Status] Ready to Merge

#4517 Update task list title
  client/task-list/index.js
Labels: Home Screen, [Status] Ready to Merge

#4522 Correctly remove reference to debounced updateSliderHeight method
  client/marketing/components/slider/index.js
Labels: Marketing, [Status] Ready to Merge

#4484 Fixed missing 'items' in collection params
  src/API/Reports/Customers/Controller.php
  src/API/Reports/Customers/Stats/Controller.php
Labels: [Status] Needs Review

#4495 Refactor and add tests for the marketing WelcomeCard component
  client/marketing/overview/welcome-card/index.js
  client/marketing/overview/welcome-card/test/index.js
Labels: Marketing, [Status] Needs Review, [Tests] Includes Tests

#4414 Homepage: Style SummaryNumbers
  bin/packages/build.js
  bin/packages/post-css-config.js
  client/homepage/stats-overview/style.scss
  client/homepage/stats-overview/test/stats-list.js
  client/quick-links/style.scss
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_global.scss
  client/stylesheets/shared/_gutenberg-components.scss
  packages/components/src/date-range-filter-picker/style.scss
  packages/components/src/segmented-selection/style.scss
  packages/components/src/summary/number.js
  packages/components/src/summary/placeholder.js
  packages/components/src/summary/style.scss
  postcss.config.js
  webpack.config.js
Labels: Build, Components, Packages, [Status] Needs Review

#4427 Update/@wordpress components base styles
  bin/packages/build.js
  bin/packages/post-css-config.js
  client/analytics/components/report-table/style.scss
  client/dashboard/style.scss
  client/homepage/stats-overview/style.scss
  client/homepage/stats-overview/test/index.js
  client/homepage/stats-overview/test/stats-list.js
  client/layout/store-alerts/index.js
  client/quick-links/style.scss
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_global.scss
  client/stylesheets/shared/_gutenberg-components.scss
  package-lock.json
  package.json
  packages/components/src/chart/index.js
  packages/components/src/chart/style.scss
  packages/components/src/compare-filter/button.js
  packages/components/src/date-range-filter-picker/style.scss
  packages/components/src/dropdown-button/style.scss
  packages/components/src/filter-picker/style.scss
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  packages/components/src/section-header/style.scss
  packages/components/src/segmented-selection/style.scss
  packages/components/src/summary/number.js
  packages/components/src/summary/placeholder.js
  packages/components/src/summary/style.scss
  packages/components/src/table/table.js
  packages/components/src/tag/index.js
  packages/components/src/tag/test/__snapshots__/index.js.snap
  postcss.config.js
  webpack.config.js
Labels: Build, Components, Packages, [Status] Needs Review

#4470 Use plugins store rather than getSettings
  client/homepage/stats-overview/install-jetpack-cta.js
Labels: [Status] Ready to Merge

#4542 Fix loading of RTL styles in chunks.
  package-lock.json
  package.json
  src/Features/ShippingLabelBanner.php
  src/Loader.php
  webpack.config.js
Labels: Build, [Status] Ready to Merge, [Type] Bug

#4144 Options: Add data store
  client/dashboard/customizable.js
  client/dashboard/utils.js
  client/homepage/layout.js
  client/layout/index.js
  client/marketing/overview/index.js
  client/marketing/overview/welcome-card/index.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/usage-modal.js
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/appearance.js
  client/task-list/tasks/payments/bacs.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/payfast.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/tasks/payments/square.js
  client/task-list/tasks/payments/stripe.js
  client/task-list/tasks/tax.js
  client/wc-api/options/index.js
  client/wc-api/options/mutations.js
  client/wc-api/options/operations.js
  client/wc-api/options/selectors.js
  client/wc-api/wc-api-spec.js
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/index.js
  packages/data/src/index.js
  packages/data/src/options/action-types.js
  packages/data/src/options/actions.js
  packages/data/src/options/constants.js
  packages/data/src/options/controls.js
  packages/data/src/options/index.js
  packages/data/src/options/reducer.js
  packages/data/src/options/resolvers.js
  packages/data/src/options/selectors.js
  packages/data/src/options/test/reducer.js
  packages/data/src/options/with-options-hydration.js
Labels: Packages, [Status] Needs Review

#4525 Add First product admin note
  src/Events.php
  src/Notes/WC_Admin_Notes_First_Product.php
Labels: [Status] Ready to Merge

#4523 Runtime feature config override
  bin/build-plugin-zip.sh
  bin/generate-feature-config.php
  client/dashboard/index.js
  client/layout/controller.js
  client/layout/index.js
  src/FeaturePlugin.php
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Loader.php
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#4508 Admin note for online clothing stores
  src/Events.php
  src/Notes/WC_Admin_Notes_Online_Clothing_Store.php
Labels: [Status] Ready to Merge

#4546 Home Screen: Update tests to account for QuickLinks
  client/homepage/test/index.js
Labels: Build, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4547 Tests: Prevent navigation warnings in tests
  client/quick-links/test/index.js
  packages/components/src/link/test/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4555 Components: Add overlooked changes to CHANGELOG.md for SelectControl, List, and Link
  packages/components/CHANGELOG.md
Labels: Components, Packages, [Status] Ready to Merge

#4548 Button: Remove deprecated isDefault
  client/analytics/settings/historical-data/actions.js
  client/analytics/settings/index.js
  client/analytics/settings/setting.js
  client/dashboard/components/cart-modal.js
  client/header/activity-panel/activity-card/test/__snapshots__/index.js.snap
  client/header/activity-panel/activity-card/test/index.js
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/panels/reviews.js
  client/header/activity-panel/panels/stock/card.js
  client/homepage/stats-overview/style.scss
  client/layout/store-alerts/index.js
  client/marketing/components/button/README.md
  client/marketing/overview/installed-extensions/row.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/steps/usage-modal.js
  client/task-list/index.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/klarna.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/tasks/payments/square.js
  client/task-list/tasks/payments/stripe.js
  client/task-list/tasks/payments/wcpay.js
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/index.js
  packages/components/src/date-range-filter-picker/content.js
Labels: [Status] Ready to Merge

#4515 Add Learn more about Product Settings note
  src/Events.php
  src/Notes/WC_Admin_Notes_Learn_More_About_Product_Settings.php
Labels: [Status] Needs Review

#4551 Update hubspot-for-woocommerce extension info
  src/Marketing/InstalledExtensions.php
Labels: Marketing, [Status] Needs Review

#4473 Create action for installing and activate plugins
  client/homepage/stats-overview/install-jetpack-cta.js
  client/lib/notices/index.js
  client/lib/notices/test/index.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/business-details.js
  packages/components/src/plugins/index.js
  packages/components/src/plugins/test/index.js
  packages/data/src/plugins/actions.js
  src/API/Plugins.php
Labels: Components, Packages, [Status] Needs Review, [Tests] Includes Tests

#4524 Refactor marketing components to make more reusable.
  client/marketing/components/knowledge-base/index.js
  client/marketing/components/knowledge-base/style.scss
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/components/recommended-extensions/index.js
  client/marketing/components/recommended-extensions/item.js
  client/marketing/components/recommended-extensions/style.scss
  client/marketing/components/recommended-extensions/test/index.js
  client/marketing/components/slider/index.js
  client/marketing/data/actions.js
  client/marketing/data/index.js
  client/marketing/data/resolvers.js
  client/marketing/data/selectors.js
  client/marketing/overview/index.js
  client/marketing/overview/knowledge-base/index.js
  client/marketing/overview/recommended-extensions/index.js
  client/marketing/overview/recommended-extensions/item.js
  src/API/Init.php
  src/API/Marketing.php
  src/API/MarketingOverview.php
  src/Features/Marketing.php
Labels: Marketing, [Status] In Progress, [Tests] Includes Tests

#4553 Use single dash for country/state dropdown options
  client/dashboard/components/settings/general/store-address.js
Labels: Onboarding, [Status] Ready to Merge

#4554 Use label tag for toggleable shipping zones
  client/task-list/tasks/shipping/rates.js
Labels: Accessibility, Onboarding, [Status] Ready to Merge

#4541 Add real time order alerts note for mobile app
  src/Events.php
  src/Notes/WC_Admin_Notes_Real_Time_Order_Alerts.php
Labels: [Status] Needs Review

#4552 Try: WC Pay payment method with custom onClick handler
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/wcpay.js
Labels: [Status] Needs Review, [Type] Try, wcpay

#4545 Task list: Add more Stripe supported countries
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#4441 Added new notification to choose a niche
  src/Events.php
  src/Notes/WC_Admin_Notes_Choose_Niche.php
Labels: Inbox, [Status] Needs Review, [Status] Needs feedback

#4561 Make it possible (far easier) to add menu items under 'Marketing'
  client/layout/controller.js
  src/Features/Marketing.php
Labels: Marketing, [Status] Ready to Merge

#4563 Fix wc-admin registered page breadcrumb path
  src/PageController.php
  tests/page-controller.php
Labels: [Status] Needs Review

#4569 Dismiss dropdown styles fixed
  client/header/activity-panel/panels/inbox/style.scss
Labels: [Status] Ready to Merge, [Type] Bug

#4507 Don't show store location in the tax and shipping tasks if it's already been provided
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/tax.js
Labels: [Status] Ready to Merge

#4509 Add Need some inspiration admin note
  src/Events.php
  src/Notes/WC_Admin_Notes_Need_Some_Inspiration.php
Labels: [Status] Ready to Merge

#4527 Add Home Screen Feedback admin note
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/WC_Admin_Notes_Home_Screen_Feedback.php
Labels: [Status] Ready to Merge

#4558 Theme color: Use dynamic variable from user preferences
  bin/packages/build.js
  client/homepage/stats-overview/style.scss
  client/quick-links/style.scss
  client/stylesheets/abstracts/_variables.scss
  package-lock.json
  package.json
  packages/components/src/summary/style.scss
  postcss.config.js
  readme.txt
  webpack.config.js
Labels: Build, Components, Packages, [Status] Ready to Merge

#4549 Rename Homepage to Homescreen
  client/dashboard/customizable.js
  client/dashboard/index.js
  client/homescreen/index.js
  client/homescreen/layout.js
  client/homescreen/stats-overview/defaults.js
  client/homescreen/stats-overview/index.js
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/homescreen/stats-overview/stats-list.js
  client/homescreen/stats-overview/style.scss
  client/homescreen/stats-overview/test/index.js
  client/homescreen/stats-overview/test/stats-list.js
  client/homescreen/style.scss
  client/homescreen/test/index.js
  client/layout/controller.js
  client/layout/index.js
  client/quick-links/stories/index.js
  config/core.json
  config/development.json
  config/plugin.json
  packages/components/src/summary/number.js
  packages/components/src/summary/style.scss
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Loader.php
Labels: Components, Packages, [Status] Ready to Merge

#4530 Check for enabled methods before payment task completion
  client/task-list/tasks/payments/index.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4531 Add note on first order creation
  src/FeaturePlugin.php
  src/Notes/WC_Admin_Notes_First_Order.php
Labels: [Status] Ready to Merge

#4574 Only mark purchase task as complete when products exist
  client/task-list/tasks.js
Labels: Onboarding, [Status] Needs Review, [Type] Bug

#4572 Add overrides for OBW styles
  client/analytics/settings/historical-data/style.scss
  client/analytics/settings/setting.js
  client/analytics/settings/setting.scss
  client/layout/style.scss
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/steps/product-types.js
  client/profile-wizard/steps/theme/style.scss
  client/profile-wizard/style.scss
  client/stylesheets/shared/_global.scss
  packages/components/src/search/style.scss
  packages/components/src/text-control/style.scss
Labels: Components, Packages

#4585 Enable homescreen in plugin and core.
  config/core.json
  config/plugin.json
Labels: [Status] Ready to Merge

#4260 Add stored state between remote inbox notification runs
  src/Notes/WC_Admin_Note.php
  src/RemoteInboxNotifications/ComparisonOperation.php
  src/RemoteInboxNotifications/DataSourcePoller.php
  src/RemoteInboxNotifications/EvaluateAndGetStatus.php
  src/RemoteInboxNotifications/FailRuleProcessor.php
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/NotRuleProcessor.php
  src/RemoteInboxNotifications/OrRuleProcessor.php
  src/RemoteInboxNotifications/OrderCountRuleProcessor.php
  src/RemoteInboxNotifications/OrdersProvider.php
  src/RemoteInboxNotifications/PassRuleProcessor.php
  src/RemoteInboxNotifications/PluginVersionRuleProcessor.php
  src/RemoteInboxNotifications/PluginsActivatedRuleProcessor.php
  src/RemoteInboxNotifications/PublishAfterTimeRuleProcessor.php
  src/RemoteInboxNotifications/PublishBeforeTimeRuleProcessor.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
  src/RemoteInboxNotifications/RuleEvaluator.php
  src/RemoteInboxNotifications/RuleProcessorInterface.php
  src/RemoteInboxNotifications/SpecRunner.php
  src/RemoteInboxNotifications/StoredStateRuleProcessor.php
  src/RemoteInboxNotifications/StoredStateSetupForProducts.php
  src/RemoteInboxNotifications/WCAdminActiveForProvider.php
  src/RemoteInboxNotifications/WCAdminActiveForRuleProcessor.php
  tests/remote-inbox-notifications/evaluate-and-get-status.php
  tests/remote-inbox-notifications/mock-wc-admin-active-for-provider.php
  tests/remote-inbox-notifications/not-rule-processor.php
  tests/remote-inbox-notifications/or-rule-processor.php
  tests/remote-inbox-notifications/plugin-version-rule-processor.php
  tests/remote-inbox-notifications/plugins-activated-rule-processor.php
  tests/remote-inbox-notifications/publish-after-time-rule-processor.php
  tests/remote-inbox-notifications/publish-before-time-rule-processor.php
  tests/remote-inbox-notifications/stored-state-rule-processor.php
  tests/remote-inbox-notifications/wcadmin-active-for-rule-processor.php
Labels: [Status] Ready to Merge

#4334 Add product count rule
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/ProductCountRuleProcessor.php
  tests/remote-inbox-notifications/mock-product-query.php
  tests/remote-inbox-notifications/product-count-rule-processor.php
Labels: [Status] Ready to Merge

#4586 G2: Remove pink/purple from ActivityPanels and Header
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-outbound-link/style.scss
  client/header/activity-panel/style.scss
  client/header/style.scss
  client/layout/style.scss
  client/stylesheets/shared/_global.scss
Labels: [Status] Needs Review

#4498 Onboarding profile rule
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/OnboardingProfileRuleProcessor.php
  src/RemoteInboxNotifications/RuleEvaluator.php
Labels: [Status] Ready to Merge

#4562 Fix Jetpack CTA primary button style
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/homescreen/stats-overview/style.scss
Labels: [Status] Needs feedback

#4573 Fix Task List styles
  client/layout/style.scss
  client/layout/transient-notices/style.scss
  client/quick-links/style.scss
  client/stylesheets/shared/_global.scss
  client/task-list/style.scss
  client/task-list/tasks/appearance.js
  packages/components/src/image-upload/index.js
  packages/components/src/image-upload/style.scss
  packages/components/src/list/style.scss
  packages/components/src/stepper/style.scss
Labels: Components, Packages, [Status] Needs Review

#4526 Add Coupon feature
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/coupons/index.js
  client/marketing/coupons/style.scss
  client/wp-admin-scripts/marketing-coupons/index.js
  config/core.json
  config/development.json
  config/plugin.json
  includes/connect-existing-pages.php
  src/FeaturePlugin.php
  src/Features/Coupons.php
  src/Features/CouponsMovedTrait.php
  src/Features/Marketing.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Notes_Coupon_Page_Moved.php
  webpack.config.js
Labels: Build, Marketing, [Status] Needs feedback

#4589 Add a bottom border to the Install Jetpack CTA
  client/homescreen/stats-overview/style.scss
Labels: [Status] Ready to Merge

#4587 Release 1.3.0-beta.1
  docs/components/_sidebar.md
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#4570 Fix column used to JOIN products to their categories.
  src/API/Reports/Categories/DataStore.php
  src/API/Reports/Coupons/Stats/Segmenter.php
  src/API/Reports/Orders/Stats/Segmenter.php
  src/API/Reports/Products/Stats/Segmenter.php
Labels: Analytics, REST API, [Status] Ready to Merge, [Type] Bug

#4582 Fix deleted products breaking Downloads Report
  client/analytics/report/downloads/table.js
  src/API/Reports/Downloads/Controller.php
  tests/api/reports-downloads.php
Labels: Analytics, REST API, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4580 Add Tool to Clear/Invalidate Analytics Cache
  src/Features/Analytics.php
Labels: Analytics, [Status] Needs feedback, [Type] Enhancement, cooldown period

#4532 Add pre-launch checklist note on task list completion
  src/Events.php
  src/Notes/WC_Admin_Notes_Launch_Checklist.php
Labels: [Status] Ready to Merge

#3614 Add Timeline component
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/style.scss
  packages/components/src/timeline/README.md
  packages/components/src/timeline/__mocks__/timeline-mock-data.js
  packages/components/src/timeline/index.js
  packages/components/src/timeline/stories/index.js
  packages/components/src/timeline/style.scss
  packages/components/src/timeline/test/__snapshots__/index.js.snap
  packages/components/src/timeline/test/index.js
  packages/components/src/timeline/timeline-group.js
  packages/components/src/timeline/timeline-item.js
  packages/components/src/timeline/util.js
Labels: Components, Packages, [Status] Needs Design Review, [Status] Ready to Merge

#4559 Fix advancedFilter filter order
  packages/components/src/advanced-filters/index.js
Labels: Components, Packages, [Status] Ready to Merge, cooldown period

#4605 Tests: Prevent UnhandledPromiseRejectionWarning in tests
  packages/components/src/plugins/test/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4598 Update readme changelog to match .org.
  readme.txt
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Task

#4606 Style cleanup from components update
  client/analytics/settings/setting.scss
  client/dashboard/components/connect/index.js
  client/layout/transient-notices/style.scss
  client/profile-wizard/steps/theme/style.scss
  client/task-list/style.scss
  packages/components/src/calendar/style.scss
  packages/components/src/date-range-filter-picker/style.scss
  packages/components/src/dropdown-button/style.scss
  packages/components/src/ellipsis-menu/style.scss
  packages/components/src/list/style.scss
Labels: Components, Design, Needs Cherry Picking, Packages, [Status] Ready to Merge, [Type] Fix

#4618 Master -> main.
  .travis.yml
  CONTRIBUTING.md
  bin/pre-push-hook.js
  docs/data.md
  docs/documentation.md
  docs/examples/activity-panel-inbox.md
  docs/features/onboarding.md
  docs/woocommerce.com/analytics-orders-report.md
  languages/README.md
  packages/README.md
  packages/components/package.json
  packages/components/src/advanced-filters/README.md
  packages/csv-export/package.json
  packages/currency/package.json
  packages/data/package.json
  packages/date/package.json
  packages/navigation/package.json
  packages/number/package.json
  readme.txt
  src/Features/Onboarding.php
  src/RemoteInboxNotifications/DataSourcePoller.php
Labels: Build, Components, Documentation, Packages, [Status] Ready to Merge, [Type] Task, cooldown period

#4560 Currency package: make naming clearer
  client/analytics/components/leaderboard/test/index.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/categories/table.js
  client/analytics/report/coupons/table.js
  client/analytics/report/customers/table.js
  client/analytics/report/downloads/table.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/table.js
  client/analytics/report/stock/table.js
  client/analytics/report/taxes/table.js
  client/dashboard/store-performance/index.js
  client/dashboard/store-performance/utils.js
  client/header/activity-panel/panels/orders.js
  client/homescreen/stats-overview/stats-list.js
  client/lib/currency-context.js
  client/profile-wizard/steps/business-details.js
  client/task-list/tasks/shipping/rates.js
  client/wc-api/reports/utils.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/filters/index.js
  packages/currency/CHANGELOG.md
  packages/currency/README.md
  packages/currency/src/index.js
  packages/currency/test/index.js
  src/API/Init.php
Labels: Components, Packages, [Status] Ready to Merge

#4516 Add Insight note
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  src/Events.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes_Insight_First_Sale.php
Labels: [Status] Ready to Merge

#4624 Fix logic error that was stopping dismiss link from appearing on the inbox cards
  client/header/activity-panel/panels/inbox/card.js
Labels: [Status] Ready to Merge

#4617 Disable task list on analytics dashboard when homepage is enabled.
  client/dashboard/customizable.js
  src/Features/AnalyticsDashboard.php
Labels: Dashboard, Home Screen, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4625 Stats Overview: Cleanup styles
  client/homescreen/stats-overview/index.js
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/homescreen/stats-overview/style.scss
  client/homescreen/style.scss
  client/quick-links/index.js
  client/task-list/index.js
  client/task-list/style.scss
  packages/components/src/ellipsis-menu/index.js
  packages/components/src/summary/style.scss
Labels: Components, Needs Cherry Picking, Packages, [Status] Needs feedback

#4623 Add a 30 day upper limit to the need some inspiration admin note
  src/Notes/WC_Admin_Notes_Need_Some_Inspiration.php
Labels: [Status] Ready to Merge

#4627 Task List: Cleanup styles
  client/homescreen/style.scss
  client/quick-links/index.js
  client/task-list/index.js
  client/task-list/style.scss
  packages/components/src/list/index.js
  packages/components/src/list/style.scss
Labels: Components, Needs Cherry Picking, Packages, [Status] Needs feedback

#4629 Change the "Deactivate plugin" admin note to be informational
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
Labels: [Status] Needs feedback

#4651 Tweak tag remove button style so it is properly centered
  client/homescreen/style.scss
  packages/components/src/tag/style.scss
Labels: Components, Needs Cherry Picking, Packages, [Status] Ready to Merge

#4642 Don't include sourcemaps or unminified JS for "core" builds.
  webpack.config.js
Labels: Build, Needs Cherry Picking, [Status] Ready to Merge

#4616 New notification: Customize your online store with WooCommerce blocks
  src/Events.php
  src/Notes/WC_Admin_Notes_Customize_Store_With_Blocks.php
Labels: Inbox, [Status] Ready to Merge

#4621 Inbox panel - Actioned inbox notifications now are visible
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/inbox/test/index.js
  client/header/activity-panel/panels/inbox/utils.js
  client/header/activity-panel/unread-indicators.js
  src/Notes/WC_Admin_Notes.php
Labels: [Status] Ready to Merge

#4659 Remove duplicate/redundant inbox note after first order received.
  src/FeaturePlugin.php
  src/Notes/WC_Admin_Notes_First_Order.php
  src/Notes/WC_Admin_Notes_Order_Milestones.php
Labels: Inbox, Needs Cherry Picking, [Status] Ready to Merge, [Type] Tweak

#4632 Fix inbox spacing
  client/analytics/report/style.scss
  client/header/activity-panel/activity-header/style.scss
  client/header/activity-panel/panels/inbox/style.scss
  client/homescreen/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4637 UserPrefs store: Introduce optimistic update
  client/dashboard/customizable.js
  packages/data/src/user-preferences/use-user-preferences.js
Labels: Needs Cherry Picking, Packages, [Status] Ready to Merge

#4647 Fix WCPay sometimes not appearing on the task list
  client/index.js
  client/profile-wizard/index.js
  client/task-list/tasks/payments/index.js
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Needs feedback

#4630 Add check that the order being queried is a valid order
  src/API/Reports/Controller.php
Labels: [Status] Ready to Merge

#4660 Tax Task: Remove check for general settings requesting
  client/task-list/style.scss
  client/task-list/tasks/tax.js
  readme.txt
Labels: Needs Cherry Picking, [Status] Needs Review

#4661 Settings: Save all settings of a group, not just the update
  client/profile-wizard/steps/store-details.js
  client/task-list/tasks/steps/location.js
  client/task-list/tasks/tax.js
Labels: Needs Cherry Picking, [Status] Needs Review

#4668 Add version 1.3.0 option update callback.
  includes/wc-admin-update-functions.php
  src/Install.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4674 Fix inbox note deletion test cases.
  tests/api/admin-notes.php
Labels: Build, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4690 Inbox panel: Added styles to the unread notes counter
  client/header/activity-panel/activity-header/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4681 Fix spacing between stats overview and store management cards
  client/homescreen/style.scss
Labels: Needs Cherry Picking, [Status] Needs feedback

#4680 Check that the possibly_add_note function exists before calling it
  src/Package.php
Labels: Needs Cherry Picking, [Status] Needs Review

#4622 Tweak the embed page CSS so the top content sits better
  client/layout/store-alerts/style.scss
  client/stylesheets/shared/_embed.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4682 Update summary number placeholder styles
  packages/components/src/summary/style.scss
Labels: Components, Packages

#4691 Remove unnecessary rest API init action.
  src/ReportCSVExporter.php
Labels: Analytics, Needs Cherry Picking, REST API, [Status] Ready to Merge, [Type] Bug

#4664 Fix dashboard task list menu placement
  client/dashboard/style.scss
  client/task-list/index.js
Labels: Needs Cherry Picking, [Status] Needs feedback

#4650 Fix reselecting advanced filters in the customer list
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/customers/config.js
  client/analytics/report/downloads/config.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/config.js
  client/analytics/report/taxes/config.js
  packages/components/src/advanced-filters/search-filter.js
  packages/components/src/filter-picker/index.js
Labels: Components, Packages, [Status] Ready to Merge

#4694 Add education and travel to the onboarding industry types
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#4655 Refactor Jetpack connection flows
  client/dashboard/components/connect/index.js
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/profile-wizard/steps/benefits/index.js
Labels: Onboarding, [Status] Ready to Merge

#4671 Fix Historical (deleted) Coupon Reporting
  client/analytics/report/coupons/table.js
  src/API/Reports/Coupons/DataStore.php
  src/Install.php
  tests/reports/class-wc-tests-reports-coupons-stats.php
  tests/reports/class-wc-tests-reports-coupons.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug, cooldown period

#4643 Added event prop 'screen' to be recorded
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  client/utils/index.js
  src/API/NoteActions.php
Labels: [Status] Ready to Merge

#4703 Remove the Composite products option from the onboarding wizard
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#4692 Inbox header: Update styles
  client/header/activity-panel/activity-header/index.js
  client/header/activity-panel/activity-header/style.scss
  client/header/activity-panel/panels/inbox/action.js
Labels: Needs Cherry Picking, [Status] Needs feedback

#4719 Fix failing order stats tests
  CONTRIBUTING.md
  tests/bootstrap.php
  tests/reports/class-wc-tests-reports-orders-stats.php
Labels: Build, [Status] Needs Review, [Tests] Includes Tests

#4699 Don't show the inbox panel on the new home screen.
  client/header/activity-panel/index.js
  client/header/index.js
Labels: Activity Panel, Home Screen, Needs Cherry Picking, [Status] Ready to Merge, [Type] Fix

#4711 Preventing refresh after answering a survey note
  client/header/activity-panel/panels/inbox/action.js
Labels: [Status] Ready to Merge
