Repository woocommerce/woocommerce-admin, pull requests merged in 2020-05, with the labels that each got.

#4157 Adds the onboarding payments note
  client/dashboard/task-list/tasks.js
  client/dashboard/task-list/tasks/payments/index.js
  src/Events.php
  src/Notes/WC_Admin_Notes_Onboarding_Payments.php
Labels: Onboarding, [Status] Ready to Merge

#4263 Don't reschedule imports on failed imports
  src/Schedulers/OrdersScheduler.php
Labels: [Priority] High, [Status] Ready to Merge, [Type] Fix

#4286 Downgrade react-dates to ^17.2.0.
  package-lock.json
  package.json
  packages/components/package.json
Labels: Build, Components, Needs Cherry Picking, Packages, [Many] Large, [Much] Large, [Status] Ready to Merge, [Type] Bug

#4264 Homepage: Add stats overview selection
  client/dashboard/store-performance/index.js
  client/homepage/index.js
  client/homepage/stats-overview/defaults.js
  client/homepage/stats-overview/index.js
  client/homepage/stats-overview/test/index.js
  client/homepage/test/index.js
  client/wc-api/user/operations.js
  src/Features/AnalyticsDashboard.php
  tests/js/setup-globals.js
Labels: Home Screen, [Status] Ready to Merge, [Tests] Includes Tests

#4182 Remove obsolete inbox messages
  src/Events.php
  src/FeaturePlugin.php
  src/Features/ActivityPanels.php
  src/Install.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Giving_Feedback_Notes.php
  src/Notes/WC_Admin_Notes_Settings_Notes.php
  src/Notes/WC_Admin_Notes_Welcome_Message.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: Inbox, [Status] Ready to Merge

#4300 React Testing Library: add linter
  .eslintrc.js
  package-lock.json
  package.json
Labels: Build, [Status] Needs Review

#4259 Fix Dashboard flash before OBW chunk loads.
  client/layout/index.js
  client/profile-wizard/index.js
  src/Loader.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4287 Add support for List item tags and link types
  package-lock.json
  package.json
  packages/components/src/link/stories/index.js
  packages/components/src/link/test/index.js
  packages/components/src/list/index.js
  packages/components/src/list/stories/index.js
  packages/components/src/list/test/index.js
Labels: Build, Components, Packages, [Status] Needs Review

#4274 write RTL css property
  bin/packages/build.js
Labels: Build, [Status] Ready to Merge, [Type] Bug

#4297 Fix/amazon plugin slug
  src/Marketing/InstalledExtensions.php
Labels: Marketing, [Type] Bug

#4244 Guard against null themes
  client/profile-wizard/steps/theme/index.js
Labels: [Status] Ready to Merge

#4323 Update wcadmin db version after db callback
  includes/wc-admin-update-functions.php
  src/Install.php
Labels: [Status] Ready to Merge, [Type] Bug

#4324 Only migrate options on version change
  src/Install.php
Labels: [Status] Ready to Merge, [Type] Bug

#4318 New notification: How to draw attention to your online store
  src/FeaturePlugin.php
  src/Notes/WC_Admin_Notes_Draw_Attention.php
Labels: [Status] Needs Review

#4317 Add back giving feedback note with some changes
  src/Events.php
  src/Notes/WC_Admin_Notes_Giving_Feedback_Notes.php
Labels: [Status] Needs Review

#4327 Add `jest-dom` eslint plugin
  .eslintrc.js
  package-lock.json
  package.json
  packages/components/src/chart/d3chart/test/legend.js
Labels: Build, Components, Packages, [Status] Ready to Merge

#4307 Fix #4086 misaligned 'required' text on selects
  packages/components/src/select-control/control.js
Labels: Components, Packages, [Status] Ready to Merge

#4326 Add JS unit tests to pre-push hook
  package.json
Labels: Build, [Status] Ready to Merge

#4347 Homepage: Add layout with sticky columns
  client/homepage/index.js
  client/homepage/layout.js
  client/homepage/style.scss
Labels: Home Screen, [Status] Ready to Merge

#4357 Fix JS error when opening dashboard after selecting n extension to purchase.
  client/dashboard/utils.js
Labels: Dashboard, Needs Cherry Picking, Onboarding, [Status] Ready to Merge, [Type] Bug

#4291 Adds Jetpack stats to performance indicator endpoints
  src/API/Reports/PerformanceIndicators/Controller.php
  tests/api/reports-performance-indicators.php
Labels: REST API, [Status] Ready to Merge, [Tests] Includes Tests

#4312 update unit test bootstrap for WC 4.2
  tests/bootstrap.php
Labels: [Status] Ready to Merge, [Type] Dev

#4288 Homepage: Add stats numbers
  client/dashboard/store-performance/index.js
  client/dashboard/store-performance/utils.js
  client/homepage/stats-overview/index.js
  client/homepage/stats-overview/stats-list.js
  client/homepage/stats-overview/style.scss
  client/homepage/stats-overview/test/index.js
  client/homepage/stats-overview/test/stats-list.js
  client/layout/controller.js
  packages/components/src/index.js
  packages/components/src/summary/placeholder.js
Labels: Components, Packages, [Status] Needs Review

#4377 Fixed PHP notice about undefined index of items
  src/API/Reports/Coupons/Stats/Controller.php
  src/API/Reports/Customers/Stats/Controller.php
  src/API/Reports/Downloads/Stats/Controller.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Taxes/Stats/Controller.php
Labels: [Status] Ready to Merge

#4382 Add Jetpack flow to onboarding profiler for release 1.1.1
  client/dashboard/profile-wizard/steps/benefits/index.js
  client/dashboard/task-list/tasks/steps/connect.js
Labels: [Status] Ready to Merge

#4368 Enable tracking on the fly during onboarding
  client/lib/tracks.js
  client/profile-wizard/steps/usage-modal.js
Labels: Needs Cherry Picking, [Priority] High, [Status] Ready to Merge

#4392 Refactor plugin install flow pending state
  client/dashboard/profile-wizard/steps/benefits/index.js
Labels: Onboarding, [Priority] Critical, [Status] Ready to Merge, [Type] Bug

#4374 Add Jetpack connection to plugin benefits step
  client/dashboard/components/connect/index.js
  client/profile-wizard/steps/benefits/index.js
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/reducer.js
  packages/data/src/plugins/resolvers.js
  packages/data/src/plugins/test/reducer.js
  packages/data/src/plugins/with-plugins-hydration.js
Labels: Components, Onboarding, Packages, [Status] Needs Review, [Tests] Includes Tests

#4356 Advanced Filters: fix currency initialization
  client/analytics/components/report-filters/index.js
  client/lib/currency-context.js
  docs/examples/extensions/dashboard-section/js/global-prices.js
  packages/components/src/advanced-filters/docs/example.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/filters/index.js
  packages/currency/README.md
  packages/currency/test/index.js
Labels: Components, Packages, [Status] Ready to Merge

#4350 Home Screen: Add Store Management (Quick Links) card
  client/homepage/layout.js
  client/homepage/style.scss
  client/quick-links/index.js
  client/quick-links/stories/index.js
  client/quick-links/style.scss
  client/quick-links/test/index.js
  package-lock.json
  package.json
  storybook/main.js
  storybook/webpack.config.js
Labels: Build, Home Screen, [Status] Ready to Merge

#4395 1.2.2 version bump
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#4301 Fix in app purchase back link for recommend marketing extensions card
  client/dashboard/components/cart-modal.js
  client/lib/in-app-purchase.js
  client/marketing/overview/recommended-extensions/item.js
  src/Features/Marketing.php
  src/Features/Onboarding.php
  src/Loader.php
Labels: Marketing, [Status] Needs Review, [Type] Bug

#4381 Separate Jetpack connection logic in shipping task
  client/dashboard/task-list/tasks/shipping/index.js
Labels: Onboarding, [Status] Ready to Merge

#4400 Home Screen: Update Store Management (Quick Links) icons
  client/quick-links/index.js
  client/quick-links/style.scss
  package-lock.json
  package.json
  readme.txt
Labels: Build, Home Screen, [Status] Ready to Merge

#4256 Inbox notification: Added layout changes
  client/header/activity-panel/activity-header/index.js
  client/header/activity-panel/activity-header/style.scss
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/inbox/style.scss
  client/stylesheets/abstracts/_colors.scss
  docs/examples/activity-panel-inbox.md
  src/API/Notes.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  tests/api/admin-notes.php
Labels: [Status] Ready to Merge

#4258 Inbox notification: Remove icons
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  docs/examples/activity-panel-inbox.md
  src/API/NoteActions.php
  src/API/Notes.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
  src/Notes/WC_Admin_Notes_Giving_Feedback_Notes.php
  src/Notes/WC_Admin_Notes_Historical_Data.php
  src/Notes/WC_Admin_Notes_Install_JP_And_WCS_Plugins.php
  src/Notes/WC_Admin_Notes_Marketing.php
  src/Notes/WC_Admin_Notes_Mobile_App.php
  src/Notes/WC_Admin_Notes_New_Sales_Record.php
  src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/Notes/WC_Admin_Notes_Order_Milestones.php
  src/Notes/WC_Admin_Notes_Personalize_Store.php
  src/Notes/WC_Admin_Notes_Settings_Notes.php
  src/Notes/WC_Admin_Notes_Tracking_Opt_In.php
  src/Notes/WC_Admin_Notes_Welcome_Message.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
  src/Notes/WC_Admin_Notes_Woo_Subscriptions_Notes.php
  tests/api/admin-notes.php
  tests/framework/helpers/class-wc-helper-admin-notes.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: [Status] Ready to Merge

#4397 make revenue total sales column optional
  client/analytics/report/revenue/table.js
Labels: Analytics, [Much] Small, [Status] Ready to Merge, [Type] Tweak

#4373 Task List: Small fixes and adjustments to WCPay task
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/payments/methods.js
  client/dashboard/task-list/tasks/payments/wcpay.js
Labels: [Status] Needs Review

#4370 Homepage: Style summary numbers
  client/homepage/stats-overview/index.js
  client/homepage/stats-overview/stats-list.js
  client/homepage/stats-overview/style.scss
  packages/components/src/summary/number.js
  packages/components/src/summary/placeholder.js
  packages/components/src/summary/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#4378 Add existing TaskList component to new home screen
  client/dashboard/customizable.js
  client/dashboard/task-list/tasks/payments/images/bacs.js
  client/dashboard/task-list/tasks/payments/images/cod.js
  client/homepage/index.js
  client/homepage/layout.js
  client/homepage/style.scss
  client/homepage/test/index.js
  client/task-list/index.js
  client/task-list/placeholder.js
  client/task-list/style.scss
  client/task-list/tasks.js
  client/task-list/tasks/appearance.js
  client/task-list/tasks/connect.js
  client/task-list/tasks/payments/bacs.js
  client/task-list/tasks/payments/images/bacs.js
  client/task-list/tasks/payments/images/cod.js
  client/task-list/tasks/payments/images/wcpay.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/klarna.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/payfast.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/tasks/payments/square.js
  client/task-list/tasks/payments/stripe.js
  client/task-list/tasks/payments/wcpay.js
  client/task-list/tasks/products.js
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/shipping/rates.js
  client/task-list/tasks/steps/location.js
  client/task-list/tasks/tax.js
  client/wc-api/options/selectors.js
  package-lock.json
  package.json
  tests/js/jest.config.json
Labels: Home Screen, [Status] Ready to Merge, [Tests] Includes Tests

#4145 Add setting to see if WcPay is configured
  client/task-list/tasks/payments/methods.js
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge, wcpay

#4340 Refactor notes and conditions for adding notes
  src/API/Plugins.php
  src/Events.php
  src/Install.php
  src/Notes/NoteTraits.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
  src/Notes/WC_Admin_Notes_Draw_Attention.php
  src/Notes/WC_Admin_Notes_Giving_Feedback_Notes.php
  src/Notes/WC_Admin_Notes_Historical_Data.php
  src/Notes/WC_Admin_Notes_Install_JP_And_WCS_Plugins.php
  src/Notes/WC_Admin_Notes_Marketing.php
  src/Notes/WC_Admin_Notes_Mobile_App.php
  src/Notes/WC_Admin_Notes_New_Sales_Record.php
  src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php
  src/Notes/WC_Admin_Notes_Onboarding_Payments.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/Notes/WC_Admin_Notes_Order_Milestones.php
  src/Notes/WC_Admin_Notes_Personalize_Store.php
  src/Notes/WC_Admin_Notes_Tracking_Opt_In.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
  src/Package.php
  tests/notes/class-wc-tests-marketing-notes.php
Labels: [Status] Needs Review

#4362 OBW: Get utils plugins data from wp.data
  client/dashboard/components/cart-modal.js
  client/dashboard/utils.js
  client/task-list/index.js
  client/task-list/tasks.js
Labels: [Status] Needs Review

#4436 Some minor color tweaks
  client/task-list/index.js
  client/task-list/style.scss
Labels: [Status] Ready to Merge

#4437 Bind onClick event handler for marketing kb article click
  client/marketing/overview/knowledge-base/index.js
Labels: Marketing, [Type] Bug

#4320 Inbox notification: add event recording
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  tests/api/admin-notes.php
Labels: [Status] Ready to Merge

#4442 Add install Jetpack CTA to stats on home page
  client/homepage/stats-overview/index.js
  client/homepage/stats-overview/install-jetpack-cta.js
  client/homepage/stats-overview/style.scss
  client/homepage/stats-overview/test/index.js
Labels: [Status] Ready to Merge

#4411 Handle multiple plugin installs in a single request
  packages/components/src/plugins/index.js
  packages/components/src/plugins/test/index.js
  packages/data/src/plugins/actions.js
  src/API/Plugins.php
  tests/api/plugins.php
Labels: Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests

#4434 Update TaskList design
  client/dashboard/customizable.js
  client/dashboard/style.scss
  client/homepage/layout.js
  client/homepage/test/index.js
  client/task-list/index.js
  client/task-list/placeholder.js
  client/task-list/style.scss
  client/task-list/tasks.js
  src/Features/Onboarding.php
Labels: Home Screen, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#4177 Add method to send WC profile data after profiler completion
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Needs feedback, [Status] Ready to Merge

#4452 Add EU VAT extension note
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/unread-indicators.js
  client/wc-api/constants.js
  src/Events.php
  src/Notes/WC_Admin_Notes_EU_VAT_Number.php
Labels: [Status] Needs Review

#4461 Update import to new pluginNames location
  packages/components/src/plugins/index.js
Labels: Build, Components, Packages, [Status] Ready to Merge, [Type] Bug

#4379 Inbox notification: added new placeholder and empty card
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-header/index.js
  client/header/activity-panel/panels/inbox/card.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/inbox/placeholder.js
  client/header/activity-panel/panels/inbox/style.scss
  client/header/activity-panel/panels/inbox/utils.js
  client/wc-api/notes/operations.js
  client/wc-api/notes/selectors.js
Labels: [Status] Ready to Merge

#4448 Homepage: Add tracks events to Stats List period changes
  client/homepage/stats-overview/index.js
  client/homepage/stats-overview/test/index.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#4337 Add time after wcadmin activation rule
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/WCAdminActiveForProvider.php
  src/RemoteInboxNotifications/WCAdminActiveForRuleProcessor.php
  tests/remote-inbox-notifications/mock-wc-admin-active-for-provider.php
  tests/remote-inbox-notifications/wcadmin-active-for-rule-processor.php
Labels: [Status] Ready to Merge

#4335 Add order count rule
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/OrderCountRuleProcessor.php
  src/RemoteInboxNotifications/OrdersProvider.php
Labels: [Status] Ready to Merge

#4415 IconButton: Replace with Button
  client/analytics/components/report-table/index.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/style.scss
  client/header/activity-panel/index.js
  client/header/activity-panel/style.scss
  client/layout/store-alerts/index.js
  client/stylesheets/shared/_global.scss
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/style.scss
  packages/components/src/chart/index.js
  packages/components/src/chart/style.scss
  packages/components/src/ellipsis-menu/index.js
  packages/components/src/filter-picker/index.js
  packages/components/src/filter-picker/style.scss
  packages/components/src/index.js
  packages/components/src/pagination/index.js
  packages/components/src/pagination/style.scss
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  packages/components/src/split-button/README.md
  packages/components/src/split-button/docs/example.js
  packages/components/src/split-button/index.js
  packages/components/src/split-button/style.scss
  packages/components/src/split-button/test/__snapshots__/index.js.snap
  packages/components/src/split-button/test/index.js
  packages/components/src/style.scss
  packages/components/src/table/style.scss
  packages/components/src/table/table.js
  packages/components/src/tag/index.js
  packages/components/src/tag/test/__snapshots__/index.js.snap
Labels: Components, Packages, [Status] Needs Review

#4468 OBW: JP step - use the correct store name for updating profile items.
  client/profile-wizard/steps/benefits/index.js
Labels: [Status] In Progress, [Status] Needs Review, [Type] Bug

#4471 Await profile items update in skip
  client/profile-wizard/steps/benefits/index.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Bug

#4469 Overview: fix reference to old wc-api method
  client/dashboard/customizable.js
Labels: [Status] Ready to Merge

#4465 Added new notification to ask about migrating from Shopify.
  src/Events.php
  src/Notes/WC_Admin_Notes_Migrate_From_Shopify.php
Labels: Inbox, [Status] Ready to Merge
