Repository woocommerce/woocommerce-admin, pull requests merged in 2020-07, with the labels that each got.

#4683 Refactor task tax to use promise chain
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/steps/store-details.js
  client/task-list/style.scss
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/tax.js
  packages/data/src/settings/actions.js
  packages/data/src/settings/selectors.js
  packages/data/src/settings/use-settings.js
Labels: Onboarding, Packages, [Status] Ready to Merge, [Type] Bug

#4695 Add bundle install UI to Business Details step
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/style.scss
  client/stylesheets/abstracts/_colors.scss
  src/API/OnboardingProfile.php
Labels: Onboarding, [Status] Ready to Merge

#4705 Include Product Bundles and Product Add-ons as OBW product options
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#4686 Added new note type
  client/wc-api/constants.js
  src/API/NoteActions.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Insight_First_Sale.php
Labels: [Status] Ready to Merge

#4745 Added default value to the note icon
  src/Install.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4740 Remove navigation feature
  client/index.js
  client/navigation/index.js
  client/navigation/style.scss
  config/core.json
  config/development.json
  config/plugin.json
  src/Features/Navigation.php
  src/Loader.php
Labels: [Status] Ready to Merge

#4742 Fix up warnings in notes
  src/Notes/WC_Admin_Notes_Choose_Niche.php
  src/Notes/WC_Admin_Notes_Customize_Store_With_Blocks.php
  src/Notes/WC_Admin_Notes_First_Product.php
  src/Notes/WC_Admin_Notes_Need_Some_Inspiration.php
  src/Notes/WC_Admin_Notes_Online_Clothing_Store.php
  src/Notes/WC_Admin_Notes_Start_Dropshipping_Business.php
  src/Notes/WC_Admin_Notes_WooCommerce_Subscriptions.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4747 Build: Don't Attempt to Load non-minified Assets in Core Build
  config/core.json
  config/development.json
  config/plugin.json
  src/FeaturePlugin.php
  src/Loader.php
  tests/bootstrap.php
  tests/loader.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Tests] Includes Tests

#4755 Avoid Jetpack REST API when retrieving active modules
  src/API/Init.php
  src/API/Reports/PerformanceIndicators/Controller.php
  src/FeaturePlugin.php
  tests/api/reports-performance-indicators.php
Labels: Analytics, Dashboard, Needs Cherry Picking, REST API, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Fix

#4713 REST API: Add support for legacy public function install_plugin.
  src/API/Plugins.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4645 Update "Deactivate old WCA version" note to be informational
  includes/wc-admin-update-functions.php
  src/Install.php
Labels: [Status] Ready to Merge

#4704 Filters: Fix regular filters not working
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/customers/config.js
  client/analytics/report/downloads/config.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/config.js
  client/analytics/report/taxes/config.js
Labels: [Status] Needs Review

#4702 Toggle the “Physical products” checkbox on by default
  client/profile-wizard/steps/product-types.js
  src/Features/Onboarding.php
Labels: [Status] Needs Review

#4715 Variation Names: Allow long names to be shown
  src/API/Reports/Products/Stats/DataStore.php
  src/API/Reports/Variations/DataStore.php
Labels: [Status] Ready to Merge

#4644 Customize webpack jsonpFunction to avoid potential collision with other Webpack bundles
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#4765 Limit inbox status to unactioned notes
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/unread-indicators.js
Labels: [Status] Ready to Merge

#4764 Make sure product count and revenue items are set in choose niche note
  src/Notes/WC_Admin_Notes_Choose_Niche.php
Labels: [Status] Ready to Merge

#4737 Trigger a remote inbox notifications engine run when the OBW completes
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/RemoteInboxNotifications/DataSourcePoller.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
Labels: [Status] Ready to Merge

#4766 Onboarding: Don't show tracking modal if site is already opted in
  client/profile-wizard/steps/usage-modal.js
Labels: [Status] Ready to Merge

#4793 Highlight WooCommerce Payments task
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/payments/methods.js
Labels: [Status] Needs Review

#4767 Readme for remote inbox notifications
  src/RemoteInboxNotifications/README.md
Labels: [Status] Needs feedback

#4733 Add option to dismiss tasks
  client/profile-wizard/index.js
  client/task-list/index.js
  client/task-list/style.scss
  client/task-list/tasks.js
  packages/components/CHANGELOG.md
  packages/components/src/list/index.js
  packages/components/src/list/style.scss
  src/Features/Onboarding.php
Labels: Components, Onboarding, Packages, [Status] Ready to Merge

#4779 Show "Help" Activity Panel When Working Single Task List Item
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  client/header/activity-panel/test/index.js
  client/header/index.js
  client/layout/controller.js
  client/layout/index.js
Labels: Activity Panel, Documentation, Onboarding, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#4780 Post-Release: Sync readme changelog, bump versions to 1.4.0-dev.
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#4781 Update JP Autoloader to 2.0.0
  composer.json
  composer.lock
Labels: Build, [Status] Ready to Merge

#4792 Changed logic of "Set up payments" reminder
  src/Notes/WC_Admin_Notes_Onboarding_Payments.php
Labels: Onboarding, [Status] Ready to Merge

#4795 Admin note to install other payment providers
  client/task-list/index.js
  src/FeaturePlugin.php
  src/Notes/NoteTraits.php
  src/Notes/WC_Admin_Notes_Set_Up_Additional_Payment_Types.php
Labels: [Status] Ready to Merge

#4808 Fix a React warning in test that the key prop wasn't assigned in List
  packages/components/src/list/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Fix

#4802 Onboarding: Center continue buttons in profile wizard
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types.js
  client/profile-wizard/steps/store-details.js
  client/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#4804 Add option to automatically create a PayPal account
  client/task-list/style.scss
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/test/payments.js
Labels: Onboarding, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#4717 Update connection flow for Bundle UI
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge

#4807 Setup Checklist: Fix Homepage Template
  src/API/OnboardingTasks.php
Labels: [Status] Ready to Merge

#4817 Allow Jetpack plugin to be manipulated via API from the home screen.
  src/Features/AnalyticsDashboard.php
Labels: Home Screen, [Status] Ready to Merge, [Type] Bug

#4794 Update marketing tab styles
  client/marketing/components/button/index.js
  client/marketing/components/button/style.scss
  client/marketing/components/knowledge-base/style.scss
  client/marketing/components/product-icon/icons/index.js
  client/marketing/components/product-icon/icons/library/amazon-ebay.js
  client/marketing/components/product-icon/icons/library/automatewoo-alt.js
  client/marketing/components/product-icon/icons/library/automatewoo.js
  client/marketing/components/product-icon/icons/library/blank.js
  client/marketing/components/product-icon/icons/library/currency-dollar.js
  client/marketing/components/product-icon/icons/library/facebook.js
  client/marketing/components/product-icon/icons/library/gift.js
  client/marketing/components/product-icon/icons/library/google.js
  client/marketing/components/product-icon/icons/library/hubspot.js
  client/marketing/components/product-icon/icons/library/link.js
  client/marketing/components/product-icon/icons/library/mailchimp.js
  client/marketing/components/product-icon/icons/library/people.js
  client/marketing/components/product-icon/icons/library/tip.js
  client/marketing/components/product-icon/index.js
  client/marketing/components/product-icon/style.scss
  client/marketing/components/recommended-extensions/index.js
  client/marketing/components/recommended-extensions/item.js
  client/marketing/components/recommended-extensions/style.scss
  client/marketing/coupons/style.scss
  client/marketing/overview/installed-extensions/row.js
  client/marketing/overview/installed-extensions/style.scss
Labels: Marketing, [Status] Ready to Merge

#4786 Enable the coupons feature in core
  config/core.json
Labels: Marketing, [Status] Ready to Merge

#4721 Added skip profiler functionality
  client/dashboard/index.js
  client/homescreen/index.js
  client/layout/controller.js
  client/profile-wizard/index.js
  client/task-list/tasks.js
  packages/data/src/onboarding/actions.js
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
  src/Loader.php
  tests/api/onboarding-profile.php
Labels: Onboarding, Packages, [Status] Ready to Merge

#4816 Fix missing version update callback and add test
  includes/wc-admin-update-functions.php
  src/Install.php
  tests/plugin-version.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug, [Type] Dev

#4743 Added event recording to home/dashboard task list
  client/task-list/tasks.js
Labels: Onboarding, [Status] Ready to Merge

#4754 Reordered home screen tasks
  client/task-list/tasks.js
Labels: Onboarding, [Status] Ready to Merge

#4759 Update @wordpress/base-styles and replace deprecated variables
  client/analytics/report/style.scss
  client/analytics/settings/setting.scss
  client/dashboard/dashboard-charts/block.scss
  client/dashboard/leaderboards/style.scss
  client/dashboard/store-performance/style.scss
  client/dashboard/style.scss
  client/devdocs/style.scss
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-header/style.scss
  client/header/activity-panel/activity-outbound-link/style.scss
  client/header/activity-panel/panels/inbox/style.scss
  client/header/activity-panel/style.scss
  client/homescreen/stats-overview/style.scss
  client/layout/store-alerts/style.scss
  client/marketing/components/button/style.scss
  client/marketing/components/knowledge-base/style.scss
  client/marketing/components/product-icon/style.scss
  client/marketing/components/recommended-extensions/style.scss
  client/marketing/coupons/style.scss
  client/marketing/overview/installed-extensions/style.scss
  client/marketing/overview/style.scss
  client/marketing/overview/welcome-card/style.scss
  client/navigation/style.scss
  client/profile-wizard/style.scss
  client/stylesheets/abstracts/_breakpoints.scss
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_mixins.scss
  client/stylesheets/abstracts/_variables.scss
  client/stylesheets/shared/_global.scss
  client/task-list/style.scss
  package-lock.json
  package.json
  packages/components/src/advanced-filters/style.scss
  packages/components/src/calendar/style.scss
  packages/components/src/chart/d3chart/legend.scss
  packages/components/src/chart/d3chart/style.scss
  packages/components/src/chart/style.scss
  packages/components/src/date-range-filter-picker/style.scss
  packages/components/src/dropdown-button/style.scss
  packages/components/src/ellipsis-menu/style.scss
  packages/components/src/filter-picker/style.scss
  packages/components/src/filters/style.scss
  packages/components/src/flag/style.scss
  packages/components/src/list/stories/style.scss
  packages/components/src/list/style.scss
  packages/components/src/order-status/style.scss
  packages/components/src/pagination/style.scss
  packages/components/src/rating/style.scss
  packages/components/src/search-list-control/style.scss
  packages/components/src/search/style.scss
  packages/components/src/segmented-selection/style.scss
  packages/components/src/stepper/style.scss
  packages/components/src/summary/style.scss
  packages/components/src/table/style.scss
  packages/components/src/tag/style.scss
  packages/components/src/text-control-with-affixes/style.scss
  packages/components/src/text-control/style.scss
Labels: Build, Components, Design, Packages, [Status] Ready to Merge

#4790 Update store management links
  client/quick-links/index.js
Labels: [Status] Ready to Merge

#4825 Create single source of truth for task list array
  client/task-list/index.js
Labels: [Status] Ready to Merge

#4831 Fix PHP Fatals from Notes DataStore when columns are missing.
  src/Notes/DataStore.php
  src/Notes/NoteTraits.php
  src/Notes/WC_Admin_Note.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Historical_Data.php
  src/Notes/WC_Admin_Notes_Install_JP_And_WCS_Plugins.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
  src/RemoteInboxNotifications/SpecRunner.php
  tests/api/admin-notes.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4758 Dashboard: Fix filter extensibility
  client/analytics/components/leaderboard/index.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/block.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/leaderboards/index.js
  client/dashboard/store-performance/index.js
  client/dashboard/store-performance/utils.js
  client/wc-api/items/utils.js
Labels: Extensibility, [Status] Ready to Merge

#4771 Rework the store details onboarding screen
  .eslintrc.js
  .prettierrc
  client/navigation/style.scss
  client/profile-wizard/index.js
  client/profile-wizard/steps/product-types.js
  client/profile-wizard/steps/store-details.js
  client/profile-wizard/style.scss
  client/stylesheets/abstracts/_variables.scss
  package-lock.json
  packages/components/src/summary/style.scss
Labels: Build, Components, Design, Onboarding, Packages, [Status] Ready to Merge

#4707 Pills and tooltips in product step of OBW
  client/devdocs/examples.json
  client/profile-wizard/steps/product-types.js
  client/profile-wizard/steps/product-types.scss
  client/profile-wizard/style.scss
  client/stylesheets/abstracts/_colors.scss
  docs/components/_sidebar.md
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/pill/README.md
  packages/components/src/pill/docs/example.js
  packages/components/src/pill/index.js
  packages/components/src/pill/pill.js
  packages/components/src/pill/stories/index.js
  packages/components/src/pill/style.scss
  packages/components/src/style.scss
  src/Features/Onboarding.php
Labels: Components, Packages, [Status] Needs Design Review, [Status] Ready to Merge

#4828 Update profiler reference links and loading state
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#4706 Theme Activation :: Fix unable to activate theme with uppercase name
  src/API/OnboardingThemes.php
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#4837 Onboarding: Fix alignment of container on benefits screen.
  client/profile-wizard/index.js
  client/profile-wizard/style.scss
Labels: [Status] Ready to Merge

#4834 Set active theme when OBW is shown via the task list
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4799 Add copy that WCS TOS will be accepted upon install.
  client/profile-wizard/steps/benefits/index.js
Labels: [Status] Needs feedback

#4846 Update versions
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#4805 New notification: Don't forget to test your checkout
  src/Events.php
  src/FeaturePlugin.php
  src/Features/OnboardingTasks.php
  src/Notes/WC_Admin_Notes_Test_Checkout.php
Labels: Inbox, [Status] Ready to Merge

#4851 Remove item "profiler" from the menu
  src/Loader.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4847 Center the skip link on the theme selection step
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/steps/theme/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4850 Register wca pages with wc navigation
  src/PageController.php
Labels: [Status] Ready to Merge

#4852 Fix child theme upload error
  src/API/Themes.php
  src/Overrides/ThemeUpgraderSkin.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4856 Fix PHP warning when preloading scripts on WPEngine
  src/Loader.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4858 Summary Numbers: Fix background
  client/analytics/components/report-summary/index.js
  client/dashboard/store-performance/style.scss
  packages/components/src/summary/style.scss
Labels: Components, Needs Cherry Picking, Packages, [Status] Needs Review

#4862 Add the experimental resolver to WCA data package
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/profile-wizard/index.js
  package.json
  packages/data/src/index.js
  packages/data/src/registry.js
Labels: Build, Needs Cherry Picking, Packages, [Status] Needs Review

#4867 Fix build check for core.
  src/FeaturePlugin.php
Labels: Build, Needs Cherry Picking, [Status] Needs Review, [Type] Bug

#4859 DateRangeFilterPicker: Fix unused ref
  packages/components/CHANGELOG.md
  packages/components/src/date-range-filter-picker/index.js
Labels: [Status] Ready to Merge

#4869 Polyfill core-data saveUser() on WP 5.3.x.
  packages/data/src/user-preferences/test/use-user-preferences.js
  packages/data/src/user-preferences/use-user-preferences.js
Labels: Needs Cherry Picking, Packages, [Priority] High, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#4879 Update changelog from 1.3.2 release.
  readme.txt
Labels: [Status] Ready to Merge, [Type] Task

#4874 Declare packages dependencies independently of main package.json
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
  package-lock.json
  package.json
  packages/components/package.json
Labels: Build, Components, Packages, [Status] Ready to Merge

#4878 Enable tax calculation before redirecting to standard tax rates page.
  client/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4900 OBW: fix product types step bugs
  client/profile-wizard/steps/product-types.js
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge, [Type] Bug

#4902 Center all descriptive text on OBW steps.
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types.js
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge, [Type] Bug

#4891 Currency: re-add deprecated formatCurrency
  package-lock.json
  packages/currency/package.json
  packages/currency/src/index.js
Labels: Build, Needs Cherry Picking, Packages, [Status] Needs feedback, [Status] Ready to Merge

#4889 Use clipRule and fillRule props
  client/marketing/components/product-icon/icons/library/amazon-ebay.js
  client/marketing/components/product-icon/icons/library/facebook.js
  client/marketing/components/product-icon/icons/library/gift.js
Labels: [Status] Ready to Merge
