Repository woocommerce/woocommerce-admin, pull requests merged in 2020-08, with the labels that each got.

#4899 Only show WCPay task in US based stores
  client/task-list/index.js
  client/task-list/tasks.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4861 Activity Panel - event tracking improved
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/panels/reviews.js
  client/header/activity-panel/panels/stock/card.js
Labels: Activity Panel, [Status] Ready to Merge

#4849 Added personalization to purchase extension task
  client/dashboard/utils.js
  client/task-list/tasks.js
Labels: Onboarding, [Status] Ready to Merge

#4905 Use lifesaver icon instead of gridicon for help panel.
  client/header/activity-panel/index.js
Labels: [Status] Ready to Merge

#4909 Onboarding: Change account required text on biz step.
  client/profile-wizard/steps/business-details.js
Labels: [Status] Ready to Merge

#4914 Remove new WP 5.5 meta box arrows in the shipping banner
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
Labels: [Status] Needs Review

#4918 Allow revisiting of the payments task
  client/task-list/tasks.js
Labels: [Status] Needs Review

#4920 Fix use of Jetpack autoloader.
  bin/pre-release.sh
  bin/update-version.php
  package.json
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, Needs Cherry Picking, [Priority] Critical, [Status] Needs Review, [Type] Fix

#4908 Prepare to publish packages
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/csv-export/CHANGELOG.md
  packages/csv-export/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/data/CHANGELOG.md
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/number/CHANGELOG.md
  packages/number/package.json
Labels: Build, Components, Packages, [Status] Needs Review

#4800 Clean up webpack config and add tsconfig.json
  tsconfig.json
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#4912 Add product and category props to mock RecommendedExtensionsItem
  client/marketing/components/recommended-extensions/test/index.js
Labels: [Status] Ready to Merge

#4890 Display modal with more info about the new homescreen
  client/homescreen/index.js
  client/homescreen/layout.js
  client/homescreen/welcome-modal/illustrations/inbox.js
  client/homescreen/welcome-modal/illustrations/line-chart.js
  client/homescreen/welcome-modal/illustrations/pie-chart.js
  client/homescreen/welcome-modal/index.js
  client/homescreen/welcome-modal/page-content/index.js
  client/homescreen/welcome-modal/style.scss
  client/homescreen/welcome-modal/test/index.js
  client/stylesheets/shared/_gutenberg-components.scss
  client/task-list/index.js
  client/task-list/style.scss
Labels: Build, Design, Home Screen, [Status] Ready to Merge

#4924 Task List: dismiss and undo dismiss animation fixed
  packages/components/src/list/index.js
Labels: Components, Needs Cherry Picking, Onboarding, Packages, [Status] Ready to Merge, [Type] Bug

#4936 Added key to generic items in list without one
  packages/components/src/list/index.js
Labels: Components, Needs Cherry Picking, Onboarding, Packages, [Status] Ready to Merge, [Type] Bug

#4937 Load chunked translation data from language packs.
  src/Loader.php
Labels: Build, Needs Cherry Picking, [Many] Large, [Much] Large, [Priority] High, [Status] Ready to Merge, [Type] Bug

#4853 Task list - add a shortcut back to store setup
  client/dashboard/test/utils.js
  client/dashboard/utils.js
  client/header/activity-panel/index.js
  client/header/activity-panel/setup-progress.js
  client/header/activity-panel/style.scss
  client/header/activity-panel/tab/index.js
  client/header/activity-panel/tab/test/index.js
  client/header/activity-panel/tabs/index.js
  client/header/activity-panel/tabs/test/index.js
  client/header/index.js
  client/layout/controller.js
  tsconfig.json
Labels: Activity Panel, [Status] Ready to Merge

#4945 Update the colors of the illustrations in the welcome modal
  client/homescreen/welcome-modal/illustrations/inbox.js
  client/homescreen/welcome-modal/illustrations/line-chart.js
  client/homescreen/welcome-modal/illustrations/pie-chart.js
  client/homescreen/welcome-modal/style.scss
Labels: [Status] Needs Review

#4948 Update style on shipping banner
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
Labels: [Status] Needs Review

#4923 Remove erroneous navigation component
  client/navigation/index.js
  client/navigation/style.scss
Labels: [Status] Ready to Merge

#4947 Setup Payments: Add eWAY for AU/NZ Stores.
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  client/task-list/tasks/payments/eway.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  src/Features/Onboarding.php
Labels: [Status] Needs feedback

#4944 Don't redirect to connect Jetpack if "no thanks!" selected.
  client/profile-wizard/index.js
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge, [Type] Bug

#4950 Post-release, update readme, bump versions to 1.6.0-dev
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build

#4857 Automatically add free local shipping zone on completing the profiler
  client/lib/sanitize-html/index.js
  src/Features/Onboarding.php
  src/Features/OnboardingSetUpShipping.php
  src/Notes/WC_Admin_Notes_Review_Shipping_Settings.php
  tests/features/class-onboarding-set-up-shipping.php
Labels: [Status] Needs feedback

#4917 Remove payment task actions
  client/task-list/index.js
  client/task-list/style.scss
  client/task-list/tasks.js
  client/task-list/tasks/payments/index.js
  docs/features/onboarding.md
  src/API/Options.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Notes/WC_Admin_Notes_Test_Checkout.php
Labels: [Status] Ready to Merge

#4974 Fix industry args type in REST API
  src/API/OnboardingProfile.php
  tests/api/onboarding-profile.php
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#4959 Fix Table component `onQueryChange` prop default
  packages/components/CHANGELOG.md
  packages/components/src/table/index.js
  packages/components/src/table/test/data/table-mock-csv.js
  packages/components/src/table/test/data/table-mock-data.js
  packages/components/src/table/test/data/table-mock-headers.js
  packages/components/src/table/test/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug, cooldown period

#4942 Improve jest performance significantly by downgrading to 24.9.0
  package-lock.json
  package.json
  tests/js/jest.config.json
  tests/js/mocks/style-mock.js
  tests/js/setup-enzyme.js
  tests/js/setup-globals.js
  tests/js/setup-window-globals.js
Labels: Build, [Status] Needs Review

#4978 Don't directly import from React, use @wordpress/element.
  client/dashboard/components/settings/general/store-address.js
  client/devdocs/example.js
  client/homescreen/stats-overview/install-jetpack-cta.js
Labels: [Status] Ready to Merge, [Type] Dev, [Type] Fix, cooldown period

#4943 Migrate notes data store to wp data
  client/analytics/settings/historical-data/index.js
  client/header/activity-panel/panels/inbox/action.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/unread-indicators.js
  client/homescreen/layout.js
  client/layout/store-alerts/index.js
  client/profile-wizard/index.js
  client/wc-api/notes/index.js
  client/wc-api/notes/mutations.js
  client/wc-api/notes/operations.js
  client/wc-api/notes/selectors.js
  client/wc-api/wc-api-spec.js
  packages/data/src/index.js
  packages/data/src/notes/action-types.js
  packages/data/src/notes/actions.js
  packages/data/src/notes/constants.js
  packages/data/src/notes/index.js
  packages/data/src/notes/reducer.js
  packages/data/src/notes/resolvers.js
  packages/data/src/notes/selectors.js
  packages/data/src/notes/test/reducer.js
  src/API/Notes.php
  tests/api/admin-notes.php
Labels: Packages, [Status] Needs Review, cooldown period

#4977 Delete associated customer analytics data when user is deleted from WordPress.
  src/API/Reports/Customers/DataStore.php
  src/Schedulers/CustomersScheduler.php
  tests/api/reports-customers.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Fix, cooldown period

#4956 Match the requires version to the exact Wordpress version number.
  woocommerce-admin.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4980 Stock Report: Fix bad text domains
  .eslintrc.js
  client/analytics/report/stock/table.js
  client/homescreen/index.js
  client/homescreen/stats-overview/index.js
Labels: Build, [Status] Needs Review

#4979 Adjust renovate to automerge devDependencies
  renovate.json
Labels: [Status] Ready to Merge

#4934 Add 'woocommerce_analytics_update_order_stats_data' filter
  src/API/Reports/Orders/Stats/DataStore.php
Labels: [Status] Needs Review

#4964 Use filtered headers array in onColumnsChange callback.
  client/analytics/components/report-table/index.js
  docs/examples/extensions/table-column/js/index.js
Labels: Extensibility, [Status] Ready to Merge, [Type] Bug, cooldown period

#4988 Update versions to 1.5.0-beta.2
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#4986 Add updateOptions prop to Layout tests
  client/homescreen/test/index.js
Labels: [Status] Ready to Merge

#4992 Fix typo in reports store action creators.
  packages/data/src/reports/actions.js
Labels: Packages, [Status] Ready to Merge, [Type] Bug, cooldown period

#4907 CSS fixes for Business Features popover.
  client/profile-wizard/style.scss
Labels: Needs Cherry Picking

#4985 jsDoc: Fix errors
  .eslintrc.js
  client/analytics/report/index.js
  client/settings/index.js
  packages/components/src/advanced-filters/utils.js
  packages/components/src/compare-filter/button.js
  packages/components/src/count/index.js
  packages/components/src/date/index.js
  packages/components/src/ellipsis-menu/menu-title.js
  packages/components/src/flag/index.js
  packages/components/src/gravatar/index.js
  packages/components/src/order-status/index.js
  packages/components/src/product-image/index.js
  packages/components/src/rating/product.js
  packages/components/src/rating/review.js
  packages/components/src/search/autocompleters/categories.js
  packages/components/src/search/autocompleters/countries.js
  packages/components/src/search/autocompleters/coupons.js
  packages/components/src/search/autocompleters/customers.js
  packages/components/src/search/autocompleters/download-ips.js
  packages/components/src/search/autocompleters/emails.js
  packages/components/src/search/autocompleters/orders.js
  packages/components/src/search/autocompleters/product.js
  packages/components/src/search/autocompleters/taxes.js
  packages/components/src/search/autocompleters/usernames.js
  packages/components/src/search/autocompleters/utils.js
  packages/components/src/search/autocompleters/variations.js
  packages/components/src/section/index.js
  packages/components/src/summary/index.js
  packages/components/src/summary/number.js
  packages/components/src/table/empty.js
  packages/components/src/table/summary.js
  packages/components/src/tag/index.js
  packages/components/src/view-more-list/index.js
  packages/data/src/settings/selectors.js
  packages/date/src/index.js
  packages/navigation/src/filters.js
  packages/number/src/index.js
Labels: Build, Components, Packages, [Status] Ready to Merge

#4991 Documentation: Fix Add Report
  client/analytics/report/README.md
  src/Features/Analytics.php
  src/PageController.php
Labels: [Status] Ready to Merge

#4987 Remove unused lib/date
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/coupons/table.js
  client/analytics/report/customers/table.js
  client/analytics/report/downloads/table.js
  client/analytics/report/orders/table.js
  client/analytics/report/revenue/table.js
  client/analytics/settings/default-date.js
  client/analytics/settings/historical-data/period-selector.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/store-performance/index.js
  client/lib/date.js
  client/wc-api/items/utils.js
Labels: [Status] Ready to Merge

#4993 Update Jetpack Autoloader to match Woo Core.
  composer.json
  composer.lock
Labels: Build, Needs Cherry Picking, [Priority] High, [Status] Ready to Merge

#4994 Onboarding: Missing CSS Change for Business Extensions Step
  client/profile-wizard/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4995 Remove composite product from 1.4 release notes
  readme.txt
Labels: [Status] Needs Review

#4996 Remove composite products from onboarding
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Needs Review

#4990 Fix note data actions and consolidate query constants
  client/layout/store-alerts/index.js
  packages/data/src/index.js
  packages/data/src/reports/constants.js
  packages/data/src/reports/utils.js
Labels: Packages, [Status] Ready to Merge

#4958 Migrate export data store to wp.data
  client/analytics/components/report-table/index.js
  client/wc-api/export/index.js
  client/wc-api/export/mutations.js
  client/wc-api/export/operations.js
  client/wc-api/wc-api-spec.js
  packages/data/src/controls.js
  packages/data/src/export/action-types.js
  packages/data/src/export/actions.js
  packages/data/src/export/constants.js
  packages/data/src/export/index.js
  packages/data/src/export/reducer.js
  packages/data/src/export/selectors.js
  packages/data/src/export/test/reducer.js
  packages/data/src/export/utils.js
  packages/data/src/index.js
  src/API/Reports/Export/Controller.php
  tests/api/reports-export.php
Labels: Packages, [Status] Ready to Merge, [Type] Dev, cooldown period

#4997 Orders Panel: get selectors from wc-api
  client/header/activity-panel/panels/orders.js
Labels: [Status] Ready to Merge

#5002 Add the jest-environment tag to known tags for jsdoc lint
  .eslintrc.js
  packages/data/src/export/test/reducer.js
  packages/data/src/notes/test/reducer.js
  packages/data/src/onboarding/test/reducer.js
  packages/data/src/options/test/reducer.js
  packages/data/src/reports/test/reducer.js
  packages/data/src/reviews/test/reducer.js
Labels: Build, Packages, [Status] Ready to Merge

#4949 Remove usage of __experimentalResolveSelect
  client/homescreen/stats-overview/index.js
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/homescreen/stats-overview/test/index.js
  client/homescreen/stats-overview/test/install-jetpack-cta.js
  client/profile-wizard/index.js
  packages/data/src/index.js
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/selectors.js
  packages/data/src/plugins/test/actions.js
  packages/data/src/plugins/test/reducer.js
  packages/data/src/registry.js
  tsconfig.json
Labels: Build, Packages, [Status] Ready to Merge, cooldown period

#5001 Group tasks by completion status
  client/task-list/tasks.js
Labels: [Status] Ready to Merge

#4962 Replace useFilters with wp's withFilters
  .eslintrc.js
  client/analytics/report/get-reports.js
  client/analytics/report/index.js
  client/analytics/settings/historical-data/status.js
  client/analytics/settings/index.js
  client/layout/index.js
  packages/components/CHANGELOG.md
  packages/components/src/higher-order/use-filters/README.md
  packages/components/src/higher-order/use-filters/index.js
Labels: Build, Components, Packages, [Status] Ready to Merge

#5009 Items dataStore: Migrate from wc-api
  client/analytics/components/leaderboard/index.js
  client/analytics/report/categories/table.js
  client/analytics/report/index.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  client/dashboard/leaderboards/index.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/panels/stock/card.js
  client/header/activity-panel/panels/stock/index.js
  client/header/activity-panel/unread-indicators.js
  client/wc-api/items/index.js
  client/wc-api/items/mutations.js
  client/wc-api/items/operations.js
  client/wc-api/items/selectors.js
  client/wc-api/wc-api-spec.js
  packages/data/src/index.js
  packages/data/src/items/action-types.js
  packages/data/src/items/actions.js
  packages/data/src/items/constants.js
  packages/data/src/items/index.js
  packages/data/src/items/reducer.js
  packages/data/src/items/resolvers.js
  packages/data/src/items/selectors.js
  packages/data/src/items/test/reducer.js
  packages/data/src/items/utils.js
Labels: Packages, [Status] Needs feedback

#5023 Refactor the Header component from class to function.
  client/header/index.js
  client/header/test/index.js
  client/layout/index.js
Labels: [Status] Needs feedback

#4984 Add filter to allow modification of report columns
  src/API/Reports/DataStore.php
Labels: [Status] Ready to Merge, cooldown period

#5000 Add complete and incomplete task counts to tasklist_complete event
  client/task-list/index.js
Labels: [Status] Ready to Merge

#4998 Refactor task list status to onboarding data store.
  client/dashboard/index.js
  client/header/activity-panel/panels/help.js
  client/homescreen/index.js
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/appearance.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/shipping/rates.js
  client/task-list/tasks/tax.js
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.js
  packages/data/src/onboarding/test/reducer.js
  packages/data/src/onboarding/with-onboarding-hydration.js
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
Labels: Home Screen, Onboarding, Packages, [Status] Ready to Merge, [Type] Dev, cooldown period

#4999 Remove onboarding feature flag and a/b testing
  client/dashboard/customizable.js
  client/dashboard/index.js
  client/dashboard/utils.js
  client/header/activity-panel/index.js
  client/homescreen/index.js
  client/homescreen/layout.js
  client/profile-wizard/steps/store-details.js
  docs/features/onboarding.md
  src/API/Init.php
  src/API/OnboardingTasks.php
  src/Features/Onboarding.php
  src/Loader.php
Labels: Onboarding, [Status] Ready to Merge

#5036 Add new note: Selling online courses
  src/FeaturePlugin.php
  src/Features/Onboarding.php
  src/Notes/WC_Admin_Notes_Selling_Online_Courses.php
Labels: [Status] Ready to Merge

#5032 Fix Advanced Filters Screen Reader Text
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/date-filter.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/advanced-filters/search-filter.js
  packages/components/src/advanced-filters/select-filter.js
Labels: Accessibility, Components, Packages, [Status] Ready to Merge, [Type] Bug

#5039 Clean up copy/paste
  client/task-list/tasks/payments/bacs.js
Labels: [Status] Ready to Merge

#5040 Onboarding: Do not show extensions bundle test if CBD is selected.
  client/profile-wizard/steps/business-details.js
Labels: Needs Cherry Picking

#5037 Add WooCommerce Mobile App Banner Ad for Android and iOS
  client/header/activity-panel/style.scss
  client/header/index.js
  client/header/style.scss
  client/header/test/index.js
  client/lib/platform/index.js
  client/mobile-banner/app-icon.js
  client/mobile-banner/constants.js
  client/mobile-banner/index.js
  client/mobile-banner/style.scss
  client/mobile-banner/test/index.js
  client/stylesheets/abstracts/_colors.scss
  config/core.json
  config/development.json
  config/plugin.json
  packages/data/src/user-preferences/use-user-preferences.js
  src/Features/MobileAppBanner.php
  src/Loader.php
Labels: Components, Packages, [Status] Needs Design Review, [Status] Needs Review

#5051 Fix a bug where an event's data was recorded in camel case.
  client/task-list/tasks/shipping/index.js
Labels: [Status] Ready to Merge

#4922 Add error logging to remote inbox notifications data source poller
  src/RemoteInboxNotifications/DataSourcePoller.php
Labels: [Status] Ready to Merge

#4965 Rename "profile" to "store details".
  client/dashboard/index.js
  client/homescreen/index.js
  client/layout/controller.js
  client/task-list/tasks.js
  src/Features/Onboarding.php
  src/Loader.php
Labels: [Status] Ready to Merge, [Type] Fix

#5038 Add "Product Attribute" advanced report filter.
  client/analytics/report/products/config.js
  client/lib/async-requests/index.js
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/attribute-filter.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/style.scss
  packages/components/src/search/autocompleters/variations.js
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Type] Enhancement

#5043 Tweak button padding so it works on Safari
  client/homescreen/welcome-modal/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5018 Fix components internal deps
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/tax.js
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/plugins/README.md
  packages/components/src/plugins/index.js
  packages/components/src/plugins/test/index.js
Labels: Build, Components, Packages, [Status] Ready to Merge

#5049 When toggling the task list, record a track event.
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#5015 Add monthly pricing toggle to product types
  client/profile-wizard/steps/product-types.scss
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/product-types/product-type.js
  client/profile-wizard/steps/product-types/style.scss
  client/profile-wizard/steps/product-types/test/__snapshots__/index.js.snap
  client/profile-wizard/steps/product-types/test/__snapshots__/product-type.js.snap
  client/profile-wizard/steps/product-types/test/index.js
  client/profile-wizard/steps/product-types/test/product-type.js
  client/profile-wizard/style.scss
Labels: [Status] Ready to Merge

#5057 Update contributors list to include woocommerce.
  readme.txt
Labels: [Status] Ready to Merge

#5025 Stop using missing installPlugin function and fix WCS 1.24 compatibility
  client/wp-admin-scripts/print-shipping-label-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
  src/Features/ShippingLabelBanner.php
Labels: Needs Cherry Picking, [Status] Needs Review
