Repository woocommerce/woocommerce-admin, pull requests merged in 2020-11, with the labels that each got.

#5373 Add store age to CES tracked data
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  packages/data/src/constants.js
  packages/data/src/index.js
Labels: [Status] Ready to Merge

#5511 Only show CES survey on correct page
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  src/Features/CustomerEffortScoreTracks.php
Labels: [Status] Ready to Merge

#5467 Home Screen - Added empty activity panel for orders
  client/header/activity-panel/activity-card/index.js
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/style.scss
  client/homescreen/activity-panel/orders/test/index.js
  client/homescreen/activity-panel/panels.js
Labels: Homescreen 2.0, [Status] Ready to Merge

#5506 Home Screen - Changed accordion styles
  packages/components/src/accordion/index.js
  packages/components/src/accordion/panel.js
  packages/components/src/accordion/style.scss
Labels: Homescreen 2.0, [Status] Ready to Merge

#5512 Add PSR-4 naming checks to PHP linting
  composer.json
  composer.lock
  phpcs.xml.dist
  src/Composer/Package.php
Labels: Build, [Status] Ready to Merge

#5497 Navigation: Applying styles & behavior for folded menu, including mobile
  client/header/index.js
  client/header/style.scss
  client/header/test/index.js
  client/hooks/useIsScrolled.js
  client/navigation/components/header/index.js
  client/navigation/index.js
  client/navigation/style.scss
  client/navigation/stylesheets/_colors.scss
  client/navigation/stylesheets/index.scss
  client/stylesheets/abstracts/_variables.scss
Labels: [Status] Ready to Merge

#5352 Display CES modal once per action per store
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  src/Features/CustomerEffortScoreTracks.php
Labels: [Status] Ready to Merge

#5519 Add width: 100% style to the container of the popover menu to expand …
  packages/components/src/advanced-filters/style.scss
Labels: [Status] Needs Review, [Type] Fix

#5496 Home Screen - Changed activity panel button styles
  client/header/activity-panel/activity-outbound-link/README.md
  client/header/activity-panel/activity-outbound-link/index.js
  client/header/activity-panel/activity-outbound-link/style.scss
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/style.scss
Labels: Homescreen 2.0, [Status] Ready to Merge

#5499 Inbox: Remove Store Setup Alert
  src/Features/Onboarding.php
  src/Install.php
  src/Notes/DeprecatedNotes.php
  src/Notes/OnboardingProfiler.php
Labels: Inbox, [Status] Ready to Merge, [Type] Tweak

#5365 Only allow Customer Effort Score gathering if tracking is allowed
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  src/Features/CustomerEffortScoreTracks.php
Labels: [Status] Ready to Merge

#5476 Reorganize the store management link section and provide extensibility
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/quick-links/index.js
  client/quick-links/stories/index.js
  client/quick-links/style.scss
  client/quick-links/test/index.js
  client/store-management-links/index.js
  client/store-management-links/quick-link-category/index.js
  client/store-management-links/quick-link-category/style.scss
  client/store-management-links/quick-link-category/test/index.js
  client/store-management-links/quick-link/index.js
  client/store-management-links/quick-link/style.scss
  client/store-management-links/quick-link/test/index.js
  client/store-management-links/style.scss
  client/store-management-links/test/index.js
  client/stylesheets/shared/_gutenberg-components.scss
Labels: Homescreen 2.0, [Status] Needs feedback, [Status] Ready to Merge, [Tests] Includes Tests

#5406 Use snackbar before CES modal
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  packages/customer-effort-score/src/index.js
Labels: [Status] Ready to Merge

#5527 Update/5394 remove label printing mention for non us countries
  src/Notes/ReviewShippingSettings.php
  tests/features/class-onboarding-set-up-shipping.php
Labels: [Status] Needs Review, [Type] Fix

#5520 Restyle the setup task list to match new designs
  client/dashboard/style.scss
  client/task-list/index.js
  client/task-list/style.scss
  packages/components/src/accordion/panel.js
  packages/components/src/accordion/style.scss
  packages/components/src/badge/index.js
  packages/components/src/badge/stories/index.js
  packages/components/src/badge/style.scss
  packages/components/src/index.js
  packages/components/src/style.scss
Labels: Homescreen 2.0, [Status] Ready to Merge

#5517 Update readme.txt to Unix Style Line Endings
  readme.txt
Labels: Build, [Priority] High, [Status] Ready to Merge

#5516 Home Screen - Changed design and onClick behavior
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/style.scss
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/style.scss
  client/homescreen/activity-panel/style.scss
Labels: Homescreen 2.0, [Status] Ready to Merge

#5513 Try: Register plugins under separate navigation menu
  client/navigation/components/container/index.js
  docs/examples/extensions/add-navigation-items/js/index.js
  docs/examples/extensions/add-navigation-items/woocommerce-admin-add-navigation-items-example.php
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Features/Marketing.php
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
  src/Features/Navigation/Screen.php
  src/PageController.php
Labels: Navigation, [Status] Ready to Merge

#5533 Update menu sorting for new nav structure
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
Labels: Navigation, [Status] Ready to Merge

#5543 Store Profiler - include Creative Mail as a free extension
  client/profile-wizard/steps/business-details.js
  images/onboarding/creativemail.png
  packages/data/src/plugins/constants.js
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
  src/Marketing/InstalledExtensions.php
Labels: [Status] Ready to Merge

#5455 Home Screen - migrated orders panel
  client/analytics/settings/config.js
  client/header/activity-panel/README.md
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-header/README.md
  client/header/activity-panel/activity-outbound-link/README.md
  client/header/activity-panel/activity-outbound-link/index.js
  client/header/activity-panel/activity-outbound-link/style.scss
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/unread-indicators.js
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/style.scss
  client/homescreen/activity-panel/orders/test/index.js
  client/homescreen/activity-panel/orders/utils.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/style.scss
  client/homescreen/activity-panel/test/index.js
  client/homescreen/layout.js
  packages/components/src/accordion/index.js
  packages/components/src/accordion/panel.js
  packages/components/src/accordion/style.scss
  packages/data/src/items/resolvers.js
Labels: Homescreen 2.0, [Status] Ready to Merge

#5546 Data: Verify we have an interval array before accessing.
  packages/data/src/reports/utils.js
Labels: [Status] Ready to Merge

#5541 Home Screen: Add missing text domain on home screen stats.
  client/homescreen/stats-overview/index.js
Labels: [Status] Ready to Merge

#5550 Added support for custom actionable statuses
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/utils.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/style.scss
  client/homescreen/activity-panel/test/index.js
Labels: Homescreen 2.0, [Status] Ready to Merge

#5465 Homescreen layout changes
  client/header/activity-panel/display-options/index.js
  client/header/activity-panel/display-options/test/index.js
  client/header/activity-panel/test/index.js
  client/homescreen/column.js
  client/homescreen/layout.js
  client/homescreen/style.scss
  client/homescreen/test/index.js
  client/inbox-panel/index.js
  client/inbox-panel/style.scss
  client/task-list/index.js
  client/task-list/test/index.js
  config/core.json
  config/development.json
  config/plugin.json
  includes/wc-admin-update-functions.php
  src/Features/AnalyticsDashboard.php
  src/Features/Homescreen.php
  src/Install.php
Labels: Homescreen 2.0, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#5549 Add missing translation call.
  src/Features/Analytics.php
Labels: [Status] Ready to Merge, [Type] Bug

#5534 Section overview should appear first in the subnav for each category
  src/Features/Marketing.php
  src/Features/Navigation/Menu.php
Labels: [Status] Ready to Merge

#5547 Do a refresh when redirecting to homescreen after completing OBW
  client/profile-wizard/index.js
Labels: [Status] Needs Review

#5524 Navigation: Adding ability for new navigation to scroll when list of links exceed viewport height
  client/navigation/components/container/index.js
  client/navigation/components/container/style.scss
  client/navigation/style.scss
Labels: Navigation, [Status] Needs Review

#5532 Copy the snackbar component from Gutenberg into wp-admin
  client/layout/transient-notices/index.js
  client/layout/transient-notices/snackbar/index.js
  client/layout/transient-notices/snackbar/list.js
  package.json
  packages/customer-effort-score/src/index.js
  packages/notices/.npmrc
  packages/notices/CHANGELOG.md
  packages/notices/README.md
  packages/notices/package.json
  packages/notices/src/index.js
  packages/notices/src/store/actions.js
  packages/notices/src/store/constants.js
  packages/notices/src/store/controls.js
  packages/notices/src/store/index.js
  packages/notices/src/store/reducer.js
  packages/notices/src/store/selectors.js
  packages/notices/src/store/test/actions.js
  packages/notices/src/store/test/reducer.js
  packages/notices/src/store/test/selectors.js
  packages/notices/src/store/utils/on-sub-key.js
  src/Loader.php
  webpack.config.js
Labels: [Status] Needs Review

#5544 Add onsubmit_label string that can be used to create a snackbar upon …
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  src/Features/CustomerEffortScoreTracks.php
Labels: Customer Effort Score, [Status] Ready to Merge

#5537 Add documentation for navigation feature
  docs/features/navigation.md
Labels: Navigation, [Status] Ready to Merge

#5542 Customers: Update column heading for date registered.
  client/analytics/report/customers/table.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5564 Navigation: Fix homescreen id on client
  client/layout/controller.js
Labels: Navigation, Needs Cherry Picking, [Status] Ready to Merge

#5576 Packages: Prep release
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
Labels: Navigation, Packages, [Status] Needs Review

#5548 Fix typo in DataStore
  src/API/Reports/DataStore.php
Labels: [Status] Needs Review

#5538 Add help tab to the home screen
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/style.scss
  client/header/activity-panel/tab/index.js
  client/header/activity-panel/tab/test/index.js
  client/header/activity-panel/test/help-panel.js
  client/header/activity-panel/test/index.js
Labels: Homescreen 2.0, [Status] Ready to Merge

#5574 Navigation: Restoring Orders "Add->Order" menu item on new nav
  src/Features/Navigation/CoreMenu.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5569 Update/5348 trigger ces on changing setting
  src/Features/CustomerEffortScoreTracks.php
  tests/features/class-wc-tests-ces-tracks.php
Labels: [Status] Ready to Merge

#5581 Fix a bug where welcome modal would briefly display even when dismissed.
  client/homescreen/layout.js
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5586 Fix column scroll collision after layout change.
  client/header/activity-panel/display-options/index.js
  client/homescreen/column.js
Labels: Homescreen 2.0, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug, [Type] Enhancement

#5579 Change rendering of homescreen layout so store links are last
  client/homescreen/layout.js
Labels: Homescreen 2.0, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5584 Fix/remove first product script navigation dependency
  src/Features/OnboardingTasks.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5593 Fix non-matching items and post type matching
  client/navigation/components/container/index.js
  client/navigation/utils.js
  src/Features/Navigation/Menu.php
Labels: Navigation, Needs Cherry Picking, [Status] Ready to Merge

#5578 Refactoring logic handling auto-folding navigation to support resize …
  client/navigation/components/header/index.js
Labels: Needs Cherry Picking, [Status] Needs feedback

#5353 Task List: Match Stripe settings to mode of provided keys
  client/task-list/tasks/payments/bacs.js
  client/task-list/tasks/payments/eway.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/payfast.js
  client/task-list/tasks/payments/stripe.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5590 Home screen - Fixed the orders not displaying bug
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/utils.js
Labels: Homescreen 2.0, Needs Cherry Picking, [Priority] High, [Status] Ready to Merge, [Type] Bug

#5603 Update Woo tested and min versions.
  tests/bootstrap.php
  woocommerce-admin.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5591 Update custom post type menu item defaults
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
Labels: Navigation, Needs Cherry Picking, [Status] Ready to Merge

#5606 Update non-wca pages registered with nav to embed pages
  client/index.js
  src/Loader.php
Labels: Navigation, Needs Cherry Picking, [Status] Ready to Merge

#5607 Allow extensions to order items in submenus
  src/Features/Navigation/Menu.php
Labels: Navigation, Needs Cherry Picking, [Status] Ready to Merge

#5610 Bump WooCommerce minimum requirements in documentation to 4.5
  readme.txt
Labels: Documentation, Needs Cherry Picking, [Status] Ready to Merge

#5598 Package builds: avoid building dependency-extraction-webpack-plugin
  bin/packages/build.js
  bin/starter-pack/._eslintrc
  bin/starter-pack/._eslintrc.js
  bin/starter-pack/._prettierrc.json
  bin/starter-pack/_package.json
  bin/starter-pack/starter-pack.js
  package-lock.json
  packages/dependency-extraction-webpack-plugin/package.json
Labels: Build, Packages, [Status] Needs feedback

#5587 Change select control padding to match text-control inputs
  packages/components/src/select-control/style.scss
Labels: [Status] Ready to Merge

#5573 Remove Inbox message is read styling
  client/inbox-panel/style.scss
Labels: [Status] Ready to Merge

#5570 Adding wrapper class around navigation to implement scroll styles/logic
  client/navigation/components/container/index.js
  client/navigation/style.scss
Labels: [Status] Ready to Merge

#5563 Add icon to snackbar
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  client/layout/transient-notices/snackbar/index.js
  client/layout/transient-notices/style.scss
  packages/customer-effort-score/src/index.js
  packages/notices/src/store/actions.js
  packages/notices/src/store/test/actions.js
  packages/notices/src/store/test/reducer.js
  packages/notices/src/store/test/selectors.js
Labels: [Status] Needs feedback

#5583 Fix reference to navigation package and fix transient notices so it l…
  client/layout/transient-notices/index.js
  src/Features/OnboardingTasks.php
Labels: [Status] Ready to Merge

#5619 Skip WC Payment plugin note if plugin not added through onboarding process
  src/Notes/SetUpAdditionalPaymentTypes.php
Labels: [Status] Ready to Merge

#5614 Fix WCS slug when building Tracks data.
  client/profile-wizard/steps/business-details.js
Labels: [Status] Ready to Merge, [Type] Bug

#5577 Composer 2: Update release scripts
  bin/pre-release.sh
  bin/update-version.php
Labels: [Status] Ready to Merge

#5612 packages: bump version Dep Ext Webpack plugin
  bin/starter-pack/_package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
Labels: Packages, [Status] Needs Review

#5635 Fix the travis build and move the e2e tests to GH actions
  .github/workflows/e2e.yml
  .travis.yml
  bin/travis.sh
  package-lock.json
Labels: [Status] Needs Review

#5624 Update panel icon order - moving help tab far right
  client/header/activity-panel/index.js
  client/header/activity-panel/tabs/index.js
  client/header/activity-panel/tabs/test/index.js
  client/header/activity-panel/test/index.js
Labels: [Status] Ready to Merge

#5616 Adding body class for navigation to indicate when it is expanded, pre…
  client/navigation/components/header/index.js
  client/navigation/style.scss
Labels: [Status] Needs feedback

#5641 PHP Fatal: Fix classnames in mobile app inbox notes.
  src/Notes/EditProductsOnTheMove.php
  src/Notes/ManageOrdersOnTheGo.php
  src/Notes/PerformanceOnMobile.php
  src/Notes/RealTimeOrderAlerts.php
Labels: Inbox, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5645 Fix a bug where wc-tracks was not loaded as a dependency.
  src/Features/OnboardingTasks.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5646 add dewps request table
  packages/dependency-extraction-webpack-plugin/README.md
Labels: [Status] Ready to Merge

#5634 Starter Pack: Create README page
  bin/starter-pack/README.md
Labels: Documentation, [Status] Ready to Merge

#5540 Show CES survey after editing an order
  packages/customer-effort-score/src/style.scss
  src/Features/CustomerEffortScoreTracks.php
Labels: Customer Effort Score, [Status] Ready to Merge

#5636 Packages: Update dependencies
  packages/components/package.json
  packages/data/package.json
Labels: [Status] Ready to Merge

#5623 Add support for an explicit dismiss button to snackbar, as well as an onDismiss callback
  client/layout/transient-notices/snackbar/index.js
  client/layout/transient-notices/style.scss
  packages/customer-effort-score/src/index.js
  packages/notices/src/store/actions.js
Labels: [Status] Needs feedback

#5650 Restore Autoloading of WooCommerce Classes in PHP Tests
  bin/install-wp-tests.sh
  tests/bootstrap.php
Labels: Build, [Status] Ready to Merge

#5653 Fixed Link component prop
  client/store-management-links/quick-link/index.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5661 Add key to the component to fix the warning and unexpected behavior
  client/analytics/report/taxes/config.js
Labels: [Status] Ready to Merge, [Type] Bug

#5660 Navigation: Renaming navigation body classes to be less generic
  client/navigation/components/header/index.js
  client/navigation/style.scss
Labels: Navigation, [Status] Ready to Merge

#5655 Fixed orders panel flickering
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/utils.js
  packages/data/src/items/selectors.js
Labels: Homescreen 2.0, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5558 Post 1.7.0 beta release chores
  bin/install-if-deps-outdated.js
  bin/travis.sh
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: [Status] Ready to Merge

#5678 CES: Update tests to fake that they are in wp-admin
  tests/features/class-wc-tests-ces-tracks.php
Labels: Customer Effort Score, [Status] Ready to Merge

#5668 Only import the Gridicons we need, to reduce package size.
  client/dashboard/dashboard-charts/index.js
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/test/index.js
  client/header/activity-panel/panels/reviews.js
  client/header/activity-panel/panels/stock/index.js
  client/marketing/overview/welcome-card/index.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/steps/theme/uploader.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/item.js
  packages/components/src/chart/index.js
  packages/components/src/rating/index.js
  packages/components/src/search-list-control/index.js
  packages/components/src/summary/number.js
Labels: [Status] Ready to Merge, [Type] Performance

#5648 CES: Add Tracks events for showing notice and modal
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  packages/customer-effort-score/src/index.js
Labels: Customer Effort Score, [Status] Ready to Merge

#5630 Hiding primary tabs on Settings within WooCommerce since it's redunda…
  client/navigation/style.scss
  src/Features/Navigation/CoreMenu.php
Labels: Navigation, [Status] Needs feedback

#5681 bump version
  src/Composer/Package.php
Labels: [Status] Needs Review

#5682 Prevent adding duplicate queue item by checking action and label values
  src/Features/CustomerEffortScoreTracks.php
  tests/features/class-wc-tests-ces-tracks.php
Labels: Customer Effort Score, [Status] Needs Review, [Type] Bug

#5685 Update the changelog for 1.7.2
  readme.txt
Labels: Documentation, [Status] Needs Review

#4933 Remove check for Jetpack and WCS from Stripe onboarding task
  client/task-list/tasks/payments/stripe.js
Labels: Onboarding, [Status] Ready to Merge

#5687 Manual version bump
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: [Status] Needs Review

#5696 Fix snackbar dismissal bug
  client/layout/transient-notices/index.js
  client/layout/transient-notices/snackbar/index.js
  client/layout/transient-notices/snackbar/list.js
Labels: [Status] Ready to Merge, [Type] Bug

#5700 CES: Fix dismissal button (X) style in notice/snackbar
  client/layout/transient-notices/style.scss
Labels: Customer Effort Score, [Status] Ready to Merge

#5703 Always call onRemove when action is clicked in Snackbar
  client/layout/transient-notices/snackbar/index.js
Labels: Customer Effort Score, [Status] Ready to Merge

#5697 Allow navigation feature in plugin and core builds
  config/core.json
  config/plugin.json
Labels: Navigation, [Status] Ready to Merge

#5698 Update core menu item order in navigation
  src/Features/Navigation/CoreMenu.php
Labels: Navigation, [Status] Ready to Merge

#5673 Continue showing task list even if entire list is complete
  client/homescreen/layout.js
  client/homescreen/test/index.js
Labels: [Status] Ready to Merge

#5701 Stripe - Remove redundant text
  client/task-list/style.scss
  client/task-list/tasks/payments/stripe.js
Labels: Onboarding, [Status] Ready to Merge

#5672 Disable Customer Effort Score for Mobile Users
  src/Features/CustomerEffortScoreTracks.php
  tests/features/class-wc-tests-ces-tracks.php
Labels: Customer Effort Score, [Status] Ready to Merge, [Tests] Includes Tests

#5611 Add fancy placeholders for Marketing components
  client/marketing/components/knowledge-base/index.js
  client/marketing/components/knowledge-base/placeholder.js
  client/marketing/components/knowledge-base/style.scss
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/components/recommended-extensions/index.js
  client/marketing/components/recommended-extensions/placeholder.js
  client/marketing/components/recommended-extensions/style.scss
  client/marketing/components/recommended-extensions/test/__snapshots__/placeholder.js.snap
  client/marketing/components/recommended-extensions/test/index.js
  client/marketing/components/recommended-extensions/test/placeholder.js
  client/marketing/coupons/style.scss
Labels: Marketing, [Status] Needs feedback

#5708 Changed price toggle placement
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/product-types/style.scss
  client/profile-wizard/steps/product-types/test/__snapshots__/index.js.snap
Labels: Onboarding, [Status] Ready to Merge

#5552 Don't show the Orders panel on the homescreen with the Task List
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/test/index.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/test/panels.js
  src/Features/Homescreen.php
Labels: Homescreen 2.0, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Tweak

#5679 Clean up menu callback methods
  src/Features/Navigation/Menu.php
Labels: Navigation, [Status] Needs feedback, [Status] Ready to Merge

#5628 Position transient notices based on nav width
  client/layout/transient-notices/style.scss
  client/navigation/style.scss
  client/navigation/stylesheets/_variables.scss
Labels: Navigation, [Status] Ready to Merge

#5715 Remove unused dependencies, convert buildScss to async
  bin/packages/build.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge, [Type] Dev

#5713 Install puppeteer just once
  package-lock.json
  package.json
Labels: [Status] Ready to Merge, [Type] Dev

#5686 Starter Pack: expand scope to all admin pages
  bin/starter-pack/_main.php
Labels: Navigation, [Status] Needs Review

#5722 Packages: Fix dependencies
  packages/navigation/src/index.js
  src/Loader.php
Labels: Packages, [Status] Ready to Merge

#5720 Revert the smart tax defaults work of #4594.
  client/profile-wizard/index.js
  src/Features/Onboarding.php
  src/Features/OnboardingAutomateTaxes.php
Labels: [Status] Ready to Merge

#5721 Revert the work to sort the task list by completion in #5001
  client/task-list/tasks.js
Labels: [Status] Ready to Merge

#5719 Remove loading state (isBusy) from the links
  client/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#5649 Add/5349 trigger ces on filtering analytics
  client/analytics/components/report-filters/index.js
  client/analytics/report/categories/index.js
  client/analytics/report/coupons/index.js
  client/analytics/report/products/index.js
  client/analytics/report/taxes/index.js
  client/analytics/report/variations/index.js
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  client/customer-effort-score-tracks/data/action-types.js
  client/customer-effort-score-tracks/data/actions.js
  client/customer-effort-score-tracks/data/constants.js
  client/customer-effort-score-tracks/data/index.js
  client/customer-effort-score-tracks/data/reducer.js
  client/customer-effort-score-tracks/data/resolvers.js
  client/customer-effort-score-tracks/data/selectors.js
  packages/components/src/compare-filter/index.js
Labels: Customer Effort Score, [Status] Needs Review

#5515 Update Customer Effort Score Modal
  packages/customer-effort-score/package.json
  packages/customer-effort-score/src/customer-feedback-modal/index.js
  packages/customer-effort-score/src/customer-feedback-modal/test/index.js
  packages/customer-effort-score/src/index.js
  packages/customer-effort-score/src/style.scss
Labels: Build, Customer Effort Score, Packages, [Status] Needs Review, [Tests] Includes Tests

#5729 Migrate Stock Panel to Homescreen
  client/header/activity-panel/activity-card/index.js
  client/header/activity-panel/activity-card/style.scss
  client/header/activity-panel/activity-card/test/__snapshots__/index.js.snap
  client/header/activity-panel/activity-card/test/index.js
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/stock/index.js
  client/header/activity-panel/unread-indicators.js
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/utils.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/stock/card.js
  client/homescreen/activity-panel/stock/index.js
  client/homescreen/activity-panel/stock/test/index.js
  client/homescreen/activity-panel/style.scss
  client/homescreen/activity-panel/test/index.js
  packages/components/CHANGELOG.md
  packages/components/src/accordion/panel.js
  packages/components/src/product-image/index.js
  packages/components/src/product-image/style.scss
  packages/components/src/product-image/test/__snapshots__/index.js.snap
  packages/data/src/items/reducer.js
  packages/data/src/items/selectors.js
  packages/data/src/items/test/reducer.js
  packages/data/src/items/test/utils.js
  packages/data/src/items/utils.js
  src/API/Products.php
  src/Features/ActivityPanels.php
  tests/api/products.php
Labels: Components, Homescreen 2.0, Packages, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#5739 Fix/some outstanding CES bugs
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  src/Features/CustomerEffortScoreTracks.php
Labels: Customer Effort Score, [Status] Ready to Merge

#5248 Add/wcpay usage tracking request
  client/layout/index.js
  client/layout/style.scss
  client/profile-wizard/steps/usage-modal.js
  client/profile-wizard/style.scss
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/wcpay-usage-modal.js
  client/task-list/tasks/payments/wcpay.js
  tests/e2e/specs/activate-and-setup/complete-store-details-section.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#5755 Customer Effort Score Package: Downgrade @wordpress/components to 11.0.0
  packages/customer-effort-score/package.json
Labels: Build, Packages, [Status] Ready to Merge

#5733 Allow actionable statuses in orders endpoint(s) filters.
  src/API/Orders.php
  src/API/Reports/Categories/Controller.php
  src/API/Reports/Controller.php
  src/API/Reports/Orders/Controller.php
  src/API/Reports/Orders/Stats/Controller.php
  tests/api/orders.php
Labels: Homescreen 2.0, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#5746 Cleanup items store actions
  client/homescreen/activity-panel/stock/card.js
  client/homescreen/activity-panel/stock/index.js
  client/homescreen/activity-panel/stock/test/index.js
  packages/data/src/items/action-types.js
  packages/data/src/items/actions.js
  packages/data/src/items/reducer.js
  packages/data/src/items/resolvers.js
  packages/data/src/items/test/reducer.js
Labels: Packages, [Status] Ready to Merge, [Type] Bug, [Type] Enhancement, cooldown period
