Repository woocommerce/woocommerce-admin, pull requests merged in 2020-03, with the labels that each got.

#3795 Onboarding: Enable taxes when automatic taxes are setup
  client/dashboard/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3790 Update Country Labeling to Match Core
  client/analytics/report/customers/config.js
  client/analytics/report/customers/table.js
  client/dashboard/components/settings/general/store-address.js
  docs/woocommerce.com/analytics-customers-report.md
  src/API/Reports/Customers/Controller.php
  src/API/Reports/Taxes/Controller.php
Labels: [Status] Ready to Merge

#3797 Version/1.0 master merge
  .travis.yml
  client/analytics/report/index.js
  client/analytics/report/products/table.js
  client/analytics/report/stock/table.js
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/style.scss
  client/dashboard/task-list/index.js
  client/dashboard/task-list/tasks/appearance.js
  client/header/activity-panel/index.js
  client/header/activity-panel/unread-indicators.js
  client/wp-admin-scripts/onboarding-homepage-notice/index.js
  images/onboarding/art-music-photography.jpg
  images/onboarding/electronics-computers.jpg
  images/onboarding/fashion-apparel-accessories.jpg
  images/onboarding/food-drink.jpg
  images/onboarding/health-beauty.jpg
  images/onboarding/home-furniture-garden.jpg
  images/onboarding/other-small.jpg
  images/onboarding/other.jpg
  package-lock.json
  package.json
  packages/components/src/dropdown-button/index.js
  packages/components/src/search/autocompleters/utils.js
  packages/components/src/search/index.js
  packages/components/src/search/test/index.js
  packages/components/src/select-control/list.js
  packages/components/src/tag/index.js
  readme.txt
  src/API/OnboardingProfile.php
  src/API/OnboardingTasks.php
  src/API/Products.php
  src/API/Reports/Products/Controller.php
  src/API/Reports/Stock/Controller.php
  src/FeaturePlugin.php
  src/Features/ActivityPanels.php
  src/Features/Onboarding.php
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, Components, Packages, [Status] Ready to Merge, [Type] Dev

#3739 Onboarding: Update screen order and remove Jetpack connection in profiler
  client/dashboard/components/cart-modal.js
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/benefits/images/card.js
  client/dashboard/profile-wizard/steps/benefits/images/flash_on.js
  client/dashboard/profile-wizard/steps/benefits/images/local_atm.js
  client/dashboard/profile-wizard/steps/benefits/images/phone_android.js
  client/dashboard/profile-wizard/steps/benefits/images/print.js
  client/dashboard/profile-wizard/steps/benefits/images/security.js
  client/dashboard/profile-wizard/steps/benefits/index.js
  client/dashboard/profile-wizard/steps/plugins.js
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Onboarding, [Status] Ready to Merge

#3759 Initial categories report user documentation
  docs/woocommerce.com/analytics-categories-report.md
  docs/woocommerce.com/images/analytics-categories-report-compare.png
  docs/woocommerce.com/images/analytics-categories-report-filter.png
  docs/woocommerce.com/images/analytics-categories-report-table-compare.png
  docs/woocommerce.com/images/analytics-categories-report.png
  docs/woocommerce.com/images/analytics-categories-search.png
  docs/woocommerce.com/images/analytics-categories-single-category.png
Labels: Documentation, [Status] Ready to Merge

#3748 Initial orders report user documentation
  docs/woocommerce.com/analytics-orders-report.md
  docs/woocommerce.com/images/analytics-orders-filter-match.png
  docs/woocommerce.com/images/analytics-orders-report-advanced-filters.png
  docs/woocommerce.com/images/analytics-orders-report.png
Labels: Documentation, [4.0] Merge

#3814 remove .jitm-card notice padding
  client/header/activity-panel/style.scss
Labels: Activity Panel, [4.0] Merge, [Status] Ready to Merge, [Type] Bug

#3786 OBW Connect: Fix requesting state
  client/dashboard/task-list/tasks/steps/connect.js
  client/dashboard/task-list/tasks/tax.js
Labels: [Status] Ready to Merge

#3807 Downloads: add docs
  docs/woocommerce.com/analytics-downloads-report.md
  docs/woocommerce.com/images/analytics-downloads-report-advanced-filters.png
  docs/woocommerce.com/images/analytics-downloads-report.png
Labels: [Status] Ready to Merge

#3809 Onboarding: Remove old development flags
  docs/features/onboarding.md
  src/Loader.php
  tests/bootstrap.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Dev

#3816 Fixes Taxes Report search bug and adds initial documentation.
  docs/woocommerce.com/analytics-taxes-report.md
  docs/woocommerce.com/images/analytics-taxes-report-comparison.png
  docs/woocommerce.com/images/analytics-taxes-report-search-results.png
  docs/woocommerce.com/images/analytics-taxes-report-search.png
  docs/woocommerce.com/images/analytics-taxes-report.png
  src/API/Taxes.php
Labels: Analytics, Documentation, [Status] Ready to Merge, [Type] Bug

#3787 OBW: Fix retry plugin install button disappearing
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/task-list/tasks/steps/plugins.js
Labels: [Status] Ready to Merge

#3826 Fix special character escaping in search.
  src/API/Coupons.php
  src/API/Products.php
  src/API/Taxes.php
Labels: Analytics, Build, REST API, [Status] Ready to Merge, [Type] Bug

#3828 Fix tracking on migrated options
  includes/core-functions.php
  src/Features/Onboarding.php
  src/Install.php
Labels: [Status] Ready to Merge, [Type] Bug

#3827 Activity Panels: Remove W Panel
  client/header/activity-panel/index.js
  client/header/activity-panel/style.scss
  client/header/activity-panel/wordpress-notices.js
Labels: Activity Panel, [Status] Needs Design Review, [Status] Ready to Merge

#3823 add npm run test:zip command
  bin/build-test-zip.sh
  bin/github-deploy.sh
  bin/make-zip.sh
  package.json
Labels: Build, [Type] Dev

#3831 1.0.0 release changes🎉
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#3830 Add Report Extension Example: Add default props to ReportFilters
  client/analytics/components/leaderboard/index.js
  client/analytics/components/report-table/index.js
  docs/examples/extensions/add-report/js/index.js
  docs/examples/extensions/add-report/woocommerce-admin-add-report-example.php
  packages/components/src/filters/index.js
  packages/components/src/table/index.js
Labels: Components, Packages, [Status] Ready to Merge

#3845 add left join to sku ordering
  src/API/Reports/Products/DataStore.php
Labels: Analytics, [4.0] Merge, [Status] Ready to Merge, [Type] Bug

#3812 Onboarding - business step: add more options in the competitors list and other fixes
  client/dashboard/profile-wizard/steps/business-details.js
  src/API/OnboardingProfile.php
  tests/api/onboarding-profile.php
Labels: Build, Onboarding, [Status] Needs Review

#3847 Onboarding: Track selling venue response in business details step
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge

#3764 Onboarding: Redesign plugin benefits screen
  client/dashboard/profile-wizard/header-logo.js
  client/dashboard/profile-wizard/header.js
  client/dashboard/profile-wizard/steps/benefits/images/card.js
  client/dashboard/profile-wizard/steps/benefits/images/flash_on.js
  client/dashboard/profile-wizard/steps/benefits/images/local_atm.js
  client/dashboard/profile-wizard/steps/benefits/images/management.js
  client/dashboard/profile-wizard/steps/benefits/images/phone_android.js
  client/dashboard/profile-wizard/steps/benefits/images/print.js
  client/dashboard/profile-wizard/steps/benefits/images/sales_tax.js
  client/dashboard/profile-wizard/steps/benefits/images/security.js
  client/dashboard/profile-wizard/steps/benefits/images/shipping_labels.js
  client/dashboard/profile-wizard/steps/benefits/images/speed.js
  client/dashboard/profile-wizard/steps/benefits/index.js
  client/dashboard/profile-wizard/steps/benefits/logo.js
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge

#3800 Changelog: Add Script
  bin/changelog.js
  bin/changelog/README.md
  bin/changelog/common/get-entry.js
  bin/changelog/common/index.js
  bin/changelog/common/make.js
  bin/changelog/config.js
  bin/changelog/github/index.js
  bin/changelog/github/make-change-log.js
  bin/changelog/github/requests.js
  bin/changelog/index.js
  bin/changelog/zenhub/index.js
  bin/changelog/zenhub/make-change-log.js
  bin/changelog/zenhub/requests.js
  package-lock.json
  package.json
Labels: Build, [Status] Needs Review

#3844 Fix/inconsistent wording downloads report
  client/analytics/report/downloads/config.js
  client/analytics/report/downloads/table.js
Labels: [Status] Ready to Merge

#3846 Onboarding: Use full width template for homepage in stores using Storefront
  src/API/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge

#3855 convert install timestamp to integer
  src/Notes/NoteTraits.php
Labels: [Many] Small, [Much] Small, [Status] Ready to Merge, [Type] Fix

#3872 Fix PHP Fatal on Multisite installs.
  src/FeaturePlugin.php
Labels: Packages, [4.0] Merge, [Status] Ready to Merge, [Type] Bug

#3870 Fix failing tests after WC 4.0 merge
  src/FeaturePlugin.php
  src/Overrides/WPPostStore.php
  src/Schedulers/SchedulerTraits.php
  tests/api/reports-import.php
  tests/batch-queue.php
  tests/framework/helpers/class-wc-helper-queue.php
  tests/queue-priority.php
Labels: [4.0] Merge, [Status] Ready to Merge, [Type] Bug

#3873 Don't attempt to create an inbox note before the tables exist.
  src/Features/ActivityPanels.php
Labels: Inbox, Needs Cherry Picking, [4.0] Merge, [Status] Ready to Merge, [Type] Bug

#3879 Update "WC tested up to" tag to "4.0.0"
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3839 Add/issue 15 trackings
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/index.js
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
  src/Features/ShippingLabelBanner.php
Labels: [Status] Needs feedback

#3883 [cherrypick] Fix feature plugin use on multisites.
  src/FeaturePlugin.php
Labels: [Status] Ready to Merge

#3884 [cherrypick] Don't attempt to create an inbox note before the tables exist.
  src/Features/ActivityPanels.php
Labels: [Status] Ready to Merge

#3857 Cherry Pick: Changelog: Add Script (#3800)
  bin/changelog.js
  bin/changelog/README.md
  bin/changelog/common/get-entry.js
  bin/changelog/common/index.js
  bin/changelog/common/make.js
  bin/changelog/config.js
  bin/changelog/github/index.js
  bin/changelog/github/make-change-log.js
  bin/changelog/github/requests.js
  bin/changelog/index.js
  bin/changelog/zenhub/index.js
  bin/changelog/zenhub/make-change-log.js
  bin/changelog/zenhub/requests.js
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#3851 fix undefined const WC_ADMIN_VERSION_NUMBER when WP < 5.3
  src/FeaturePlugin.php
  src/Package.php
Labels: [Status] Ready to Merge

#3876 Remove 'add first product' note
  src/Events.php
  src/Notes/WC_Admin_Notes_Add_First_Product.php
Labels: [Status] Ready to Merge

#3885 Cherrypick 3870 to version 1.0
  src/Overrides/WPPostStore.php
  src/Schedulers/SchedulerTraits.php
  tests/api/reports-import.php
  tests/batch-queue.php
  tests/framework/helpers/class-wc-helper-queue.php
  tests/queue-priority.php
Labels: [Status] Ready to Merge

#3886 Cherrypick "WC tested up to" tag
  woocommerce-admin.php
Labels: [Status] Ready to Merge

#3887 Release v1.0.1
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#3890 Zip: include files instead of exclude
  bin/build-test-zip.sh
  bin/make-zip.sh
Labels: Needs Cherry Picking

#3891 Delete an .orig file accidentally added during rebase
  client/dashboard/task-list/index.js.orig
Labels: [Status] Ready to Merge

#3896 Create database tables earlier - like core.
  src/Install.php
Labels: Build, Needs Cherry Picking, [4.0] Merge, [Status] Ready to Merge, [Type] Tweak

#3899 [cherrypick] 3896 Create database tables earlier - like core.
  src/Install.php
Labels: [Status] Ready to Merge

#3782 Onboarding: Update payments task flow
  client/dashboard/task-list/index.js
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/klarna.js
  client/dashboard/task-list/tasks/payments/payfast.js
  client/dashboard/task-list/tasks/payments/paypal.js
  client/dashboard/task-list/tasks/payments/square.js
  client/dashboard/task-list/tasks/payments/stripe.js
  client/wc-api/onboarding/constants.js
  src/API/OnboardingPlugins.php
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3725 Onboarding: business step: add Google Ads extension install
  client/dashboard/profile-wizard/steps/business-details.js
  client/wc-api/onboarding/constants.js
  images/onboarding/google-ads.png
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
Labels: [Status] Needs feedback

#3801 Onboarding: Add toggles to configured payments in task list
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/methods.js
  client/dashboard/task-list/tasks/payments/paypal.js
  client/dashboard/task-list/tasks/payments/stripe.js
  client/wc-api/options/operations.js
  client/wc-api/options/selectors.js
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge

#3832 Onboarding: Add offline payment methods
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/payments/bacs.js
  client/dashboard/task-list/tasks/payments/images/bacs.js
  client/dashboard/task-list/tasks/payments/images/cod.js
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/methods.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3898 [cherrypick] 3890 Zip: include files instead of exclude
  bin/build-test-zip.sh
  bin/make-zip.sh
Labels: Build, [Status] Ready to Merge

#3910 Task List: Verify Stripe key patterns before continuing.
  client/dashboard/task-list/tasks/payments/stripe.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3911 Update prestart script so readme.txt stable tag is updated
  bin/update-version.php
Labels: Build, [Status] Ready to Merge

#3917 Update prestart script so readme.txt stable tag is updated (#3911)
  bin/update-version.php
Labels: Build, [Status] Ready to Merge

#3909 Don't clear WCCOM note when clicking the action button.
  src/Notes/WC_Admin_Notes_Woo_Subscriptions_Notes.php
Labels: Inbox, [Status] Ready to Merge, [Type] Enhancement

#3916 [Cherrypick] #3725 to version/1.0
  client/dashboard/profile-wizard/steps/business-details.js
  client/wc-api/onboarding/constants.js
  images/onboarding/google-ads.png
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
Labels: [Status] Needs Review

#3918 Release 1.0.2
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Notes/DataStore.php
  src/Package.php
  tests/notes/class-wc-tests-notes-data-store.php
  woocommerce-admin.php
Labels: Build, Needs Cherry Picking, [Status] Needs Review

#3852 New/shipping banner display logic 13
  src/Features/ShippingLabelBanner.php
  src/Features/ShippingLabelBannerDisplayRules.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
Labels: Build, [Status] Needs Review

#3938 Fix calling protected has_satisfied_dependencies on outdated plugin
  src/Package.php
Labels: [Status] Ready to Merge

#3940 🍒 pick 3851 and 3938 into master
  src/FeaturePlugin.php
  src/Package.php
Labels: [Status] Ready to Merge

#3931 Rename Google Shopping image asset.
  client/dashboard/profile-wizard/steps/business-details.js
  images/onboarding/fb-woocommerce.png
  images/onboarding/g-shopping.png
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3941 🍒 Rename Google Shopping image asset. (#3931)
  client/dashboard/profile-wizard/steps/business-details.js
  images/onboarding/fb-woocommerce.png
  images/onboarding/g-shopping.png
Labels: [Status] Ready to Merge

#3929 Onboarding: Modified the recorded data in profile wizard
  client/dashboard/profile-wizard/steps/industry.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3936 remove replace_actionscheduler_store_class function
  src/FeaturePlugin.php
  src/Notes/WC_Admin_Notes.php
  src/Overrides/WPPostStore.php
  src/Package.php
  src/Schedulers/SchedulerTraits.php
  tests/framework/helpers/class-wc-helper-queue.php
Labels: [4.0] Merge, [Status] Needs Review, [Type] Bug

#3945 Tag version 1.0.3 in `master`.
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3745 Onboarding - payments task: filter payment gateways if the user selects CBD
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/payments/methods.js
  src/API/OnboardingPlugins.php
Labels: Build, Onboarding, [Status] Needs Review

#3927 Onboarding: Create flat rate and free shipping methods from task list
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/shipping/rates.js
Labels: Onboarding, [Status] Ready to Merge

#3908 Add WooCommerce support if store is using default theme
  src/Features/Onboarding.php
Labels: Onboarding, [Type] Bug

#3967 Onboarding: Add task completion and task list completion tracks
  client/dashboard/customizable.js
  client/dashboard/task-list/index.js
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
Labels: Onboarding

#3958 Add feature flag for wcpay (WooCommerce Payments)
  config/core.json
  config/development.json
  config/plugin.json
Labels: [Status] Ready to Merge

#3798 Make WooCommerce breadcrumbs use WooCommerce branding if it is installed
  client/header/index.js
  client/layout/controller.js
  includes/connect-existing-pages.php
  src/Loader.php
  src/PageController.php
Labels: [Status] Ready to Merge

#3961 Made the data store reading of content_data more resilient (#3926)
  src/Notes/DataStore.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: [Status] Needs Review

#3942 Fix undefined variable slug on theme activation error
  src/API/OnboardingThemes.php
Labels: [Status] Needs Review

#3965 Style and icon updates for Activity Panel
  client/header/activity-panel/index.js
  client/header/activity-panel/style.scss
  readme.txt
Labels: [Status] Ready to Merge

#3979 Don't change the banner text during WCS installation/activation
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
Labels: [Status] Needs Review

#3939 Animation slider example fix
  packages/components/CHANGELOG.md
  packages/components/src/animation-slider/docs/example.js
Labels: Components, Packages, [Status] Ready to Merge

#3313 Settings: wp.data feature branch
  client/analytics/components/leaderboard/index.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/downloads/table.js
  client/analytics/report/revenue/table.js
  client/analytics/settings/README.md
  client/analytics/settings/config.js
  client/analytics/settings/default-date.js
  client/analytics/settings/index.js
  client/dashboard/customizable.js
  client/dashboard/index.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/store-performance/index.js
  client/dashboard/style.scss
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/tax.js
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/unread-indicators.js
  client/index.js
  client/lib/date.js
  client/settings/index.js
  client/wc-api/items/utils.js
  client/wc-api/reports/utils.js
  client/wc-api/wc-api-spec.js
  package.json
  packages/data/.npmrc
  packages/data/README.md
  packages/data/package.json
  packages/data/src/constants.js
  packages/data/src/index.js
  packages/data/src/settings/action-types.js
  packages/data/src/settings/actions.js
  packages/data/src/settings/constants.js
  packages/data/src/settings/index.js
  packages/data/src/settings/reducer.js
  packages/data/src/settings/resolvers.js
  packages/data/src/settings/selectors.js
  packages/data/src/settings/use-settings.js
  packages/data/src/settings/with-settings-hydration.js
  packages/data/src/use-select-with-refresh.js
  packages/data/src/utils.js
  src/Loader.php
  webpack.config.js
Labels: Build, Packages, [Status] Needs Review

#3984 Verify coupon dates are DateTime instances before trying to format them.
  src/API/Reports/Coupons/DataStore.php
Labels: Analytics, REST API, [Status] Ready to Merge, [Type] Fix, cooldown period

#3975 Hide the WC Shipping banner until the create shipping label popup is open
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
Labels: Build, [Status] Needs Review

#3976 Add flex to banner to center vertical text alignment
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
Labels: [Status] Needs Review

#4001 Storybook: point to correct folder
  storybook/main.js
Labels: [Status] Needs Review

#4004 Ignore *.swp files
  .gitignore
Labels: Build, [Status] Ready to Merge

#3895 "Personalize your store" reminder: new inbox notification
  src/API/OnboardingTasks.php
  src/Events.php
  src/Notes/WC_Admin_Notes_Personalize_Store.php
Labels: [Status] Needs Review

#3980 Add showPagePicker, showPerPagePicker props to Pagination component
  packages/components/src/pagination/README.md
  packages/components/src/pagination/index.js
  packages/components/src/pagination/stories/index.js
Labels: Components, Marketing, Packages, [Status] Ready to Merge, [Type] Enhancement

#3999 Abstract onboarding plugin code into a PluginsHelper class
  src/Features/Onboarding.php
  src/PluginsHelper.php
  tests/plugins-helper.php
Labels: Marketing, Onboarding, [Status] Ready to Merge, [Tests] Includes Tests

#4010 Position error message directly under the paragraph
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
Labels: [Status] Needs Review

#3996 Fix/remove address alerts 55
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
Labels: Build

#4011 Onboarding: only validate other platform name for 'other' selling venues
  client/dashboard/profile-wizard/steps/business-details.js
Labels: [Status] Ready to Merge

#4007 Onboarding: Business details: Change "Google Shopping" to "Google Ads" and update Google Ads logo
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/style.scss
  client/wc-api/onboarding/constants.js
  images/onboarding/g-shopping.png
Labels: Onboarding, [Status] Ready to Merge

#3969 Reduce queries in Orders Panel.
  client/header/activity-panel/panels/orders.js
  src/API/Orders.php
  src/Overrides/Order.php
Labels: Activity Panel, REST API, [Status] Ready to Merge, [Type] Performance, cooldown period

#3993 Remove icon-button classes from Tag component
  packages/components/src/tag/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#4018 Fix/shipping banner dismiss
  src/Features/ShippingLabelBannerDisplayRules.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
Labels: [Status] Needs Review

#3955 WooCommerce Shipping order page banner prompt
  bin/make-zip.sh
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/index.js
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/setup-notice/index.js
  client/wp-admin-scripts/print-shipping-label-banner/setup-notice/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
  client/wp-admin-scripts/print-shipping-label-banner/wcs-api.js
  config/core.json
  config/development.json
  config/plugin.json
  images/shippingillustration.svg
  src/API/Init.php
  src/Features/ShippingLabelBanner.php
  src/Features/ShippingLabelBannerDisplayRules.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
  webpack.config.js
Labels: Build, [Status] Needs Review, [Type] Enhancement

#3997 Avoid making redundant requests for performance indicators.
  src/API/Reports/PerformanceIndicators/Controller.php
Labels: Dashboard, REST API, [Status] Ready to Merge, [Type] Performance, cooldown period

#4022 Merge add/wc-pay to master, enabled for development only
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/payments/images/wcpay.js
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/methods.js
  client/dashboard/task-list/tasks/payments/wcpay.js
  client/wc-api/onboarding/constants.js
  config/core.json
  config/development.json
  config/plugin.json
  src/API/OnboardingPlugins.php
  src/Features/Onboarding.php
Labels: [Status] Ready to Merge

#3953 Marketing Tab MVP
  client/layout/controller.js
  client/marketing/README.md
  client/marketing/components/button/README.md
  client/marketing/components/button/index.js
  client/marketing/components/button/style.scss
  client/marketing/components/index.js
  client/marketing/components/product-icon/README.md
  client/marketing/components/product-icon/index.js
  client/marketing/components/product-icon/style.scss
  client/marketing/components/slider/index.js
  client/marketing/components/slider/style.scss
  client/marketing/data/actions.js
  client/marketing/data/constants.js
  client/marketing/data/index.js
  client/marketing/data/resolvers.js
  client/marketing/data/selectors.js
  client/marketing/overview/index.js
  client/marketing/overview/installed-extensions/index.js
  client/marketing/overview/installed-extensions/row.js
  client/marketing/overview/installed-extensions/style.scss
  client/marketing/overview/knowledge-base/index.js
  client/marketing/overview/knowledge-base/style.scss
  client/marketing/overview/recommended-extensions/index.js
  client/marketing/overview/recommended-extensions/item.js
  client/marketing/overview/recommended-extensions/style.scss
  client/marketing/overview/style.scss
  client/marketing/overview/welcome-card/images/welcome.png
  client/marketing/overview/welcome-card/index.js
  client/marketing/overview/welcome-card/style.scss
  client/stylesheets/abstracts/_colors.scss
  config/core.json
  config/development.json
  config/plugin.json
  images/marketing/facebook.svg
  images/marketing/mailchimp.svg
  src/API/Init.php
  src/API/MarketingOverview.php
  src/API/OnboardingPlugins.php
  src/Features/Marketing.php
  src/Marketing/InstalledExtensions.php
  tests/js/jest.config.json
  tests/js/mocks/static.js
Labels: Components, Marketing, Packages, [Status] Ready to Merge

#4009 Only query requested stat totals in reports.
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/categories/index.js
  client/analytics/report/categories/table.js
  client/analytics/report/coupons/index.js
  client/analytics/report/coupons/table.js
  client/analytics/report/customers/table.js
  client/analytics/report/downloads/index.js
  client/analytics/report/downloads/table.js
  client/analytics/report/orders/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/index.js
  client/analytics/report/revenue/table.js
  client/analytics/report/stock/table.js
  client/analytics/report/taxes/index.js
  client/analytics/report/taxes/table.js
  client/dashboard/dashboard-charts/block.js
  client/dashboard/dashboard-charts/index.js
  client/wc-api/reports/utils.js
  src/API/Reports/Coupons/Stats/Controller.php
  src/API/Reports/Customers/Stats/Controller.php
  src/API/Reports/Downloads/Stats/Controller.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Revenue/Stats/Controller.php
  src/API/Reports/Taxes/Stats/Controller.php
Labels: REST API, [Status] Ready to Merge, [Type] Performance, cooldown period

#4019 Show admin notices on legacy admin screens
  src/Loader.php
Labels: [Status] Needs Review, [Type] Bug, cooldown period
