Repository woocommerce/woocommerce-admin, pull requests merged in 2020-09, with the labels that each got.

#5061 Show usage modal when skipping the OBW
  client/profile-wizard/steps/store-details.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5065 Remove industry option for travel.
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5059 Profile wizard style consistency updates
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/product-types/label.js
  client/profile-wizard/steps/product-types/style.scss
  client/profile-wizard/steps/product-types/test/__snapshots__/index.js.snap
  client/profile-wizard/steps/store-details.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/style.scss
  composer.json
  composer.lock
  package-lock.json
  packages/components/src/pill/pill.js
  packages/components/src/pill/style.scss
  packages/components/src/stepper/style.scss
  readme.txt
Labels: Build, Components, Packages, [Status] Needs Review

#5056 Show full variation name instead of parent product in orders report.
  src/API/Reports/Orders/DataStore.php
  tests/reports/class-wc-tests-reports-orders.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#5050 Add support for advanced filters with multiple instances.
  packages/components/src/advanced-filters/README.md
  packages/components/src/advanced-filters/attribute-filter.js
  packages/components/src/advanced-filters/date-filter.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/item.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/advanced-filters/search-filter.js
  packages/components/src/advanced-filters/select-filter.js
  packages/data/src/reports/utils.js
  packages/navigation/CHANGELOG.md
  packages/navigation/src/filters.js
  packages/navigation/src/test/filters.js
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#4982 Migrated "import" store to "wp.data"
  client/analytics/settings/historical-data/actions.js
  client/analytics/settings/historical-data/index.js
  client/analytics/settings/historical-data/layout.js
  client/analytics/settings/historical-data/period-selector.js
  client/analytics/settings/historical-data/skip-checkbox.js
  client/analytics/settings/historical-data/test/utils.js
  client/analytics/settings/historical-data/utils.js
  client/wc-api/imports/index.js
  client/wc-api/imports/operations.js
  client/wc-api/imports/selectors.js
  client/wc-api/wc-api-spec.js
  packages/data/src/import/action-types.js
  packages/data/src/import/actions.js
  packages/data/src/import/constants.js
  packages/data/src/import/index.js
  packages/data/src/import/reducer.js
  packages/data/src/import/resolvers.js
  packages/data/src/import/selectors.js
  packages/data/src/import/test/reducer.js
  packages/data/src/index.js
Labels: Packages, [Status] Ready to Merge, cooldown period

#5074 New marketing copy for the Kliken Google Ads plugin
  client/profile-wizard/steps/business-details.js
Labels: Needs Cherry Picking, [Status] Needs Review

#5067 Consistently use USA spelling for "optimize"
  src/Notes/WC_Admin_Notes_Facebook_Marketing_Expert.php
Labels: Marketing, [Status] Needs Review

#5085 Add ToS agreement copy to the WCPay setup task
  client/task-list/index.js
  client/task-list/style.scss
  client/task-list/tasks.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5076 Automated taxes smart default
  client/profile-wizard/index.js
  src/Features/Onboarding.php
  src/Features/OnboardingAutomateTaxes.php
Labels: [Status] Needs Review

#5079 Fix `analytics_filters_filter` event props.
  client/analytics/components/report-filters/index.js
Labels: [Status] Ready to Merge, [Type] Bug

#5068 Add product attribute filter to Orders Report.
  client/analytics/report/orders/config.js
  src/API/Reports/DataStore.php
  src/API/Reports/Orders/Controller.php
  src/API/Reports/Orders/DataStore.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/Orders/Stats/DataStore.php
  tests/api/reports-orders-stats.php
  tests/api/reports-orders.php
Labels: Analytics, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#5075 Remove wc api 🎉
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/components/report-table/utils.js
  client/analytics/report/customers/config.js
  client/analytics/report/revenue/table.js
  client/analytics/report/taxes/config.js
  client/analytics/settings/historical-data/index.js
  client/dashboard/customizable.js
  client/dashboard/store-performance/index.js
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/index.js
  client/header/activity-panel/panels/reviews.js
  client/homescreen/layout.js
  client/homescreen/stats-overview/stats-list.js
  client/index.js
  client/layout/store-alerts/index.js
  client/layout/transient-notices/index.js
  client/lib/async-requests/index.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/theme/index.js
  client/task-list/tasks/appearance.js
  client/task-list/tasks/connect.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/tasks/payments/square.js
  client/task-list/tasks/payments/stripe.js
  client/task-list/tasks/shipping/index.js
  client/wc-api/constants.js
  client/wc-api/utils.js
  client/wc-api/wc-api-spec.js
  client/wc-api/with-select.js
  client/wc-api/wp-data-store/create-api-client.js
  client/wc-api/wp-data-store/create-store.js
  client/wc-api/wp-data-store/index.js
  client/wc-api/wp-data-store/reducer.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  package-lock.json
  package.json
  packages/data/src/index.js
Labels: [Status] Ready to Merge

#5096 Onboarding: Add TOS note to bundle install.
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/style.scss
Labels: Needs Cherry Picking, [Status] Needs Review

#5028 Initial end to end tests
  .eslintignore
  .travis.yml
  README.md
  babel.config.js
  client/dashboard/components/settings/general/store-address.js
  docker-compose.yaml
  package-lock.json
  package.json
  tests/e2e/config/default.json
  tests/e2e/config/env.setup.js
  tests/e2e/config/jest.config.js
  tests/e2e/config/test-e2e.json
  tests/e2e/docker/initialize.sh
  tests/e2e/specs/activate-and-setup/complete-benefits-section.js
  tests/e2e/specs/activate-and-setup/complete-business-section.js
  tests/e2e/specs/activate-and-setup/complete-industry-section.js
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.js
  tests/e2e/specs/activate-and-setup/complete-product-types-section.js
  tests/e2e/specs/activate-and-setup/complete-store-details-section.js
  tests/e2e/specs/activate-and-setup/complete-theme-selection-section.js
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
  tests/e2e/specs/activate-and-setup/utils.js
  tests/e2e/utils/actions.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/lib.js
  tests/js/jest.config.json
Labels: Build, [Status] Needs Review, [Tests] Includes Tests

#5101 Onboarding: Set woocommerce_setup_jetpack_opted_in on Jetpack connect
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5097 Add ToS copy to OBW business details
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/style.scss
Labels: [Status] Needs feedback, [Status] Ready to Merge

#5094 Combine translation chunks when language packs are updated.
  src/Loader.php
Labels: [Status] Ready to Merge, [Type] Bug

#5054 Add Edit products on the move admin note
  src/Events.php
  src/Notes/NoteTraits.php
  src/Notes/WC_Admin_Notes_Edit_Products_On_The_Move.php
  src/Notes/WC_Admin_Notes_Real_Time_Order_Alerts.php
Labels: [Status] Ready to Merge

#5105 Update Storybook to latest
  package-lock.json
  package.json
  storybook/webpack.config.js
Labels: Build, [Status] Ready to Merge

#5100 Avoid changing product titles by removing variation title filter usage.
  client/analytics/report/products/table-variations.js
  src/API/ProductVariations.php
  src/API/Reports/Products/Stats/DataStore.php
  src/API/Reports/Segmenter.php
  src/API/Reports/Variations/DataStore.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#5122 Packages: release prep
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/tracks/package.json
Labels: Build, Components, Packages, [Status] Ready to Merge

#5114 Remove the chevron icons from the “Finish setup” task list
  client/task-list/index.js
  client/task-list/test/index.js
Labels: [Status] Ready to Merge

#5129 Home Screen: Fixed card to connect to woo.com account
  src/Notes/WC_Admin_Notes_Woo_Subscriptions_Notes.php
Labels: [Status] Ready to Merge

#5111 Add option to not charge sales tax
  client/dashboard/components/connect/index.js
  client/dashboard/components/connect/test/index.js
  client/task-list/tasks/tax.js
  packages/components/src/plugins/index.js
  packages/components/src/plugins/test/index.js
  src/Features/OnboardingTasks.php
Labels: Components, Packages, [Status] Ready to Merge

#5134 Add filters for columns in reports
  src/API/Reports/Categories/Controller.php
  src/API/Reports/Coupons/Controller.php
  src/API/Reports/Customers/Controller.php
  src/API/Reports/Downloads/Controller.php
  src/API/Reports/Orders/Controller.php
  src/API/Reports/Products/Controller.php
  src/API/Reports/Stock/Controller.php
Labels: [Status] Ready to Merge

#5108 Enable the home screen for everybody
  client/dashboard/customizable.js
  client/dashboard/index.js
  client/header/activity-panel/index.js
  client/homescreen/stats-overview/stats-list.js
  client/layout/controller.js
  client/layout/index.js
  config/core.json
  config/development.json
  config/plugin.json
  packages/components/src/summary/number.js
  packages/components/src/summary/style.scss
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Loader.php
  src/Notes/WC_Admin_Notes_Home_Screen_Feedback.php
Labels: Components, Packages, [Status] Ready to Merge

#5130 Don't include "min" suffix in build JavaScript when targeting core.
  config/core.json
  config/development.json
  config/plugin.json
  src/Loader.php
  webpack.config.js
Labels: Build, [Status] Ready to Merge, [Type] Bug

#5149 Taxes Sync: Force float before addition of string numbers
  src/API/Reports/Taxes/DataStore.php
Labels: [Status] Ready to Merge

#5139 chore: rename WCS to WC Shipping & Tax
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  client/profile-wizard/steps/business-details.js
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/tax.js
  docs/features/onboarding.md
  packages/data/src/plugins/constants.js
  src/API/OnboardingProfile.php
  src/API/Plugins.php
  src/Features/ShippingLabelBannerDisplayRules.php
  src/Notes/WC_Admin_Notes_Install_JP_And_WCS_Plugins.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
Labels: [Status] Ready to Merge

#5153 Update/components deps
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: Build, Components, Packages, [Status] Ready to Merge

#5158 Remove ` @woocommerce/wc-admin-settings` from data package
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/profile-wizard/index.js
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/test/actions.js
Labels: Build, Components, Packages, [Status] Needs Review

#5162 Add Opt-Out for Remote Inbox Notifications
  src/Events.php
Labels: [Status] Needs Review

#5152 Use 'yes' to update modal dismiss option.
  client/homescreen/layout.js
Labels: [Status] Ready to Merge, [Type] Bug

#5157 Store Profiler - Industry: reduced padding and removed industry
  client/profile-wizard/style.scss
  src/Features/Onboarding.php
  tests/e2e/specs/activate-and-setup/complete-industry-section.js
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.js
Labels: Onboarding, [Status] Ready to Merge

#5166 Show payments task for non-US stores when wcpay installed
  client/task-list/tasks.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5165 Fix version update script for composer.json
  bin/update-version.php
Labels: Build, [Status] Ready to Merge

#5170 Remove store registration checks that are no longer needed.
  packages/data/src/export/index.js
  packages/data/src/import/index.js
  packages/data/src/items/index.js
  packages/data/src/notes/index.js
  packages/data/src/onboarding/index.js
  packages/data/src/plugins/index.js
  packages/data/src/reports/index.js
  packages/data/src/reviews/index.js
  packages/data/src/settings/index.js
Labels: Packages, [Status] Ready to Merge

#5190 Renamed task list item
  client/task-list/tasks.js
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge

#5180 Display the store setup link on the homescreen if the task list is incomplete.
  client/header/activity-panel/index.js
  client/header/activity-panel/test/index.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5169 Navigation package: Declare script dependencies
  src/Loader.php
Labels: [Status] Needs feedback

#5196 Renamed OBW skip button
  client/profile-wizard/steps/store-details.js
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge

#5197 Pass Stripe supported countries in tasks status REST API
  src/API/OnboardingTasks.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
Labels: [Status] Ready to Merge

#5203 Add rule processors for country and state
  src/RemoteInboxNotifications/BaseLocationCountryRuleProcessor.php
  src/RemoteInboxNotifications/BaseLocationStateRuleProcessor.php
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/README.md
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5173 Fix header height and positioning for wc nav
  client/header/activity-panel/style.scss
  client/header/style.scss
  client/layout/style.scss
  client/profile-wizard/index.js
  client/profile-wizard/steps/theme/style.scss
  client/profile-wizard/style.scss
  client/stylesheets/abstracts/_variables.scss
Labels: Navigation, [Status] Ready to Merge

#5194 Enlarged store profiler text in two steps
  client/profile-wizard/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5124 Onboarding - Store Profiler - Removed selected CBD option for eCommerce plan
  client/task-list/tasks/payments/index.js
  src/API/OnboardingProfile.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5205 Fix a bug where the store task list would remain after completion
  client/task-list/index.js
Labels: Needs Cherry Picking, [Status] Needs Review

#5213 Remove product settings video note
  src/Events.php
  src/Install.php
  src/Notes/DeprecatedNotes.php
  src/Notes/LearnMoreAboutProductSettings.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5210 Fix smart tax defaults Jetpack connection logic
  src/Features/OnboardingAutomateTaxes.php
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge, [Type] Bug

#5214 Redirect to setup wizard when activation transient is present
  src/Features/Onboarding.php
Labels: [Status] Needs Review

#5219 Navigation package: Version bump
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
Labels: Build, Packages

#5211 Fix wakeup visibility for PHP 8 compatibility
  src/FeaturePlugin.php
Labels: [Status] Ready to Merge

#5226 Task list: Turn off Stripe test mode when submitting live keys
  client/task-list/tasks/payments/stripe.js
Labels: [Status] Needs Review
