Repository woocommerce/woocommerce-admin, pull requests merged in 2020-10, with the labels that each got.

#5171 Remove Customer Analytics Data Upon Order Deletion
  src/API/Reports/Customers/DataStore.php
  src/API/Reports/Orders/Stats/DataStore.php
  tests/reports/class-wc-tests-reports-customers.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#5230 Onboarding: Remove check for legacy onboarding in redirect logic.
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5212 Change store details tooltip to a popover
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/store-details/style.scss
Labels: [Status] Ready to Merge

#5233 Improve the pre-commit hook setup for wc-admin
  lint-staged.config.js
  package-lock.json
  package.json
Labels: Build, [Status] Needs feedback, [Status] Ready to Merge, cooldown period

#5201 Updating Stripe key field validation to support test keys (#4391)
  client/layout/style.scss
  client/task-list/tasks/payments/stripe.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#5207 Add note status remote inbox notifications rule processor
  src/Notes/Notes.php
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/NoteStatusRuleProcessor.php
  src/RemoteInboxNotifications/README.md
Labels: [Status] Ready to Merge

#5199 Search component: Behavior and styling tweaks
  packages/components/src/select-control/index.js
  packages/components/src/select-control/style.scss
  packages/components/src/tag/style.scss
Labels: Components, Packages, [Status] Ready to Merge

#5215 Declare the note constants on the deprecated class.
  src/DeprecatedClassFacade.php
  src/Notes/DeprecatedNotes.php
Labels: [Status] Ready to Merge, [Type] Bug

#5229 Remove dynamic content hash from chunk names.
  chunk-src-version-param.js
  src/Loader.php
  webpack.config.js
Labels: Build, [Status] Ready to Merge, [Type] Dev, cooldown period

#5252 Inbox Panel component moved
  client/header/activity-panel/index.js
  client/header/activity-panel/unread-indicators.js
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/inbox-panel/action.js
  client/inbox-panel/card.js
  client/inbox-panel/index.js
  client/inbox-panel/placeholder.js
  client/inbox-panel/style.scss
  client/inbox-panel/test/index.js
  client/inbox-panel/utils.js
Labels: [Status] Ready to Merge, cooldown period

#5263 Add animation to Inbox note deletion
  client/inbox-panel/index.js
  client/inbox-panel/style.scss
Labels: [Status] Ready to Merge, cooldown period

#5231 Wrap search control selected items in list
  packages/components/src/search-list-control/index.js
  packages/components/src/search-list-control/style.scss
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
Labels: Components, Packages, [Status] Ready to Merge

#5200 Update store setup link to redirect to setup wizard
  src/Notes/OnboardingProfiler.php
Labels: [Status] Ready to Merge

#5232 Removing breadcrumbs from wc-admin header, replacing with simple titl…
  client/header/index.js
  client/header/style.scss
  client/header/test/index.js
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_reset.scss
  src/Loader.php
Labels: [Status] Ready to Merge

#5281 Fix inconsistent line endings in readme.txt
  readme.txt
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5254 Update Starter Pack
  bin/starter-pack/._eslintrc
  bin/starter-pack/_main.php
  bin/starter-pack/_package.json
  bin/starter-pack/_webpack.config.js
  bin/starter-pack/starter-pack.js
Labels: [Status] Ready to Merge

#5255 Navigation: Update PHP registration
  src/Features/Analytics.php
  src/PageController.php
Labels: Navigation, [Status] Needs feedback

#5283 Add @deprecated tag to DeprecatedNotes comments
  src/Notes/DeprecatedNotes.php
Labels: [Status] Ready to Merge

#5279 Add/confirm tax settings note
  src/Features/OnboardingAutomateTaxes.php
  src/Notes/ConfirmTaxSettings.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5276 Fix a bug in tax automation logic and track the event in analytics
  src/Features/OnboardingAutomateTaxes.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5305 Notes: Change WooCommerce Services to WooCommerce Shipping & Tax.
  src/Notes/ConfirmTaxSettings.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5291 Task List - Solving browser back button issue
  client/task-list/tasks/payments/index.js
Labels: Needs Cherry Picking, Setup Checklist, [Status] Needs Review, [Type] Bug

#5293 Version bump: WP components and base styles
  client/stylesheets/shared/_gutenberg-components.scss
  package-lock.json
  package.json
Labels: Navigation, [Status] Needs Review

#5290 Load onboarding data when enabled or directly visiting
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5302 Handle variation IDs that are no longer found.
  src/API/Reports/Variations/DataStore.php
Labels: Analytics, Needs Cherry Picking, [Status] Needs Review, [Type] Bug

#5310 Fix Inconsistent Newlines in 1.6.0 Release Readme
  readme.txt
Labels: [Status] Needs Review

#5311 Ensure that the iOS smart banner is rendered on all WC pages
  src/Loader.php
Labels: Needs Cherry Picking, [Status] Needs Review

#5312 Shipping task smart default: add exceptions
  client/task-list/tasks.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5314 Change constants to use old notes class name.
  src/Notes/ConfirmTaxSettings.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
Labels: [Priority] Critical

#5317 Fix note class name.
  src/Notes/ConfirmTaxSettings.php
Labels: Needs Cherry Picking, [Status] Needs Review, [Type] Bug

#5319 Fix/5318 shipping default exclusions
  client/task-list/tasks.js
  src/Features/OnboardingSetUpShipping.php
Labels: [Status] Needs Review, [Type] Bug

#5320 Fix shipping task smart defaults
  client/task-list/tasks.js
  src/Features/OnboardingSetUpShipping.php
Labels: Needs Cherry Picking, [Status] Needs Review, [Type] Bug

#5275 Remove devdocs from wc-admin
  client/devdocs/docs.js
  client/devdocs/example.js
  client/devdocs/examples.json
  client/devdocs/index.js
  client/devdocs/style.scss
  client/layout/controller.js
  client/layout/test/index.js
  config/core.json
  config/development.json
  config/plugin.json
  docs/documentation.md
  package-lock.json
  package.json
  packages/components/src/advanced-filters/stories/index.js
  packages/components/src/compare-filter/stories/index.js
  packages/components/src/filter-picker/stories/index.js
  src/FeaturePlugin.php
  src/Features/Onboarding.php
  src/Loader.php
Labels: [Status] Ready to Merge

#5313 Test Zips: make sure assets are up to date
  package.json
Labels: [Status] Ready to Merge

#5206 Add option remote inbox notifications rule processor
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/OptionRuleProcessor.php
  src/RemoteInboxNotifications/README.md
  tests/remote-inbox-notifications/option-rule-processor.php
Labels: [Status] Ready to Merge

#5292 Navigation: Prep feature flags and option
  client/layout/index.js
  config/core.json
  config/development.json
  config/plugin.json
  src/Features/Navigation.php
Labels: Navigation, [Status] Ready to Merge

#5308 Navigation: Move PHP code to WC Admin
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
  src/Features/Navigation/Navigation.php
  src/Features/Navigation/Screen.php
Labels: Navigation, [Status] Ready to Merge

#5360 Store setup shortcut - not showing up anymore after dismissing the setup tasks
  client/header/activity-panel/index.js
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5364 Change readme.txt Line Endings to Unix Style
  readme.txt
Labels: [Priority] Critical, [Status] Needs Review

#5307 Preventing the legacy coupons page from being readded when the naviga…
  src/Features/CouponsMovedTrait.php
  src/Notes/CouponPageMoved.php
Labels: Navigation, [Status] Ready to Merge

#5342 Refactor CustomerEffortScore as Package
  bin/starter-pack/_webpack.config.js
  client/customer-effort-score-tracks/customer-effort-score.scss
  client/customer-effort-score-tracks/index.js
  package-lock.json
  package.json
  packages/customer-effort-score/.npmrc
  packages/customer-effort-score/CHANGELOG.md
  packages/customer-effort-score/README.md
  packages/customer-effort-score/package.json
  packages/customer-effort-score/src/index.js
  packages/customer-effort-score/src/style.scss
  packages/customer-effort-score/src/test/index.js
  src/Loader.php
  webpack.config.js
Labels: Customer Effort Score, [Status] Needs Review

#5367 Attempt to check for a theme step specific element when completing e2e test
  tests/e2e/specs/activate-and-setup/complete-theme-selection-section.js
Labels: [Status] Ready to Merge, [Type] Dev

#5379 Polyfill wc_is_running_from_async_action_scheduler().
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#5359 Adding 24px spacing between any sibling nav groups (#5329)
  client/navigation/components/container/style.scss
Labels: Navigation, [Status] Needs feedback

#5198 New Package: DependencyExtractionWebpackPlugin
  .gitignore
  bin/packages/build.js
  bin/starter-pack/_package.json
  bin/starter-pack/_webpack.config.js
  packages/dependency-extraction-webpack-plugin/.npmrc
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/README.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/dependency-extraction-webpack-plugin/src/index.js
Labels: Build, Packages, [Status] Ready to Merge, cooldown period

#5377 Task List: Show Stripe task in Brazil
  src/Features/OnboardingTasks.php
Labels: [Status] Ready to Merge

#5299 Migrate Enzyme tests to React Testing Library
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  client/analytics/components/leaderboard/test/index.js
  client/analytics/components/report-chart/test/index.js
  client/analytics/components/report-summary/test/index.js
  client/header/activity-panel/activity-card/test/__snapshots__/index.js.snap
  client/header/activity-panel/activity-card/test/__snapshots__/placeholder.js.snap
  client/header/activity-panel/activity-card/test/index.js
  client/header/activity-panel/activity-card/test/placeholder.js
  client/header/activity-panel/tab/test/index.js
  client/header/activity-panel/tabs/test/index.js
  client/homescreen/stats-overview/test/install-jetpack-cta.js
  client/homescreen/welcome-modal/test/index.js
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/components/recommended-extensions/test/index.js
  client/marketing/overview/welcome-card/test/index.js
  client/mobile-banner/test/index.js
  client/profile-wizard/steps/product-types/test/__snapshots__/product-type.js.snap
  client/profile-wizard/steps/product-types/test/product-type.js
  client/wp-admin-scripts/print-shipping-label-banner/dismiss-modal/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/setup-notice/test/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js
  package-lock.json
  package.json
  packages/components/src/card/test/__snapshots__/index.js.snap
  packages/components/src/card/test/index.js
  packages/components/src/chart/d3chart/d3base/test/index.js
  packages/components/src/chart/d3chart/test/legend.js
  packages/components/src/date/test/__snapshots__/index.js.snap
  packages/components/src/date/test/index.js
  packages/components/src/gravatar/test/index.js
  packages/components/src/image-upload/test/index.js
  packages/components/src/plugins/test/index.js
  packages/components/src/product-image/test/__snapshots__/index.js.snap
  packages/components/src/product-image/test/index.js
  packages/components/src/rating/test/__snapshots__/index.js.snap
  packages/components/src/rating/test/index.js
  packages/components/src/search/test/index.js
  packages/components/src/select-control/test/index.js
  packages/components/src/timeline/test/__snapshots__/index.js.snap
  packages/components/src/timeline/test/index.js
  tests/js/jest.config.json
  tests/js/setup-enzyme.js
  tests/js/setup-react-testing-library.js
Labels: Build, Tech debt, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Dev, cooldown period

#5400 Show orders, stock and reviews activity panels
  client/header/activity-panel/index.js
Labels: Needs Cherry Picking, [Priority] Critical, [Type] Bug

#5397 Update version to 1.7.0-dev.
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: [Status] Ready to Merge

#5363 Fix up menu item migrations in WC navigation
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Features/Marketing.php
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
  src/PageController.php
Labels: Navigation, [Status] Ready to Merge

#5388 Exclude TODO Comments from PHP Linter
  phpcs.xml.dist
Labels: Build, [Status] Ready to Merge

#5383 Fix navigation and WooCommerce menu ordering
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Features/Navigation/CoreMenu.php
  src/PageController.php
Labels: Navigation, [Status] Needs feedback

#5415 Added array casting to avoid PHP Warning
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Needs Review, [Type] Bug

#5416 Home Screen: Always show the inbox for temporary gutenberg plugin fix.
  client/homescreen/layout.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5409 Fix a number of crashes that occur in reports when Gutenberg is active
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/customers/table.js
  client/analytics/report/stock/table.js
  client/layout/controller.js
  packages/data/src/items/utils.js
Labels: Needs Cherry Picking, [Status] Needs feedback, [Type] Bug

#5405 Homescreen: Indicator labels i18n
  src/API/Reports/PerformanceIndicators/Controller.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#5411 Display messages for empty content and network request error
  client/marketing/components/knowledge-base/index.js
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/data/action-types.js
  client/marketing/data/actions.js
  client/marketing/data/index.js
  client/marketing/data/reducer.js
  client/marketing/data/resolvers.js
  client/marketing/data/selectors.js
Labels: Marketing, [Status] Needs Review

#5387 Add CES feature toggle
  config/core.json
  config/development.json
  config/plugin.json
  src/Loader.php
Labels: [Status] Needs feedback

#5419 Enqueue styles on non-WC pages
  client/navigation/stylesheets/index.scss
  packages/navigation/src/style.scss
  src/Features/Navigation/Navigation.php
Labels: Navigation, [Status] Ready to Merge

#5422 Exclude certain nav items from core migration
  src/Features/Navigation/CoreMenu.php
Labels: Navigation, [Status] Ready to Merge

#5407 Fix plugin page screen registration in navigation
  src/Features/Navigation/Screen.php
Labels: Navigation, [Status] Ready to Merge

#5403 Only show menu group if items exist
  client/navigation/components/container/index.js
Labels: Navigation, [Status] Ready to Merge

#5420 Migrate navigation store to data package
  client/navigation/components/container/index.js
  client/navigation/components/header/index.js
  client/navigation/index.js
  client/navigation/test/utils.js
  client/navigation/utils.js
  packages/data/src/index.js
  packages/data/src/navigation/action-types.js
  packages/data/src/navigation/actions.js
  packages/data/src/navigation/constants.js
  packages/data/src/navigation/index.js
  packages/data/src/navigation/reducer.js
  packages/data/src/navigation/selectors.js
  packages/data/src/navigation/test/reducer.js
  packages/data/src/navigation/with-navigation-hydration.js
  src/Features/Navigation/Menu.php
Labels: Navigation, [Status] Needs Review

#5381 Add features section and settings
  src/Features/Navigation/Navigation.php
  src/Loader.php
Labels: Navigation, [Status] Ready to Merge

#5413 Redirect instead of stalling on WCPay inbox note install action
  src/Notes/WooCommercePayments.php
Labels: [Status] Ready to Merge

#5445 Navigation: extend with WC Admin router links
  client/analytics/report/get-reports.js
  client/layout/controller.js
  client/layout/index.js
  client/layout/navigation.js
  client/navigation/components/Item/index.js
  client/navigation/index.js
  packages/navigation/src/index.js
  src/Features/Navigation/Navigation.php~HEAD
  src/Loader.php
Labels: Navigation, [Status] Ready to Merge

#5404 Update Notes deprecation versions.
  src/DeprecatedClassFacade.php
  src/Notes/DeprecatedNotes.php
Labels: [Status] Ready to Merge

#5423 Inbox Panel: Remove no longer used isPanelEmpty logic.
  client/inbox-panel/index.js
Labels: [Status] Ready to Merge

#5454 Allow full URLs to be used for nav items
  src/Features/Navigation/Menu.php
Labels: Navigation, [Status] Ready to Merge

#5456 Set WCA pages as top level in navigation if no parent exists
  src/PageController.php
Labels: Navigation, [Status] Ready to Merge

#5435 Show parent as default back button label
  client/navigation/components/container/index.js
  src/Features/Navigation/Menu.php
Labels: Navigation, [Status] Ready to Merge

#5457 Navigation: Include Animation Styles
  client/stylesheets/shared/_gutenberg-components.scss
Labels: Navigation, [Status] Ready to Merge

#5429 Add Homescreen layout control
  client/header/activity-panel/display-options/icons/display.js
  client/header/activity-panel/display-options/icons/single-column.js
  client/header/activity-panel/display-options/icons/two-columns.js
  client/header/activity-panel/display-options/index.js
  client/header/activity-panel/display-options/test/index.js
  client/header/activity-panel/index.js
  client/header/activity-panel/setup-progress.js
  client/header/activity-panel/style.scss
  client/header/activity-panel/tabs/index.js
  client/header/activity-panel/test/index.js
  client/homescreen/layout.js
  client/homescreen/style.scss
  client/homescreen/test/index.js
  client/stylesheets/shared/_reset.scss
  packages/data/src/user-preferences/use-user-preferences.js
  src/Features/AnalyticsDashboard.php
Labels: Activity Panel, Homescreen 2.0, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#5466 Navigation: Adding Tracks by tying into wc-admin page view
  client/layout/index.js
Labels: [Status] Needs feedback

#5453 Display a "read blog" message
  client/marketing/components/knowledge-base/ReadBlogMessage.js
  client/marketing/components/knowledge-base/index.js
  client/marketing/components/knowledge-base/test/index.js
  packages/components/src/empty-content/index.js
Labels: [Status] Ready to Merge

#5425 Add navigation plugin example
  docs/examples/extensions/add-navigation-items/js/index.js
  docs/examples/extensions/add-navigation-items/woocommerce-admin-add-navigation-items-example.php
Labels: Navigation, [Status] Ready to Merge

#5471 Redirect on WCPay inbox note install action on 1.6
  client/header/activity-panel/panels/inbox/index.js
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
Labels: [Status] Needs Review, wcpay

#5448 Fix missing custom autocompleter attribute in Search component of Advanced Filter
  packages/components/src/advanced-filters/search-filter.js
Labels: [Status] Ready to Merge

#5441 Fix downloads report
  src/API/Reports/Downloads/Controller.php
Labels: [Status] Ready to Merge

#5464 Add 1.6.x changelog entries
  readme.txt
Labels: [Status] Ready to Merge

#5462 Update dependencies in prep for Composer 2.x.
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  includes/wc-admin-update-functions.php
  src/API/Plugins.php
  src/DeprecatedClassFacade.php
  src/Events.php
  src/FeaturePlugin.php
  src/Features/Coupons.php
  src/Features/Onboarding.php
  src/Features/OnboardingAutomateTaxes.php
  src/Features/OnboardingSetUpShipping.php
  src/Install.php
  src/Notes/ChooseNiche.php
  src/Notes/ConfirmTaxSettings.php
  src/Notes/CouponPageMoved.php
  src/Notes/CustomizeStoreWithBlocks.php
  src/Notes/DeactivatePlugin.php
  src/Notes/DeprecatedNotes.php
  src/Notes/DrawAttention.php
  src/Notes/EUVATNumber.php
  src/Notes/EditProductsOnTheMove.php
  src/Notes/FirstProduct.php
  src/Notes/GivingFeedbackNotes.php
  src/Notes/GoogleAdsAndMarketing.php
  src/Notes/HistoricalData.php
  src/Notes/HomeScreenFeedback.php
  src/Notes/InsightFirstSale.php
  src/Notes/InstallJPAndWCSPlugins.php
  src/Notes/LaunchChecklist.php
  src/Notes/ManageOrdersOnTheGo.php
  src/Notes/MigrateFromShopify.php
  src/Notes/MobileApp.php
  src/Notes/NeedSomeInspiration.php
  src/Notes/NewSalesRecord.php
  src/Notes/OnboardingEmailMarketing.php
  src/Notes/OnboardingPayments.php
  src/Notes/OnboardingProfiler.php
  src/Notes/OnlineClothingStore.php
  src/Notes/OrderMilestones.php
  src/Notes/PerformanceOnMobile.php
  src/Notes/PersonalizeStore.php
  src/Notes/RealTimeOrderAlerts.php
  src/Notes/ReviewShippingSettings.php
  src/Notes/SellingOnlineCourses.php
  src/Notes/SetUpAdditionalPaymentTypes.php
  src/Notes/StartDropshippingBusiness.php
  src/Notes/TestCheckout.php
  src/Notes/TrackingOptIn.php
  src/Notes/WooCommercePayments.php
  src/Notes/WooCommerceSubscriptions.php
  src/Notes/WooSubscriptionsNotes.php
  src/Package.php
  tests/e2e/docker/initialize.sh
  tests/notes/class-wc-tests-marketing-notes.php
Labels: Build, [Status] Ready to Merge, [Type] Dev

#5474 Added Accordion component
  packages/components/src/accordion/README.md
  packages/components/src/accordion/index.js
  packages/components/src/accordion/panel.js
  packages/components/src/accordion/stories/index.js
  packages/components/src/accordion/style.scss
  packages/components/src/accordion/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
Labels: Homescreen 2.0, [Status] Needs Review

#5417 use consistent markdown headers in navigation readme
  packages/navigation/README.md
Labels: Documentation, [Status] Ready to Merge

#5504 Use the Puppeteer waitForSelector to fix flakyness in e2e tests.
  tests/e2e/specs/activate-and-setup/complete-benefits-section.js
  tests/e2e/specs/activate-and-setup/complete-business-section.js
  tests/e2e/specs/activate-and-setup/complete-store-details-section.js
  tests/e2e/specs/activate-and-setup/complete-theme-selection-section.js
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
  tests/e2e/specs/activate-and-setup/utils.js
  tests/e2e/utils/actions.js
  tests/e2e/utils/lib.js
Labels: Build, [Status] Needs feedback, [Status] Ready to Merge

#5491 Import @wordpress/base-styles/default-custom-properties to get --wp-admin-theme-color
  client/stylesheets/abstracts/_variables.scss
Labels: [Status] Needs Review

#5475 Add navigation feedback notes
  src/Events.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationFeedbackFollowUp.php
Labels: Navigation, [Status] Ready to Merge

#5324 Basic customer effort score survey functionality
  client/customer-effort-score-tracks/customer-effort-score-tracks-container.js
  client/customer-effort-score-tracks/customer-effort-score-tracks.js
  client/customer-effort-score-tracks/index.js
  client/index.js
  config/core.json
  config/development.json
  config/plugin.json
  package-lock.json
  package.json
  packages/customer-effort-score/.npmrc
  packages/customer-effort-score/CHANGELOG.md
  packages/customer-effort-score/README.md
  packages/customer-effort-score/package.json
  packages/customer-effort-score/src/index.js
  packages/customer-effort-score/src/style.scss
  packages/customer-effort-score/src/test/index.js
  src/Features/CustomerEffortScoreTracks.php
  src/Loader.php
  webpack.config.js
Labels: [Status] Ready to Merge

#5495 Prevent double fill of Customers nav slot
  client/analytics/report/get-reports.js
Labels: Navigation, [Status] Ready to Merge

#5510 Fixing features contained in subdirectories are not loaded when using Composer v2
  src/Features/Navigation/Init.php
  src/Loader.php
Labels: Navigation, [Status] Ready to Merge

#5489 Update navigation width to match designs
  client/navigation/stylesheets/_variables.scss
Labels: Navigation, [Status] Ready to Merge
