Repository woocommerce/woocommerce-admin, pull requests merged in 2020-04, with the labels that each got.

#4017 Add caching to performance indicators.
  client/dashboard/store-performance/index.js
  src/API/Reports/CacheableTraits.php
  src/API/Reports/DataStore.php
  src/API/Reports/PerformanceIndicators/Controller.php
Labels: REST API, [Status] Ready to Merge, [Type] Performance, cooldown period

#4034 Fix aria-label attribute.
  client/dashboard/profile-wizard/steps/benefits/logo.js
Labels: Accessibility, Onboarding, [Status] Ready to Merge, [Type] Fix

#4035 Update default dashboard view.
  client/dashboard/default-sections.js
Labels: Dashboard, [Status] Ready to Merge, [Type] Tweak, cooldown period

#3974 Onboarding: Remove plugins step from profiler
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/benefits/index.js
  client/dashboard/profile-wizard/steps/plugins.js
Labels: Onboarding, [Status] Ready to Merge

#4026 Update WooCommerce Payments Dev Mode doc link
  client/dashboard/task-list/tasks/payments/methods.js
Labels: [Status] Ready to Merge

#4036 Update marketing hub recommended plugins API url.
  src/Features/Marketing.php
Labels: Marketing, [Status] Needs Review

#4033 SQL example: update to dynamic currencies
  docs/examples/extensions/sql-modification/js/index.js
Labels: [Status] Ready to Merge

#4037 Support IE11 in `wc-admin`
  client/wp-admin-scripts/onboarding-menu-experience/index.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge, [Type] Bug

#4042 Cast to float, to avoid performing arithmetic with strings
  src/Overrides/OrderTraits.php
Labels: [Status] Ready to Merge

#4027 Dynamic Currency with Context API
  client/analytics/components/leaderboard/test/index.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/report/categories/table.js
  client/analytics/report/coupons/table.js
  client/analytics/report/customers/table.js
  client/analytics/report/downloads/table.js
  client/analytics/report/index.js
  client/analytics/report/orders/table.js
  client/analytics/report/orders/utils.js
  client/analytics/report/products/table-variations.js
  client/analytics/report/products/table.js
  client/analytics/report/revenue/table.js
  client/analytics/report/stock/table.js
  client/analytics/report/taxes/table.js
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/steps/store-details.js
  client/dashboard/store-performance/index.js
  client/dashboard/task-list/tasks/shipping/rates.js
  client/header/activity-panel/panels/orders.js
  client/lib/currency-context.js
  client/lib/currency-format.js
  client/lib/number-format.js
  client/wc-api/reports/utils.js
  docs/examples/extensions/sql-modification/js/index.js
  packages/currency/CHANGELOG.md
  packages/currency/src/index.js
  packages/number/src/index.js
Labels: Packages, [Status] Needs Review

#4051 Fix RTL issues with `wc-admin` pages
  client/layout/store-alerts/style.scss
  packages/components/src/chart/d3chart/legend.scss
  packages/components/src/summary/style.scss
Labels: Components, Packages, [Status] Needs Review, [Type] Bug

#4066 Replace welcome image on marketing tab with svg. closes #4057
  client/marketing/overview/welcome-card/images/welcome.png
  client/marketing/overview/welcome-card/images/welcome.svg
  client/marketing/overview/welcome-card/index.js
Labels: [Status] Ready to Merge

#4070 OBW: fix use of unbound this in business details step.
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#4068 Update Jetpack Autoloader.
  composer.json
  composer.lock
Labels: Build, Needs Cherry Picking, [Status] Ready to Merge

#4065 Fix double prefixed wcadmin events
  client/dashboard/task-list/index.js
  src/Features/Onboarding.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4071 Setup Checklist: Fix exception in shipping.
  client/dashboard/task-list/tasks/shipping/rates.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#3994 remove use of undefined QUEUE_GROUP
  includes/wc-admin-update-functions.php
  src/Install.php
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4030 Marketing inbox note
  includes/wc-admin-update-functions.php
  src/Events.php
  src/FeaturePlugin.php
  src/Features/OnboardingTasks.php
  src/Install.php
  src/Notes/WC_Admin_Notes_Facebook_Extension.php
  src/Notes/WC_Admin_Notes_Marketing.php
  src/Notes/WC_Admin_Notes_Onboarding.php
Labels: Marketing, [Status] Ready to Merge

#4072 Enable the default homepage template to be filtered
  src/API/OnboardingTasks.php
  tests/api/onboarding-tasks.php
Labels: [Status] Ready to Merge

#4085 Setup Checklist: Remove Setup Menu Item and I'll Do This Later link
  client/dashboard/customizable.js
  client/dashboard/task-list/index.js
  client/wp-admin-scripts/onboarding-menu-experience/index.js
  src/Features/OnboardingTasks.php
  webpack.config.js
Labels: Build, Needs Cherry Picking, [Status] Ready to Merge

#4060 Add missing prompts to installed extensions
  images/marketing/amazon-ebay.svg
  images/marketing/automatewoo.svg
  images/marketing/google.svg
  images/marketing/hubspot.svg
  src/Marketing/InstalledExtensions.php
Labels: Marketing, Needs Cherry Picking, [Status] Ready to Merge

#4046 Enable wcpay feature flag in plugin and core
  config/core.json
  config/plugin.json
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4061 Bugfix on payments step in CBD flow
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/methods.js
  client/dashboard/task-list/tasks/payments/square.js
  src/API/OnboardingPlugins.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4105 Added check to show WC Pay option only when Jetpack is connected
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/methods.js
Labels: Needs Cherry Picking, [Status] Needs Review

#4090 Handle orphaned order statuses in analytics settings.
  client/analytics/settings/config.js
  src/API/Reports/Orders/DataStore.php
  src/Loader.php
Labels: Analytics, Settings, [Status] Ready to Merge, [Type] Fix, cooldown period

#4108 Overwrite button overflow css from Wordpress 5.4 defaults
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
Labels: Needs Cherry Picking, [Status] Ready to Merge, [Type] Fix

#4115 Fix usage of WP_Error in non-global namespaces.
  src/API/OnboardingPlugins.php
  src/API/Reports/Orders/Stats/DataStore.php
Labels: Needs Cherry Picking, REST API, [Status] Ready to Merge, [Type] Bug

#4111 Onboarding - business details step: increase max-height on competitors listbox
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/style.scss
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge

#4117 OBW: allow CBD only for US stores
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Needs Cherry Picking, Onboarding, [Status] Ready to Merge

#4120 Store details: check if industries exist before trimming
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4133 Fix confusing UX when knowledge base card fails to retreive posts
  client/marketing/overview/knowledge-base/index.js
  src/Features/Marketing.php
Labels: Marketing, Needs Cherry Picking, [Status] Ready to Merge, [Type] Bug

#4130 Add PHP unit test instructions to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: [Status] Ready to Merge

#4063 Improve layout of Installed Extensions marketing card for tablet and mobile screens
  client/marketing/overview/installed-extensions/row.js
  client/marketing/overview/installed-extensions/style.scss
  client/marketing/overview/welcome-card/style.scss
  src/Marketing/InstalledExtensions.php
Labels: Marketing, Needs Cherry Picking

#4093 Plugins: Move API out of Onboarding
  client/dashboard/task-list/tasks/connect.js
  client/dashboard/task-list/tasks/payments/paypal.js
  client/dashboard/task-list/tasks/payments/square.js
  client/dashboard/task-list/tasks/payments/wcpay.js
  docs/features/onboarding.md
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/resolvers.js
  src/API/Init.php
  src/API/Plugins.php
  src/Features/Onboarding.php
  src/Loader.php
  src/Notes/WC_Admin_Notes_WooCommerce_Payments.php
  tests/api/onboarding-profile.php
  tests/api/plugins.php
Labels: Components, Packages, [Status] Ready to Merge

#4149 OBW: respect Store Location async
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/steps/location.js
  client/dashboard/task-list/tasks/tax.js
Labels: Needs Cherry Picking

#4141 Add profiler step view tracks
  client/dashboard/profile-wizard/index.js
  client/dashboard/profile-wizard/steps/benefits/index.js
Labels: Onboarding, [Status] Ready to Merge

#4148 OBW: "activated" success message upon continuing with existing theme
  client/dashboard/profile-wizard/steps/theme/index.js
Labels: [Status] Ready to Merge

#4158 Release 1.1.0 Prep
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3977 Reduce queries in Inbox Panel.
  client/header/activity-panel/panels/inbox/index.js
  src/Notes/WC_Admin_Note.php
Labels: Activity Panel, REST API, [Status] Ready to Merge, [Type] Performance, cooldown period

#4169 Homepage: Add Hello World, routing, and feature flag
  client/homepage/index.js
  client/layout/controller.js
  config/core.json
  config/development.json
  config/plugin.json
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Loader.php
Labels: Home Screen, [Status] Ready to Merge

#4167 Changed email marketing note and the old filter was removed
  src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php
Labels: Inbox, [Status] Ready to Merge

#4180 Remove A/B testing from order page shipping prompt.
  src/Features/ShippingLabelBannerDisplayRules.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4166 Reset profiler when visiting old obw URL
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#4164 Remove auto connect functionality from Stripe payment task
  client/dashboard/task-list/tasks/payments/stripe.js
Labels: Onboarding

#4184 Change "Demo" to "Sample" products
  client/dashboard/profile-wizard/steps/usage-modal.js
  client/dashboard/task-list/tasks/appearance.js
Labels: [Status] Ready to Merge

#4194 Hide Marketing Tab Recomended Extensions card if marketing suggestions are disabled
  client/marketing/overview/index.js
  src/Loader.php
Labels: Marketing, Needs Cherry Picking

#3202 POC store navigation
  client/index.js
  client/navigation/index.js
  client/navigation/style.scss
  config/core.json
  config/development.json
  config/plugin.json
  src/FeaturePlugin.php
  src/Features/Navigation.php
  src/Loader.php
  src/PageController.php
Labels: Dashboard, [Status] Needs Review, [Type] Dev, cooldown period

#4189 New home screen pageview tracking
  client/dashboard/customizable.js
  client/dashboard/index.js
  client/layout/index.js
Labels: Home Screen, [Status] Ready to Merge, [Type] Task

#4215 Fix OBW when new home screen is enabled.
  client/dashboard/index.js
  client/homepage/index.js
  client/profile-wizard/header.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/images/management.js
  client/profile-wizard/steps/benefits/images/sales_tax.js
  client/profile-wizard/steps/benefits/images/shipping_labels.js
  client/profile-wizard/steps/benefits/images/speed.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/benefits/logo.js
  client/profile-wizard/steps/business-details.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types.js
  client/profile-wizard/steps/store-details.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/steps/theme/preview.js
  client/profile-wizard/steps/theme/style.scss
  client/profile-wizard/steps/theme/uploader.js
  client/profile-wizard/steps/usage-modal.js
  client/profile-wizard/style.scss
Labels: Dashboard, Home Screen, Onboarding, [Status] Ready to Merge, [Type] Bug

#4221 Add React Testing Library
  client/homepage/test/index.js
  package-lock.json
  package.json
Labels: Build, Home Screen, [Status] Ready to Merge, [Tests] Includes Tests

#4233 Add WCS to allowed plugins list for order page prompt.
  src/Features/ShippingLabelBanner.php
Labels: Needs Cherry Picking, [Status] Ready to Merge

#4230 Make button hover color match WCS modal button hover color.
  client/wp-admin-scripts/print-shipping-label-banner/style.scss
Labels: Needs Cherry Picking, [Status] Needs Review

#4187 Fix sorting to push Storefront to the top of the theme list
  src/Features/Onboarding.php
  tests/features/class-wc-tests-onboarding.php
Labels: Needs Cherry Picking, Onboarding, [Status] Needs Review

#4219 Add List and Link components to Storybook
  packages/components/src/link/stories/index.js
  packages/components/src/list/stories/index.js
  packages/components/src/list/stories/style.scss
  storybook/webpack.config.js
Labels: Build, Components, Design, Packages, [Status] Ready to Merge

#4094 Use Route based code splitting to optimize bundle size
  client/analytics/report/get-reports.js
  client/analytics/report/index.js
  client/dashboard/customizable.js
  client/dashboard/default-sections.js
  client/dashboard/index.js
  client/dashboard/style.scss
  client/header/activity-panel/index.js
  client/homepage/index.js
  client/index.js
  client/layout/controller.js
  client/layout/index.js
  client/layout/style.scss
  client/profile-wizard/index.js
  package-lock.json
  package.json
  src/Features/OnboardingTasks.php
  src/Features/ShippingLabelBanner.php
  src/Loader.php
  unminify.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge, cooldown period

#4242 Update version to 1.1.1 and adjust changelog
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#4238 Use PAGE_ROOT constant to reduce redundancy
  src/PageController.php
Labels: [Status] Needs Review
