Repository woocommerce/woocommerce-admin, pull requests merged in 2020-01, with the labels that each got.

#3495 Onboarding: Redirect the user to the task list if referer is wccom checkout
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3493 Onboarding: Add tracks to extension purchase task and modal
  client/dashboard/components/cart-modal.js
  client/dashboard/task-list/index.js
Labels: Onboarding, [Status] Ready to Merge

#3285 Reports sync refactor
  CONTRIBUTING.md
  client/analytics/settings/historical-data/layout.js
  client/analytics/settings/historical-data/status.js
  src/API/Reports/Import/Controller.php
  src/ReportExporter.php
  src/ReportsSync.php
  src/Schedulers/CustomersScheduler.php
  src/Schedulers/ImportScheduler.php
  src/Schedulers/OrdersScheduler.php
  src/Schedulers/SchedulerTraits.php
  tests/api-init.php
  tests/api/reports-import.php
  tests/batch-queue.php
  tests/queue-priority.php
Labels: [Status] Ready to Merge, [Tests] Includes Tests, [Type] Dev

#3512 CI: use PR repo instead of main repo when checking out branches.
  bin/install-wp-tests.sh
Labels: Build, [Status] Ready to Merge, [Type] Bug

#3510 Included RegExp for JS files in examples.config.js
  docs/examples/extensions/examples.config.js
Labels: Build, Extensibility, [Type] Dev, [Type] Fix

#3514 Analytics: Change Refunds to Returns
  client/dashboard/dashboard-charts/config.js
  src/API/Reports/Revenue/Stats/Controller.php
Labels: [Status] Ready to Merge, [Type] Tweak

#3507 Add SelectControl debouncing and keyboard fixes
  packages/components/src/search/index.js
  packages/components/src/select-control/control.js
  packages/components/src/select-control/index.js
  packages/components/src/select-control/list.js
Labels: Components, Packages, [Status] Ready to Merge, [Type] Bug

#3517 Add singular/plural distinction to onboarding plugins installation
  client/dashboard/profile-wizard/steps/business-details.js
Labels: Onboarding, [Status] Ready to Merge

#3508 Update task list success notices
  client/dashboard/task-list/tasks/appearance.js
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/shipping/index.js
  client/dashboard/task-list/tasks/tax.js
  client/wp-admin-scripts/onboarding-product-notice/index.js
Labels: Onboarding, [Status] Needs Review

#3506 Add initial documentation for the historical data import.
  docs/woocommerce.com/analytics-historical-data-import.md
  docs/woocommerce.com/images/analytics-historical-data-import-complete.png
  docs/woocommerce.com/images/analytics-historical-data-import-in-progress.png
  docs/woocommerce.com/images/analytics-historical-data-import-notice.png
  docs/woocommerce.com/images/analytics-historical-data-import-ready-to-import.png
Labels: Documentation, [Status] Ready to Merge

#3513 Onboarding: Fix exception when task list is not shown.
  client/dashboard/utils.js
Labels: [Status] Ready to Merge, [Type] Fix

#3516 Update date format for import status
  client/analytics/settings/historical-data/status.js
Labels: [Status] Needs Review, [Type] Fix

#3520 Release 0.24.0
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge, [Type] Task

#3504 Sync refactor tweaks
  src/Schedulers/ImportScheduler.php
  src/Schedulers/SchedulerTraits.php
Labels: Analytics, [Status] Ready to Merge, [Type] Tweak

#3525 Add initial Activity Panel documentation.
  client/header/activity-panel/panels/orders.js
  docs/woocommerce.com/activity-panels.md
  docs/woocommerce.com/images/activity-panels-inbox.png
  docs/woocommerce.com/images/activity-panels-mobile-view.png
  docs/woocommerce.com/images/activity-panels-orders-empty.png
  docs/woocommerce.com/images/activity-panels-orders-settings.png
  docs/woocommerce.com/images/activity-panels-orders.png
  docs/woocommerce.com/images/activity-panels-reviews-empty.png
  docs/woocommerce.com/images/activity-panels-reviews-settings.png
  docs/woocommerce.com/images/activity-panels-reviews.png
  docs/woocommerce.com/images/activity-panels-stock-empty.png
  docs/woocommerce.com/images/activity-panels-stock-settings.png
  docs/woocommerce.com/images/activity-panels-stock-update.png
  docs/woocommerce.com/images/activity-panels-stock.png
  docs/woocommerce.com/images/activity-panels-tabs.png
  docs/woocommerce.com/images/activity-panels-wp-notices.png
Labels: Activity Panel, Documentation, [Status] Needs Review

#3503 Onboarding: Add option to track appearance completion
  client/dashboard/task-list/tasks.js
  client/dashboard/task-list/tasks/appearance.js
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge

#3535 Update broken note action hooks
  src/API/NoteActions.php
  src/API/Notes.php
  src/Notes/WC_Admin_Notes_Facebook_Extension.php
  src/Notes/WC_Admin_Notes_Tracking_Opt_In.php
Labels: Activity Panel, Inbox, [Status] Ready to Merge, [Type] Fix

#3538 Onboarding: Set minimum height on muriel text inputs
  packages/components/src/text-control/style.scss
Labels: Components, Onboarding, Packages, [Status] Ready to Merge, [Type] Fix

#3539 Update historical data notice to actioned on import
  client/analytics/settings/historical-data/index.js
  src/Notes/WC_Admin_Notes_Historical_Data.php
  src/ReportsSync.php
Labels: Inbox, [Status] Ready to Merge, [Type] Fix

#3511 add privacy erasure via woocommerce hook
  src/Schedulers/CustomersScheduler.php
Labels: Analytics, [Status] Ready to Merge, [Type] Enhancement

#3526 add analytics settings docs
  docs/woocommerce.com/analytics-settings.md
  docs/woocommerce.com/images/settings-default-date-range.png
  docs/woocommerce.com/images/settings-excluded-statuses.png
Labels: Documentation, [Status] Ready to Merge

#3524 Onboarding: Add reminder to complete profiler
  client/dashboard/profile-wizard/index.js
  src/Features/Onboarding.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
Labels: Onboarding, [Status] Ready to Merge

#3545 Onboarding: Only Show Retry Button on Plugin install failure
  client/dashboard/profile-wizard/steps/plugins.js
Labels: [Status] Ready to Merge

#3547 Fix mobile table header styling
  client/analytics/components/report-table/style.scss
  packages/components/src/search/style.scss
Labels: Components, Packages, [Status] Needs Review, [Type] Bug

#3540 Onboarding: Don't exclude selected option from options list in countrystate dropdown
  client/dashboard/components/settings/general/store-address.js
Labels: Onboarding, [Status] Ready to Merge

#3542 remove languages/woocommerce-admin.php from deploy
  bin/github-deploy.sh
Labels: Build, [Status] Ready to Merge

#3349 Handle custom currency formats
  packages/components/src/chart/d3chart/utils/tooltip.js
  packages/currency/src/index.js
Labels: Components, Packages, [Status] Ready to Merge

#3548 Onboarding: Update profiler theme action buttons
  client/dashboard/profile-wizard/steps/theme/index.js
  client/dashboard/profile-wizard/steps/theme/style.scss
Labels: Onboarding, [Status] Ready to Merge

#3550 Updating unread stock indicator on stock update
  client/header/activity-panel/unread-indicators.js
  client/wc-api/items/operations.js
Labels: [Status] Ready to Merge, [Type] Fix

#3551 SelectControl: Add an option to show all options on refocus
  client/dashboard/components/settings/general/store-address.js
  packages/components/src/select-control/control.js
  packages/components/src/select-control/docs/example.js
  packages/components/src/select-control/index.js
Labels: Components, Packages, [Status] Ready to Merge

#3555 Make package-based load inert when plugin is active.
  src/Package.php
Labels: On Merge to WC Core, [Status] Ready to Merge, [Type] Fix

#3515 Added @woocommerce/wc-admin-settings as alias in examples.config.js
  docs/examples/extensions/examples.config.js
Labels: Build

#3556 Update README Files
  README.md
  docs/README.md
Labels: [Status] Ready to Merge

#3521 fix SQL error in category sort
  src/API/Reports/Categories/DataStore.php
  tests/api/reports-categories.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3571 Update PHPUnit to version 7
  .travis.yml
  bin/phpunit.sh
  bin/travis.sh
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: Build, [Status] Ready to Merge, [Type] Dev

#3580 Avoid redundant/unnecessary cleanup.
  src/FeaturePlugin.php
  src/Install.php
  src/Package.php
Labels: On Merge to WC Core, [Status] Ready to Merge, [Type] Task

#3546 Revamp uninstallation when WooCommerce Admin is in core.
  src/API/OnboardingProfile.php
  src/API/OnboardingTasks.php
  src/Features/Onboarding.php
  src/Install.php
  src/Loader.php
  src/Notes/NoteTraits.php
  src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
  src/Notes/WC_Admin_Notes_Order_Milestones.php
  src/Notes/WC_Admin_Notes_Woo_Subscriptions_Notes.php
  src/ReportExporter.php
  src/ReportsSync.php
  src/Schedulers/ImportScheduler.php
  uninstall.php
Labels: On Merge to WC Core, [Status] Ready to Merge, [Type] Bug

#3573 Re-add stockStatuses to wcSettings
  src/Loader.php
Labels: [Status] Ready to Merge

#3582 Ignore vendor directory for stylelint
  .stylelintrc.json
Labels: Build, [Status] Ready to Merge

#3584 Remove defunct hook removals.
  src/FeaturePlugin.php
Labels: [Status] Ready to Merge, [Type] Dev, [Type] Fix

#3583 fix strict standards in Scheduler classes
  src/Schedulers/ImportInterface.php
  src/Schedulers/ImportScheduler.php
  src/Schedulers/SchedulerTraits.php
Labels: [Status] Ready to Merge, [Type] Dev

#3585 Don't modify the document title on existing WooCommerce pages.
  client/header/index.js
  src/Loader.php
Labels: On Merge to WC Core, [Status] Ready to Merge, [Type] Tweak

#3586 Dashboard: fix usermeta prefix
  src/Loader.php
Labels: Dashboard, [Status] Ready to Merge

#3593 Onboarding: Redirect old onboarding wizard to profiler when active
  src/Features/Onboarding.php
Labels: On Merge to WC Core, Onboarding, [Status] Ready to Merge

#3594 Onboarding: Fix gap on plugins step
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3595 Onboarding: Use existing store country if address line 1 is set
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3598 Remove unnecessary use of lodash get
  client/dashboard/profile-wizard/steps/store-details.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Performance

#3589 Onboarding: Allow Jetpack connection to be skipped in tax task
  client/dashboard/task-list/tasks/steps/connect.js
  client/dashboard/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3603 Fix styling of search control in report table header and filters.
  client/analytics/components/report-table/style.scss
  packages/components/src/advanced-filters/style.scss
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Type] Fix

#3552 add PHP 7.3 to Travis unit tests
  .travis.yml
  bin/phpunit.sh
  bin/travis.sh
  composer.json
  composer.lock
Labels: Build, [Status] Ready to Merge

#3616 Update PHP 5.6 in Travis test matrix to WC 3.8.1
  .travis.yml
  bin/install-wp-tests.sh
Labels: Build, [Status] Ready to Merge

#3588 Onboarding: Center button to continue without installation
  client/dashboard/profile-wizard/steps/business-details.js
  client/dashboard/profile-wizard/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3618 Fix Search component token display in ReportTable
  client/analytics/components/report-table/index.js
  packages/components/CHANGELOG.md
  packages/components/src/select-control/style.scss
  packages/components/src/select-control/tags.js
Labels: Analytics, Components, Packages, [Status] Ready to Merge, [Type] Bug

#3622 Onboarding: Vertically align button text
  client/dashboard/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3612 Onboarding: Add missing space between manual tax info and link
  client/dashboard/task-list/tasks/tax.js
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3620 Onboarding: Allow any uploaded theme to be activated
  client/dashboard/profile-wizard/steps/theme/index.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3621 Onboarding: Hide other elements in wpcontent while in full screen mode
  client/layout/style.scss
Labels: Onboarding, [Status] Ready to Merge, [Type] Fix

#3623 Onboarding: Fix shipping rates overlapping currency prefix
  client/dashboard/task-list/style.scss
  client/dashboard/task-list/tasks/shipping/rates.js
  packages/components/CHANGELOG.md
  packages/components/src/text-control-with-affixes/index.js
Labels: Components, Onboarding, Packages, [Status] Ready to Merge, [Type] Fix

#3576 Onboarding: Mark payments task complete when payment configured
  client/dashboard/task-list/tasks/payments/index.js
  src/Features/OnboardingTasks.php
Labels: Onboarding, [Status] Needs Review, [Type] Fix

#3590 Onboarding: Mark profiler complete on WC update
  src/Features/Onboarding.php
  src/Loader.php
Labels: On Merge to WC Core, Onboarding, [Status] Ready to Merge, [Type] Fix

#3651 Fix for onboarding in 25.0
  src/Loader.php
Labels: Onboarding, [Status] Ready to Merge
