Repository woocommerce/woocommerce-admin, pull requests merged in 2020-02, with the labels that each got.

#3667 Match Woo Core JP Autoloader version
  composer.json
  composer.lock
Labels: Build, [Status] Needs Review

#3641 tag version 0.25
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Needs Review, [Type] Task

#3656 cast tax amount to float
  src/API/Reports/Products/DataStore.php
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3653 Decode breadcrumb correctly
  client/header/index.js
  client/header/test/index.js
Labels: Activity Panel, [Status] Ready to Merge

#3680 Enable onboarding in production.
  config/core.json
Labels: [Status] Needs Review

#3681 tag version 0.25.1
  package-lock.json
  package.json
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3686 Initial documentation of the Customers Report.
  docs/woocommerce.com/analytics-customers-report.md
  docs/woocommerce.com/images/analytics-customers-report-advanced-filters.png
  docs/woocommerce.com/images/analytics-customers-report-name-filter.png
  docs/woocommerce.com/images/analytics-customers-report-single-customer.png
  docs/woocommerce.com/images/analytics-customers-report-table-search-partial-string.png
  docs/woocommerce.com/images/analytics-customers-report-table-search.png
  docs/woocommerce.com/images/analytics-customers-report.png
Labels: Documentation, [Status] Ready to Merge, cooldown period

#3706 Update form example to better format the form return data
  packages/components/src/form/docs/example.js
Labels: Components, Packages, [Status] Ready to Merge

#3632 Try: Moving Customers to main Woo Menu
  client/analytics/report/index.js
  client/layout/controller.js
  src/Features/Analytics.php
Labels: [Status] Ready to Merge

#3712 Added link to "go shopping" button
  src/API/OnboardingTasks.php
Labels: Onboarding, [Status] Needs Review

#3684 Documentation: Analytics basics doc
  docs/woocommerce.com/analytics-basics.md
  docs/woocommerce.com/images/analytics-basics-advanced-filters.png
  docs/woocommerce.com/images/analytics-basics-charts.png
  docs/woocommerce.com/images/analytics-basics-date-range-picker.png
  docs/woocommerce.com/images/analytics-basics-download-email.png
  docs/woocommerce.com/images/analytics-basics-summary-number.png
  docs/woocommerce.com/images/analytics-basics-summary-numbers-chart.png
  docs/woocommerce.com/images/analytics-basics-table-column-sort.png
  docs/woocommerce.com/images/analytics-basics-table-footer.png
  docs/woocommerce.com/images/analytics-basics-table.png
  docs/woocommerce.com/images/analytics-date-range-picker-custom.png
  docs/woocommerce.com/images/analytics-date-range-picker-presets.png
  docs/woocommerce.com/images/analytics-table-column-visbility.png
  docs/woocommerce.com/images/analytics-table-download-button.png
Labels: Documentation, [Status] Ready to Merge

#3491 Documentation: Add Dashboard Documentation.
  docs/woocommerce.com/analytics-dashboard.md
Labels: Documentation, [Status] Ready to Merge

#3724 Coding Standards: Fix getReportItems function call order
  client/wc-api/reports/utils.js
Labels: [Status] Needs Review

#3715 Make analytics tables use the site's date format setting
  client/analytics/report/coupons/table.js
  client/analytics/report/customers/table.js
  client/analytics/report/downloads/table.js
  client/analytics/report/orders/table.js
  client/analytics/report/revenue/table.js
  src/Loader.php
Labels: Analytics, [Status] Ready to Merge

#3722 Only add onboarding settings on wc-admin pages when task list should …
  src/Features/OnboardingTasks.php
Labels: [Status] Needs Review, [Type] Performance

#3662 Use cron for unsnoozing admin notes
  includes/wc-admin-update-functions.php
  src/Install.php
  src/Notes/WC_Admin_Notes.php
Labels: [Status] Ready to Merge, [Type] Tweak

#3645 Onboarding: Fix toggle tracking events
  src/Features/Onboarding.php
Labels: Build, Onboarding, [Status] Ready to Merge, [Type] Fix

#3726 Onboarding: Add tracks events when profiler steps are completed
  client/dashboard/profile-wizard/index.js
Labels: Onboarding, [Status] Ready to Merge

#3685 add wccom docs for coupons report
  docs/woocommerce.com/analytics-coupons-report.md
  docs/woocommerce.com/images/analytics-coupons-report-coupon-compare.png
  docs/woocommerce.com/images/analytics-coupons-report-coupon-filter.png
  docs/woocommerce.com/images/analytics-coupons-report-coupon-single.png
  readme.txt
Labels: Activity Panel, Documentation, [Status] Ready to Merge

#3646 Ensure continue setup loads the onboarding profiler
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3700 'All that include' option removed when input field is empty
  packages/components/src/select-control/list.js
  packages/components/src/select-control/test/index.js
Labels: Components, Packages, [Status] Ready to Merge

#3723 Fix/select text alignment
  client/stylesheets/shared/_global.scss
Labels: Analytics, [Status] Ready to Merge, [Type] Bug

#3729 Stock panel indicator - cache and use lookup tables.
  client/header/activity-panel/index.js
  client/header/activity-panel/unread-indicators.js
  src/Features/ActivityPanels.php
Labels: [Status] Needs Review, [Type] Performance

#3731 Checklist: Remove sideloaded images to reduce build size, take 2
  images/onboarding/art-music-photography.jpg
  images/onboarding/electronics-computers.jpg
  images/onboarding/fashion-apparel-accessories.jpg
  images/onboarding/food-drink.jpg
  images/onboarding/health-beauty.jpg
  images/onboarding/home-furniture-garden.jpg
  images/onboarding/other-small.jpg
  images/onboarding/other.jpg
  src/API/OnboardingTasks.php
Labels: [4.0] Merge, [Status] Needs Design Review, [Status] Ready to Merge

#3740 Merge Version/1.0 to master
  client/analytics/report/index.js
  client/dashboard/profile-wizard/index.js
  client/layout/controller.js
  includes/wc-admin-update-functions.php
  packages/components/src/select-control/list.js
  packages/components/src/select-control/test/index.js
  src/Features/Analytics.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Install.php
  src/Notes/WC_Admin_Notes.php
  src/Notes/WC_Admin_Notes_Onboarding_Profiler.php
Labels: Components, Packages, [Status] Ready to Merge, [Type] Dev

#3730 Fix/3631
  client/dashboard/profile-wizard/steps/industry.js
  client/dashboard/profile-wizard/style.scss
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Ready to Merge

#3721 Add documentation for Products Report.
  docs/woocommerce.com/analytics-products-report.md
  docs/woocommerce.com/images/analytics-products-report-comparison-search.png
  docs/woocommerce.com/images/analytics-products-report-comparison.png
  docs/woocommerce.com/images/analytics-products-report-single-product-search.png
  docs/woocommerce.com/images/analytics-products-report-single-product.png
  docs/woocommerce.com/images/analytics-products-report-table-search-results.png
  docs/woocommerce.com/images/analytics-products-report-table-search.png
  docs/woocommerce.com/images/analytics-products-report.png
Labels: Documentation, [Status] Ready to Merge, cooldown period

#3727 Onboarding: Create homepage without redirect
  client/dashboard/task-list/tasks/appearance.js
  client/wp-admin-scripts/onboarding-homepage-notice/index.js
  src/API/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge

#3687 Add deactivation note for feature plugin
  src/Notes/WC_Admin_Notes_Deactivate_Plugin.php
  src/Package.php
Labels: [4.0] Merge, [Status] Needs Review

#3751 Add Travis tests on GH for release branch
  .travis.yml
  client/dashboard/task-list/tasks/appearance.js
  client/header/activity-panel/index.js
  src/Features/ActivityPanels.php
Labels: Build

#3755 Remove free text Search option when no query exists
  packages/components/src/search/index.js
  packages/components/src/search/test/index.js
  packages/components/src/select-control/list.js
  packages/components/src/select-control/test/index.js
Labels: Components, Packages, [Status] Ready to Merge, [Tests] Includes Tests

#3743 Fix image sideloading for store industries.
  src/API/OnboardingTasks.php
Labels: Onboarding, [Status] Ready to Merge, [Type] Bug

#3757 StoreAlert: Fix typo in API description
  src/API/Notes.php
Labels: [Status] Ready to Merge, [Type] Tweak

#3762 [0.26.0] OBW: fix sideloading image test error
  src/API/OnboardingTasks.php
Labels: [Status] Needs Review

#3679 Add Storybook for documenting and testing components in isolation
  .gitignore
  package-lock.json
  package.json
  packages/components/src/rating/stories/index.js
  storybook/main.js
  storybook/preview.js
  storybook/style.scss
  storybook/webpack.config.js
Labels: Build, Components, Packages, [Status] Needs Review

#3738 Add PayFast payment gateway option for sites in South Africa
  client/dashboard/task-list/tasks/payments/index.js
  client/dashboard/task-list/tasks/payments/payfast.js
  src/Features/Onboarding.php
Labels: Onboarding, [Status] Needs feedback

#3753 Release 0.26.0 changes
  package-lock.json
  package.json
  readme.txt
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Ready to Merge

#3675 Settings Refactor: Handle mutable settings with store only
  client/analytics/components/leaderboard/index.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-filters/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/downloads/table.js
  client/analytics/report/revenue/table.js
  client/analytics/settings/README.md
  client/analytics/settings/config.js
  client/analytics/settings/default-date.js
  client/analytics/settings/index.js
  client/dashboard/customizable.js
  client/dashboard/store-performance/index.js
  client/dashboard/style.scss
  client/header/activity-panel/panels/orders.js
  client/header/activity-panel/unread-indicators.js
  client/lib/date.js
  client/settings/fallbacks.js
  client/settings/index.js
  client/wc-api/items/utils.js
  client/wc-api/reports/utils.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#3763 Fix/coding standards violations
  client/header/activity-panel/panels/orders.js
  client/wc-api/items/utils.js
  client/wc-api/reports/utils.js
Labels: [Status] Ready to Merge

#3749 Initial revenue report user documentation
  docs/woocommerce.com/analytics-revenue-report.md
  docs/woocommerce.com/images/analytics-revenue-report.png
Labels: Documentation, [4.0] Merge, [Status] Ready to Merge

#3744 initial stock report user documentation
  docs/woocommerce.com/analytics-stock-report.md
  docs/woocommerce.com/images/analytics-stock-report.png
  docs/woocommerce.com/images/analytics-stock-single-status.png
  docs/woocommerce.com/images/analytics-stock-status-filter.png
Labels: Documentation, [Status] Ready to Merge

#3770 add deactivation hook to Package.php
  src/Package.php
Labels: On Merge to WC Core, [Priority] High, [Status] Ready to Merge

#3772 Add active version functions
  src/Package.php
Labels: On Merge to WC Core, [Status] Needs Review

#3773 0.26.1 changes
  package-lock.json
  package.json
  src/FeaturePlugin.php
  src/Package.php
  woocommerce-admin.php
Labels: Build, [Status] Needs Review

#3778 Customers Report: fix missing report param in search
  client/analytics/report/index.js
Labels: [Status] Ready to Merge

#3776 Starter Pack: Make adding styles easier
  bin/starter-pack/src/index.js
  bin/starter-pack/src/index.scss
Labels: Build, [Status] Ready to Merge

#3765 Product titles include encoded entities
  client/analytics/report/products/table.js
  client/analytics/report/stock/table.js
  packages/components/src/dropdown-button/index.js
  packages/components/src/search/autocompleters/utils.js
  packages/components/src/search/test/index.js
  packages/components/src/tag/index.js
  src/API/Products.php
  src/API/Reports/Products/Controller.php
  src/API/Reports/Stock/Controller.php
Labels: Components, Packages, [Status] Ready to Merge
