Repository woocommerce/woocommerce-admin, pull requests merged in 2021-12, with the labels that each got.

#7985 Fix shipping task -- completing step 2 redirects users to Woo Home
  client/tasks/fills/shipping/index.js
Labels: status: needs review

#7991 Update/version 3.1.0 dev and changelogs
  changelog.txt
  changelogs/7445_add_tests_to_subscriptions_inclusion
  changelogs/add-7854
  changelogs/add-7951
  changelogs/dev-payment-method-suggestion-endpoint-change
  changelogs/dev-remove_unused_package
  changelogs/fix-7758
  changelogs/fix-7807-navigation-nudge-shows-up-when-invalid
  changelogs/fix-7938-navigation-feedback-follow-up-note-should-self-delete-when-not-relevant
  changelogs/fix-tasklist-ui-experiment-enablement-logic
  changelogs/update-7243-action-to-dismiss-all-notes
  changelogs/update-7247-introduce-320-char-limit-for-inbox-notes
  changelogs/update-7248-update-inbox-link-to-activity
  changelogs/update-7720
  changelogs/update-7751
  changelogs/update-7793-set-a-note-as-read-after-clicking-cta-buttons
  changelogs/update-7941
  changelogs/update-7946-support-hiding-inbox-panel-header
  changelogs/update-pin-node-to-14-in-nvmrc
  changelogs/update-task-initialization
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: status: needs review, Build, needs changelog entry

#7989 Fix PHP Warning on 'Add new product' page
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7956
  src/Features/OnboardingTasks/Task.php
Labels: status: ready to merge, needs cherry picking

#7983 Display actioned notes on Woo Home
  changelogs/feature-7981-load-actioned-notes
  client/inbox-panel/index.js
  packages/experimental/src/inbox-note/style.scss
Labels: status: ready to merge, Packages, needs cherry picking

#7994 Correctly match payment gateways by id
  client/tasks/fills/PaymentGatewaySuggestions/index.js
Labels: status: ready to merge, needs cherry picking

#7982 Fix datepicker in advanced filter
  changelogs/fix-7507_fix_datepicker
  packages/components/CHANGELOG.md
  packages/components/src/calendar/date-picker.js
Labels: status: ready to merge, Packages, Components

#7979 Add loading icon and disable continue until free extensions are loaded
  changelogs/fix-7321_free_extensions_list
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  packages/admin-e2e-tests/src/sections/onboarding/BusinessSection.ts
Labels: status: ready to merge, Packages

#8000 Update e2e-environment, so tests are run successfully locally.
  changelogs/fix-e2e-tests
  package-lock.json
  package.json
Labels: status: ready to merge, Build

#7966 Add payment gateway suggestion docs and example extensions
  changelogs/add-7937
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  docs/examples/extensions/payment-gateway-suggestions/class-my-simple-gateway.php
  docs/examples/extensions/payment-gateway-suggestions/class-my-slot-filled-gateway.php
  docs/examples/extensions/payment-gateway-suggestions/js/index.js
  docs/examples/extensions/payment-gateway-suggestions/woocommerce-admin-payment-gateway-suggestions-mock-installer.php
  docs/examples/extensions/payment-gateway-suggestions/woocommerce-admin-payment-gateway-suggestions.php
  docs/features/payment-gateway-suggestions.md
  src/Features/PaymentGatewaySuggestions/Init.php
Labels: status: ready to merge

#8001 Remove limit from coupons query when getting the total count
  changelogs/fix-7681_coupons_query
  src/API/Reports/Coupons/DataStore.php
Labels: status: ready to merge

#8002 Add inbox_note_view Tracks Event
  changelogs/fix-inbox-panel-view-event
  client/inbox-panel/index.js
  client/inbox-panel/test/index.js
Labels: status: ready to merge

#8003 wp-env - Update doc for the default mysql username and password
  docker/wc-admin-wp-env/README.md
Labels: status: needs review

#8016 Sync up changelogs after 3.0.0-beta.2 release
  changelog.txt
  changelogs/feature-7981-load-actioned-notes
  changelogs/fix-7507_fix_datepicker
  changelogs/fix-7956
  changelogs/fix-inbox-panel-view-event
Labels: status: ready to merge, needs changelog entry

#8023 Do not truncate notes created before WC 6.1 release
  client/inbox-panel/index.js
Labels: status: ready to merge, needs cherry picking

#8025 Add Testing Instructions for Inbox 2.0
  TESTING-INSTRUCTIONS.md
Labels: status: ready to merge, needs cherry picking

#8022 Do not truncate non-U.S notes.
  client/inbox-panel/index.js
Labels: status: needs review, needs cherry picking

#8019 Add Inbox Note example code to docs
  docs/examples/extensions/simple-inbox-note/class-simpleinboxnote.php
  docs/examples/extensions/simple-inbox-note/js/index.js
  docs/examples/extensions/simple-inbox-note/woocommerce-admin-simple-inbox-note-example.php
Labels: status: ready to merge

#8009 Add featured pill for MailPoet and Google Listings in marketing task
  changelogs/add-7542
  client/tasks/fills/Marketing/Plugin.scss
  client/tasks/fills/Marketing/Plugin.tsx
  client/tasks/fills/Marketing/PluginList.tsx
  client/tasks/fills/Marketing/index.tsx
  client/tasks/fills/Marketing/test/index.tsx
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
Labels: status: ready to merge, feature: setup checklist

#8031 Fix shipping task completion status
  changelogs/fix-8026
  client/tasks/fills/shipping/index.js
Labels: status: needs review, needs cherry picking

#7988 Fix/7660 Remove note->read_meta
  changelogs/fix-7660-remove-note-read-meta-data-calls
  src/Notes/DataStore.php
Labels: status: ready to merge

#8032 Sync up changelogs after 3.0.0-rc.1 release
  changelog.txt
  changelogs/fix-8026
Labels: status: ready to merge

#8045 Fix select-control component label value alignment css style
  changelogs/fix-7786-searchable-select-control-label-alginment
  packages/components/CHANGELOG.md
  packages/components/src/select-control/style.scss
Labels: status: ready to merge, Packages, Components

#8046 Allow storybook use different style based on a config
  README.md
  package.json
  storybook/.storybook/main.js
  storybook/.storybook/preview-head.html
Labels: status: ready to merge, Build, priority: low

#7996 Add e2e tests for PR 7963
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  packages/admin-e2e-tests/src/sections/onboarding/BusinessSection.ts
  packages/admin-e2e-tests/src/specs/activate-and-setup/complete-onboarding-wizard.ts
  tests/e2e/config/default.json
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.tsx
Labels: status: needs review, status: ready to merge, Packages

#8047 Allow content data note props to be passed from remote sources
  changelogs/update-7915
  src/RemoteInboxNotifications/SpecRunner.php
Labels: status: ready to merge

#8055 Remove navigation feedback notes
  changelogs/remove-5475-navigation-feedback-notes
  src/Events.php
  src/Install.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationFeedbackFollowUp.php
Labels: status: ready to merge

#8054 Remove low performing inbox notes
  changelogs/remove-5475-navigation-feedback-notes
  changelogs/remove-7970-low-performing-inbox-notes
  src/Events.php
  src/FeaturePlugin.php
  src/Install.php
  src/Notes/ChooseNiche.php
  src/Notes/DeprecatedNotes.php
  src/Notes/DrawAttention.php
  src/Notes/FilterByProductVariationsInReports.php
  src/Notes/GettingStartedInEcommerceWebinar.php
  src/Notes/LearnMoreAboutVariableProducts.php
  src/Notes/Marketing.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationFeedbackFollowUp.php
  src/Notes/NeedSomeInspiration.php
  src/Notes/StartDropshippingBusiness.php
  tests/notes/class-wc-marketing.php
  tests/notes/class-wc-tests-learn-more-about-variable-product.php
Labels: status: ready to merge

#8038 OBW: Update WC Pay label on recommended extensions list
  changelogs/tweak-7551
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
Labels: status: ready to merge, feature: onboarding

#8072 Fix unexpected analytics report table filter results
  changelogs/fix-7895-filter-customer-table
  client/analytics/components/report-table/index.js
Labels: status: ready to merge

#8087 Do not initialize WC Pay promotion if spec is empty
  src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php
Labels: status: ready to merge

#8086 Add/8073 add action_click event to inbox 2.0
  changelogs/add-8073-add-inbox2-click-event
  client/inbox-panel/index.js
Labels: status: ready to merge

#8044 Syc 2.9.x changelog entries
  changelog.txt
Labels: status: ready to merge, needs cherry picking

#8085 Add payments remind me later note
  changelogs/add-8077-wcpay-payments-remind-me-later-note
  src/Events.php
  src/Notes/PaymentsRemindMeLater.php
Labels: status: ready to merge

#8089 OBW: Hide the extensions header when no available plugins in the category
  changelogs/fix-8006-hide-header-if-no-plugin
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js
  client/profile-wizard/steps/business-details/test/index.js
Labels: status: ready to merge, feature: onboarding

#8093 Changelog - Update release date
  changelog.txt
Labels: status: ready to merge

#8090 Disallow whitespace as a platform name input
  changelogs/fix-7907-disallow-white-space-platform-name-input
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
Labels: status: ready to merge

#8092 Sync version and changelogs after 3.1.0 beta
  TESTING-INSTRUCTIONS.md
  changelog.txt
  changelogs/add-7542
  changelogs/add-7689
  changelogs/add-7937
  changelogs/add-8073-add-inbox2-click-event
  changelogs/fix-7321_free_extensions_list
  changelogs/fix-7660-remove-note-read-meta-data-calls
  changelogs/fix-7681_coupons_query
  changelogs/fix-7786-searchable-select-control-label-alginment
  changelogs/fix-7895-filter-customer-table
  changelogs/fix-e2e-tests
  changelogs/fix-wc31285-disable-coupon-notice-for-new-installs
  changelogs/remove-5475-navigation-feedback-notes
  changelogs/remove-7970-low-performing-inbox-notes
  changelogs/tweak-7551
  changelogs/update-7915
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: status: ready to merge, Build
