Repository woocommerce/woocommerce-admin, pull requests merged in 2021-11, with the labels that each got.

#7873 Add extra intl countries to WC Pay support
  changelogs/update-7862_wc_pay_intl_expansion
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
Labels: status: needs review, needs cherry picking

#7856 Only load tasks during rest api requests
  changelogs/fix-task-list-performance
  src/Features/Onboarding.php
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/TaskLists.php
Labels: status: ready to merge, category: performance

#7876 Remove store setup from the things to do list in the Task List UI experiment
  client/two-column-tasks/extended-task.tsx
Labels: status: ready to merge

#7878 Task List UI - use single column placeholder
  client/homescreen/layout.js
  client/two-column-tasks/index.js
  client/two-column-tasks/placeholder.js
Labels: status: ready to merge

#7861 Add Profile Notes
  changelogs/add-profile-notes
  includes/class-experimental-abtest.php
  src/API/Notes.php
  src/Events.php
  src/Notes/CompleteStoreDetails.php
  src/Notes/UpdateStoreDetails.php
Labels: status: needs review

#7830 Add WC Pay in person text
  changelogs/update-7719
  client/tasks/fills/PaymentGatewaySuggestions/components/Action.js
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7870 Clean up tax task components
  changelogs/add-7442
  client/tasks/fills/tax/automated-taxes.tsx
  client/tasks/fills/tax/configuration-stepper/connect.tsx
  client/tasks/fills/tax/configuration-stepper/index.tsx
  client/tasks/fills/tax/configuration-stepper/manual-configuration.tsx
  client/tasks/fills/tax/configuration-stepper/plugins.tsx
  client/tasks/fills/tax/configuration-stepper/store-location.tsx
  client/tasks/fills/tax/index.js
  client/tasks/fills/tax/index.tsx
  client/tasks/fills/tax/utils.ts
Labels: status: ready to merge, needs changelog entry

#7835 Adding unfulfilled order count badge to woo navigation
  client/navigation/components/Item/index.js
  src/Features/Navigation/CoreMenu.php
Labels: status: needs review, needs changelog entry

#7819 Avoid caching extended info on Analytics -> Products
  changelogs/fix-7540-product-stocks-fails-to-update-on-analytics
  src/API/Reports/Products/DataStore.php
Labels: status: ready to merge, feature: analytics

#7872 Add 2col Experiment
  changelogs/feature-add-2col-experiment
  client/homescreen/layout.js
Labels: status: needs review

#7883 Bump Minimum Versions for 2.9 Release
  README.md
  woocommerce-admin.php
Labels: status: needs review

#7880 Sync changelog from 2.8.0
  changelog.txt
  changelogs/fix-7812_activity_panel_styling
  changelogs/fix-7814-correct-link-to-wc-dev-blog
  changelogs/fix-7816_stock_activity_panel
  changelogs/update-7862_wc_pay_intl_expansion
Labels: status: ready to merge, Build

#7886 Remove the Spinner component while loading the store alerts
  changelogs/update-7336-remove-loading-indicator
  client/layout/index.js
Labels: status: ready to merge, needs cherry picking

#7829 Fix wc_admin_daily from a missed change
  src/Events.php
  src/RemoteInboxNotifications/DataSourcePoller.php
Labels: status: ready to merge, needs cherry picking

#7865 Use $id instance property in DataSourcePoller instead of ID const defined in child classes
  src/DataSourcePoller.php
Labels: status: ready to merge, type: technical debt

#7804 Add tests to Subscriptions inclusion
  changelogs/7445_add_tests_to_subscriptions_inclusion
  packages/admin-e2e-tests/CHANGELOG.md
  packages/admin-e2e-tests/src/pages/BasePage.ts
  packages/admin-e2e-tests/src/pages/OnboardingWizard.ts
  packages/admin-e2e-tests/src/pages/ProductsSetup.ts
  packages/admin-e2e-tests/src/pages/WcSettings.ts
  packages/admin-e2e-tests/src/sections/onboarding/IndustrySection.ts
  packages/admin-e2e-tests/src/sections/onboarding/ProductTypesSection.ts
  packages/admin-e2e-tests/src/specs/activate-and-setup/complete-onboarding-wizard.ts
  packages/admin-e2e-tests/src/specs/tasks/payment.ts
  packages/admin-e2e-tests/src/utils/actions.ts
  tests/api/onboarding-product-types.php
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.tsx
Labels: status: ready to merge, Packages

#7901 Revert #7471 – use "Extensions" as the page title for My Subscriptions and Marketplace pages
  changelogs/update-7901-revert-page-title-to-extensions
  includes/connect-existing-pages.php
Labels: status: ready to merge, needs cherry picking

#7902 Revert #7529 – remove Marketplace menu
  changelogs/update-revert-extensions-menu-split
  src/Features/Navigation/CoreMenu.php
Labels: status: ready to merge, needs cherry picking

#7864 Present Inbox notes in a panel with header
  changelogs/feature-7242-inbox-notes-in-panel-with-header
  client/header/activity-panel/panels/inbox/inbox.scss
  client/inbox-panel/index.js
  client/inbox-panel/index.scss
  packages/experimental/CHANGELOG.md
  packages/experimental/src/inbox-note/action.tsx
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
  packages/experimental/src/inbox-note/test/inbox-note.tsx
Labels: status: needs review, Packages

#7887 Allow for 9 items in Marketing recommended lists
  changelogs/update-7887
  client/marketing/components/product-icon/icons/index.js
  client/marketing/components/product-icon/icons/library/mailpoet.js
  client/marketing/data/resolvers.js
Labels: status: ready to merge, needs cherry picking

#7904 Only load default tasks during REST requests
  changelogs/fix-task-performance-2.9
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/TaskLists.php
Labels: status: ready to merge, needs cherry picking

#7874 Add Avalara to tax task
  TESTING-INSTRUCTIONS.md
  changelogs/add-7442-2
  client/tasks/fills/tax/avalara/card.tsx
  client/tasks/fills/tax/avalara/logo.png
  client/tasks/fills/tax/components/bullet.tsx
  client/tasks/fills/tax/components/partner-card.scss
  client/tasks/fills/tax/components/partner-card.tsx
  client/tasks/fills/tax/components/partners.scss
  client/tasks/fills/tax/components/partners.tsx
  client/tasks/fills/tax/components/store-location.tsx
  client/tasks/fills/tax/configuration-stepper/index.tsx
  client/tasks/fills/tax/index.tsx
  client/tasks/fills/tax/manual-configuration/configure.tsx
  client/tasks/fills/tax/manual-configuration/index.tsx
  client/tasks/fills/tax/utils.ts
  client/tasks/fills/tax/woocommerce-tax/automated-taxes.tsx
  client/tasks/fills/tax/woocommerce-tax/card.tsx
  client/tasks/fills/tax/woocommerce-tax/connect.tsx
  client/tasks/fills/tax/woocommerce-tax/index.tsx
  client/tasks/fills/tax/woocommerce-tax/logo.png
  client/tasks/fills/tax/woocommerce-tax/plugins.tsx
  client/tasks/fills/tax/woocommerce-tax/setup.scss
  client/tasks/fills/tax/woocommerce-tax/setup.tsx
  package-lock.json
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/Tasks/Tax.php
Labels: status: ready to merge, needs cherry picking

#7841 Remove task status endpoint
  changelogs/update-7372
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  client/homescreen/index.tsx
  client/tasks/fills/appearance.js
  client/tasks/fills/shipping/rates.js
  client/tasks/fills/tax/avalara/card.tsx
  client/tasks/fills/tax/index.tsx
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  packages/data/src/onboarding/test/reducer.js
  packages/data/src/onboarding/with-onboarding-hydration.js
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/Task.php
  src/Features/OnboardingTasks/Tasks/Appearance.php
  src/Features/OnboardingTasks/Tasks/Products.php
  src/Features/OnboardingTasks/Tasks/Tax.php
Labels: status: ready to merge, Packages

#7908 Fix marketing extensions tracks
  changelogs/fix-7903
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
Labels: type: bug, status: ready to merge, feature: onboarding, needs cherry picking

#7909 Prepare 3.0.0 release cycle
  changelog.txt
  changelogs/add-7442
  changelogs/add-7442-2
  changelogs/add-7636-header-cards
  changelogs/add-no-match-layout
  changelogs/add-profile-notes
  changelogs/add-task-list-docs
  changelogs/feature-7242-inbox-notes-in-panel-with-header
  changelogs/feature-7637-summary-tasks
  changelogs/feature-add-2col-experiment
  changelogs/fix-7540-product-stocks-fails-to-update-on-analytics
  changelogs/fix-7703
  changelogs/fix-7713-dismiss-calendar-on-blur
  changelogs/fix-7772-wpNavMenuClassChange-scope
  changelogs/fix-7806
  changelogs/fix-7846-update-personalize-task-cta
  changelogs/fix-7847-replace-experiment-task-titles-with-original
  changelogs/fix-task-performance-2.9
  changelogs/fix-tasklist-ui-illustrations-styling
  changelogs/tweak-7642_minor_design_update_to_marketing_task
  changelogs/update-7336-remove-loading-indicator
  changelogs/update-7374
  changelogs/update-7719
  changelogs/update-7815-nav-contrast
  changelogs/update-7823
  changelogs/update-7887
  changelogs/update-7901-revert-page-title-to-extensions
  changelogs/update-datasource_classes_refactor
  changelogs/update-revert-extensions-menu-split
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#7928 Bump experimental version
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: status: needs review, Build, Packages

#7926 Fix ExPlat PHP client and experimental onboarding note
  changelogs/fix-explat-php-client-and-profile-note
  includes/class-experimental-abtest.php
  src/API/Notes.php
  src/Notes/CompleteStoreDetails.php
  src/Notes/UpdateStoreDetails.php
Labels: status: ready to merge, needs cherry picking

#7930 Fix TaskList UI experiment enablement logic
  changelogs/fix-tasklist-ui-experiment-enablement-logic
  client/homescreen/layout.js
  client/two-column-tasks/headers/payments.js
Labels: status: ready to merge, needs cherry picking

#7932 Set Node version to 14 in .nvmrc to prevent incompatible versions of Node from being used with nvm
  .nvmrc
  changelogs/update-pin-node-to-14-in-nvmrc
Labels: type: bug, status: ready to merge, Build

#7929 Pass child props to partners card
  client/tasks/fills/tax/avalara/card.tsx
  client/tasks/fills/tax/components/partner-card.tsx
  client/tasks/fills/tax/index.tsx
  client/tasks/fills/tax/woocommerce-tax/card.tsx
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7922 Sync WooCommerce Payments default gateway with WCCOM
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge, needs changelog entry

#7820 Replace old task list option calls with data store selectors
  changelogs/update-7751
  client/header/activity-panel/display-options/index.js
  client/header/activity-panel/display-options/test/index.js
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/abbreviated-notifications-panel.js
  client/header/activity-panel/test/index.js
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/test/index.js
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/profile-wizard/index.js
  docs/features/onboarding-tasks.md
  packages/admin-e2e-tests/src/fixtures/options.ts
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/admin-e2e-tests/src/specs/homescreen/task-list.ts
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  src/API/OnboardingTasks.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks/DeprecatedOptions.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/Purchase.php
  tests/features/onboarding-tasks/task-list.php
Labels: status: ready to merge, Packages

#7934 Addressing blank screen displayed on products task
  client/tasks/fills/products/product-template-modal.js
  client/tasks/fills/products/products.js
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7914 Have NavigationNudge and NavigationFeedback self-delete when irrelevant
  changelogs/fix-7807-navigation-nudge-shows-up-when-invalid
  src/Events.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationNudge.php
  src/Notes/NoteTraits.php
Labels: status: ready to merge, needs feedback

#7913 Update payment method suggestion endpoint
  changelogs/dev-payment-method-suggestion-endpoint-change
  client/payments/payment-recommendations.tsx
  client/payments/test/payment-recommendations.test.tsx
  packages/data/src/plugins/actions.ts
  src/API/Plugins.php
  src/DataSourcePoller.php
  src/Features/WcPayPromotion/Init.php
  src/PaymentMethodSuggestionsDataSourcePoller.php
  src/PaymentPlugins.php
  tests/api/plugins.php
Labels: status: ready to merge, Packages, type: technical debt

#7918 Use abstraction to add and retrieve task data
  changelogs/update-task-initialization
  packages/data/src/onboarding/deprecated-tasks.js
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/DeprecatedExtendedTask.php
  src/Features/OnboardingTasks/Task.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/Appearance.php
  src/Features/OnboardingTasks/Tasks/Marketing.php
  src/Features/OnboardingTasks/Tasks/Payments.php
  src/Features/OnboardingTasks/Tasks/Products.php
  src/Features/OnboardingTasks/Tasks/Purchase.php
  src/Features/OnboardingTasks/Tasks/Shipping.php
  src/Features/OnboardingTasks/Tasks/StoreDetails.php
  src/Features/OnboardingTasks/Tasks/Tax.php
  src/Features/OnboardingTasks/Tasks/WooCommercePayments.php
  tests/api/onboarding-tasks.php
  tests/features/onboarding-tasks/task-list.php
  tests/features/onboarding-tasks/task.php
  tests/features/onboarding-tasks/test-task.php
Labels: status: ready to merge, Packages

#7871 Add dismiss all button for Inbox 2.0
  changelogs/update-7243-action-to-dismiss-all-notes
  client/inbox-panel/dissmiss-all-modal.js
  client/inbox-panel/index.js
  client/inbox-panel/index.scss
  packages/experimental/src/inbox-note/style.scss
Labels: status: needs review, Packages, feature: inbox

#7879 Rename Inbox -> Activity from the activity header
  changelogs/update-7248-update-inbox-link-to-activity
  client/header/activity-panel/icon-flag.js
  client/header/activity-panel/index.js
  client/header/activity-panel/test/index.js
Labels: status: ready to merge

#7855 Update PageController.php
  changelogs/fix-7758
  src/PageController.php
Labels: status: ready to merge

#7896 Implement inbox note read state
  changelogs/update-7793-set-a-note-as-read-after-clicking-cta-buttons
  client/inbox-panel/index.js
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
  packages/experimental/src/inbox-note/test/inbox-note.tsx
  src/API/NoteActions.php
  src/API/Notes.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/Note.php
  src/Notes/Notes.php
Labels: status: ready to merge, Packages

#7947 Fix race condition in data package's options module
  packages/data/CHANGELOG.md
  packages/data/src/options/controls.js
Labels: status: ready to merge, Packages, needs cherry picking

#7943 Fix WC pay promotion ordering
  changelogs/fix-7942_wc_pay_promotion
  client/wp-admin-scripts/payment-method-promotions/index.tsx
  client/wp-admin-scripts/payment-method-promotions/payment-promotion-row.tsx
  src/Features/WcPayPromotion/Init.php
Labels: type: bug, status: ready to merge, needs cherry picking

#7924 Refactor `wcadmin_storeprofiler_store_business_features_continue` Tracks event handling
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
Labels: status: ready to merge, feature: onboarding

#7949 Remove @woocommerce/settings package, that is not used
  changelogs/dev-remove_unused_package
  package-lock.json
  package.json
Labels: status: ready to merge, Build

#7939 Fix/7938 navigation feedback follow up note should self delete when not relevant
  changelogs/fix-7938-navigation-feedback-follow-up-note-should-self-delete-when-not-relevant
  src/Events.php
  src/Notes/NavigationFeedbackFollowUp.php
Labels: status: ready to merge

#7952 Hide InboxPanel header content in the sidebar
  changelogs/update-7946-support-hiding-inbox-panel-header
  client/header/activity-panel/panels/inbox/inbox-panel.js
  client/inbox-panel/index.js
Labels: status: ready to merge, feature: inbox

#7961 Fix the failing e2e test
  packages/admin-e2e-tests/src/pages/PaymentsSetup.ts
  packages/admin-e2e-tests/src/specs/tasks/payment.ts
Labels: status: needs review, Packages

#7958 Introduce a 320 character limit for inbox note contents
  changelogs/update-7247-introduce-320-char-limit-for-inbox-notes
  client/inbox-panel/index.js
  client/inbox-panel/test/utils.js
  client/inbox-panel/utils.js
Labels: status: ready to merge, has tests, feature: inbox

#7960 Add Tracks prop when WCPay is installed in Product Types step of store profiler
  client/profile-wizard/steps/product-types/index.js
Labels: status: ready to merge, feature: onboarding

#7945 Add a new update callback for the 3.0 version to update is_read column
  includes/wc-admin-update-functions.php
  src/Install.php
  tests/db-updates/class-wc-tests-update-is-read-from-last-read.php
Labels: status: ready to merge, needs feedback

#7963 OBW - Add number of employees field
  changelogs/add-7854
  client/profile-wizard/steps/business-details/data/employee-options.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/index.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/selectors.ts
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
  tests/api/onboarding-profile.php
Labels: status: ready to merge, Packages, feature: onboarding

#7974 Add testing instructions
  TESTING-INSTRUCTIONS.md
Labels: status: ready to merge

#7969 Make Homescreen Default to Single Column Layout
  changelogs/fix-default-layout
  client/tasks/tasks.tsx
  client/tasks/test/tasks.test.tsx
  client/two-column-tasks/index.js
  includes/wc-admin-update-functions.php
  packages/admin-e2e-tests/src/pages/PaymentsSetup.ts
  packages/admin-e2e-tests/src/specs/tasks/payment.ts
  src/Install.php
Labels: status: needs review, Packages, needs cherry picking

#7977 Make inbox note title clickable
  packages/experimental/CHANGELOG.md
  packages/experimental/src/inbox-note/action.tsx
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
Labels: status: ready to merge, Packages, feature: inbox

#7976 Sync changelog entries from 2.9.0 final
  changelog.txt
  changelogs/fix-7903
  changelogs/fix-7942_wc_pay_promotion
  changelogs/fix-default-layout
  changelogs/fix-explat-php-client-and-profile-note
  changelogs/update-7372
Labels: status: ready to merge

#7962 Ending wcpay promotion experiment and always displaying in payment methods table
  changelogs/update-7941
  src/Features/WcPayPromotion/Init.php
Labels: status: ready to merge, needs changelog entry

#7965 Add option to dismiss promotional payment gateway
  changelogs/add-7951
  client/wp-admin-scripts/payment-method-promotions/index.tsx
  client/wp-admin-scripts/payment-method-promotions/payment-promotion-row.scss
  client/wp-admin-scripts/payment-method-promotions/payment-promotion-row.tsx
  src/Features/WcPayPromotion/Init.php
  src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php
Labels: status: ready to merge

#7980 Move payments task to extended task list when WC Pay task is shown
  changelogs/update-7720
  src/Events.php
  src/Features/OnboardingTasks/Tasks/Payments.php
  src/Notes/SetUpAdditionalPaymentTypes.php
Labels: status: ready to merge
