Repository woocommerce/woocommerce-admin, pull requests merged in 2021-05, with the labels that each got.

#6910 Expand collapse extendable task list
  client/task-list/index.js
  client/task-list/task-list.js
  client/task-list/test/index.js
  readme.txt
Labels: Components, Packages, needs feedback, status: ready to merge

#6884 Make `Search` accept sync `autocompleter.options.`
  packages/components/CHANGELOG.md
  packages/components/src/search/index.js
  packages/components/src/search/test/index.js
  readme.txt
Labels: Components, Packages, has tests, needs feedback, status: ready to merge

#6914 Correct the left position of transient notices when the new nav is used
  client/layout/transient-notices/style.scss
  readme.txt
Labels: status: ready to merge

#6917 Exclude woocommerce shipping for stores that are only offering downlo…
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge, type: bug

#6916 Add task hierarchy support to task item
  client/task-list/index.js
  client/task-list/style.scss
  client/task-list/task-item.scss
  client/task-list/task-item.tsx
  client/task-list/task-list.js
  client/task-list/tasks.js
  client/task-list/test/index.js
  client/task-list/test/task-sort.js
  readme.txt
  typings/index.d.ts
Labels: needs feedback, status: ready to merge, type: enhancement

#6924 Fix incorrect casing of any mention of MailPoet
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
Labels: status: ready to merge, type: bug

#6931 Add a security doc based on other woocommerce repos
  SECURITY.md
Labels: status: ready to merge

#6934 Fix inconsistent quoting in the storybook script
  bin/import-wp-css-storybook.sh
Labels: Build, status: ready to merge

#6933 Use Rule Processing for Free Extensions List
  config/core.json
  config/development.json
  config/plugin.json
  package-lock.json
  src/API/Init.php
  src/API/OnboardingFreeExtensions.php
  src/Features/RemoteFreeExtensions/DataSourcePoller.php
  src/Features/RemoteFreeExtensions/EvaluateExtension.php
  src/Features/RemoteFreeExtensions/Init.php
Labels: needs changelog entry, needs feedback, status: ready to merge

#6945 Do a git clean before the core release as well
  bin/build-plugin-zip.sh
  readme.txt
Labels: Build, status: needs review

#6906 Fix SelectControl focus and de-focus bug
  packages/components/CHANGELOG.md
  packages/components/src/select-control/index.js
  packages/components/src/select-control/list.js
  packages/components/src/select-control/stories/index.js
  packages/components/src/select-control/test/index.js
  readme.txt
Labels: Components, Packages, status: needs review

#6951 Make asset registry loading safer, fallback to different file suffix if it doesn't exist
  readme.txt
  src/Loader.php
Labels: needs cherry picking, status: needs review

#6921 Try add payment method selector to onboarding store
  client/task-list/tasks/payments/RemotePayments/index.js
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  packages/data/src/onboarding/test/reducer.js
  packages/data/src/types/index.ts
  packages/data/src/types/rule-processor.ts
  packages/data/src/types/wp-data.ts
  readme.txt
Labels: Packages, needs feedback, status: ready to merge

#6957 Fix an issue with OBW when wc-pay and Jetpack are both being installed
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Plugins.php
  src/Features/Onboarding.php
Labels: status: ready to merge

#6913 Add filter variation to tracks data in products analytics
  client/analytics/components/report-filters/index.js
  readme.txt
Labels: status: needs review

#6826 remove unnecessary vars from e2e action
  .github/workflows/e2e.yml
Labels: Build, type: task

#6939 Replace marketing extension - Google Listings and Ads
  client/marketing/components/product-icon/icons/index.js
  client/marketing/components/product-icon/icons/library/google.js
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
  images/marketing/google.svg
  packages/data/src/plugins/constants.ts
  readme.txt
  src/API/OnboardingProfile.php
  src/Events.php
  src/Install.php
  src/Notes/GoogleAdsAndMarketing.php
Labels: Packages, status: ready to merge

#6950 Move experimental list components to experimental package
  client/task-list/task-item.tsx
  client/task-list/task-list.js
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/list/index.js
  packages/components/src/list/test/index.js
  packages/components/src/style.scss
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/experimental/src/experimental-list/collapsible-list/index.tsx
  packages/experimental/src/experimental-list/collapsible-list/style.scss
  packages/experimental/src/experimental-list/experimental-list-item.tsx
  packages/experimental/src/experimental-list/experimental-list.tsx
  packages/experimental/src/experimental-list/style.scss
  packages/experimental/src/experimental-list/test/index.tsx
  packages/experimental/src/index.js
  packages/experimental/src/style.scss
  readme.txt
  src/Loader.php
Labels: Build, Components, Packages, status: ready to merge

#6960 Bump @woocommerce/experimental version.
  packages/experimental/CHANGELOG.md
  packages/experimental/README.md
  packages/experimental/package.json
Labels: Build, Packages, status: needs review, type: task

#6925 Make the stat titles more specific to remove ambiguity
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Variations/Stats/Controller.php
Labels: status: ready to merge, type: bug

#6932 Adding Slotfill extension components for remote payments
  client/homescreen/activity-panel/reviews/test/index.js
  client/navigation/components/Item/index.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  packages/components/src/index.js
  packages/components/src/settings-form/README.md
  packages/components/src/settings-form/index.js
  packages/components/src/settings-form/stories/index.js
  packages/components/src/settings-form/style.scss
  packages/components/src/settings-form/types/index.js
  packages/components/src/settings-form/types/setting-checkbox.js
  packages/components/src/settings-form/types/setting-password.js
  packages/components/src/settings-form/types/setting-select.js
  packages/components/src/settings-form/types/setting-text.js
  packages/components/src/style.scss
  packages/components/src/woo-remote-payment-settings/README.md
  packages/components/src/woo-remote-payment-settings/index.js
  packages/components/src/woo-remote-payment/README.md
  packages/components/src/woo-remote-payment/index.js
  readme.txt
  tests/js/util/index.js
Labels: Components, Packages, status: needs review

#6946 Add dry run option for the release script
  README.md
  bin/build-plugin-zip.sh
  bin/github-deploy.sh
Labels: Build, status: ready to merge

#6969 Add note date range logic
  readme.txt
  src/Notes/GivingFeedbackNotes.php
  src/Notes/InsightFirstSale.php
  src/Notes/NoteTraits.php
  src/WCAdminHelper.php
  tests/wc-admin-helper.php
Labels: feature: inbox, status: needs review

#6964 Only fetch remote payment gateway recommendations when opted in
  readme.txt
  src/Features/RemotePaymentMethods/Init.php
Labels: status: ready to merge

#6809 Add transient notices feature
  client/layout/transient-notices/index.js
  client/layout/transient-notices/test/index.js
  config/core.json
  config/development.json
  config/plugin.json
  docs/features/transient-notices.md
  readme.txt
  src/Features/TransientNotices.php
  src/PluginsInstaller.php
  tests/features/class-wc-tests-transient-notices.php
Labels: Build, status: ready to merge

#6978 Move TaskItem component to experimental package for reuse.
  client/task-list/style.scss
  client/task-list/task-list.js
  package-lock.json
  package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
  packages/experimental/src/index.js
  packages/experimental/src/style.scss
Labels: Build, Packages, status: ready to merge

#6911 Forward `autocompleter` prop from `CompareFilter` to `Search`
  packages/components/CHANGELOG.md
  packages/components/src/compare-filter/index.js
  packages/components/src/compare-filter/stories/index.js
  packages/components/src/compare-filter/test/compare-filter.js
  readme.txt
Labels: Components, Packages, status: ready to merge

#6983 Missed styling tweak
  packages/experimental/src/experimental-list/task-item.scss
Labels: Build, Packages

#6985 Update package versions for publishing.
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/package.json
Labels: Build, Components, Packages, status: needs review, type: task

#6948 Support transformers in remote inbox notifications
  readme.txt
  src/RemoteInboxNotifications/OptionRuleProcessor.php
  src/RemoteInboxNotifications/README.md
  src/RemoteInboxNotifications/TransformerInterface.php
  src/RemoteInboxNotifications/TransformerService.php
  src/RemoteInboxNotifications/Transformers/ArrayColumn.php
  src/RemoteInboxNotifications/Transformers/ArrayFlatten.php
  src/RemoteInboxNotifications/Transformers/ArrayKeys.php
  src/RemoteInboxNotifications/Transformers/ArraySearch.php
  src/RemoteInboxNotifications/Transformers/ArrayValues.php
  src/RemoteInboxNotifications/Transformers/DotNotation.php
  src/RemoteInboxNotifications/Transformers/README.md
  tests/remote-inbox-notifications/Transformers/array-column.php
  tests/remote-inbox-notifications/Transformers/array-flatten.php
  tests/remote-inbox-notifications/Transformers/array-keys.php
  tests/remote-inbox-notifications/Transformers/array-search.php
  tests/remote-inbox-notifications/Transformers/array-values.php
  tests/remote-inbox-notifications/Transformers/dot-notation.php
  tests/remote-inbox-notifications/transformer-service.php
Labels: feature: inbox, status: ready to merge

#6987 Make sure transformers exist
  src/RemoteInboxNotifications/OptionRuleProcessor.php
Labels: needs changelog entry

#6986 Remove `woocommerce/experimental` dependency from `woocommerce/components`
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/index.js
  packages/components/src/compare-filter/index.js
  packages/components/src/experimental.js
  packages/components/src/list/stories/index.js
  packages/components/src/pill/pill.js
  packages/components/src/summary/number.js
  packages/experimental/src/experimental-list/stories/index.js
  packages/experimental/src/experimental-list/stories/style.scss
  storybook/main.js
  storybook/webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#6979 Add source support for notes query
  readme.txt
  src/API/Notes.php
  src/Notes/DataStore.php
  tests/api/admin-notes.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: feature: inbox, status: ready to merge

#6991 Update Version to 2.4.0-dev
  bin/composer/phpunit/composer.lock
  composer.json
  composer.lock
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, needs changelog entry, status: ready to merge

#6967 Get post install scripts from gateway and enqueue in client
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/index.js
  client/wc-admin-settings/index.js
  readme.txt
  src/Features/RemotePaymentMethods/PaymentGatewaysController.php
Labels: status: ready to merge

#6998 Avoid duplicate preload tags.
  readme.txt
  src/Loader.php
Labels: cooldown period, status: ready to merge, type: bug

#6952 Consume Remote Free Extensions from UI
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
  src/Features/RemoteFreeExtensions/EvaluateExtension.php
  src/Features/RemoteFreeExtensions/Init.php
Labels: status: ready to merge

#6708 Update Form's documentation
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/store-details/index.js
  client/task-list/tasks/payments/generic-payment-step.js
  client/task-list/tasks/payments/methods/bacs.js
  client/task-list/tasks/payments/methods/eway.js
  client/task-list/tasks/payments/methods/paypal.js
  client/task-list/tasks/payments/methods/razorpay.js
  client/task-list/tasks/payments/methods/stripe.js
  client/task-list/tasks/shipping/rates.js
  client/task-list/tasks/steps/location.js
  packages/components/src/form/README.md
  packages/components/src/form/index.js
  packages/components/src/form/stories/index.js
Labels: Components, Packages, needs feedback

#6626 Call existing filters for leaderboards.
  readme.txt
  src/API/Leaderboards.php
Labels: feature: analytics

#6999 Set target to blank for the external links
  TESTING-INSTRUCTIONS.md
  client/store-management-links/quick-link/index.js
  readme.txt
Labels: feature: home screen, status: ready to merge, type: bug

#6981 Typescript conversion of DynamicForm Component
  .eslintrc.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/index.js
  packages/components/src/dynamic-form/README.md
  packages/components/src/dynamic-form/dynamic-form.tsx
  packages/components/src/dynamic-form/field-types/field-checkbox.tsx
  packages/components/src/dynamic-form/field-types/field-password.tsx
  packages/components/src/dynamic-form/field-types/field-select.tsx
  packages/components/src/dynamic-form/field-types/field-text.tsx
  packages/components/src/dynamic-form/field-types/index.ts
  packages/components/src/dynamic-form/index.js
  packages/components/src/dynamic-form/stories/index.js
  packages/components/src/dynamic-form/style.scss
  packages/components/src/dynamic-form/types.ts
  packages/components/src/index.js
  packages/components/src/settings-form/README.md
  packages/components/src/settings-form/index.js
  packages/components/src/settings-form/types/index.js
  packages/components/src/settings-form/types/setting-checkbox.js
  packages/components/src/settings-form/types/setting-password.js
  packages/components/src/settings-form/types/setting-select.js
  packages/components/src/settings-form/types/setting-text.js
  packages/components/src/style.scss
  packages/components/src/woo-remote-payment-form/README.md
  packages/components/src/woo-remote-payment-form/index.js
  packages/components/src/woo-remote-payment-settings/README.md
  packages/components/src/woo-remote-payment-settings/index.js
  readme.txt
Labels: Build, Components, Packages, needs feedback

#6990 Tweak: change MailPoet's title and description in Store Profiler (#6989)
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  readme.txt
Labels: feature: onboarding, needs cherry picking

#7001 Add PayPal to fallback payment gateways
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethodList/PaymentMethodList.js
  readme.txt
  src/Features/OnboardingTasks.php
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
  src/Features/RemotePaymentMethods/EvaluateMethod.php
  src/Features/RemotePaymentMethods/Init.php
  src/Features/RemotePaymentMethods/PaymentGatewaysController.php
Labels: status: needs review

#7015 Revert copy for setup checklist
  client/header/index.js
  client/header/test/index.js
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/test/index.js
  readme.txt
  tests/e2e/constants/taskTitles.ts
  tests/e2e/pages/PaymentsSetup.ts
  tests/e2e/pages/WcHomescreen.ts
  tests/e2e/specs/tasks/payment.test.ts
Labels: needs cherry picking, status: ready to merge

#7026 Fixing redudant notices when installing plugins via payment task list
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/index.js
  readme.txt
Labels: status: ready to merge

#7054 Temporarily hardcode e2e workflow to use WordPress 5.7.1
  .github/workflows/e2e.yml
Labels: Build

#7048 WCPay: Update supported countries
  client/task-list/tasks/payments/methods/wcpay/is-supported.js
  readme.txt
Labels: needs cherry picking, needs feedback

#7049 Setup Checklist: Copy text changes from 7015
  .github/workflows/e2e.yml
  client/header/index.js
  client/header/test/index.js
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/test/index.js
  package-lock.json
  tests/e2e/constants/taskTitles.ts
  tests/e2e/pages/PaymentsSetup.ts
  tests/e2e/pages/WcHomescreen.ts
  tests/e2e/specs/tasks/payment.test.ts
  typings/index.d.ts
Labels: Build, needs changelog entry, status: needs review

#7029 Replace marketing extension - Google Listings and Ads - fix
  client/marketing/components/product-icon/icons/library/google.js
  readme.txt
  src/Marketing/InstalledExtensions.php
Labels: Build, needs cherry picking, status: needs review

#7050 WCPay: Enable wcpay/support-international-countries on 2.3.1
  config/core.json
Labels: Build, needs changelog entry, status: needs review

#7002 Fix styling of chart component header.
  packages/components/CHANGELOG.md
  packages/components/src/chart/index.js
  packages/components/src/chart/style.scss
  readme.txt
Labels: Components, Packages, cooldown period, status: ready to merge, type: bug

#6918 Add a new store to interact with WC Payments REST APIs
  packages/data/src/index.ts
  packages/data/src/payment-gateways/action-types.ts
  packages/data/src/payment-gateways/actions.ts
  packages/data/src/payment-gateways/constants.ts
  packages/data/src/payment-gateways/index.ts
  packages/data/src/payment-gateways/reducer.ts
  packages/data/src/payment-gateways/resolvers.ts
  packages/data/src/payment-gateways/selectors.ts
  packages/data/src/payment-gateways/test-helpers/stub.ts
  packages/data/src/payment-gateways/test/reducer.ts
  packages/data/src/payment-gateways/types.ts
  readme.txt
Labels: Packages, needs feedback

#7008 Remote Free Extensions: clean up usage of slugs/keys
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  src/Features/RemoteFreeExtensions/EvaluateExtension.php
Labels: needs changelog entry, status: ready to merge

#7009 Rule Processing: pass in default
  readme.txt
  src/RemoteInboxNotifications/OptionRuleProcessor.php
  src/RemoteInboxNotifications/TransformerInterface.php
  src/RemoteInboxNotifications/TransformerService.php
  src/RemoteInboxNotifications/Transformers/ArrayColumn.php
  src/RemoteInboxNotifications/Transformers/ArrayFlatten.php
  src/RemoteInboxNotifications/Transformers/ArrayKeys.php
  src/RemoteInboxNotifications/Transformers/ArraySearch.php
  src/RemoteInboxNotifications/Transformers/ArrayValues.php
  src/RemoteInboxNotifications/Transformers/DotNotation.php
  tests/remote-inbox-notifications/Transformers/dot-notation.php
  tests/remote-inbox-notifications/transformer-service.php
Labels: status: ready to merge

#7010 bump ExPlat deps and prep for release
  package-lock.json
  package.json
  packages/explat/CHANGELOG.md
  packages/explat/package.json
Labels: Build, Packages, needs changelog entry, status: ready to merge

#7037 Rule processing transformers: Add count rule
  src/RemoteInboxNotifications/Transformers/Count.php
  tests/remote-inbox-notifications/Transformers/count.php
Labels: status: needs review

#7062 Post-Release 2.3.1: Sync readme changelog and testing instructions
  TESTING-INSTRUCTIONS.md
  package.json
  readme.txt
Labels: Build, status: needs review

#7071 Add missing argument to match TransformerInterface
  src/RemoteInboxNotifications/Transformers/Count.php
Labels: status: ready to merge

#7025 Add Paystack as fallback gateway
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: needs feedback

#7044 Add PayPal as default fallback gateway
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: needs changelog entry, needs feedback

#7043 Add Mercado Pago as default fallback payment gateway
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: status: ready to merge

#7053 Remove fragile selector.
  client/index.js
  readme.txt
Labels: status: ready to merge, type: bug

#7060 Set autoload to false for all remote inbox notifications options
  readme.txt
  src/RemoteInboxNotifications/DataSourcePoller.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
Labels: status: ready to merge

#7038 Hook up payments gateway data store
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  packages/components/src/dynamic-form/dynamic-form.tsx
  packages/components/src/form/README.md
  packages/data/src/payment-gateways/actions.ts
  packages/data/src/payment-gateways/reducer.ts
  packages/data/src/payment-gateways/selectors.ts
  packages/data/src/payment-gateways/test/reducer.ts
  packages/data/src/payment-gateways/types.ts
  readme.txt
Labels: Components, Packages, status: ready to merge

#7034 Add tree shaking support for woocommerce components
  bin/packages/build.js
  packages/components/CHANGELOG.md
  packages/components/README.md
  packages/components/package.json
  packages/components/src/advanced-filters/utils.js
  packages/components/src/calendar/date-range.js
  packages/components/src/index.js
  packages/components/src/section-header/index.js
  packages/components/src/section/context.js
  packages/components/src/section/header.js
  packages/components/src/section/index.js
  packages/components/src/section/section.js
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/README.md
  packages/dependency-extraction-webpack-plugin/src/index.js
  webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#7005 Fix advanced filter operator selector styling.
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/style.scss
  readme.txt
Labels: Components, Packages, cooldown period, feature: analytics, status: ready to merge, type: bug

#7057 Add COD method to default payment gateway recommendations
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethodList/index.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.scss
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/index.js
  client/task-list/tasks/payments/RemotePayments/index.js
  images/onboarding/cod.svg
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: status: ready to merge

#6995 Offload remote inbox notifications engine run using action-scheduler
  readme.txt
  src/RemoteInboxNotifications/ProductCountRuleProcessor.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
  src/RemoteInboxNotifications/StoredStateSetupForProducts.php
Labels: status: ready to merge

#7063 add count transformer ReadMe
  src/RemoteInboxNotifications/Transformers/README.md
Labels: status: ready to merge

#7080 Fix Formatting in Coupons E2E Test
  tests/e2e/specs/marketing/coupons.test.ts
Labels: status: ready to merge

#7051 Image optimization
  images/admin_notes/dashboard-widget-setup.png
  images/admin_notes/filter-by-product-variations-note.svg
  images/empty-content.svg
  images/marketing/amazon-ebay.svg
  images/marketing/automatewoo.svg
  images/marketing/facebook.svg
  images/marketing/google.svg
  images/marketing/hubspot.svg
  images/marketing/mailchimp.svg
  images/onboarding/creativemail.png
  images/onboarding/fb-woocommerce.png
  images/onboarding/g-shopping.png
  images/onboarding/mailchimp.png
  images/onboarding/mailpoet.png
  images/onboarding/mercadopago.png
  images/onboarding/other-small.jpg
  images/onboarding/paystack.png
  images/shippingillustration.svg
Labels: status: ready to merge

#7056 bump E2E package versions to latest
  package-lock.json
  package.json
Labels: Build, status: ready to merge, type: task

#7058 Refactoring WCPayCard into new onboarding package
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.scss
  client/task-list/tasks/payments/RemotePayments/index.js
  client/task-list/tasks/payments/components/PaymentAction.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.scss
  client/task-list/tasks/payments/components/WCPayCard/WCPayCard.js
  client/task-list/tasks/payments/components/WCPayCard/index.js
  client/task-list/tasks/payments/components/WCPayMethodCard.js
  docs/features/remote-payments.md
  package.json
  packages/components/src/index.js
  packages/onboarding/.npmrc
  packages/onboarding/README.md
  packages/onboarding/package.json
  packages/onboarding/src/components/RecommendedRibbon/RecommendedRibbon.js
  packages/onboarding/src/components/RecommendedRibbon/RecommendedRibbon.scss
  packages/onboarding/src/components/RecommendedRibbon/index.js
  packages/onboarding/src/components/SetupRequired.js
  packages/onboarding/src/components/WCPayAcceptedMethods.js
  packages/onboarding/src/components/WCPayCard/WCPayCard.js
  packages/onboarding/src/components/WCPayCard/WCPayCard.scss
  packages/onboarding/src/components/WCPayCard/index.js
  packages/onboarding/src/components/woo-remote-payment-form/README.md
  packages/onboarding/src/components/woo-remote-payment-form/index.js
  packages/onboarding/src/components/woo-remote-payment/README.md
  packages/onboarding/src/components/woo-remote-payment/index.js
  packages/onboarding/src/images/cards/amex.js
  packages/onboarding/src/images/cards/applepay.js
  packages/onboarding/src/images/cards/cb.js
  packages/onboarding/src/images/cards/diners.js
  packages/onboarding/src/images/cards/discover.js
  packages/onboarding/src/images/cards/jcb.js
  packages/onboarding/src/images/cards/maestro.js
  packages/onboarding/src/images/cards/mastercard.js
  packages/onboarding/src/images/cards/unionpay.js
  packages/onboarding/src/images/cards/visa.js
  packages/onboarding/src/images/wcpay-logo.js
  packages/onboarding/src/index.js
  packages/onboarding/src/style.scss
  readme.txt
  src/Loader.php
  webpack.config.js
Labels: Build, Components, Packages, needs feedback

#7087 Add `md5` for `/data` dependencies.
  packages/data/CHANGELOG.md
  packages/data/package.json
Labels: Build, Packages, status: ready to merge
