Repository woocommerce/woocommerce-admin, pull requests merged in 2021-06, with the labels that each got.

#6846 Reduce the specificity and complexity of the `ReportError` component
  client/analytics/components/leaderboard/index.js
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-error/index.js
  client/analytics/components/report-summary/index.js
  client/analytics/components/report-table/index.js
  client/analytics/report/index.js
  client/analytics/report/products/index.js
  client/analytics/report/variations/index.js
  docs/components/analytics/report-error.md
  readme.txt
Labels: status: ready to merge

#6956 Add conditional copy/content and CTA to expanded task items
  client/task-list/index.js
  client/task-list/style.scss
  client/task-list/task-list.js
  client/task-list/tasks.js
  client/task-list/tasks/tax.js
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
  readme.txt
  tests/e2e/pages/WcHomescreen.ts
Labels: Packages, feature: setup checklist, status: ready to merge

#7079 Update remote payment docs gateway methods
  docs/features/remote-payments.md
  readme.txt
Labels: status: ready to merge

#7089 Add progressive task list experiment
  client/task-list/index.js
  client/task-list/task-list.js
  client/task-list/test/index.js
  readme.txt
Labels: Packages, feature: setup checklist, has tests, status: ready to merge, type: enhancement

#7055 Publish storybook docs, remove react docgen based docs
  .github/workflows/gh-pages.yml
  .gitignore
  README.md
  bin/generate-docs/index.js
  bin/generate-docs/lib/file-system.js
  bin/generate-docs/lib/formatting.js
  bin/packages/build.js
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_variables.scss
  docs/_sidebar.md
  docs/components/README.md
  docs/components/_sidebar.md
  docs/components/analytics/README.md
  docs/components/analytics/report-chart.md
  docs/components/analytics/report-error.md
  docs/components/analytics/report-summary.md
  docs/components/analytics/report-table.md
  docs/components/packages
  docs/documentation.md
  docs/features/README.md
  docs/index.html
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/animation-slider/stories/index.js
  packages/components/src/badge/index.js
  packages/components/src/badge/index.tsx
  packages/components/src/badge/stories/index.js
  packages/components/src/badge/stories/index.tsx
  packages/components/src/table/style.scss
  packages/experimental/package.json
  packages/experimental/src/experimental-list/experimental-list.tsx
  packages/experimental/src/experimental-list/stories/index.tsx
  readme.txt
  storybook/.storybook/main.js
  storybook/.storybook/preview-head.html
  storybook/main.js
  storybook/preview-head.html
  storybook/preview.js
  storybook/style.scss
  storybook/tsconfig.json
  storybook/webpack.config.js
  webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#7102 When publishing the docs on gh workflow the WP css was not imported
  .gitignore
  package.json
Labels: Build, status: needs review

#7077 Fix notices, to make sure it uses the correct store
  client/layout/transient-notices/index.js
  readme.txt
Labels: status: ready to merge, type: bug

#7006 Refactor and extract inbox panel components
  client/inbox-panel/action.js
  client/inbox-panel/card.js
  client/inbox-panel/index.js
  client/inbox-panel/index.scss
  client/inbox-panel/placeholder.js
  client/inbox-panel/test/index.js
  package-lock.json
  packages/components/src/section/header.js
  packages/components/src/section/section.js
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/experimental/src/inbox-note/action.tsx
  packages/experimental/src/inbox-note/inbox-dismiss-confirmation-modal.tsx
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/index.ts
  packages/experimental/src/inbox-note/placeholder.tsx
  packages/experimental/src/inbox-note/style.scss
  packages/experimental/src/inbox-note/test/inbox-dismiss-confirmation-modal.tsx
  packages/experimental/src/inbox-note/test/inbox-note.tsx
  packages/experimental/src/inbox-note/test/use-callback-on-link-click.tsx
  packages/experimental/src/inbox-note/use-callback-on-link-click.ts
  packages/experimental/src/index.js
  packages/experimental/src/style.scss
  readme.txt
Labels: Build, Components, Packages, status: ready to merge

#7073 Add BACS as default fallback payment gateway
  client/task-list/style.scss
  client/task-list/tasks/payments/RemotePayments/components/BacsPaymentGatewaySetup.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayListItem.js
  client/task-list/tasks/payments/RemotePayments/index.js
  images/onboarding/bacs.svg
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: status: ready to merge

#7092 Add Mollie to DefaultPaymentGateways
  client/task-list/tasks/payments/images/mollie.js
  client/task-list/tasks/payments/methods/index.js
  images/onboarding/mollie.svg
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: needs feedback

#7094 Fix a bug where the test zip command used the wrong file suffix for JS
  bin/build-test-zip.sh
Labels: Build, status: ready to merge, type: bug

#7103 Remove business step original flow
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/benefit.js
  client/profile-wizard/steps/benefits/benefits.js
  client/profile-wizard/steps/benefits/images/management.js
  client/profile-wizard/steps/benefits/images/sales_tax.js
  client/profile-wizard/steps/benefits/images/shipping_labels.js
  client/profile-wizard/steps/benefits/images/speed.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/benefits/logo.js
  client/profile-wizard/steps/benefits/test/index.js
  client/profile-wizard/steps/business-details/data/segmentation.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/business-extensions/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/index.js
  client/profile-wizard/style.scss
  readme.txt
  tests/e2e/pages/OnboardingWizard.ts
  tests/e2e/sections/onboarding/BenefitsSection.ts
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.ts
Labels: needs feedback

#7111 Go back to using latest version of WP docker image
  .github/workflows/e2e.yml
Labels: Build, status: ready to merge

#7095 Add payment gateway return URL and action
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  docs/features/remote-payments.md
  readme.txt
  src/Features/RemotePaymentMethods/PaymentGatewaysController.php
Labels: status: ready to merge

#7096 Add in Razorpay as default fallback payment gateway
  client/task-list/tasks/payments/images/cod.js
  client/task-list/tasks/payments/images/razorpay.js
  client/task-list/tasks/payments/methods/index.js
  images/onboarding/razorpay.svg
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: status: ready to merge

#7104 Fixing incorrect Transformer casing throwing an error in case-sensitive environments
  readme.txt
  src/RemoteInboxNotifications/TransformerService.php
Labels: status: ready to merge

#7097 Adding WCPay payment configuration defaults
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayListItem.js
  client/task-list/tasks/payments/RemotePayments/index.js
  client/task-list/tasks/payments/components/WCPayMethodCard.js
  client/task-list/tasks/payments/images/wcpay.js
  client/task-list/tasks/payments/methods/index.js
  images/onboarding/wcpay.svg
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
  src/Features/RemotePaymentMethods/Init.php
Labels: needs feedback, status: ready to merge

#7123 Add loading placeholders for payment gateways task
  client/homescreen/layout.js
  client/task-list/style.scss
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod/PaymentMethod.scss
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod/PaymentMethodPlaceholder.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod/index.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.scss
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayListPlaceholder.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/index.js
  client/task-list/tasks/payments/RemotePayments/index.js
  readme.txt
Labels: status: ready to merge

#7114 Remove the deprecated Card component
  docs/examples/extensions/dashboard-section/js/global-prices.js
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/README.md
  packages/components/src/card/README.md
  packages/components/src/card/index.js
  packages/components/src/card/stories/index.js
  packages/components/src/card/style.scss
  packages/components/src/card/test/__snapshots__/index.js.snap
  packages/components/src/card/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
Labels: Build, Components, Packages, status: ready to merge

#7115 Deprecate the no longer used Count component
  packages/components/CHANGELOG.md
  packages/components/src/count/index.js
Labels: Build, Components, Packages, status: ready to merge

#7112 Drop IE11 support, trim the build ~800kb
  package-lock.json
  package.json
  readme.txt
Labels: Build, status: ready to merge

#7118 Deprecate the SegmentedSelection component, its no longer used.
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/segmented-selection/index.js
Labels: Build, Components, Packages, status: ready to merge

#6923 Add remind me later support to task list
  client/dashboard/style.scss
  client/task-list/index.js
  client/task-list/task-list.js
  client/task-list/task-list.scss
  client/task-list/test/index.js
  package-lock.json
  packages/components/src/ellipsis-menu/index.js
  packages/components/src/ellipsis-menu/test/index.js
  packages/experimental/src/experimental-list/collapsible-list/index.tsx
  packages/experimental/src/experimental-list/collapsible-list/style.scss
  packages/experimental/src/experimental-list/experimental-list-item.tsx
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
  packages/experimental/src/experimental-list/test/index.tsx
  readme.txt
  src/Features/Onboarding.php
  tests/js/jest.config.json
Labels: Build, Components, Packages, needs feedback, status: ready to merge

#7117 Remove useFilters, it was deprecated a long time ago.
  packages/components/CHANGELOG.md
  packages/components/src/higher-order/use-filters/README.md
  packages/components/src/higher-order/use-filters/index.js
  packages/components/src/index.js
Labels: Components, Packages, status: ready to merge

#7116 Deprecate the no longer used Gravatar component
  packages/components/CHANGELOG.md
  packages/components/src/gravatar/index.js
Labels: Build, Components, Packages, status: ready to merge

#6738 Admin Notes: Add new Note suggesting Jetpack Backup to WooCommerce users
  readme.txt
  src/Events.php
  src/Notes/MarketingJetpack.php
Labels: feature: inbox, status: ready to merge

#7129 Revert store setup task list title.
  client/task-list/index.js
  client/task-list/test/index.js
  tests/e2e/pages/WcHomescreen.ts
Labels: status: ready to merge, type: task

#7124 Optimize payment gateway resolution
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayListItem.js
  client/task-list/tasks/payments/RemotePayments/index.js
  packages/data/src/payment-gateways/resolvers.ts
  readme.txt
Labels: Packages, status: ready to merge

#7108 Add eWAY as default fallback gateway
  readme.txt
  src/Features/RemotePaymentMethods/DefaultPaymentGateways.php
Labels: needs feedback

#7110 Add target to the button to open it in a new tab
  TESTING-INSTRUCTIONS.md
  client/payments/payment-recommendations.tsx
  readme.txt
Labels: feature: settings, status: ready to merge, type: bug

#7128 Add progressive task list animation
  client/task-list/task-list.js
  client/task-list/test/index.js
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
Labels: Packages, feature: setup checklist, status: ready to merge, type: enhancement

#7130 Update payment gateway suggestions semantics to be more consistent
  client/task-list/style.scss
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/List.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/List.scss
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/Placeholder.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/index.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Placeholder.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Setup.scss
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/index.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/index.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/plugins/Bacs.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod/index.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/RecommendedPaymentGatewayList.js
  client/task-list/tasks/payments/RemotePayments/components/RecommendedPaymentGatewayList/index.js
  client/task-list/tasks/payments/RemotePayments/index.js
  client/task-list/tasks/payments/components/PaymentAction.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/WCPayMethodCard.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/stripe.js
  config/core.json
  config/development.json
  config/plugin.json
  docs/features/payment-gateway-suggestions.md
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  packages/onboarding/src/components/WooPaymentGatewayConnect/README.md
  packages/onboarding/src/components/WooPaymentGatewayConnect/WooPaymentGatewayConnect.js
  packages/onboarding/src/components/WooPaymentGatewayConnect/index.js
  packages/onboarding/src/components/WooPaymentGatewaySetup/README.md
  packages/onboarding/src/components/WooPaymentGatewaySetup/WooPaymentGatewaySetup.js
  packages/onboarding/src/components/WooPaymentGatewaySetup/index.js
  packages/onboarding/src/components/woo-remote-payment-form/index.js
  packages/onboarding/src/components/woo-remote-payment/index.js
  packages/onboarding/src/index.js
  readme.txt
  src/API/OnboardingPayments.php
  src/Features/PaymentGatewaySuggestions/DataSourcePoller.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
  src/Features/PaymentGatewaySuggestions/EvaluateMethod.php
  src/Features/PaymentGatewaySuggestions/Init.php
  src/Features/PaymentGatewaySuggestions/PaymentGatewaysController.php
Labels: Packages, needs changelog entry, needs feedback

#7021 Include orders without coupons when excluding specific coupon IDs.
  readme.txt
  src/API/Reports/Orders/DataStore.php
  tests/reports/class-wc-tests-reports-orders.php
Labels: cooldown period, feature: analytics, has tests, status: ready to merge, type: bug

#7107 Add Square as default fallback gateway
  readme.txt
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7126 Update engines to better reflect supported node/npm versions.
  package.json
Labels: Build, status: ready to merge

#7085 Add a default gateway for the klarna plugin/gateway `klarna-checkout-for-woocommerce`
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7139 Business features uncheck creative mail by default
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
  readme.txt
Labels: status: ready to merge

#7144 Prepare Remote Free Extensions for release
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  config/core.json
  config/plugin.json
  readme.txt
  src/Features/RemoteFreeExtensions/DataSourcePoller.php
Labels: status: ready to merge

#7134 Reconsider the removal version for deprecated components
  packages/components/src/count/index.js
  packages/components/src/gravatar/index.js
  packages/components/src/segmented-selection/index.js
Labels: Components, Packages, status: needs review

#7137 Remove stylesheets supporting IE11
  client/ie.scss
  packages/components/src/ie.scss
  packages/components/src/segmented-selection/ie.scss
  packages/components/src/summary/ie.scss
  readme.txt
  src/Loader.php
  webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#7017 Show task and activity notifications in the Inbox panel
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/abbreviated-notifications-panel.js
  client/header/activity-panel/panels/inbox/icons/bell.js
  client/header/activity-panel/panels/inbox/inbox-panel.js
  client/header/activity-panel/panels/inbox/inbox.scss
  client/header/activity-panel/style.scss
  client/header/activity-panel/test/abbreviated-notifications-panel.js
  client/header/activity-panel/test/index.js
  client/header/activity-panel/unread-indicators.js
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/reviews/index.js
  client/homescreen/activity-panel/stock/index.js
  client/inbox-panel/index.scss
  client/task-list/index.js
  docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php
  packages/components/CHANGELOG.md
  packages/components/src/abbreviated-card/README.md
  packages/components/src/abbreviated-card/index.js
  packages/components/src/abbreviated-card/stories/index.js
  packages/components/src/abbreviated-card/style.scss
  packages/components/src/abbreviated-card/test/__snapshots__/index.js.snap
  packages/components/src/abbreviated-card/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
  readme.txt
Labels: Components, Packages, feature: inbox, status: ready to merge

#7125 Fix some minor inbox panel issues, left over from re-factor
  client/inbox-panel/index.js
  packages/experimental/src/inbox-note/action.tsx
  packages/experimental/src/inbox-note/inbox-note.tsx
  typings/global.d.ts
Labels: Packages, status: ready to merge

#7106 Bump package versions for release
  bin/starter-pack/_package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/notices/CHANGELOG.md
  packages/notices/package.json
  packages/onboarding/CHANGELOG.md
Labels: Build, Components, Packages, status: ready to merge

#7147 Fix error handling when remote free extension API returns empty array
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: status: ready to merge

#7150 Add changelog note about ExPlat
  readme.txt
Labels: needs changelog entry, status: ready to merge

#7148 chore: change WCS onboarding copy
  client/task-list/tasks/shipping/index.js
  readme.txt
Labels: status: needs review

#7136 Use sass-migrator to migrate division to math.div
  bin/packages/build.js
  client/analytics/settings/historical-data/style.scss
  client/dashboard/style.scss
  client/header/activity-panel/activity-header/style.scss
  client/homescreen/activity-panel/style.scss
  client/stylesheets/abstracts/_mixins.scss
  package-lock.json
  packages/components/src/chart/style.scss
  packages/components/src/pagination/style.scss
  packages/components/src/search-list-control/style.scss
  packages/components/src/stepper/style.scss
  webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#7149 Wraps the dropdown icon in a button to allow keyboard usability
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/style.scss
  readme.txt
Labels: status: needs review

#7151 Fixing local WCPay payment task and refactoring for dumber components
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/List.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/index.js
  client/task-list/tasks/payments/components/WCPaySuggestion.js
  client/task-list/tasks/payments/methods/index.js
  packages/onboarding/src/components/WooPaymentGatewayConnect/README.md
  packages/onboarding/src/components/WooPaymentGatewaySetup/README.md
  readme.txt
  src/Features/PaymentGatewaySuggestions/Init.php
Labels: Packages, needs feedback

#7156 Bump version to 2.5.0-dev and sync changelog and testing instructions
  TESTING-INSTRUCTIONS.md
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#7109 Include onboarding settings on the analytic pages
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/Onboarding.php
Labels: feature: onboarding, status: ready to merge, type: bug

#7167 Revert Card component removal
  docs/examples/extensions/dashboard-section/js/global-prices.js
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/README.md
  packages/components/src/card/README.md
  packages/components/src/card/index.js
  packages/components/src/card/stories/index.js
  packages/components/src/card/style.scss
  packages/components/src/card/test/__snapshots__/index.js.snap
  packages/components/src/card/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
  readme.txt
Labels: Components, Packages, needs cherry picking, status: needs review

#7157 Add core-data dependency to data package
  packages/data/CHANGELOG.md
  packages/data/package.json
Labels: Build, Packages, status: needs review

#7091 Add `slotFill` to Abbreviated Notification panel
  client/header/activity-panel/index.js
  client/header/activity-panel/panels/inbox/abbreviated-notifications-panel.js
  docs/examples/extensions/add-abbreviated-notification/js/index.js
  docs/examples/extensions/add-abbreviated-notification/woocommerce-admin-add-abbreviated-notification-example.php
  readme.txt
Labels: status: ready to merge

#7133 Add unit tests around extended payment gateway controller
  readme.txt
  src/Features/PaymentGatewaySuggestions/PaymentGatewaysController.php
  tests/bootstrap.php
  tests/features/payment-gateway-suggestions/payment-gateway-controller.php
  tests/framework/class-wc-mock-enhanced-payment-gateway.php
Labels: status: needs review

#7161 Parse transient value to integer if retrieved from transient
  readme.txt
  src/API/Reports/Stock/Stats/DataStore.php
Labels: needs cherry picking, status: ready to merge, type: bug

#7164 Update error messages for plugin activation and installation
  packages/data/CHANGELOG.md
  packages/data/src/plugins/actions.ts
Labels: Packages, status: needs review

#7169 Increase ellipsis toggle specificity
  packages/components/src/ellipsis-menu/style.scss
Labels: Components, Packages, needs cherry picking

#7182 RemoteFreeExtension hide bundle when all of its plugins are not visible
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: needs cherry picking, status: ready to merge

#7166 Add tests for Payment Gateway Connect component
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/test/connect.js
Labels: needs changelog entry, status: ready to merge

#7163 Add Payment Gateway Suggestion Setup related component tests
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/test/setup.js
Labels: needs changelog entry, status: ready to merge

#7181 Fix currency display errors in homescreen order activity card
  client/homescreen/activity-panel/orders/index.js
  readme.txt
  src/API/Reports/Controller.php
  src/API/Reports/Orders/Controller.php
  tests/api/reports-orders.php
Labels: feature: activity panel, status: ready to merge, type: bug

#7142 Add payment gateway suggestion unit tests
  readme.txt
  src/API/OnboardingPayments.php
  src/Features/PaymentGatewaySuggestions/DataSourcePoller.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
  src/Features/PaymentGatewaySuggestions/EvaluateMethod.php
  src/Features/PaymentGatewaySuggestions/EvaluateSuggestion.php
  src/Features/PaymentGatewaySuggestions/Init.php
  tests/features/payment-gateway-suggestions/payment-gateway-suggestions.php
Labels: status: ready to merge

#7152 Add unit tests for EvaluateSuggestion class
  tests/features/payment-gateway-suggestions/evaluate-suggestion.php
Labels: needs changelog entry, status: ready to merge

#7153 Add unit tests for payment gateway suggestions data source poller
  src/Features/PaymentGatewaySuggestions/DataSourcePoller.php
  tests/features/payment-gateway-suggestions/data-source-poller.php
  tests/features/payment-gateway-suggestions/payment-gateway-suggestions.php
Labels: needs changelog entry, status: needs review

#7204 Add fallback for the select/dispatch data-controls for older WP versions
  packages/data/src/payment-gateways/resolvers.ts
  packages/data/src/plugins/actions.ts
  packages/data/src/plugins/resolvers.ts
  packages/data/src/settings/actions.js
  packages/data/src/settings/resolvers.js
Labels: Packages, needs cherry picking, needs feedback

#7202 Update the wordpress/babel-preset to avoid crashes in WP5.8 beta2
  bin/packages/get-babel-config.js
  package-lock.json
  package.json
  packages/data/package.json
  tests/js/setup-globals.js
Labels: Build, Packages, needs cherry picking, status: ready to merge

#7196 Add rowKey prop to table for allowing custom keys in rows
  packages/components/CHANGELOG.md
  packages/components/src/table/README.md
  packages/components/src/table/index.js
  packages/components/src/table/stories/table.js
  packages/components/src/table/table.js
  packages/components/src/table/test/index.js
Labels: Components, Packages, cooldown period, status: ready to merge

#7165 Fix report arguments handling in CSV export.
  readme.txt
  src/API/Reports/Products/DataStore.php
  src/ReportCSVExporter.php
  tests/reports/class-wc-tests-reports-products.php
Labels: feature: analytics, has tests, status: ready to merge, type: bug

#7200 Fixing button state logic for payment gateways
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/PaymentAction.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/index.js
  client/task-list/tasks/payments/components/PaymentActionLocal.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/WCPaySuggestion.js
  readme.txt
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7046 Fix attribute filter for "any X" variations.
  packages/components/CHANGELOG.md
  packages/components/src/select-control/index.js
  readme.txt
  src/API/CustomAttributeTraits.php
  src/API/ProductAttributeTerms.php
  src/API/ProductAttributes.php
  src/API/Reports/DataStore.php
  src/API/Reports/Orders/DataStore.php
  src/API/Reports/Orders/Stats/DataStore.php
  src/API/Reports/Variations/DataStore.php
  src/API/Reports/Variations/Stats/DataStore.php
  tests/api/product-attributes.php
  tests/reports/class-wc-tests-reports-variations.php
Labels: Components, Packages, cooldown period, feature: analytics, has tests, status: ready to merge, type: bug

#7154 Use tab char instead of single quote to prevent CSV injection
  packages/csv-export/CHANGELOG.md
  packages/csv-export/src/__mocks__/mock-csv-data.js
  packages/csv-export/src/index.js
  packages/csv-export/src/test/index.js
  readme.txt
Labels: Packages, has tests, type: enhancement

#7223 Bump up csv-export version
  packages/csv-export/package.json
Labels: Build, Packages, status: needs review

#7209 Add notice and enable gateway on successful connection
  src/Features/PaymentGatewaySuggestions/PaymentGatewaysController.php
Labels: needs changelog entry, status: ready to merge

#7191 Add text for manage button when no help text exists
  client/task-list/style.scss
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/Connect.js
  client/task-list/tasks/payments/PaymentGatewaySuggestions/components/Setup/test/connect.js
Labels: needs changelog entry, status: ready to merge

#7214 Skip schedule customer data deletion on site deletion
  readme.txt
  src/Schedulers/CustomersScheduler.php
Labels: status: ready to merge

#7168 Analytics: Add toggle to disable UI features
  readme.txt
  src/Features/Analytics.php
  src/Features/Features.php
  src/Features/Navigation/CoreMenu.php
Labels: status: ready to merge

#7193 Load Analytics API behind feature check
  readme.txt
  src/API/Features.php
  src/API/Init.php
  src/FeaturePlugin.php
  src/Features/Features.php
Labels: needs feedback, status: ready to merge

#7226 Use saved form values when switching tabs
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge, type: bug

#7178 Change the emailed report filename
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Reports/Export/Controller.php
Labels: status: ready to merge

#7237 Use gridicons as ReactElement versus SVG to fix blank screen
  client/dashboard/section-controls.js
  readme.txt
Labels: needs cherry picking, status: ready to merge

#7203 Vertical CSS transition component helper
  client/task-list/test/index.js
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
  packages/experimental/src/index.js
  packages/experimental/src/vertical-css-transition/README.md
  packages/experimental/src/vertical-css-transition/index.ts
  packages/experimental/src/vertical-css-transition/stories/index.tsx
  packages/experimental/src/vertical-css-transition/stories/style.scss
  packages/experimental/src/vertical-css-transition/test/vertical-css-transition.tsx
  packages/experimental/src/vertical-css-transition/vertical-css-transition.tsx
Labels: Build, Packages, cooldown period, has tests, status: ready to merge

#7210 Fixed testing instructions
  TESTING-INSTRUCTIONS.md
Labels: cooldown period, status: ready to merge

#7222 Add date range support to remaining notes
  readme.txt
  src/Notes/AddingAndManangingProducts.php
  src/Notes/ChoosingTheme.php
  src/Notes/CustomizeStoreWithBlocks.php
  src/Notes/DrawAttention.php
  src/Notes/FirstProduct.php
  src/Notes/InsightFirstProductAndPayment.php
  src/Notes/LaunchChecklist.php
  src/Notes/ManageOrdersOnTheGo.php
  src/Notes/Marketing.php
  src/Notes/MarketingJetpack.php
  src/Notes/MigrateFromShopify.php
  src/Notes/MobileApp.php
  src/Notes/NeedSomeInspiration.php
  src/Notes/NoteTraits.php
  src/Notes/OnboardingPayments.php
  src/Notes/OnlineClothingStore.php
  src/Notes/PersonalizeStore.php
  src/Notes/RealTimeOrderAlerts.php
  src/Notes/StartDropshippingBusiness.php
  src/Notes/TrackingOptIn.php
  src/Notes/WooCommercePayments.php
  src/Notes/WooCommerceSubscriptions.php
  src/WCAdminHelper.php
  tests/wc-admin-helper.php
Labels: status: ready to merge

#7219 Localize string for description
  readme.txt
  src/Features/Onboarding.php
Labels: needs feedback, status: ready to merge

#7228 Fix eway payment gateway key
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: needs changelog entry, status: ready to merge

#7238 Add E2E tests for analytics overview screen section removal
  client/dashboard/section-controls.js
  tests/e2e/pages/AnalyticsOverview.ts
  tests/e2e/specs/analytics/analytics-overview.test.ts
Labels: status: ready to merge

#7229 Fixing invalid key props, changing to id
  readme.txt
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7255 WordPress 5.8 compatibility UI fixes
  client/analytics/components/leaderboard/index.js
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  client/dashboard/dashboard-charts/block.js
  client/header/activity-panel/activity-header/index.js
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/panels/inbox/abbreviated-notifications-panel.js
  client/header/index.js
  client/homescreen/activity-panel/index.js
  client/homescreen/stats-overview/index.js
  client/layout/store-alerts/index.js
  client/layout/store-alerts/style.scss
  client/marketing/components/card/index.js
  client/marketing/overview/installed-extensions/index.js
  client/navigation/components/category-title/style.scss
  client/navigation/components/intro-modal/index.js
  client/payments/payment-recommendations.tsx
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/product-types/test/__snapshots__/index.js.snap
  client/profile-wizard/steps/product-types/test/__snapshots__/product-type.js.snap
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/style.scss
  client/store-management-links/index.js
  client/store-management-links/quick-link/index.js
  client/task-list/task-list.js
  client/task-list/tasks/payments/components/WCPaySuggestion.js
  client/task-list/tasks/tax.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/card/style.scss
  packages/components/src/compare-filter/index.js
  packages/components/src/list/style.scss
  packages/components/src/pill/pill.js
  packages/components/src/summary/number.js
  packages/components/src/table/index.js
  packages/customer-effort-score/src/customer-feedback-modal/index.tsx
  packages/experimental/README.md
  packages/experimental/src/experimental-list/task-item.tsx
  packages/onboarding/src/components/SetupRequired.js
  packages/onboarding/src/components/WCPayAcceptedMethods.js
  packages/onboarding/src/components/WCPayCard/WCPayCard.js
  readme.txt
Labels: Components, Packages, needs cherry picking, status: ready to merge

#7028 Make `getIdsFromQuery` consider `0` as a valid id.
  packages/navigation/CHANGELOG.md
  packages/navigation/README.md
  packages/navigation/src/index.js
  packages/navigation/src/test/index.js
Labels: Packages, feature: navigation, has tests, status: ready to merge

#7224 Remove old payment gateway task components
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  client/layout/index.js
  client/payments/payment-recommendations.tsx
  client/payments/test/payment-recommendations.test.tsx
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/task-list/tasks.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Action.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/List.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/List.scss
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Placeholder.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/index.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Connect.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Placeholder.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.scss
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/index.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/test/connect.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/test/setup.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/Suggestion.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/UsageModal.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/index.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/utils.js
  client/task-list/tasks/PaymentGatewaySuggestions/index.js
  client/task-list/tasks/PaymentGatewaySuggestions/plugins/Bacs.js
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/components/PaymentActionLocal.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.scss
  client/task-list/tasks/payments/components/PaymentMethodList/index.js
  client/task-list/tasks/payments/components/PaymentSetup.js
  client/task-list/tasks/payments/generic-payment-step.js
  client/task-list/tasks/payments/images/bacs.js
  client/task-list/tasks/payments/images/payu-india.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/bacs.js
  client/task-list/tasks/payments/methods/eway.js
  client/task-list/tasks/payments/methods/index.js
  client/task-list/tasks/payments/methods/klarna.js
  client/task-list/tasks/payments/methods/mercadopago.js
  client/task-list/tasks/payments/methods/mollie.js
  client/task-list/tasks/payments/methods/paypal.js
  client/task-list/tasks/payments/methods/payu-india.js
  client/task-list/tasks/payments/methods/razorpay.js
  client/task-list/tasks/payments/methods/square.js
  client/task-list/tasks/payments/methods/stripe.js
  client/task-list/tasks/payments/methods/wcpay/index.js
  client/task-list/tasks/payments/methods/wcpay/is-supported.js
  client/task-list/tasks/payments/methods/wcpay/wcpay.js
  client/task-list/test/payments.js
  config/core.json
  config/plugin.json
  readme.txt
  tests/e2e/pages/PaymentsSetup.ts
Labels: status: ready to merge

#7201 Adding tests for Payment Gateway List component
  client/task-list/tasks/PaymentGatewaySuggestions/components/Action.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/test/list.js
  readme.txt
Labels: status: ready to merge

#7261 Fix CurrencyFactory constructor to use proper function
  packages/currency/src/index.js
  readme.txt
Labels: Packages, needs cherry picking, status: ready to merge

#7257 Fix payment gateway zip folder names
  TESTING-INSTRUCTIONS.md
Labels: needs changelog entry, status: ready to merge

#7251 Fix successful gateway configuration message
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Configure.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/test/configure.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/test/setup.js
  docs/features/payment-gateway-suggestions.md
  packages/onboarding/src/components/WooPaymentGatewayConfigure/README.md
  packages/onboarding/src/components/WooPaymentGatewayConfigure/WooPaymentGatewayConfigure.js
  packages/onboarding/src/components/WooPaymentGatewayConfigure/index.js
  packages/onboarding/src/components/WooPaymentGatewayConnect/WooPaymentGatewayConnect.js
  packages/onboarding/src/components/WooPaymentGatewayConnect/index.js
  packages/onboarding/src/index.js
Labels: Packages, needs changelog entry, status: ready to merge

#7256 Make use of memoization to prevent DynamicForm re-initialization
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Configure.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js
  packages/components/src/dynamic-form/dynamic-form.tsx
  packages/onboarding/src/components/WooPaymentGatewayConfigure/README.md
Labels: Components, Packages, status: ready to merge

#7233 Feature Flags: Removed unused flags
  client/dashboard/dashboard-charts/index.js
  client/dashboard/index.js
  client/dashboard/leaderboards/index.js
  client/dashboard/store-performance/index.js
  config/core.json
  config/development.json
  config/plugin.json
  readme.txt
  src/Features/Analytics.php
  src/Features/AnalyticsDashboard.php
  src/Features/Navigation/CoreMenu.php
Labels: status: ready to merge

#7234 Analytics Flag: Remove performance indicators when disabled
  client/header/activity-panel/display-options/index.js
  client/homescreen/layout.js
  readme.txt
Labels: status: ready to merge
