Repository woocommerce/woocommerce-admin, pull requests merged in 2021-01, with the labels that each got.

#5971 Reverts work done in #4857 for automated shipping after OBW is completed
  readme.txt
  src/Features/Onboarding.php
  src/Features/OnboardingSetUpShipping.php
  src/Install.php
  src/Notes/DeprecatedNotes.php
  src/Notes/ReviewShippingSettings.php
  tests/features/class-onboarding-set-up-shipping.php
Labels: status: ready to merge

#5915 Fix/5872 nav back btn color
  client/navigation/components/container/index.js
Labels: Build, feature: navigation, needs feedback

#5969 Localize regional currency information for use during onboarding setup
  client/profile-wizard/steps/store-details/index.js
  packages/currency/package.json
  packages/currency/src/index.js
  src/Features/Onboarding.php
Labels: Build, Packages, needs feedback, status: ready to merge

#5881 Add link to update WordPress when min version not met
  src/Loader.php
Labels: feature: navigation, status: ready to merge

#5904 Update table component to use wp card
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  client/analytics/components/report-table/ie.scss
  client/analytics/components/report-table/index.js
  client/analytics/components/report-table/style.scss
  client/analytics/report/style.scss
  client/ie.scss
  client/stylesheets/abstracts/_colors.scss
  packages/components/src/chart/style.scss
  packages/components/src/table/index.js
  packages/components/src/table/stories/table-placeholder.js
  packages/components/src/table/stories/table.js
  packages/components/src/table/style.scss
Labels: Packages, feature: components, status: ready to merge

#5987 Compile debug module and remove use of flat
  babel.config.js
  webpack.config.js
Labels: Build, status: needs review

#6009 1.8.3 changelog
  readme.txt
Labels: needs cherry picking, status: needs review

#5786 A/B test creating a business features step for free extensions
  client/lib/collections/index.js
  client/lib/collections/test/index.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  client/profile-wizard/steps/business-details/data/platform-options.js
  client/profile-wizard/steps/business-details/data/product-options.js
  client/profile-wizard/steps/business-details/data/revenue-options.js
  client/profile-wizard/steps/business-details/data/segmentation.js
  client/profile-wizard/steps/business-details/data/selling-venue-options.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/app-illustration.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/business-extensions/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/style.scss
  client/profile-wizard/steps/business-details/flows/selective-bundle/style.scss
  client/profile-wizard/steps/business-details/index.js
  client/profile-wizard/steps/business-details/style.scss
  client/profile-wizard/style.scss
  client/task-list/tasks.js
  packages/components/src/form/index.js
  readme.txt
  tests/e2e/specs/activate-and-setup/complete-benefits-section.js
  tests/e2e/specs/activate-and-setup/complete-business-section.js
  tests/e2e/specs/activate-and-setup/complete-industry-section.js
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.js
  tests/e2e/specs/activate-and-setup/utils.js
Labels: Components, Packages, feature: components, feature: onboarding, status: ready to merge

#5917 Add Line-Ending Normalization to Text Files in Git
  .gitattributes
Labels: Build, status: ready to merge

#5995 Add missing text domain
  client/task-list/tasks.js
Labels: needs feedback, status: ready to merge

#5986 Reduce Unnecessary Re-renders in Revenue Report
  client/analytics/components/report-table/index.js
  client/analytics/report/revenue/table.js
  packages/data/src/reports/selectors.js
  packages/data/src/reports/utils.js
  packages/date/src/index.js
Labels: Packages, category: performance, cooldown period, feature: analytics, needs feedback

#5975 Fix task list toggle logic in help tab.
  src/Features/Onboarding.php
Labels: status: ready to merge, type: bug

#6015 Add new note for the first product and payment setup insight
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/InsightFirstProductAndPayment.php
Labels: feature: inbox, status: ready to merge

#6014 Remove HomeScreenFeedback note
  src/Events.php
  src/FeaturePlugin.php
  src/Install.php
  src/Notes/DeprecatedNotes.php
  src/Notes/HomeScreenFeedback.php
Labels: feature: inbox, status: ready to merge

#6003 Update title and content for GivingFeedbackNotes.php
  src/Notes/GivingFeedbackNotes.php
Labels: feature: inbox, status: ready to merge

#6016 Add new note for the theme marketplace
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/ChoosingTheme.php
Labels: feature: inbox, status: ready to merge

#5996 Remove visit count on track and only count uncompleted task visits
  client/task-list/index.js
  readme.txt
Labels: status: needs review

#5883 Adding history listener to update persisted queries for nav
  client/layout/controller.js
  client/layout/navigation.js
  packages/navigation/CHANGELOG.md
  packages/navigation/src/index.js
Labels: Packages, feature: navigation, status: ready to merge

#6001 Fix visual glitches on OBW when viewport is small
  client/profile-wizard/steps/product-types/style.scss
Labels: feature: onboarding, status: needs review, type: bug

#5999 Version bump to 1.9.0-dev
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#5990 Fix undefined index error
  src/API/Products.php
Labels: status: ready to merge

#5998 Show DrawAttention note after 3 days
  src/Events.php
  src/Notes/DrawAttention.php
Labels: status: ready to merge

#5997 Update onboarding email marketing note title
  src/Notes/OnboardingEmailMarketing.php
Labels: status: needs review

#6019 Add a new note when the store is 3+ days old and product count is 0
  src/Events.php
  src/Notes/AddingAndManangingProducts.php
Labels: feature: inbox, status: ready to merge

#6004 Add welcome modal when coming from Calypso
  client/homescreen/layout.js
  client/homescreen/welcome-from-calypso-modal/index.js
  client/homescreen/welcome-from-calypso-modal/style.scss
  client/homescreen/welcome-from-calypso-modal/welcome-from-calypso-modal.js
  readme.txt
  src/Features/Onboarding.php
Labels: needs feedback

#6026 Display the task components regardless of woocommerce_task_list_hidde…
  client/homescreen/layout.js
  client/task-list/index.js
Labels: feature: home screen, status: needs review

#5976 Merchant email notifications - Action triggering
  includes/emails/html-merchant-notification.php
  includes/emails/plain-merchant-notification.php
  src/API/NoteActions.php
  src/FeaturePlugin.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
  src/Notes/Notes.php
  tests/notes/class-wc-tests-email-notes.php
Labels: status: ready to merge

#6007 Add feature toggle and extensibility
  config/core.json
  src/Features/Navigation/Init.php
  src/Loader.php
Labels: feature: navigation, status: ready to merge

#6030 Add note for users coming from Calypso
  readme.txt
  src/FeaturePlugin.php
  src/Notes/WelcomeToWooCommerceForStoreUsers.php
Labels: feature: inbox, status: needs review

#5992 Set `$collate` to an empty string in case a database backend doesn't support collation
  readme.txt
  src/Install.php
Labels: needs feedback

#6024 Add your first product: email notification
  images/admin_notes/img-product-light.png
  readme.txt
  src/Events.php
  src/Notes/AddFirstProduct.php
Labels: status: ready to merge

#5929 Fix Deprecated Use of Jetpack in Shipping Label Banner
  readme.txt
  src/Features/ShippingLabelBanner.php
Labels: status: ready to merge

#6002 Remove unnecessary color override for the primary button
  client/stylesheets/shared/_global.scss
Labels: status: ready to merge, type: bug

#6047 Add an unread indicator to inbox messages based on existing logic.
  client/inbox-panel/card.js
  client/inbox-panel/style.scss
  readme.txt
Labels: feature: home screen, feature: inbox, status: ready to merge

#5970 Try: Replace Accordion with Panel component
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/style.scss
  client/homescreen/activity-panel/style.scss
  client/homescreen/activity-panel/test/index.js
  packages/components/CHANGELOG.md
  packages/components/src/accordion/README.md
  packages/components/src/accordion/index.js
  packages/components/src/accordion/panel.js
  packages/components/src/accordion/stories/index.js
  packages/components/src/accordion/style.scss
  packages/components/src/accordion/test/index.js
  packages/components/src/index.js
  packages/components/src/style.scss
Labels: Components, Packages, status: ready to merge

#5922 Add merchant email notifications
  images/admin_notes/img-product-light.png
  includes/emails/html-merchant-notification.php
  includes/emails/plain-merchant-notification.php
  packages/data/src/constants.js
  readme.txt
  src/API/NoteActions.php
  src/API/Notes.php
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/AddFirstProduct.php
  src/Notes/DeprecatedNotes.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
  src/Notes/Note.php
  src/Notes/Notes.php
  tests/framework/helpers/class-wc-helper-admin-notes.php
  tests/notes/class-wc-tests-email-notes.php
Labels: Packages, status: needs review

#6054 Restrict beta features to only those that have opted into tracking, adding modal for navigation feature
  client/wp-admin-scripts/beta-features-tracking-modal/container.js
  client/wp-admin-scripts/beta-features-tracking-modal/index.js
  client/wp-admin-scripts/beta-features-tracking-modal/style.scss
  src/Loader.php
  webpack.config.js
Labels: Build, feature: navigation, status: needs review

#6068 Apply IE fix for Array.flat
  babel.config.js
  client/task-list/list.js
  webpack.config.js
Labels: Build, status: needs review

#6048 Update the content of the ChooseNiche note.
  readme.txt
  src/Notes/ChooseNiche.php
Labels: feature: inbox, status: ready to merge

#6028 Fix for translation chunks not generated on plugin activation
  readme.txt
  src/Loader.php
Labels: status: needs review

#6067 Update travis CI to use a new distribution - xenial
  .travis.yml
  bin/travis.sh
  readme.txt
Labels: Build, status: ready to merge

#6050 Fixed error hiding core task list
  client/task-list/index.js
  client/task-list/test/index.js
  readme.txt
Labels: needs feedback, type: bug

#6071 Version bump to 2.0.0-dev
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#6065 Add missing keys to activity panel on homescreen
  client/homescreen/activity-panel/index.js
Labels: feature: home screen, status: ready to merge

#6021 Add a new note about the variable product when the owner adds the fir…
  src/FeaturePlugin.php
  src/Notes/LearnMoreAboutVariableProducts.php
  tests/notes/class-wc-tests-learn-more-about-variable-product.php
Labels: feature: inbox, needs tests, status: ready to merge

#6070 Changelog update
  readme.txt
Labels: needs cherry picking, status: needs review

#6072 New note: manage activity from home screen
  readme.txt
  src/FeaturePlugin.php
  src/Install.php
  src/Notes/ManageStoreActivityFromHomeScreen.php
Labels: needs cherry picking

#6066 Add survey URL builder method
  client/wp-admin-scripts/navigation-opt-out/container.js
  src/Features/Navigation/Init.php
  src/Notes/GivingFeedbackNotes.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationFeedbackFollowUp.php
  src/Survey.php
Labels: feature: navigation, status: ready to merge

#6076 Update content and timing of NeedSomeInspiration.php.
  readme.txt
  src/Notes/NeedSomeInspiration.php
Labels: feature: inbox, status: ready to merge

#6077 Allow for larger result sets of attribute terms
  packages/components/src/advanced-filters/attribute-filter.js
  readme.txt
Labels: Components, Packages, status: ready to merge

#6073 Add remote inbox notifications contains comparison and fix product count rule
  readme.txt
  src/RemoteInboxNotifications/ComparisonOperation.php
  src/RemoteInboxNotifications/ProductCountRuleProcessor.php
  src/RemoteInboxNotifications/README.md
  src/RemoteInboxNotifications/StoredStateSetupForProducts.php
Labels: status: ready to merge

#6094 Update store deprecation welcome modal support doc link
  client/homescreen/welcome-from-calypso-modal/welcome-from-calypso-modal.js
  readme.txt
  src/Notes/WelcomeToWooCommerceForStoreUsers.php
Labels: status: needs review

#6109 Pin WooCommerce Version in Travis Builds
  .travis.yml
Labels: Build, priority: critical, status: ready to merge

#6114 Make sure current_page has path index
  src/Features/Onboarding.php
Labels: needs cherry picking, type: bug

#6075 Disable features on tracking opt out
  src/Features/Features.php
  src/Features/Navigation/Init.php
  src/Loader.php
Labels: needs cherry picking, status: ready to merge

#6096 Fix WooCommerce mobile menu for new navigation
  packages/navigation/src/style.scss
  src/Features/Navigation/Menu.php
Labels: Packages, feature: navigation, needs cherry picking, status: ready to merge

#6117 Fix fatal error on homescreen when clicking add products task
  client/header/activity-panel/index.js
  client/task-list/index.js
Labels: status: needs review

#6046 Bump Minimum Supported PHP Version to 7.0
  .travis.yml
  composer.json
  composer.lock
  readme.txt
Labels: Build, status: ready to merge

#6086 Add the "Getting started in Ecommerce" inbox note
  readme.txt
  src/Events.php
  src/Notes/GettingStartedInEcommerceWebinar.php
  src/Notes/OnboardingTraits.php
  tests/notes/class-wc-onboarding-traits.php
Labels: feature: inbox, status: ready to merge

#6032 Add a new note a day after adding the first product
  src/Events.php
  src/Notes/CustomizingProductCatalog.php
  tests/notes/class-wc-tests-customizing-product-catalog.php
Labels: feature: inbox, has tests, status: ready to merge

#6082 Add a stale check to PRs and issues.
  .github/workflows/stale.yml
Labels: Build, status: needs review

#5926 Render SummaryNumber delta precisely.
  packages/components/src/summary/number.js
  packages/components/src/summary/stories/index.js
  readme.txt
Labels: Components, Packages, feature: components, status: ready to merge

#6139 Onboarding: Fix new business step error
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
Labels: needs cherry picking, status: ready to merge

#6140 Fix payment task styling, to match old format
  client/task-list/style.scss
  client/task-list/tasks/payments/index.js
Labels: needs cherry picking, status: ready to merge

#6102 Navigation should fold automattically after clicking link in mobile
  client/navigation/components/header/index.js
Labels: feature: navigation, status: ready to merge

#6112 Update/inconsistent button look in OBW
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/store-details/index.js
Labels: feature: onboarding, status: ready to merge

#6146 Update Jetpack Autoloader Dependency to 2.7.1
  composer.json
  composer.lock
Labels: Build, status: needs review

#6147 Go to v3 of stale action to support the arguments we're using
  .github/workflows/stale.yml
Labels: Build, status: needs review

#6149 Increase makes ops per run for the stale action to audit what will be closed
  .github/workflows/stale.yml
Labels: Build, status: needs review

#6151 Update Stale Action with Ascending Order
  .github/workflows/stale.yml
Labels: Build

#6152 Make stale bot use 60 days for PRs and issues
  .github/workflows/stale.yml
Labels: Build, status: needs review

#6116 Try: Use settings tabs filter to get setting pages for nav
  src/Features/Navigation/CoreMenu.php
Labels: feature: navigation, status: ready to merge

#6144 Disable lint of the storybook wordpress folder
  package.json
Labels: Build, status: ready to merge

#5928 Update README.md
  packages/components/src/filter-picker/README.md
Labels: Components, Packages, feature: components, status: needs review

#5892 Add option to create product by template
  client/task-list/tasks.js
  client/task-list/tasks/products/index.js
  client/task-list/tasks/products/product-template-modal.js
  client/task-list/tasks/products/product-template-modal.scss
  client/task-list/tasks/products/products.js
  client/task-list/test/products.js
  packages/components/src/list/README.md
  packages/components/src/list/index.js
  packages/components/src/list/list-item.js
  packages/data/src/items/actions.js
  packages/data/src/items/reducer.js
  readme.txt
  src/API/OnboardingTasks.php
  src/API/Templates/digital_product.csv
  src/API/Templates/physical_product.csv
  src/API/Templates/variable_product.csv
  tests/api/onboarding-tasks.php
Labels: Components, Packages, feature: onboarding, status: ready to merge

#5856 Update @wordpress/eslint-plugin dependency to latest version.
  .eslintrc.js
  .prettierrc.js
  .prettierrc.json
  bin/starter-pack/_package.json
  client/homescreen/activity-panel/reviews/test/index.js
  client/marketing/components/knowledge-base/test/index.js
  client/marketing/components/recommended-extensions/test/index.js
  package-lock.json
  package.json
  packages/components/src/chart/d3chart/utils/test/scales.js
  packages/data/src/items/test/reducer.js
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/README.md
  packages/eslint-plugin/configs/custom.js
  packages/eslint-plugin/package.json
Labels: Build, Components, Packages, needs feedback

#6154 Turn stale bot on
  .github/workflows/stale.yml
Labels: Build, status: needs review

#6179 Navigation: Change default location and add Product category items
  package-lock.json
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
  src/Features/Navigation/Screen.php
Labels: feature: navigation, needs feedback, status: ready to merge

#6178 Delete all products before running tests
  tests/api/onboarding-tasks.php
Labels: status: ready to merge

#6185 Add wait for mysql script to php unit entrypoint
  docker/wc-admin-php-test-suite/entrypoint.sh
  package.json
  readme.txt
Labels: Build, cooldown period, status: needs review

#6081 Extended task list refactor
  client/header/activity-panel/index.js
  client/header/activity-panel/test/index.js
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/task-list/index.js
  client/task-list/list.js
  client/task-list/test/index.js
  docs/examples/extensions/add-task/js/index.js
  docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  tests/features/class-wc-tests-task-lists.php
Labels: category: refactor, status: ready to merge

#6188 Return countryInfo as an empty object if not in locale info
  packages/currency/src/index.js
Labels: Packages, needs cherry picking, status: ready to merge

#6182 Hide Inventory and Reviews panels if store setup task list is visible
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/test/panels.js
  client/homescreen/test/index.js
Labels: needs cherry picking, status: needs review, type: bug

#6205 Normalize installed WC Admin version
  src/Notes/ManageStoreActivityFromHomeScreen.php
Labels: needs cherry picking, status: ready to merge, type: bug

#6196 Add unit test for CES package
  packages/customer-effort-score/src/index.js
  packages/customer-effort-score/src/test/index.js
Labels: Packages, feature: customer effort score, status: ready to merge

#6209 Skip failing tests in WP 5.3 and 5.4
  tests/api/reports-orders-stats.php
  tests/api/reports-orders.php
Labels: needs feedback, type: bug

#6169 Remove unnecessary if statement
  bin/install-wp-tests.sh
Labels: Build, status: ready to merge

#6200 Change siteUrl to shopUrl
  client/store-management-links/index.js
  src/Loader.php
Labels: status: needs review

#6122 Move inbox panel to left column, to increase user interaction
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/inbox-panel/placeholder.js
  client/inbox-panel/style.scss
  readme.txt
Labels: feature: home screen, status: ready to merge

#6097 Remove old debug code for connecting to Calypso / WordPress.com in help section
  readme.txt
  src/Features/Onboarding.php
Labels: status: ready to merge

#6222 Replaced method `woocommerce_get_page_id` with `wc_get_page_id`
  src/Loader.php
Labels: status: ready to merge

#6220 Hide Home screen panels if store setup task list is visible
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/test/panels.js
Labels: status: ready to merge

#6177 Update product template icon and copy
  client/task-list/style.scss
  client/task-list/tasks/products/products.js
  client/task-list/test/products.js
  package-lock.json
  package.json
Labels: Build, feature: onboarding, status: ready to merge
