Repository woocommerce/woocommerce-admin, pull requests merged in 2021-03, with the labels that each got.

#6469 Skip a test that is currently broken till we can find the cause.
  packages/date/test/index.js
Labels: Packages

#6441 Clean up unused deps and add TS to the build
  .eslintrc.js
  bin/changelog/README.md
  bin/changelog/common/get-entry.js
  bin/changelog/common/index.js
  bin/changelog/common/make.js
  bin/changelog/config.js
  bin/changelog/github/index.js
  bin/changelog/github/make-change-log.js
  bin/changelog/github/requests.js
  bin/changelog/index.js
  bin/changelog/zenhub/index.js
  bin/changelog/zenhub/make-change-log.js
  bin/changelog/zenhub/requests.js
  package-lock.json
  package.json
  packages/README.md
  packages/components/package.json
  packages/csv-export/package.json
  packages/currency/package.json
  packages/customer-effort-score/package.json
  packages/data/package.json
  packages/date/package.json
  packages/navigation/package.json
  packages/number/package.json
  packages/tracks/package.json
  tsconfig.json
  webpack.config.js
Labels: Build, Components, Packages, status: ready to merge

#6470 Dates: Account for leat year in `getLastPeriod`
  packages/date/CHANGELOG.md
  packages/date/src/index.js
  packages/date/test/index.js
Labels: Packages, needs changelog entry, status: ready to merge

#6115 Add exclusion on getOptions and method renaming
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  packages/components/src/select-control/control.js
  packages/components/src/select-control/index.js
Labels: Components, Packages, status: ready to merge

#6413 Update payment card style on mobile
  TESTING-INSTRUCTIONS.md
  client/task-list/style.scss
  readme.txt
Labels: status: ready to merge

#5913 Fix summary number style regression on analytics reports
  TESTING-INSTRUCTIONS.md
  client/dashboard/store-performance/style.scss
  packages/components/src/summary/style.scss
  readme.txt
Labels: Components, Packages, feature: components, status: ready to merge

#6409 Add navigation favorites tests
  readme.txt
  tests/navigation/class-wc-favorites.php
Labels: cooldown period, feature: navigation, status: ready to merge

#6460 Fix double prefixing of navigation URLs
  TESTING-INSTRUCTIONS.md
  client/navigation/test/utils.js
  client/navigation/utils.js
  readme.txt
Labels: cooldown period, feature: navigation, needs changelog entry, status: ready to merge

#6446 Add nav favorite button tests
  client/navigation/components/favorite-button/test/index.js
  readme.txt
Labels: cooldown period, feature: navigation, status: ready to merge

#6448 Add docker setup using WP-ENV
  .gitignore
  .wp-env.json
  README.md
  docker/wc-admin-wp-env/README.md
  docker/wc-admin-wp-env/mysql-port.js
  package.json
  readme.txt
Labels: Build, cooldown period, status: ready to merge

#6475 Add a new revenue option, 'rather not say'
  client/profile-wizard/steps/business-details/data/revenue-options.js
  readme.txt
  src/API/OnboardingProfile.php
Labels: status: ready to merge

#6493 Use static images for nav intro modal
  client/navigation/components/intro-modal/images/nav-intro-1.png
  client/navigation/components/intro-modal/images/nav-intro-2.png
  client/navigation/components/intro-modal/images/nav-intro-3.png
  client/navigation/components/intro-modal/index.js
Labels: feature: navigation, needs changelog entry, needs cherry picking, status: ready to merge

#6397 Add a back button to the Header when the task list is displayed.
  TESTING-INSTRUCTIONS.md
  client/header/index.js
  client/header/style.scss
  client/header/test/index.js
  readme.txt
Labels: needs feedback

#6492 Add initial tests for navigation Menu class
  readme.txt
  src/Features/Navigation/Menu.php
  tests/navigation/class-wc-menu.php
Labels: cooldown period, feature: navigation, status: ready to merge

#6486 Remove active item from navigation store
  client/navigation/components/container/index.js
  packages/data/src/navigation/action-types.js
  packages/data/src/navigation/actions.js
  packages/data/src/navigation/reducer.js
  packages/data/src/navigation/selectors.js
  packages/data/src/navigation/test/reducer.js
  readme.txt
Labels: Packages, feature: navigation, status: ready to merge

#6472 Fixed a few console errors in JS tests
  client/dashboard/components/connect/test/index.js
  client/homescreen/activity-panel/stock/test/index.js
  packages/components/src/plugins/test/index.js
Labels: Components, Packages, cooldown period, status: ready to merge

#6445 Add category title tests
  client/navigation/components/category-title/index.js
  client/navigation/components/category-title/test/index.js
Labels: cooldown period, feature: navigation, needs changelog entry, status: ready to merge

#6507 Add legacy report items to new navigation
  TESTING-INSTRUCTIONS.md
  client/navigation/style.scss
  readme.txt
  src/Features/Navigation/CoreMenu.php
Labels: feature: navigation, status: ready to merge

#6453 Added warning when WC-Admin is active but not being used
  readme.txt
  src/Loader.php
Labels: cooldown period, status: ready to merge

#6509 Add nav header component tests
  client/navigation/components/header/test/index.js
  readme.txt
Labels: cooldown period, feature: navigation, status: ready to merge

#6510 Remove Mollie promo note on install
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Install.php
Labels: status: ready to merge

#6040 Add remote inbox notifications rule that triggers when WCA is updated
  readme.txt
  src/RemoteInboxNotifications/GetRuleProcessor.php
  src/RemoteInboxNotifications/README.md
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
  src/RemoteInboxNotifications/WooCommerceAdminUpdatedRuleProcessor.php
Labels: status: ready to merge

#6513 add preview site btn in personalize store task
  TESTING-INSTRUCTIONS.md
  client/header/activity-panel/index.js
  readme.txt
Labels: feature: onboarding, needs changelog entry, status: needs review

#6464 Add navigation container tests
  TESTING-INSTRUCTIONS.md
  client/header/test/index.js
  client/navigation/components/container/index.js
  client/navigation/components/container/test/index.js
  readme.txt
Labels: cooldown period, feature: navigation, status: ready to merge

#6505 Adding client-side filter to navigation root url
  client/navigation/components/container/primary-menu.js
  readme.txt
  src/Features/Navigation/Menu.php
Labels: feature: navigation, status: ready to merge, type: enhancement

#6508 Update/6487 target audience of business feature step
  TESTING-INSTRUCTIONS.md
  client/layout/index.js
  client/profile-wizard/steps/business-details/data/segmentation.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/index.js
  client/task-list/tasks.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/wcpay/index.js
  client/task-list/tasks/payments/wcpay/install-activate-and-connect.js
  client/task-list/tasks/payments/wcpay/is-supported.js
  client/task-list/tasks/payments/wcpay/wcpay-usage-modal.js
  client/task-list/tasks/payments/wcpay/wcpay.js
  config/core.json
  config/development.json
  config/plugin.json
  readme.txt
  tests/e2e/specs/activate-and-setup/complete-business-section.js
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.js
  tests/e2e/specs/activate-and-setup/homescreen.js
Labels: status: ready to merge

#6540 Fix a bug in useSettings that causes an infinite loop.
  packages/data/src/settings/use-settings.js
  readme.txt
Labels: Packages, needs cherry picking

#6539 Remove mobile activity panel toggle
  client/header/activity-panel/index.js
  client/header/activity-panel/panel.js
  client/header/activity-panel/style.scss
  readme.txt
Labels: feature: activity panel, status: ready to merge

#6503 Store profiler: Business Details steps changes
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  images/onboarding/mailpoet.png
  packages/data/src/plugins/constants.js
  readme.txt
  src/API/OnboardingProfile.php
  src/Features/Onboarding.php
Labels: Packages, feature: onboarding, status: ready to merge

#6428 Fixed associated Order Number for refunds
  TESTING-INSTRUCTIONS.md
  client/analytics/components/report-table/index.js
  readme.txt
  src/API/Reports/Controller.php
  src/API/Reports/Orders/DataStore.php
  tests/reports/class-wc-tests-reports-orders.php
Labels: feature: analytics, has tests, status: ready to merge, type: bug

#6532 Add Guards to "Deactivate Plugin" Note Handlers
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Composer/Package.php
Labels: needs cherry picking, status: ready to merge

#6525 Use wc filter to get status tabs for tools category
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/Navigation/CoreMenu.php
Labels: cooldown period, feature: navigation, status: ready to merge

#6543 Add testing instructions for mobile header toggle changes
  TESTING-INSTRUCTIONS.md
Labels: needs changelog entry, status: ready to merge

#6526 Change "Store Setup" link in top bar to "Finish setup"
  client/header/activity-panel/index.js
  client/header/activity-panel/test/index.js
Labels: needs feedback

#6518 Add nav intro modal tests
  client/navigation/components/intro-modal/index.js
  client/navigation/components/intro-modal/test/index.js
  readme.txt
Labels: cooldown period, feature: navigation, status: ready to merge

#6541 Fix renovate bot check in changelog lint
  .github/workflows/lint-changelog.yml
Labels: Build, needs changelog entry, status: needs review

#6553 Never skip changelog labelling, default to remove label.
  .github/workflows/lint-changelog.yml
Labels: Build

#6517 Add tilde (~) option for client root directory
  .eslintrc.js
  client/profile-wizard/steps/business-details/data/revenue-options.js
  client/profile-wizard/steps/business-details/data/segmentation.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  package-lock.json
  package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/rules/dependency-group.js
  readme.txt
  tests/js/jest.config.json
  tsconfig.json
  webpack.config.js
Labels: Build, Packages, status: ready to merge

#6515 Business features step: include Mailpoet
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
  tests/e2e/specs/activate-and-setup/complete-business-section.js
Labels: Packages, feature: onboarding, status: needs review

#6520 Remove rest API props from onboarding confirmed as no longer used.
  readme.txt
  src/API/OnboardingProfile.php
  tests/api/onboarding-profile.php
Labels: status: needs review

#6557 Docs: Fix wrong filename for feature config
  docs/features/feature-flags.md
Labels: status: ready to merge, type: documentation

#6559 Add Ireland to Square payment method
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/methods.js
  readme.txt
Labels: feature: setup checklist, status: ready to merge

#6420 Add CES survey for search product, order, customer
  TESTING-INSTRUCTIONS.md
  client/analytics/components/report-table/index.js
  client/customer-effort-score-tracks/data/actions.js
  client/customer-effort-score-tracks/data/reducer.js
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
Labels: feature: customer effort score, status: needs review

#6419 Add CES survey for importing products
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
Labels: feature: customer effort score, status: ready to merge

#6418 Add CES survey for adding product categories, tags, and attributes
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
Labels: feature: customer effort score, status: ready to merge

#6562 Fix hidden menu title on smaller screens
  TESTING-INSTRUCTIONS.md
  client/navigation/style.scss
  readme.txt
Labels: feature: navigation, status: ready to merge

#6576 Fix CI issues
  .github/workflows/e2e.yml
  .github/workflows/test-php.yml
Labels: Build, status: ready to merge

#6521 Fix a bug where the JP connection flow would not activate
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/index.js
  readme.txt
  src/API/OnboardingProfile.php
  tests/api/onboarding-profile.php
Labels: Build, needs cherry picking, status: needs review

#6399 Move Lodash to a Peer Dependency in Packages
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/notices/CHANGELOG.md
  packages/notices/package.json
Labels: Build, Components, Packages, status: ready to merge

#6577 Allow manager role to query options
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Options.php
Labels: status: ready to merge, type: bug, type: task

#6544 Add Google Analytics tracking to layout.
  index.html
Labels: status: ready to merge

#6567 Add gross sales column to CSV export
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Reports/Revenue/Stats/Controller.php
Labels: status: ready to merge

#6587 Prepare Documentation for 2.1.3 release
  TESTING-INSTRUCTIONS.md
  readme.txt
Labels: needs cherry picking, status: ready to merge

#6565 Update undefined task name properties for help panel tracks
  TESTING-INSTRUCTIONS.md
  client/header/activity-panel/panels/help.js
  readme.txt
Labels: feature: activity panel, status: ready to merge

#6556 Add customer name column to CSV export
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Reports/Orders/Controller.php
Labels: needs feedback

#6566 Close activity panel tabs by default and track
  TESTING-INSTRUCTIONS.md
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/panels.js
  readme.txt
Labels: feature: activity panel, status: ready to merge

#6564 Add filter to profile wizard steps
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#6583 Refactor profile wizard benefits step and add tests
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/benefit.js
  client/profile-wizard/steps/benefits/benefits.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/benefits/test/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#6563 Loader::is_admin_page() throws fatal error if woocommerce_admin_disabled is true.
  readme.txt
  src/Loader.php
Labels: status: ready to merge

#6454 Hook Reference: Automate a reference resource
  .eslintrc.js
  bin/hook-reference/data.js
  bin/hook-reference/data.json
  bin/hook-reference/index.js
  client/homescreen/stats-overview/defaults.js
  package-lock.json
  package.json
  readme.txt
Labels: Build, status: ready to merge

#6554 Adjust targeting store age: 2 - 5 days for the Add First Product note
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Notes/AddFirstProduct.php
Labels: feature: inbox, status: ready to merge

#6547 Improve WC Shipping & Tax logic
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
  packages/data/src/plugins/constants.js
  readme.txt
  tests/e2e/specs/activate-and-setup/complete-business-section.js
Labels: Packages, feature: onboarding, status: ready to merge

#6555 Update insight inbox message and add no option
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Notes/InsightFirstProductAndPayment.php
Labels: feature: inbox, status: ready to merge

#6582 Add Typescript and page objects to E2E suite
  .eslintrc.js
  babel.config.js
  bin/wait-for-build.sh
  package-lock.json
  package.json
  readme.txt
  tests/e2e/config/jest.config.js
  tests/e2e/constants/taskTitles.ts
  tests/e2e/models/DropdownField.ts
  tests/e2e/models/DropdownTypeaheadField.ts
  tests/e2e/models/OnboardingWizard.ts
  tests/e2e/models/WcHomescreen.ts
  tests/e2e/models/WcSettings.ts
  tests/e2e/models/WpSettings.ts
  tests/e2e/models/onboarding/BenefitsSection.ts
  tests/e2e/models/onboarding/BusinessSection.ts
  tests/e2e/models/onboarding/IndustrySection.ts
  tests/e2e/models/onboarding/ProductTypesSection.ts
  tests/e2e/models/onboarding/StoreDetailsSection.ts
  tests/e2e/models/onboarding/ThemeSection.ts
  tests/e2e/specs/activate-and-setup/complete-benefits-section.js
  tests/e2e/specs/activate-and-setup/complete-business-section.js
  tests/e2e/specs/activate-and-setup/complete-business-section.ts
  tests/e2e/specs/activate-and-setup/complete-industry-section.js
  tests/e2e/specs/activate-and-setup/complete-industry-section.ts
  tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.ts
  tests/e2e/specs/activate-and-setup/complete-product-types-section.js
  tests/e2e/specs/activate-and-setup/complete-product-types-section.ts
  tests/e2e/specs/activate-and-setup/complete-store-details-section.js
  tests/e2e/specs/activate-and-setup/complete-store-details-section.ts
  tests/e2e/specs/activate-and-setup/complete-theme-selection-section.js
  tests/e2e/specs/activate-and-setup/complete-theme-selection-section.ts
  tests/e2e/specs/activate-and-setup/homescreen.js
  tests/e2e/specs/activate-and-setup/setup-wizard.test.ts
  tests/e2e/specs/activate-and-setup/utils.js
  tests/e2e/specs/globalTypes.ts
  tests/e2e/utils/actions.js
  tests/e2e/utils/actions.ts
  tests/e2e/utils/constants.ts
  tests/e2e/utils/flows.js
  tests/e2e/utils/flows.ts
  tests/e2e/utils/lib.js
  tsconfig.json
  typings/index.d.ts
Labels: Build, status: ready to merge

#6575 Add tracking for the business step
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: status: ready to merge

#6574 Delete customer data on network user deletion
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Schedulers/CustomersScheduler.php
Labels: status: needs review

#6579 Added paystack to payment methods for african countries
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/generic-payment-step.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/payfast.js
  client/task-list/test/payments.js
  images/onboarding/paystack.png
  readme.txt
  src/Features/Onboarding.php
Labels: status: ready to merge

#6504 Update contrast and hover / active colors for analytics dropdown buttons
  TESTING-INSTRUCTIONS.md
  packages/components/src/dropdown-button/style.scss
  readme.txt
Labels: Components, Packages, Trash Pickup, category: accessibility, feature: analytics, feature: components, status: ready to merge

#6622 Set default value to array when op is 'contains'
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/RemoteInboxNotifications/OptionRuleProcessor.php
Labels: feature: inbox, status: ready to merge

#6578 Fix "Themes" step visibility bug in IE 11
  TESTING-INSTRUCTIONS.md
  client/ie.scss
  client/profile-wizard/steps/theme/style.scss
  readme.txt
Labels: feature: onboarding, status: ready to merge, type: bug

#6572 Payments task: include Mercado Pago
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/mercadopago.js
  client/task-list/tasks/payments/methods.js
  client/task-list/test/payments.js
  images/onboarding/mercadopago.png
  packages/data/src/plugins/constants.js
  readme.txt
  src/Features/Onboarding.php
Labels: Packages, needs feedback

#6635 Ensure script asset.php files are included in builds
  bin/make-zip.sh
  readme.txt
Labels: Build, needs cherry picking, status: ready to merge

#6624 Adding typescript resolver to fix linting issues with imports
  package.json
Labels: Build, status: needs review

#6542 Remove hardcoded dependencies from examples.
  docs/examples/extensions/add-navigation-items/woocommerce-admin-add-navigation-items-example.php
  docs/examples/extensions/add-report/woocommerce-admin-add-report-example.php
  docs/examples/extensions/add-task/js/index.js
  docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php
  docs/examples/extensions/dashboard-section/woocommerce-admin-dashboard-section.php
  docs/examples/extensions/examples.config.js
  docs/examples/extensions/important-admin-notice/woocommerce-admin-important-admin-notice-example.php
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
  docs/examples/extensions/table-column/woocommerce-admin-table-column.php
  package.json
Labels: Build, needs feedback

#6640 Remove CI tests for WooCommerce 4.7
  .github/workflows/test-php.yml
Labels: Build, status: ready to merge

#6641 Remove Composer v1 Downgrade in PHP Tests
  bin/install-wp-tests.sh
Labels: Build, status: ready to merge

#6649 Add IE and NZ to the selective bundle install list
  client/profile-wizard/steps/business-details/data/segmentation.js
  readme.txt
Labels: needs cherry picking, needs feedback

#6595 Fix TypeScript build for `packages` and add types for wc/data's onboarding store
  bin/packages/build.js
  bin/packages/get-babel-config.js
  client/dashboard/index.js
  client/homescreen/index.tsx
  package-lock.json
  package.json
  packages/data/package.json
  packages/data/src/export/constants.ts
  packages/data/src/import/constants.ts
  packages/data/src/index.js
  packages/data/src/index.ts
  packages/data/src/items/constants.ts
  packages/data/src/navigation/constants.ts
  packages/data/src/notes/constants.ts
  packages/data/src/onboarding/constants.ts
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/selectors.js
  packages/data/src/onboarding/selectors.ts
  packages/data/src/onboarding/test/reducer.js
  packages/data/src/options/constants.ts
  packages/data/src/plugins/constants.ts
  packages/data/src/reports/constants.ts
  packages/data/src/reviews/constants.ts
  packages/data/src/settings/constants.ts
  packages/data/src/types.ts
  packages/data/src/user/constants.ts
  tests/js/jest.config.json
  typings/index.d.ts
  webpack.config.js
Labels: Build, Packages, status: ready to merge

#6653 Add some guidelines on changelog and testing instructions.
  CONTRIBUTING.md
Labels: Build, status: ready to merge

#6656 Revert "Add Ireland to Square payment method (#6559)"
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/methods.js
  readme.txt
Labels: needs cherry picking

#6658 Add Tests for Database Table Creation
  tests/install.php
Labels: status: ready to merge

#6645 Check if value for contains comparison is an array
  readme.txt
  src/Features/OnboardingTasks.php
  src/RemoteInboxNotifications/OptionRuleProcessor.php
  tests/remote-inbox-notifications/option-rule-processor.php
Labels: Build, status: ready to merge

#6677 Update the mercado option name, so it enables correctly
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/test/payments.js
  readme.txt
  src/Features/Onboarding.php
Labels: needs cherry picking, status: ready to merge

#6657 Show management links when the task list is complete (even if its not hidden).
  client/homescreen/layout.js
  client/homescreen/test/index.js
  readme.txt
Labels: needs cherry picking, status: ready to merge

#6661 Bump main to 2.3.0-dev
  TESTING-INSTRUCTIONS.md
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#6679 Fix the activity panel toggle not closing on click
  client/header/activity-panel/index.js
  client/header/activity-panel/panel.js
  client/header/activity-panel/style.scss
  readme.txt
Labels: needs changelog entry, needs cherry picking, status: ready to merge, type: bug

#6610 Next new novel navigation nudge note
  readme.txt
  src/Events.php
  src/FeaturePlugin.php
  src/Features/Features.php
  src/Features/Navigation/Init.php
  src/Notes/NavigationNudge.php
Labels: feature: navigation, needs changelog entry, needs cherry picking, status: ready to merge

#6617 Improve AddFirstProduct email note contents
  TESTING-INSTRUCTIONS.md
  images/admin_notes/dashboard-widget-setup.png
  images/admin_notes/openbox+purple.png
  includes/emails/html-merchant-notification.php
  readme.txt
  src/Notes/AddFirstProduct.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
  tests/notes/class-wc-tests-email-notes.php
Labels: feature: inbox, needs cherry picking, status: ready to merge

#6681 Build: Fix production script asset names
  readme.txt
  src/Features/Coupons.php
  src/Features/Navigation/Init.php
  src/Features/OnboardingTasks.php
  src/Features/ShippingLabelBanner.php
  src/Loader.php
Labels: Build, needs changelog entry, needs cherry picking, status: needs review

#6670 Fix Database Table Creation Test
  tests/install.php
Labels: status: ready to merge

#6672 Update Customer Effort Score changelog
  packages/customer-effort-score/CHANGELOG.md
Labels: Packages, status: ready to merge

#6688 Check if features are currently being enabled
  readme.txt
  src/Features/Features.php
Labels: feature: navigation, needs changelog entry, needs cherry picking, status: ready to merge, type: bug

#6687 Fix use of feature checks and remove deprecated method calls
  docs/features/feature-flags.md
  includes/connect-existing-pages.php
  readme.txt
  src/Events.php
  src/Features/Coupons.php
  src/Features/CouponsMovedTrait.php
  src/Features/Marketing.php
  src/Loader.php
  src/Notes/CouponPageMoved.php
  src/Notes/NavigationFeedback.php
  src/Notes/NavigationFeedbackFollowUp.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
Labels: feature: navigation, needs changelog entry, needs cherry picking

#6616 Fixed event tracking for merchant email notes
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/API/Notes.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
Labels: feature: inbox, status: ready to merge

#6620 #6600 Add marginBottom setup wizard container
  client/profile-wizard/style.scss
  readme.txt
Labels: Build

#6498 Add TypeScript to CustomerFeedbackModal
  package-lock.json
  package.json
  packages/customer-effort-score/package.json
  packages/customer-effort-score/src/customer-feedback-modal/index.tsx
  readme.txt
Labels: Build, Packages, status: needs review

#6623 Add track data for the preview site btn
  client/header/activity-panel/index.js
  readme.txt
Labels: feature: activity panel, status: ready to merge

#6647 Fix variation bug with Products reports
  TESTING-INSTRUCTIONS.md
  client/analytics/report/variations/table.js
  readme.txt
Labels: feature: analytics, status: ready to merge, type: bug

#6706 Bump PHP Test Version to 7.0 in PHPCS config
  phpcs.xml.dist
Labels: status: ready to merge

#6705 Fix Various PHP Lint Errors
  src/Features/OnboardingTasks.php
  src/Notes/InsightFirstProductAndPayment.php
  tests/install.php
Labels: status: ready to merge
