Repository woocommerce/woocommerce-admin, pull requests merged in 2021-08, with the labels that each got.

#7436 Add additional countries to WCPay for business features and payment task fallback
  changelogs/update-7295-wcpay-add-more-countries
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/utils.js
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: needs cherry picking, status: ready to merge

#7419 Separate installed plugins from plugin lists
  changelogs/add-7314
  client/task-list/tasks/Marketing/Marketing.scss
  client/task-list/tasks/Marketing/Plugin.scss
  client/task-list/tasks/Marketing/Plugin.tsx
  client/task-list/tasks/Marketing/PluginList.scss
  client/task-list/tasks/Marketing/PluginList.tsx
  client/task-list/tasks/Marketing/index.tsx
Labels: needs changelog entry, status: ready to merge

#7420 Add free extensions data store
  client/task-list/tasks/Marketing/index.tsx
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
Labels: Packages, needs changelog entry, status: ready to merge

#7447 refactor: payment recommendations eligibility
  changelogs/refactor-payment-recommendations-eligibiility
  client/payments/payment-recommendations-wrapper.tsx
  client/payments/payment-recommendations.tsx
  client/payments/test/payment-recommendations.test.tsx
  client/settings-recommendations/recommendations-eligibility-wrapper.tsx
  client/settings-recommendations/test/recommendations-eligibility-wrapper.test.js
Labels: status: ready to merge

#7429 Fix/7427 collapsible list transition
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/collapsible-list/index.tsx
  packages/experimental/src/experimental-list/task-item.tsx
Labels: Packages, status: ready to merge

#7408 Update outgoing woocommerce.com links to include `utm_medium=product`
  changelogs/dev-add-utm-medium
  client/dashboard/components/cart-modal.js
  client/header/activity-panel/panels/help.js
  client/marketing/components/knowledge-base/ReadBlogMessage.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/usage-modal.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/UsageModal.js
  client/task-list/tasks/products/products.js
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/tax.js
  client/wp-admin-scripts/beta-features-tracking-modal/container.js
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  packages/onboarding/src/components/WCPayCard/WCPayCard.js
  src/Features/Marketing.php
  src/Features/Onboarding.php
  src/Marketing/InstalledExtensions.php
  src/Notes/AddFirstProduct.php
  src/Notes/AddingAndManangingProducts.php
  src/Notes/ChooseNiche.php
  src/Notes/ChoosingTheme.php
  src/Notes/ConfirmTaxSettings.php
  src/Notes/CustomizeStoreWithBlocks.php
  src/Notes/CustomizingProductCatalog.php
  src/Notes/DrawAttention.php
  src/Notes/EUVATNumber.php
  src/Notes/EditProductsOnTheMove.php
  src/Notes/FilterByProductVariationsInReports.php
  src/Notes/FirstDownlaodableProduct.php
  src/Notes/LaunchChecklist.php
  src/Notes/LearnMoreAboutVariableProducts.php
  src/Notes/ManageOrdersOnTheGo.php
  src/Notes/ManageStoreActivityFromHomeScreen.php
  src/Notes/MigrateFromShopify.php
  src/Notes/MobileApp.php
  src/Notes/NeedSomeInspiration.php
  src/Notes/OnboardingPayments.php
  src/Notes/OnlineClothingStore.php
  src/Notes/OrderMilestones.php
  src/Notes/PerformanceOnMobile.php
  src/Notes/RealTimeOrderAlerts.php
  src/Notes/SellingOnlineCourses.php
  src/Notes/StartDropshippingBusiness.php
  src/Notes/TrackingOptIn.php
  src/Notes/WooCommercePayments.php
  src/Notes/WooCommerceSubscriptions.php
  src/Notes/WooSubscriptionsNotes.php
Labels: Packages, needs feedback, status: ready to merge

#7456 Bump version to 2.7.0-dev
  TESTING-INSTRUCTIONS.md
  changelog.txt
  changelogs/fix-7339-home-crashes-after-disabling-analytics-feature
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#7454 Delete free extensions transient on WCA update
  client/task-list/tasks.js
  config/core.json
  config/development.json
  config/plugin.json
  src/Features/RemoteFreeExtensions/Init.php
Labels: needs changelog entry, status: ready to merge

#7451 Add marketing task completion check and tests
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/Marketing/index.tsx
  client/task-list/tasks/Marketing/test/index.tsx
Labels: needs changelog entry, needs feedback

#7452 Update business details to use extensions data store
  changelogs/update-business-details-extensions-data-store
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
  src/Features/RemoteFreeExtensions/EvaluateExtension.php
  src/Features/RemoteFreeExtensions/Init.php
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7457 Add Missing Changelog Entries for 2.4.x
  changelog.txt
Labels: status: ready to merge

#7467 Add tracks to marketing manage button click
  client/task-list/tasks/Marketing/Plugin.tsx
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7466 Add default marketing extensions as fallbacks
  images/onboarding/creative-mail-by-constant-contact.png
  images/onboarding/google-listings-and-ads.png
  images/onboarding/mailchimp-for-woocommerce.png
  images/onboarding/mailpoet.png
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7460 Don't show the marketing task if no marketing tasks exist
  client/task-list/tasks.js
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7469 Sync changelog to 2.6.0-beta.2
  changelog.txt
Labels: status: ready to merge

#7465 Replace first occurrence of the bullet char only
  bin/changelogger/WCAdminFormatter.php
Labels: status: ready to merge, Build

#7464 Add changelog.txt when creating a zip file.
  bin/make-zip.sh
Labels: status: ready to merge, Build

#7431 Update component Table to align texts and numeric a bit smarter
  changelogs/update-table-align-isNumeric
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  packages/components/CHANGELOG.md
  packages/components/src/table/README.md
  packages/components/src/table/table.js
  packages/components/src/table/test/index.js
Labels: status: ready to merge, feature: components, Packages, Components

#7483 Fix all links with hash to behind query parameters
  changelogs/fix-7477-link-hash-issue
  client/header/activity-panel/panels/help.js
  client/task-list/tasks/tax.js
  src/Notes/FilterByProductVariationsInReports.php
Labels: status: ready to merge

#7482 Fix blank screen on analytics categories when searching
  changelogs/fix-7473-blank-screen-search-categories
  client/analytics/report/index.js
Labels: status: ready to merge

#7475 Make sure defaultSections is a unique object, so we do not remove icon
  changelogs/fix-7350_modifying_overview_screen
  client/dashboard/customizable.js
Labels: status: ready to merge, needs cherry picking

#7490 Fix up onboarding profiler not working when opted out of tracking
  changelogs/fix-7487
  src/Features/Features.php
  src/Features/Onboarding.php
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7489 Add super admin check to preloaded user data
  changelogs/fix-7397
  packages/data/src/user/use-user.js
  src/Loader.php
Labels: status: ready to merge, Packages, needs cherry picking, needs changelog entry

#7488 Set padding: 0 to override Gutenberg style
  changelogs/fix-7479-home-style-issue
  client/homescreen/style.scss
Labels: status: ready to merge, needs feedback, needs cherry picking

#7485 Add rimraf dev dependency to admin-e2e-tests package
  packages/admin-e2e-tests/package.json
Labels: status: ready to merge, Build, Packages

#7492 Prepare Packages for Publishing
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: status: ready to merge, Build, Packages, Components, needs changelog entry

#7338 Remove the preloaded onboarding options
  changelogs/remove-onboarding-preload
  client/homescreen/layout.js
  client/homescreen/test/index.js
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/usage-modal.js
  client/task-list/index.js
  client/task-list/tasks/tax.js
  client/task-list/test/index.js
  docs/features/onboarding.md
  package-lock.json
  package.json
  packages/admin-e2e-tests/src/pages/OnboardingWizard.ts
  packages/admin-e2e-tests/src/pages/PaymentsSetup.ts
  packages/admin-e2e-tests/src/pages/WcHomescreen.ts
  packages/admin-e2e-tests/src/specs/tasks/payment.ts
  packages/admin-e2e-tests/src/utils/actions.ts
  packages/admin-e2e-tests/typings/index.d.ts
  src/Features/Onboarding.php
Labels: status: ready to merge, Build, Packages, cooldown period, needs changelog entry

#7493 Add missing : in the changelog
  changelog.txt
Labels: status: ready to merge

#7494 Add missing ---> tag in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: ready to merge, Build

#7446 feat: add shipping marketplace recommendations
  changelogs/feat-add-shipping-settings-plugins-recommendations
  client/embedded-body-layout/embedded-body-layout.tsx
  client/embedded-body-layout/embedded-body-props.ts
  client/settings-recommendations/dismissable-list.scss
  client/settings-recommendations/dismissable-list.tsx
  client/settings-recommendations/test/dismissable-list.test.js
  client/shipping/index.ts
  client/shipping/shipping-recommendations-wrapper.tsx
  client/shipping/shipping-recommendations.scss
  client/shipping/shipping-recommendations.tsx
  client/shipping/test/shipping-recommendations.test.js
  client/shipping/woo-icon.svg
  client/shipping/woocommerce-services-item.scss
  client/shipping/woocommerce-services-item.tsx
Labels: needs feedback

#7471 Split the Extensions page into Marketplace and My Subscriptions.
  changelogs/update-7471-split-extensions-pages
  includes/connect-existing-pages.php
Labels: status: ready to merge, needs cherry picking

#6584 Fix end date for last periods
  TESTING-INSTRUCTIONS.md
  changelogs/fix-6471
  packages/date/src/index.js
  packages/date/src/test/index.js
Labels: status: ready to merge, Packages, needs feedback

#6506 Update analytics card header text styles
  changelogs/update-analytics-card-hearder-styles
  client/analytics/components/leaderboard/index.js
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  client/analytics/components/leaderboard/test/index.js
  client/dashboard/dashboard-charts/block.js
  client/header/activity-panel/activity-header/index.js
  packages/components/src/chart/style.scss
  packages/components/src/table/index.js
Labels: status: needs review, feature: analytics, Packages, Components, Trash Pickup

#7506 Set default value for orders var
  changelogs/fix-7504-blank-screen-when-actionable-status-are-disabled
  client/homescreen/activity-panel/orders/index.js
Labels: type: bug, status: needs review, needs cherry picking, feature: home screen

#7426 Making business details sticky in OBW
  TESTING-INSTRUCTIONS.md
  changelogs/fix-6718
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
Labels: status: ready to merge, needs feedback, needs changelog entry

#7524 Add missing single quote
  src/Notes/NeedSomeInspiration.php
Labels: type: bug, status: ready to merge, needs cherry picking

#7511 Update changelog
  changelog.txt
  changelogs/fix-7504-blank-screen-when-actionable-status-are-disabled
Labels: status: ready to merge

#7526 Fix broken PHP linter workflow
  bin/phpcs.sh
Labels: status: ready to merge, Build

#7532 Bump the fallback WP version to 5.8.0 in E2E
  .github/workflows/e2e.yml
Labels: status: ready to merge, Build

#7533 Add woo_country_code param to the assignment fetch request in ExPlat
  packages/explat/CHANGELOG.md
  packages/explat/src/assignment.ts
  packages/explat/src/utils.ts
Labels: status: ready to merge, Packages

#7534 Update Packages for Publishing
  packages/explat/package.json
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: status: needs review, Build, Packages

#7535 Update Packages for Publishing
  packages/explat/CHANGELOG.md
  packages/explat/package.json
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: status: needs review, Build, Packages

#7529 Add Marketplace and My Subscriptions to the new WooCommerce Navigation.
  changelogs/new-7529-marketplace-nav-items
  src/Features/Navigation/CoreMenu.php
Labels: status: ready to merge

#7531 Refactor package style builds
  bin/packages/build.js
  bin/packages/get-packages.js
  bin/packages/watch.js
  changelogs/update-package-sass-build
  docs/stylesheets.md
  lint-staged.config.js
  package-lock.json
  package.json
  packages/admin-e2e-tests/package.json
  packages/components/package.json
  packages/components/webpack.config.js
  packages/csv-export/package.json
  packages/currency/package.json
  packages/customer-effort-score/package.json
  packages/customer-effort-score/webpack.config.js
  packages/data/package.json
  packages/date/package.json
  packages/experimental/package.json
  packages/experimental/webpack.config.js
  packages/explat/package.json
  packages/js-tests/package.json
  packages/navigation/package.json
  packages/notices/package.json
  packages/onboarding/package.json
  packages/onboarding/webpack.config.js
  packages/style-build/.npmrc
  packages/style-build/README.md
  packages/style-build/abstracts/_breakpoints.scss
  packages/style-build/abstracts/_colors.scss
  packages/style-build/abstracts/_mixins.scss
  packages/style-build/abstracts/_variables.scss
  packages/style-build/index.js
  packages/style-build/package.json
  packages/tracks/package.json
  packages/tsconfig.json
  packages/wc-admin-settings/package.json
  src/Loader.php
  webpack.config.js
Labels: Build, Packages, Components

#7512 Create task list REST API endpoint
  changelogs/add-7365
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
  src/Features/RemoteFreeExtensions/EvaluateExtension.php
  src/Features/RemoteFreeExtensions/Init.php
Labels: needs feedback

#7502 Deleting unneeded double spaces in text strings.
  changelogs/update-7502
  src/API/Plugins.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
  src/Notes/DeactivatePlugin.php
  src/ReportsSync.php
Labels: status: ready to merge

#7544 Bump package versions
  packages/explat/CHANGELOG.md
  packages/explat/package.json
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: Build, Packages, needs feedback

#7521 Skip scheduling action if Action Scheduler tables have not been set up
  changelogs/fix-7398
  src/Schedulers/SchedulerTraits.php
Labels: status: ready to merge

#7538 Add task dismissal endpoints
  changelogs/add-7369
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
Labels: status: ready to merge

#7522 Add tasks feature flag
  client/homescreen/layout.js
  client/tasks/index.ts
  client/tasks/placeholder.scss
  client/tasks/placeholder.tsx
  client/tasks/tasks.tsx
  config/core.json
  config/development.json
  config/plugin.json
Labels: status: ready to merge, needs changelog entry

#7497 Fix country region select with autocomplete
  changelogs/fix-5523_select_control
  client/dashboard/components/settings/general/store-address.js
  client/dashboard/components/settings/general/test/use-get-country-state-autofill.js
  packages/components/CHANGELOG.md
  packages/components/src/select-control/control.js
  packages/components/src/select-control/index.js
Labels: status: ready to merge, Packages, Components

#7480 Remove depreciated shared settings hook
  changelogs/update-6900_depreciated_shared_settings
  client/header/activity-panel/index.js
  client/index.js
  client/layout/controller.js
  client/layout/index.js
  client/marketing/overview/index.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/theme/style.scss
  client/profile-wizard/steps/theme/uploader.js
  client/wp-admin-scripts/print-shipping-label-banner/index.js
  package-lock.json
  package.json
  packages/wc-admin-settings/src/index.js
  src/Features/ActivityPanels.php
  src/Features/Homescreen.php
  src/Features/Marketing.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Features/Settings.php
  src/Loader.php
  src/WCAdminSharedSettings.php
Labels: status: ready to merge, Build, Packages, needs feedback

#7539 Create snooze task endpoint
  changelogs/add-7368-tasks-snooze-endpoint
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks.php
Labels: needs feedback, needs changelog entry

#7557 Fix wrong function name
  src/WCAdminSharedSettings.php
Labels: status: ready to merge

#7570 Add pre-fill for email address field in OBW
  client/profile-wizard/steps/store-details/index.js
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  src/API/OnboardingProfile.php
Labels: status: ready to merge, Packages, feature: onboarding

#7590 Add error handling for email validation errors from backend
  client/profile-wizard/steps/store-details/index.js
  packages/data/src/onboarding/actions.js
Labels: status: ready to merge, Packages, feature: onboarding

#7585 Fix business step auto installing
  changelogs/fix-7564_business_step_auto_installing
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js
Labels: status: needs review, needs cherry picking

#7580 Fix marketing task visibility
  changelogs/fixed_marketing_task_visibility_7580
  client/task-list/tasks.js
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7582 Fix broken PHP tests with the latest WC
  tests/reports/class-wc-tests-reports-coupons.php
  tests/reports/class-wc-tests-reports-products.php
Labels: type: bug, status: ready to merge, Build

#7594 Use !important to force padding:0
  client/homescreen/stats-overview/index.js
  client/homescreen/style.scss
Labels: type: bug, status: ready to merge, needs cherry picking

#7194 Feature/add logger to rin
  readme.txt
  src/RemoteInboxNotifications/EvaluateAndGetStatus.php
  src/RemoteInboxNotifications/EvaluationLogger.php
  src/RemoteInboxNotifications/README.md
  src/RemoteInboxNotifications/RuleEvaluator.php
  tests/remote-inbox-notifications/evaluate-and-get-status.php
Labels: status: ready to merge, cooldown period

#7595 Remove OnboardingEmailMarketing note class
  changelogs/update-7514-remove-onboarding-email-marketing-inbox-notification
  src/Events.php
  src/Notes/OnboardingEmailMarketing.php
Labels: status: ready to merge, feature: inbox

#7598 Fix CSS layout issue on the marketing task
  client/task-list/tasks/Marketing/Marketing.scss
Labels: type: bug, status: ready to merge, needs cherry picking

#7600 Fix 'cannot read property' error from ExPlat
  packages/explat/CHANGELOG.md
  packages/explat/src/assignment.ts
  packages/explat/src/utils.ts
Labels: type: bug, status: ready to merge, Packages

#7601 Add Newsletter Signup
  TESTING-INSTRUCTIONS.md
  changelogs/add-7517-add-email-address-field-obw
  changelogs/add-7519-subscribe-onboarding-email-to-mailchimp
  changelogs/update-7514-remove-onboarding-email-marketing-inbox-notification
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/style.scss
  client/profile-wizard/steps/business-details/index.js
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/store-details/style.scss
  client/profile-wizard/style.scss
  packages/admin-e2e-tests/src/sections/onboarding/BusinessSection.ts
  packages/admin-e2e-tests/src/sections/onboarding/StoreDetailsSection.ts
  packages/admin-e2e-tests/src/specs/activate-and-setup/complete-onboarding-wizard.ts
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  packages/data/src/onboarding/resolvers.js
  packages/data/src/onboarding/selectors.ts
  src/API/OnboardingProfile.php
  src/Events.php
  src/Features/Onboarding.php
  src/Notes/OnboardingEmailMarketing.php
  src/Schedulers/MailchimpScheduler.php
  tests/api/onboarding-profile.php
  tests/e2e/config/default.json
  tests/schedulers/class-wc-tests-mailchimp-scheduler.php
Labels: status: ready to merge, Packages

#7602 Update Email Prefill Endpoint as Experimental
  packages/data/src/onboarding/resolvers.js
  src/API/OnboardingProfile.php
Labels: status: needs review, Packages

#7593 Adjust task item class name to prevent conflicts with older versions
  client/task-list/style.scss
  client/task-list/test/index.js
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/style.scss
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
Labels: status: ready to merge, Packages, needs cherry picking, Components
