Repository woocommerce/woocommerce-admin, pull requests merged in 2021-07, with the labels that each got.

#7274 Fix and refactor explat polling to use setTimeout
  packages/explat/CHANGELOG.md
  packages/explat/src/anon.ts
  readme.txt
Labels: Packages, needs cherry picking, status: needs review

#7232 Disabling wc-admin: Repurpose filter to remove optional features
  readme.txt
  src/FeaturePlugin.php
  src/Features/Features.php
Labels: status: needs review

#7279 Add PayU to default payment gateway suggestions
  TESTING-INSTRUCTIONS.md
  images/onboarding/payu.svg
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: needs changelog entry, status: ready to merge

#7281 Add ability to override payment gateway settings URL
  src/Features/PaymentGatewaySuggestions/PaymentGatewaysController.php
Labels: needs changelog entry, status: ready to merge

#7217 Localize payment gateway suggestions on wccom
  docs/features/payment-gateway-suggestions.md
  src/Features/PaymentGatewaySuggestions/DataSourcePoller.php
  src/Features/PaymentGatewaySuggestions/Init.php
  tests/features/payment-gateway-suggestions/data-source-poller.php
  tests/features/payment-gateway-suggestions/payment-gateway-suggestions.php
Labels: needs changelog entry, status: ready to merge

#7273 Remove unused WC Pay feature flags
  client/task-list/tasks.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/WCPay/utils.js
  config/core.json
  config/development.json
  config/plugin.json
  readme.txt
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7231 Fixing logic around recommended gateways in payment suggestions feature
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/PaymentGatewaySuggestions/index.js
  docs/features/payment-gateway-suggestions.md
  package-lock.json
  packages/onboarding/src/components/RecommendedRibbon/RecommendedRibbon.js
  readme.txt
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: Packages, status: ready to merge

#7088 Update issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Labels: Build, priority: low, status: ready to merge

#7267 Add Klarna Payments to default payment gateway suggestions
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: needs changelog entry, status: needs review, status: ready to merge

#7300 Add a delete option to completed tasks
  docs/examples/extensions/add-task/js/index.js
  packages/experimental/src/experimental-list/task-item.tsx
  readme.txt
Labels: Build, Components, Packages, status: ready to merge

#7270 Add CES to translated scripts list
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Loader.php
Labels: category: i18n, feature: customer effort score, status: ready to merge, type: bug

#7268 Add missing translation strings in the business features section
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge, type: bug

#7278 Fix inbox note dismiss dropdown not closing on Safari
  TESTING-INSTRUCTIONS.md
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
  readme.txt
Labels: Packages, feature: home screen, status: ready to merge, type: bug

#7155 Filters: On update respect all other queries, not just persistedQueries
  packages/components/CHANGELOG.md
  packages/components/src/filter-picker/index.js
  packages/components/src/filter-picker/test/index.js
  packages/components/src/filters/index.js
  readme.txt
Labels: Components, Packages, category: extensibility, status: ready to merge

#7266 Use payment gateway suggestion title instead of local plugin names
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/test/setup.js
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: needs changelog entry, status: ready to merge

#7263 Make task item action button optional
  package-lock.json
  packages/components/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/collapsible-list/index.tsx
  packages/experimental/src/experimental-list/style.scss
  packages/experimental/src/experimental-list/task-item.scss
  packages/experimental/src/experimental-list/task-item.tsx
  packages/experimental/src/experimental-list/test/index.tsx
  packages/experimental/src/vertical-css-transition/test/vertical-css-transition.tsx
  packages/experimental/src/vertical-css-transition/vertical-css-transition.tsx
Labels: Build, Components, Packages, status: ready to merge

#7225 Add height auto on autocomplete popover button
  packages/components/src/search/style.scss
  readme.txt
Labels: Components, Packages

#7276 Change event name to reflect plugin name
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  readme.txt
Labels: status: ready to merge

#7213 Add padding on table header button
  TESTING-INSTRUCTIONS.md
  packages/components/src/table/style.scss
  readme.txt
Labels: Components, Packages, status: ready to merge

#7302 Fix transient overlapping adjacent content
  client/layout/transient-notices/style.scss
  readme.txt
Labels: status: ready to merge

#7311 Components, Experimental, Data package release prep
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: Build, Components, Packages

#7290 Sync the category lookup table when a new category gets created
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/CategoryLookup.php
Labels: needs feedback, status: ready to merge

#6833 Hook reference: Add SlotFill support
  .eslintrc.js
  bin/hook-reference/data.js
  bin/hook-reference/data.json
  bin/hook-reference/index.js
  client/homescreen/stats-overview/defaults.js
  packages/navigation/src/index.js
  readme.txt
Labels: Build, Packages, needs feedback, status: ready to merge

#7299 Preloaded options: remove unused feature options
  readme.txt
  src/Features/Analytics.php
  src/Features/Navigation/Init.php
Labels: status: ready to merge

#6870 use Jetpack Changelogger for changelog management
  .github/PULL_REQUEST_TEMPLATE.md
  bin/changelogger/WCAdminFormatter.php
  changelog.txt
  changelogs/.gitkeep
  composer.json
  composer.lock
  package.json
  readme.txt
Labels: Build, cooldown period, needs feedback

#7334 Fix minimum expected recommended extension count.
  tests/e2e/sections/onboarding/BusinessSection.ts
Labels: has tests, status: ready to merge

#7318 Changelogger Linter: Point to correct file to test presence of changelog entry
  bin/ci/lint-changelog.sh
  changelogs/test-changelogger-lint
Labels: Build, status: ready to merge

#7287 Remove facebook extension from onboarding extensions fallback list
  TESTING-INSTRUCTIONS.md
  changelogs/update-7282-remove-facebook-extension
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#7337 Bumping onboarding package version
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: Build, Packages, needs changelog entry, status: ready to merge

#7269 Render a spinner while woocommerce_setup_jetpack_opted_in is being loaded
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7239-tos-link-disappears-from-setup-tax-screen
  client/task-list/tasks/tax.js
Labels: feature: onboarding, needs changelog entry, status: ready to merge, type: bug

#7186 AdvancedFilters: Create workable defaults for Reports that don't have them
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/products/config.js
  client/analytics/report/revenue/config.js
  client/analytics/report/stock/config.js
  client/analytics/report/taxes/config.js
  packages/components/CHANGELOG.md
  packages/components/src/filters/index.js
Labels: Components, Packages, needs changelog entry, needs cherry picking, status: ready to merge

#7293 Remove deprecated components in prep for release 8.0.0 of @woocommerce/components
  client/header/activity-panel/activity-card/test/__snapshots__/index.js.snap
  client/header/activity-panel/activity-card/test/index.js
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/card/README.md
  packages/components/src/card/index.js
  packages/components/src/card/stories/index.js
  packages/components/src/card/style.scss
  packages/components/src/card/test/__snapshots__/index.js.snap
  packages/components/src/card/test/index.js
  packages/components/src/count/README.md
  packages/components/src/count/index.js
  packages/components/src/count/stories/index.js
  packages/components/src/count/style.scss
  packages/components/src/count/test/__snapshots__/index.js.snap
  packages/components/src/count/test/index.js
  packages/components/src/gravatar/README.md
  packages/components/src/gravatar/index.js
  packages/components/src/gravatar/stories/index.js
  packages/components/src/gravatar/style.scss
  packages/components/src/gravatar/test/index.js
  packages/components/src/index.js
  packages/components/src/list/index.js
  packages/components/src/segmented-selection/index.js
  packages/components/src/style.scss
Labels: Build, Components, Packages, status: ready to merge

#7298 Remote Inbox: Add feature to list of optional feature flags
  src/FeaturePlugin.php
  src/Features/Features.php
  src/Features/RemoteInboxNotifications.php
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
Labels: needs changelog entry, needs cherry picking, status: needs review

#7343 Set default value for performanceIndicators var
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7339-home-crashes-after-disabling-analytics-feature
  client/homescreen/stats-overview/index.js
Labels: needs cherry picking, status: ready to merge, type: bug

#7294 Add TableSummaryPlaceholder to support skeleton loading
  TESTING-INSTRUCTIONS.md
  changelogs/add-placeholder-TableSummary
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/table/README.md
  packages/components/src/table/index.js
  packages/components/src/table/stories/table-summary-placeholder.js
  packages/components/src/table/stories/table-summary.js
  packages/components/src/table/style.scss
  packages/components/src/table/summary.js
  packages/components/src/table/test/data/table-mock-summary.js
  packages/components/src/table/test/index.js
Labels: Components, Packages, status: ready to merge

#7342 Fix/7322 unable to dismiss inbox note
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7322-unable-to-dismiss-inbox-note
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
Labels: Packages, needs cherry picking, status: ready to merge, type: bug

#7344 Fix undefined method error when setting up WC Tax
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7340-unable-to-setup-automated-tax-via-tasklist
  client/task-list/tasks/tax.js
Labels: feature: onboarding, needs cherry picking, status: ready to merge, type: bug

#7330 Invalidate task status when enabling a payment gateway
  client/task-list/tasks/PaymentGatewaySuggestions/index.js
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7332 Redirect to homescreen after payment gateway setup
  client/task-list/tasks/PaymentGatewaySuggestions/index.js
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Features/PaymentGatewaySuggestions/PaymentGatewaysController.php
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7320 Changelogs: Add 2.5.0
  changelog.txt
  package-lock.json
Labels: Build, needs cherry picking, status: ready to merge

#7361 Fix TSC config and package build script.
  package.json
  tsconfig.json
Labels: Build, needs changelog entry, needs cherry picking, status: ready to merge

#7353 Fixed OBW - Business details style
  changelogs/fix-7324
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/style.scss
Labels: needs cherry picking, status: needs review, type: bug

#7364 Add cache-control header to low stock response
  changelogs/fix-slow-low-stock
  src/API/Products.php
Labels: needs changelog entry, status: needs review

#7379 Add lazy loading by checking panel open status and lint fix
  changelogs/fix-7376-lazy-load-activity-panel
  client/header/activity-panel/index.js
Labels: needs changelog entry, status: ready to merge

#7304 Fixing a few issues with tracks events in gateway suggestions
  changelogs/fix-gateway-suggestions-tracks
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/Item.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/List/List.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Configure.js
  client/task-list/tasks/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/task-list/tasks/PaymentGatewaySuggestions/index.js
Labels: status: ready to merge

#7388 Use the original endpoint in products test
  tests/api/products.php
Labels: needs cherry picking, status: ready to merge

#7389 Bug fixes for the new low in stock endpoint
  src/API/ProductsLowInStock.php
Labels: needs cherry picking, status: ready to merge

#7384 Adding links to help panel for marketing task
  changelogs/add-7329-marketing-help-links
  client/header/activity-panel/panels/help.js
Labels: status: ready to merge

#7405 Add scope to BACS slotfill
  client/task-list/tasks/PaymentGatewaySuggestions/plugins/Bacs.js
  packages/admin-e2e-tests/src/pages/WcHomescreen.ts
Labels: Packages, needs changelog entry, needs cherry picking, status: ready to merge

#7404 Attempt to fix broken test in PHP 7 + WC latest + Composer 1.10.19
  tests/bootstrap.php
Labels: Build, needs feedback

#7406 Update e2e matcher for tasklist header
  packages/admin-e2e-tests/src/pages/WcHomescreen.ts
Labels: Packages, status: ready to merge

#7400 Update changelog info in the contributing doc
  CONTRIBUTING.md
Labels: needs cherry picking, status: ready to merge

#7395 Fix orders panel loading
  changelogs/fix-7382_orders_panel_loading
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/test/index.js
  packages/data/src/items/selectors.js
  src/API/Orders.php
Labels: Packages, needs cherry picking, status: ready to merge, type: bug

#7285 Try: Register a fake wc-admin homepage to for users without permission
  changelogs/try-7061
  src/Features/Homescreen.php
Labels: needs changelog entry, status: ready to merge

#7410 Fix analytics filter Gutenberg CSS conflict
  changelogs/fix-7362-analytics-filter-gutenberg-conflict
  packages/components/src/advanced-filters/style.scss
Labels: Components, Packages, needs cherry picking, status: ready to merge

#7403 Import createElement to fix build issues with SlotFill
  packages/onboarding/CHANGELOG.md
  packages/onboarding/src/components/WooPaymentGatewayConfigure/WooPaymentGatewayConfigure.js
Labels: Packages, needs changelog entry, needs cherry picking, status: ready to merge

#7401 Skip category creation on WC install
  src/CategoryLookup.php
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7399 Add limit clause to coupons data store query
  changelogs/fix-7393
  src/API/Reports/Coupons/DataStore.php
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7411 Fix Gutenberg CardBody styles for task card
  changelogs/fix-gb-task-card
  client/task-list/style.scss
  client/task-list/task-list.js
Labels: needs changelog entry, needs cherry picking, status: ready to merge

#7356 Fix the deprecated behaviour for `<Form>` callbacks and push removal to 9.0.0
  packages/components/CHANGELOG.md
  packages/components/src/form/index.js
  packages/components/src/form/test/index.js
Labels: Components, Packages, status: needs review

#7414 Update help tooltip styling
  changelogs/fix-7413_help_tooltip_styling
  client/header/activity-panel/highlight-tooltip/style.scss
Labels: needs cherry picking, status: ready to merge

#7421 Update payment gateway plugins for testing
  TESTING-INSTRUCTIONS.md
Labels: needs cherry picking, status: needs review

#7409 Fix recommended card Gutenberg CSS conflict
  changelogs/fix-7394-recommended-card-gutenberg-conflict
  client/embedded-body-layout/style.scss
  client/payments/payment-recommendations.scss
  client/payments/payment-recommendations.tsx
Labels: needs cherry picking, status: ready to merge

#7355 Refactoring report table withSelect to fix issues with the table data populating correctly
  changelogs/fix-6820
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-table/index.js
  client/analytics/components/report-table/utils.js
  client/analytics/report/index.js
  client/analytics/report/products/index.js
  client/analytics/report/products/table.js
  packages/data/src/items/utils.js
  packages/data/src/reports/utils.js
Labels: Packages, status: ready to merge

#7341 Add `navigation.getIdsSetFromQuery` util.
  packages/navigation/CHANGELOG.md
  packages/navigation/src/index.js
  packages/navigation/src/test/index.js
Labels: Packages, feature: navigation, has tests, priority: low, status: ready to merge

#7378 Add `hidden` legendPosition to `Chart`.
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/chart/README.md
  packages/components/src/chart/index.js
  packages/components/src/chart/stories/index.js
  packages/components/src/chart/test/legend.js
Labels: Build, Components, Packages, status: ready to merge, type: enhancement

#7424 Add eslint rule to prevent missing createElement imports.
  .eslintrc.js
  package.json
Labels: Build, Trash Pickup, status: ready to merge, type: technical debt

#7386 Removing grow section from local free extensions in OBW
  changelogs/update-7312-remove-grow-from-obw
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
Labels: status: ready to merge

#7284 Match stock status value in CSV download to the table
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7283-stock-report-has-inconsistent-word-for-status
  client/analytics/report/stock/table.js
  src/API/Reports/Stock/Controller.php
Labels: feature: analytics, status: ready to merge

#7385 Increase per_page value for search results on the Analytics pages.
  changelogs/update-6790-increase-per-page-for-search
  client/analytics/report/index.js
  packages/data/src/items/utils.js
Labels: Packages, feature: analytics, status: ready to merge

#7391 Add locale param as part of free extensions request
  changelogs/update-obw-free-extensions-locale
  src/Features/RemoteFreeExtensions/DataSourcePoller.php
  src/Features/RemoteFreeExtensions/Init.php
Labels: needs changelog entry, status: ready to merge

#7357 Display green indicator for a drop in refunds in report summary
  changelogs/add-reverse-trend-support-summary-number
  client/analytics/components/report-summary/index.js
  client/analytics/report/revenue/config.js
Labels: status: ready to merge

#7412 Fix WooCommerce payments action button styling
  changelogs/fix-7347_wcpay_get_started_alignment
  packages/onboarding/CHANGELOG.md
  packages/onboarding/src/components/WCPayCard/WCPayCard.scss
Labels: Packages, status: ready to merge

#7430 Jest: Update to version 27
  changelogs/update-jest-27
  client/navigation/components/container/test/index.js
  package-lock.json
  package.json
  packages/components/src/form/test/index.js
  packages/experimental/src/vertical-css-transition/test/vertical-css-transition.tsx
  packages/js-tests/jest.config.js
Labels: Build, Components, Packages, status: ready to merge

#7383 Add marketing extensions task to task list
  changelogs/add-7313
  client/task-list/tasks.js
  client/task-list/tasks/Marketing/Marketing.scss
  client/task-list/tasks/Marketing/Plugin.scss
  client/task-list/tasks/Marketing/Plugin.tsx
  client/task-list/tasks/Marketing/PluginList.scss
  client/task-list/tasks/Marketing/PluginList.tsx
  client/task-list/tasks/Marketing/index.tsx
  packages/data/src/plugins/selectors.ts
  src/Features/RemoteFreeExtensions/DataSourcePoller.php
Labels: Packages, needs changelog entry, needs feedback

#7440 Bump version to 2.6.0-dev
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#7425 Update test renderer in few components,
  packages/components/src/animation-slider/test/__snapshots__/index.js.snap
  packages/components/src/animation-slider/test/index.js
  packages/components/src/dropdown-button/test/__snapshots__/index.js.snap
  packages/components/src/dropdown-button/test/index.js
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
  packages/components/src/search-list-control/test/index.js
  packages/components/src/section-header/test/__snapshots__/index.js.snap
  packages/components/src/section-header/test/index.js
  packages/components/src/tag/test/__snapshots__/index.js.snap
  packages/components/src/tag/test/index.js
Labels: Components, Packages, priority: low, type: technical debt
