Repository woocommerce/woocommerce-admin, pull requests merged in 2021-09, with the labels that each got.

#7586 Adjust marketing completion logic
  changelogs/update-7567_marketing_task_completion_logic
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/Marketing/index.tsx
Labels: needs feedback

#7608 Sync 2.6.0 and 2.6.1 changelog back to main
  changelog.txt
  changelogs/fixed_marketing_task_visibility_7580
  changelogs/update-7567_marketing_task_completion_logic
Labels: status: ready to merge

#7607 Remove docs command from pre-release command
  bin/pre-release.sh
Labels: status: ready to merge, Build

#7577 Create task list APIs
  docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php
  docs/features/onboarding.md
  includes/wc-admin-update-functions.php
  packages/admin-e2e-tests/src/specs/tasks/payment.ts
  src/API/OnboardingTasks.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
  src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php
  src/Install.php
  tests/features/class-wc-tests-task-lists.php
Labels: status: needs review, Packages, needs changelog entry

#7619 Add Powered by Mailchimp
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/store-details/style.scss
Labels: status: ready to merge, needs cherry picking

#7611 Only display expanded content when expanded is true
  changelogs/fix-7609_task_item_content_logic
  client/task-list/test/index.js
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/task-item.tsx
Labels: status: ready to merge, Packages

#7509 Add task list and activity panel E2E tests
  package-lock.json
  package.json
  packages/admin-e2e-tests/CHANGELOG.md
  packages/admin-e2e-tests/src/constants/taskTitles.ts
  packages/admin-e2e-tests/src/elements/HelpMenu.ts
  packages/admin-e2e-tests/src/elements/OrdersActivityPanel.ts
  packages/admin-e2e-tests/src/fixtures/http-client.ts
  packages/admin-e2e-tests/src/fixtures/index.ts
  packages/admin-e2e-tests/src/fixtures/options.ts
  packages/admin-e2e-tests/src/fixtures/orders.ts
  packages/admin-e2e-tests/src/pages/AnalyticsOverview.ts
  packages/admin-e2e-tests/src/pages/WcHomescreen.ts
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/admin-e2e-tests/src/specs/homescreen/task-list.ts
  packages/admin-e2e-tests/src/specs/index.ts
  packages/admin-e2e-tests/src/utils/actions.ts
  packages/admin-e2e-tests/typings/index.d.ts
  tests/e2e/docker/initialize.sh
  tests/e2e/specs/homescreen/activity-panel.test.ts
  tests/e2e/specs/homescreen/task-list.test.ts
Labels: Build, Packages

#7575 Add optional parameter to `/currency`'s `formatAmount` to display currency code.
  packages/currency/CHANGELOG.md
  packages/currency/src/index.js
  packages/currency/src/test/index.js
Labels: type: enhancement, status: ready to merge, Packages

#7624 Add marketing task testing instructions
  TESTING-INSTRUCTIONS.md
Labels: status: needs review, needs changelog entry

#7587 Make sure batch fetch resolved data remains consistent
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/data/CHANGELOG.md
  packages/data/src/options/controls.js
Labels: status: ready to merge, Packages, needs feedback

#7550 Render psuedo wc pay payment gateway in payment method table
  client/payments/payment-recommendations.tsx
  client/payments/test/payment-recommendations.test.tsx
  client/wp-admin-scripts/wc-pay-payments-promotion/index.tsx
  client/wp-admin-scripts/wc-pay-payments-promotion/wc-payments-row.scss
  client/wp-admin-scripts/wc-pay-payments-promotion/wc-payments-row.tsx
  config/core.json
  config/development.json
  config/plugin.json
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/onboarding/src/images/cards/googlepay.js
  packages/onboarding/src/index.js
  src/Features/WcPayPromotion/Init.php
  src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php
  src/PaymentPlugins.php
  webpack.config.js
Labels: status: ready to merge, Build, Packages, needs feedback

#7553 Feature/7319 add woocommerce com data
  client/wp-admin-scripts/payment-method-promotions/index.tsx
  client/wp-admin-scripts/payment-method-promotions/payment-promotion-row.scss
  client/wp-admin-scripts/payment-method-promotions/payment-promotion-row.tsx
  client/wp-admin-scripts/wc-pay-payments-promotion/index.tsx
  client/wp-admin-scripts/wc-pay-payments-promotion/wc-payments-row.tsx
  packages/data/src/index.ts
  packages/data/src/plugins/actions.ts
  src/Features/WcPayPromotion/DataSourcePoller.php
  src/Features/WcPayPromotion/Init.php
  src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php
  webpack.config.js
Labels: Build, Packages, needs feedback

#7632 Add toggle to experimental task item
  client/task-list/task-list.js
  client/task-list/test/index.js
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/collapsible-list/index.tsx
  packages/experimental/src/experimental-list/collapsible-list/style.scss
  packages/experimental/src/experimental-list/task-item.tsx
Labels: status: ready to merge, Packages

#7650 Bump experimental version
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: status: needs review, Build, Packages

#7651 Bump experimental version
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: status: ready to merge, Build, Packages

#7554 Add explat variation for wc pay promotion
  includes/class-experimental-abtest.php
  src/FeaturePlugin.php
  src/Features/WcPayPromotion/DataSourcePoller.php
  src/Features/WcPayPromotion/Init.php
Labels: needs feedback

#7612 Get email prefill to avoid infinite loading state
  client/profile-wizard/steps/store-details/index.js
Labels: status: ready to merge, needs cherry picking, needs changelog entry

#7654 Bump experimental version to 2.0.2
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
Labels: status: needs review, Build, Packages

#7656 Bump experimental version to 2.0.3
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/experimental/tsconfig.json
Labels: status: needs review, Build, Packages

#7640 Fix/7548 set up marketing tools title
  changelogs/fix-7548_set_up_marketing_tools_title
  client/header/index.js
Labels: status: ready to merge, needs feedback

#7615 Fixing an unwanted page refresh when using Woo Navigation
  changelogs/fix-woonav-page-refresh
  client/layout/index.js
  client/layout/navigation.js
  docs/examples/extensions/add-navigation-items/js/index.js
  docs/features/navigation.md
Labels: status: needs review

#7543 Console command to order PRs by merge date
  bin/sort-pr-by-date.sh
Labels: status: ready to merge, Build

#7675 allow CBD to be optional in business details in E2E
  packages/admin-e2e-tests/src/sections/onboarding/IndustrySection.ts
  packages/admin-e2e-tests/src/specs/activate-and-setup/complete-onboarding-wizard.ts
Labels: type: task, Packages

#7663 Add API methods to store task lists and tasks
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/StoreDetails.php
Labels: status: ready to merge

#7578 Add hide task list endpoint and data actions
  packages/data/src/onboarding/action-types.js
  packages/data/src/onboarding/actions.js
  packages/data/src/onboarding/reducer.js
  src/API/OnboardingTasks.php
Labels: Packages, needs feedback, needs changelog entry

#7682 Fixes for analytics bugs introduced in 2.6
  changelogs/fix-7473-blank-screen-search-categories
  changelogs/fix-analytics-categories-fatal-on-search
  client/analytics/report/categories/table.js
  client/analytics/report/index.js
  packages/data/src/items/utils.js
Labels: status: needs review, Packages, needs cherry picking

#7665 Add Task API
  src/Features/OnboardingTasks/Task.php
  src/Features/OnboardingTasks/TaskList.php
  tests/features/onboarding-tasks/task.php
Labels: status: ready to merge, needs changelog entry

#7692 Pass empty string instead of null to init
  src/Features/WcPayPromotion/Init.php
Labels: status: needs review

#7691 Fix unsecured report files
  changelogs/fix-reports-dir
  includes/wc-admin-update-functions.php
  src/Install.php
  src/Notes/UnsecuredReportFiles.php
  src/ReportCSVExporter.php
  tests/reports/class-wc-tests-reports.php
Labels: status: ready to merge, needs cherry picking

#7616 Adding SlotFill support for API-driven tasks components
  client/layout/index.js
  client/layout/style.scss
  client/tasks/fills/Marketing/Marketing.scss
  client/tasks/fills/Marketing/Plugin.scss
  client/tasks/fills/Marketing/Plugin.tsx
  client/tasks/fills/Marketing/PluginList.scss
  client/tasks/fills/Marketing/PluginList.tsx
  client/tasks/fills/Marketing/index.tsx
  client/tasks/fills/Marketing/test/index.tsx
  client/tasks/fills/PaymentGatewaySuggestions/components/Action.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/Item.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/List.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/List.scss
  client/tasks/fills/PaymentGatewaySuggestions/components/List/Placeholder.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/index.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/test/list.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Configure.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Placeholder.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Setup.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Setup.scss
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/index.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/test/configure.js
  client/tasks/fills/PaymentGatewaySuggestions/components/Setup/test/setup.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/Suggestion.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/UsageModal.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/index.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/utils.js
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  client/tasks/fills/PaymentGatewaySuggestions/plugins/Bacs.js
  client/tasks/fills/appearance.js
  client/tasks/fills/connect.js
  client/tasks/fills/index.js
  client/tasks/fills/products/index.js
  client/tasks/fills/products/product-template-modal.js
  client/tasks/fills/products/product-template-modal.scss
  client/tasks/fills/products/products.js
  client/tasks/fills/purchase.js
  client/tasks/fills/shipping/index.js
  client/tasks/fills/shipping/rates.js
  client/tasks/fills/steps/location.js
  client/tasks/fills/tax.js
  client/tasks/fills/woocommerce-payments.js
  client/tasks/index.ts
  client/tasks/task-list-item.tsx
  client/tasks/task.tsx
  client/tasks/tasks.tsx
  packages/experimental/CHANGELOG.md
  packages/experimental/src/experimental-list/task-item.tsx
  packages/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js
  packages/onboarding/src/components/WooOnboardingTask/index.js
  packages/onboarding/src/components/WooOnboardingTaskListItem/WooOnboardingTaskListItem.js
  packages/onboarding/src/components/WooOnboardingTaskListItem/index.js
  packages/onboarding/src/index.js
  src/Features/OnboardingTasks/TaskLists.php
Labels: needs feedback, needs changelog entry

#7679 Add France to list of countries that get Square as an option…
  changelogs/tweak-7631_include_square_in_fr
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7698 Add filters to get new hidden options
  src/Features/OnboardingTasks.php
Labels: status: ready to merge, priority: high, needs cherry picking, needs changelog entry

#7253 Assign parent order status as children order status if refund order
  changelogs/fix-7197
  includes/wc-admin-update-functions.php
  src/API/Reports/Orders/Stats/DataStore.php
  src/Install.php
  src/Schedulers/OrdersScheduler.php
Labels: status: ready to merge

#7695 Include yoast phpunit polyfills in phpunit tests
  .github/workflows/test-php.yml
  composer.json
  composer.lock
  tests/api/data.php
  tests/api/reports-downloads-stats.php
  tests/api/reports-downloads.php
  tests/api/reports-performance-indicators.php
  tests/bootstrap.php
Labels: status: ready to merge, Build

#7686 Fix issue where variation name might not exist in analytics
  changelogs/fix-7443_analytics_variations_table
  client/lib/async-requests/index.js
Labels: status: ready to merge

#7700 Bump admin-e2e-tests version to 0.1.1
  packages/admin-e2e-tests/CHANGELOG.md
  packages/admin-e2e-tests/package.json
Labels: status: needs review, Build, Packages

#7678 Fix/7591 eWAY to Eway
  TESTING-INSTRUCTIONS.md
  changelogs/Change eWAY to Eway in payment gateway display text #7678
  client/header/activity-panel/panels/help.js
  client/header/activity-panel/test/help-panel.js
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge

#7688 Add old option back with depreciated notice for backwards compatibility
  package-lock.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/data/src/reports/utils.js
Labels: status: ready to merge, Build, Packages

#7664 Sync changelog entires from 2.6.x releases
  changelog.txt
Labels: status: ready to merge

#7705 Update option list migrations to run on 2.7.1
  includes/wc-admin-update-functions.php
  src/Install.php
Labels: status: ready to merge, needs changelog entry

#7666 Add changelog and enable promotion in core and plugin configs
  changelogs/update-7319_enable_wc_pay_experiment
  client/settings-recommendations/recommendations-eligibility-wrapper.tsx
  config/core.json
  config/plugin.json
  src/Features/PaymentGatewaySuggestions/EvaluateSuggestion.php
  src/Features/WcPayPromotion/Init.php
  tests/features/payment-gateway-suggestions/evaluate-suggestion.php
Labels: status: ready to merge

#7697 Fixing error thrown when dimissing/snoozing tasks via API
  src/API/OnboardingTasks.php
Labels: status: ready to merge, needs changelog entry

#7699 Migrate tasks to task API
  packages/data/src/onboarding/selectors.ts
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/Appearance.php
  src/Features/OnboardingTasks/Tasks/Marketing.php
  src/Features/OnboardingTasks/Tasks/Payments.php
  src/Features/OnboardingTasks/Tasks/Products.php
  src/Features/OnboardingTasks/Tasks/Purchase.php
  src/Features/OnboardingTasks/Tasks/Shipping.php
  src/Features/OnboardingTasks/Tasks/StoreDetails.php
  src/Features/OnboardingTasks/Tasks/Tax.php
  src/Features/OnboardingTasks/Tasks/WooCommercePayments.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
Labels: status: ready to merge, Packages, needs changelog entry

#7709 Fix category lookup class
  changelogs/fix-7680_category_lookup_class
  src/CategoryLookup.php
  tests/category-lookup.php
Labels: status: ready to merge

#7687 Add experimental list documentation
  packages/experimental/src/experimental-list/stories/index.tsx
  packages/experimental/src/experimental-list/stories/style.scss
  packages/experimental/src/experimental-list/task-item/README.md
  packages/experimental/src/experimental-list/task-item/index.tsx
  packages/experimental/src/experimental-list/task-item/style.scss
  packages/experimental/src/style.scss
Labels: status: ready to merge, type: documentation, Packages

#7731 Bump version to 2.9.0-dev
  TESTING-INSTRUCTIONS.md
  changelog.txt
  changelogs/Change eWAY to Eway in payment gateway display text #7678
  changelogs/add-7365
  changelogs/add-7368-tasks-snooze-endpoint
  changelogs/add-7369
  changelogs/add-7517-add-email-address-field-obw
  changelogs/add-7519-subscribe-onboarding-email-to-mailchimp
  changelogs/add-7547_wcpay_intl_countries
  changelogs/add-7559-snooze-undo-endpoint
  changelogs/add-marketing-pinterest-info
  changelogs/feat-add-shipping-settings-plugins-recommendations
  changelogs/fix-5523_select_control
  changelogs/fix-6471
  changelogs/fix-6718
  changelogs/fix-7197
  changelogs/fix-7350_modifying_overview_screen
  changelogs/fix-7397
  changelogs/fix-7398
  changelogs/fix-7423-date-filter-retains-values
  changelogs/fix-7443_analytics_variations_table
  changelogs/fix-7477-link-hash-issue
  changelogs/fix-7479-home-style-issue
  changelogs/fix-7487
  changelogs/fix-7548_set_up_marketing_tools_title
  changelogs/fix-7564_business_step_auto_installing
  changelogs/fix-7609_task_item_content_logic
  changelogs/fix-7630_track_event_props
  changelogs/fix-7680_category_lookup_class
  changelogs/fix-analytics-categories-fatal-on-search
  changelogs/fix-reports-dir
  changelogs/fix-woonav-page-refresh
  changelogs/new-7529-marketplace-nav-items
  changelogs/remove-onboarding-preload
  changelogs/tweak-7631_include_square_in_fr
  changelogs/update-6900_depreciated_shared_settings
  changelogs/update-7319_enable_wc_pay_experiment
  changelogs/update-7471-split-extensions-pages
  changelogs/update-7502
  changelogs/update-7514-remove-onboarding-email-marketing-inbox-notification
  changelogs/update-analytics-card-hearder-styles
  changelogs/update-eway-suggestions-defaults
  changelogs/update-package-sass-build
  changelogs/update-sentence-case-analytics
  changelogs/update-table-align-isNumeric
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#7728 Fix task snooze and dismiss functions
  client/tasks/task-list-item.tsx
  client/tasks/task-list.tsx
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/Task.php
  src/Features/OnboardingTasks/TaskList.php
  src/Features/OnboardingTasks/TaskLists.php
Labels: status: ready to merge, needs changelog entry

#7718 Only return viewable tasks from tasks endpoint
  client/tasks/task-list.tsx
  src/API/OnboardingTasks.php
  src/Features/OnboardingTasks/Task.php
  src/Features/OnboardingTasks/TaskList.php
  tests/features/onboarding-tasks/task.php
Labels: status: ready to merge, needs changelog entry
