Repository woocommerce/woocommerce-admin, pull requests merged in 2021-04, with the labels that each got.

#6724 Update folded header style
  client/header/style.scss
  readme.txt
Labels: status: ready to merge

#6594 Update select control logic so value type stays consistent
  packages/components/CHANGELOG.md
  packages/components/src/select-control/README.md
  packages/components/src/select-control/index.js
  packages/components/src/select-control/test/index.js
Labels: Components, Packages, needs changelog entry, status: ready to merge, type: bug

#6721 Update 2.2.0 release date
  readme.txt
Labels: status: ready to merge

#6736 Components: Release prep
  packages/README.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: Build, Components, Packages, needs changelog entry, status: ready to merge

#6734 Update WC Payments plugin copy
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#6730 Set international countries feature flag to false for core
  config/core.json
Labels: Build, needs changelog entry, needs cherry picking, needs feedback

#6733 Update choose niche note cta URL
  readme.txt
  src/Notes/ChooseNiche.php
Labels: status: ready to merge

#6614 Fix persisted queries being lost when navigating to excluded page (such as Homescreen)
  TESTING-INSTRUCTIONS.md
  client/layout/navigation.js
  client/navigation/components/container/index.js
  client/navigation/components/header/index.js
  client/navigation/test/utils.js
  client/navigation/utils.ts
  packages/data/CHANGELOG.md
  packages/data/src/navigation/action-types.js
  packages/data/src/navigation/actions.js
  packages/data/src/navigation/dispatchers.js
  packages/data/src/navigation/index.js
  packages/data/src/navigation/reducer.js
  packages/data/src/navigation/selectors.js
  packages/data/src/navigation/test/reducer.js
  packages/navigation/CHANGELOG.md
  packages/navigation/src/index.js
  packages/navigation/src/test/index.js
  readme.txt
Labels: Packages, feature: navigation, status: ready to merge

#6716 Add Daily E2E Tests to CI
  .github/workflows/daily-e2e.yml
Labels: Build, status: needs review

#6746 Add readme instructions on how to use CustomerEffortScore
  packages/customer-effort-score/README.md
Labels: Packages, needs changelog entry, status: ready to merge

#6678 Add support for php8 unit tests (locally and in GH actions)
  .github/workflows/test-php.yml
  .gitignore
  bin/composer/phpunit/composer.json
  bin/composer/phpunit/composer.lock
  bin/phpunit.sh
  composer.json
  composer.lock
  docker/wc-admin-php-test-suite/Dockerfile
  docker/wc-admin-php-test-suite/docker-compose.yml
  docker/wc-admin-php-test-suite/entrypoint.sh
  docker/wc-admin-php-test-suite/install-php-version.sh
  readme.txt
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
  tests/notes/class-wc-tests-email-notes.php
  tests/notes/class-wc-tests-notes-data-store.php
Labels: Build, cooldown period, status: ready to merge

#6750 Fix a syntax error in the phpcs script
  bin/phpcs.sh
Labels: Build, status: ready to merge

#6642 Update Paths to Exclude from Composer
  .gitattributes
Labels: Build, status: ready to merge

#6762 Add settings_section event prop for CES
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
Labels: feature: customer effort score, status: needs review

#6644 Remove no-reply from inbox notification emails
  readme.txt
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
Labels: feature: inbox, status: needs review

#6765 Avoid updating customer info synchronously when "last active" is modified.
  readme.txt
  src/API/Reports/Customers/DataStore.php
  src/Schedulers/CustomersScheduler.php
  tests/api-init.php
Labels: category: performance, has tests, status: ready to merge, type: bug

#6783 Update docker test suite readme
  docker/wc-admin-php-test-suite/readme.md
Labels: status: ready to merge

#6767 Packages: Bump versions for release
  packages/csv-export/CHANGELOG.md
  packages/csv-export/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/customer-effort-score/CHANGELOG.md
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/notices/README.md
  packages/number/CHANGELOG.md
  packages/number/package.json
  packages/tracks/CHANGELOG.md
  packages/tracks/package.json
Labels: Build, Packages, needs changelog entry, status: ready to merge

#6784 Make @woocommerce/notices private package
  packages/notices/package.json
Labels: Build, Packages, needs changelog entry, status: ready to merge

#6785 CSS Linting: Exclude Storybook CSS
  .stylelintignore
Labels: Build, status: ready to merge

#6715 Add Daily PHP Tests to CI
  .github/workflows/daily-php.yml
  bin/install-wp-tests.sh
Labels: Build, status: ready to merge

#6725 Make pagination buttons height and width consistent
  packages/components/src/pagination/style.scss
  readme.txt
Labels: Components, Packages, status: ready to merge

#6782 Add content grouping for Google Analytics.
  index.html
Labels: status: ready to merge

#6793 Don't run Daily PHP tests on pull requests.
  .github/workflows/daily-php.yml
Labels: Build, priority: high, status: needs review, type: bug

#6791 Redirect to shipping settings page when task is completed
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks.js
  readme.txt
Labels: status: ready to merge, type: bug

#6732 Add unminified assets if no minified assets exist in `make-zip.sh`
  bin/make-zip.sh
Labels: Build, needs changelog entry, status: ready to merge

#6786 Refactor payments to allow management of methods
  TESTING-INSTRUCTIONS.md
  client/layout/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/task-list/tasks.js
  client/task-list/tasks/payments/action.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/bacs.js
  client/task-list/tasks/payments/methods/eway.js
  client/task-list/tasks/payments/methods/index.js
  client/task-list/tasks/payments/methods/klarna.js
  client/task-list/tasks/payments/methods/mercadopago.js
  client/task-list/tasks/payments/methods/mollie.js
  client/task-list/tasks/payments/methods/paypal.js
  client/task-list/tasks/payments/methods/payu-india.js
  client/task-list/tasks/payments/methods/razorpay.js
  client/task-list/tasks/payments/methods/square.js
  client/task-list/tasks/payments/methods/stripe.js
  client/task-list/tasks/payments/methods/wcpay/index.js
  client/task-list/tasks/payments/methods/wcpay/install-activate-and-connect.js
  client/task-list/tasks/payments/methods/wcpay/is-supported.js
  client/task-list/tasks/payments/methods/wcpay/wcpay-usage-modal.js
  client/task-list/tasks/payments/methods/wcpay/wcpay.js
  client/task-list/tasks/payments/recommended-ribbon.js
  client/task-list/tasks/payments/setup.js
  client/task-list/test/payments.js
  readme.txt
  tests/e2e/pages/PaymentsSetup.ts
  tests/e2e/specs/tasks/payment.test.ts
Labels: feature: onboarding, status: ready to merge

#6794 Add data source filter to remote inbox notification system
  readme.txt
  src/RemoteInboxNotifications/DataSourcePoller.php
Labels: feature: inbox, status: ready to merge

#6800 Add in missing awaits that could have been causing tests to be flaky.
  tests/e2e/pages/OnboardingWizard.ts
  tests/e2e/sections/onboarding/StoreDetailsSection.ts
Labels: Build, status: ready to merge

#6669 Try ExPlat: Add A/A test
  bin/packages/build.js
  bin/packages/watch.js
  client/homescreen/stats-overview/index.js
  client/profile-wizard/steps/usage-modal.js
  client/wp-admin-scripts/beta-features-tracking-modal/container.js
  package-lock.json
  package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/assets/packages.js
  packages/explat/.npmrc
  packages/explat/README.md
  packages/explat/package.json
  packages/explat/src/anon.ts
  packages/explat/src/assignment.ts
  packages/explat/src/error.ts
  packages/explat/src/index.ts
  packages/explat/src/utils.ts
  readme.txt
  src/Loader.php
  tests/js/setup-globals.js
  webpack.config.js
Labels: Build, Packages, status: needs review

#6748 Render optional children in summary number component
  packages/components/CHANGELOG.md
  packages/components/src/summary/README.md
  packages/components/src/summary/number.js
  packages/components/src/summary/stories/index.js
  readme.txt
Labels: Components, Packages, status: ready to merge

#6698 Updated event tracking for merchant email notes
  src/API/Notes.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/MerchantEmailNotifications/NotificationEmail.php
  src/Notes/Notes.php
Labels: feature: inbox, status: ready to merge

#6803 Update onboarding logic setting task list to hidden
  readme.txt
  src/Features/Onboarding.php
  src/Notes/NoteTraits.php
  src/RemoteInboxNotifications/WCAdminActiveForProvider.php
  src/WCAdminHelper.php
Labels: status: ready to merge

#6804 Add dompurify and md5 to @woocommerce/components dependencies list
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: Build, Components, Packages, needs changelog entry, status: ready to merge

#6806 Bumped version and changelog of component package to 6.1.0
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: Build, Components, Packages, status: needs review

#6808 Update experimental package path, and bump patch version
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: Build, Components, Packages, status: ready to merge

#6766 Update UI for Payment Task Screen
  client/task-list/style.scss
  client/task-list/tasks/payments/components/Action.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.scss
  client/task-list/tasks/payments/components/PaymentMethodList/index.js
  client/task-list/tasks/payments/components/RecommendedRibbon.js
  client/task-list/tasks/payments/components/Setup.js
  client/task-list/tasks/payments/components/WCPayAcceptedMethods.js
  client/task-list/tasks/payments/components/WCPayCard/WCPayCard.js
  client/task-list/tasks/payments/components/WCPayCard/WCPayCard.scss
  client/task-list/tasks/payments/components/WCPayCard/index.js
  client/task-list/tasks/payments/images/cards/amex.js
  client/task-list/tasks/payments/images/cards/applepay.js
  client/task-list/tasks/payments/images/cards/cb.js
  client/task-list/tasks/payments/images/cards/diners.js
  client/task-list/tasks/payments/images/cards/discover.js
  client/task-list/tasks/payments/images/cards/jcb.js
  client/task-list/tasks/payments/images/cards/maestro.js
  client/task-list/tasks/payments/images/cards/mastercard.js
  client/task-list/tasks/payments/images/cards/unionpay.js
  client/task-list/tasks/payments/images/cards/visa.js
  client/task-list/tasks/payments/images/wcpay-logo.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/index.js
  client/task-list/tasks/payments/methods/mercadopago.js
  client/utils/index.js
  readme.txt
Labels: Build, feature: wcpay, needs feedback, status: ready to merge

#6811 Adding setup required indicator for non-configured payment methods
  client/task-list/style.scss
  client/task-list/tasks/payments/components/PaymentAction.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/components/PaymentMethodList/PaymentMethodList.scss
  client/task-list/tasks/payments/components/PaymentSetup.js
  client/task-list/tasks/payments/components/SetupRequired.js
  client/task-list/tasks/payments/components/WCPayAcceptedMethods.js
  client/task-list/tasks/payments/components/WCPayCard/WCPayCard.js
  client/task-list/tasks/payments/components/WCPayCard/WCPayCard.scss
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/index.js
  readme.txt
Labels: feature: wcpay, status: ready to merge

#6812 Add some tweaks to e2e tests to try and resolve flakyness issues
  package-lock.json
  package.json
  tests/e2e/pages/BasePage.ts
  tests/e2e/pages/Login.ts
Labels: Build

#6810 Making experimental package public and updating its dependency versions
  bin/starter-pack/_package.json
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/currency/package.json
  packages/data/package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/dependency-extraction-webpack-plugin/src/index.js
  packages/experimental/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  src/Loader.php
  webpack.config.js
Labels: Build, Components, Packages, status: needs review

#6726 Add Nonce Support to Note Actions
  readme.txt
  src/API/Notes.php
  src/Install.php
  src/Notes/DataStore.php
  src/Notes/Note.php
  tests/api/admin-notes.php
  tests/notes/class-note.php
Labels: status: needs review

#6802 Pause inbox message "GivingFeedbackNotes"
  readme.txt
  src/Events.php
Labels: feature: inbox, status: ready to merge

#6792 Show/hide (extension) task list and move completed tasks to bottom
  client/header/activity-panel/display-options/index.js
  client/header/activity-panel/style.scss
  client/layout/index.js
  client/task-list/index.js
  client/task-list/list.js
  client/task-list/test/index.js
  readme.txt
Labels: feature: setup checklist, has tests, status: ready to merge, type: enhancement

#6818 Detect missed DB version number updates and fix them.
  readme.txt
  src/Install.php
  tests/install.php
Labels: has tests, status: ready to merge, type: bug

#6805 Add plugin installer to allow installation of plugins via URL
  TESTING-INSTRUCTIONS.md
  docs/features/onboarding.md
  readme.txt
  src/API/MarketingOverview.php
  src/API/Plugins.php
  src/FeaturePlugin.php
  src/Features/Homescreen.php
  src/Features/Onboarding.php
  src/Features/ShippingLabelBanner.php
  src/PluginsHelper.php
  src/PluginsInstaller.php
  tests/api/plugins.php
Labels: needs feedback, needs tests, status: ready to merge

#6632 Try: Use the store timezone to make time data requests
  TESTING-INSTRUCTIONS.md
  packages/date/README.md
  packages/date/src/index.js
  packages/date/test/index.js
  readme.txt
  src/Loader.php
Labels: Packages, feature: analytics, status: ready to merge

#6819 Add try catch around JSON parse of users meta values
  packages/data/CHANGELOG.md
  packages/data/src/user/use-user-preferences.js
  readme.txt
Labels: Packages, status: ready to merge, type: bug

#6801 Add event recording to start of gateway connections
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/components/PaymentSetup.js
  client/task-list/tasks/payments/generic-payment-step.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods/eway.js
  client/task-list/tasks/payments/methods/paypal.js
  client/task-list/tasks/payments/methods/square.js
  client/task-list/tasks/payments/methods/stripe.js
  readme.txt
Labels: feature: setup checklist, status: needs review

#6828 Remove PayPal for India
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/methods/index.js
  readme.txt
Labels: priority: high, status: ready to merge, type: bug

#6827 Sort unreleased readme for ease of consumption.
  readme.txt
Labels: status: ready to merge

#6821 Ensure get_active_plugins returns an array to populate preloaded plugin settings
  src/API/Plugins.php
Labels: needs changelog entry, status: ready to merge

#6760 Add recommended payment methods
  .eslintrc.js
  TESTING-INSTRUCTIONS.md
  client/embedded-body-layout/embedded-body-layout.tsx
  client/embedded-body-layout/embedded-body-props.ts
  client/embedded-body-layout/index.ts
  client/embedded-body-layout/style.scss
  client/embedded-body-layout/test/embedded-body-layout.test.tsx
  client/index.js
  client/payments/index.ts
  client/payments/payment-recommendations-wrapper.tsx
  client/payments/payment-recommendations.scss
  client/payments/payment-recommendations.tsx
  client/payments/test/payment-recommendations.test.tsx
  package-lock.json
  package.json
  packages/data/package.json
  packages/data/src/index.ts
  packages/data/src/options/test/with-options-hydration.js
  packages/data/src/options/with-options-hydration.js
  packages/data/src/plugins/action-types.js
  packages/data/src/plugins/action-types.ts
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/actions.ts
  packages/data/src/plugins/index.ts
  packages/data/src/plugins/reducer.js
  packages/data/src/plugins/reducer.ts
  packages/data/src/plugins/resolvers.ts
  packages/data/src/plugins/selectors.js
  packages/data/src/plugins/selectors.ts
  packages/data/src/plugins/test/actions.ts
  packages/data/src/plugins/test/reducer.ts
  packages/data/src/plugins/types.ts
  packages/data/src/plugins/with-plugins-hydration.js
  packages/data/src/plugins/with-plugins-hydration.tsx
  packages/data/src/types.ts
  readme.txt
  src/API/Plugins.php
  src/PaymentPlugins.php
  tests/api/plugins.php
  tests/js/jest.config.json
  typings/global.d.ts
Labels: Build, Packages, needs feedback

#6795 Convert date to timestamp before passing to set_date_prop to persist …
  readme.txt
  src/Notes/Note.php
  tests/notes/class-wc-tests-notes-note.php
Labels: feature: inbox, type: bug

#6838 Disable the continue btn when plugins are being installed/activated
  TESTING-INSTRUCTIONS.md
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#6843 Deleted and re-generated package lock to fix packages
  .github/workflows/e2e.yml
  package-lock.json
  readme.txt
Labels: Build, status: needs review

#6835 Add JS debugger instruction to package.json
  package.json
Labels: Build, cooldown period, status: ready to merge

#6847 Move CES action dispatch to report filter configs.
  client/analytics/report/categories/config.js
  client/analytics/report/categories/index.js
  client/analytics/report/coupons/config.js
  client/analytics/report/coupons/index.js
  client/analytics/report/products/config.js
  client/analytics/report/products/index.js
  client/analytics/report/taxes/config.js
  client/analytics/report/taxes/index.js
  client/analytics/report/variations/config.js
  client/analytics/report/variations/index.js
  readme.txt
Labels: category: extensibility, feature: analytics, feature: customer effort score, needs testing instructions, needs tests, status: ready to merge, type: bug

#6832 SlotFill: Remove Navigation's context
  client/layout/index.js
  client/navigation/components/Item/index.js
  client/navigation/index.js
  packages/navigation/src/index.js
  readme.txt
Labels: Packages, category: extensibility, status: ready to merge

#6787 Refactor <List> to support custom markup
  package-lock.json
  package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/index.js
  packages/components/src/list/experimental-list-item.tsx
  packages/components/src/list/experimental-list.tsx
  packages/components/src/list/index.js
  packages/components/src/list/list-item.js
  packages/components/src/list/stories/index.js
  packages/components/src/list/style.scss
  packages/components/src/list/test/index.js
Labels: Build, Components, Packages, status: ready to merge

#6875 Change `import-wp-css-storybook.sh`'s shebang to portable bash.
  bin/import-wp-css-storybook.sh
  readme.txt
Labels: Build

#6858 Update E2E config to support screenshots on test failure
  .github/workflows/daily-e2e.yml
  .github/workflows/e2e.yml
  .gitignore
  bin/wait-for-build.sh
  readme.txt
  tests/e2e/config/jest.config.js
  typings/index.d.ts
Labels: Build, status: ready to merge

#6830 Try: Use rule processing for remote payment methods
  config/core.json
  config/development.json
  config/plugin.json
  readme.txt
  src/API/Init.php
  src/API/OnboardingPayments.php
  src/Features/RemotePaymentMethods/DataSourcePoller.php
  src/Features/RemotePaymentMethods/EvaluateMethod.php
  src/Features/RemotePaymentMethods/Init.php
  src/RemoteInboxNotifications/RuleEvaluator.php
Labels: status: ready to merge

#6771 Throw custom exception in NoteTraits if notes are disabled
  readme.txt
  src/Composer/Package.php
  src/Notes/InstallJPAndWCSPlugins.php
  src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php
  src/Notes/NavigationFeedbackFollowUp.php
  src/Notes/NavigationNudge.php
  src/Notes/Note.php
  src/Notes/NoteTraits.php
  src/Notes/Notes.php
  src/Notes/NotesUnavailableException.php
  src/Notes/WooCommercePayments.php
  src/Notes/WooSubscriptionsNotes.php
  src/RemoteInboxNotifications/SpecRunner.php
  tests/notes/class-wc-tests-learn-more-about-variable-product.php
  tests/notes/class-wc-tests-marketing-notes.php
  tests/notes/class-wc-tests-note-traits.php
  tests/notes/class-wc-tests-notes.php
Labels: has tests, status: ready to merge, type: bug

#6871 Make ids unique in SearchListControlItem
  packages/components/CHANGELOG.md
  packages/components/src/search-list-control/index.js
  packages/components/src/search-list-control/item.js
  packages/components/src/search-list-control/stories/index.js
  packages/components/src/search-list-control/style.scss
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
Labels: Components, Packages, feature: components, status: ready to merge

#6862 SelectControl: fix display of multiple selections without inline tags.
  packages/components/CHANGELOG.md
  packages/components/src/select-control/index.js
  packages/components/src/select-control/test/index.js
  readme.txt
Labels: Components, Packages, feature: analytics, feature: components, has tests, status: ready to merge, type: bug

#6867 Try: Consume remote payment methods on frontend
  client/task-list/tasks/payments/LocalPayments.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentConnect.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethod.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethodList/PaymentMethodList.js
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethodList/PaymentMethodList.scss
  client/task-list/tasks/payments/RemotePayments/components/PaymentMethodList/index.js
  client/task-list/tasks/payments/RemotePayments/index.js
  client/task-list/tasks/payments/index.js
  client/task-list/test/payments.js
  readme.txt
Labels: status: ready to merge

#6849 Update task list component to make use of new experimental list
  client/task-list/index.js
  client/task-list/list.js
  client/task-list/task-item.scss
  client/task-list/task-item.tsx
  client/task-list/task-step.tsx
  client/task-list/test/index.js
  package-lock.json
  packages/components/src/index.js
  packages/components/src/list/experimental-list.tsx
  packages/customer-effort-score/package.json
  packages/data/src/plugins/selectors.ts
  packages/experimental/CHANGELOG.md
  readme.txt
  tests/e2e/pages/WcHomescreen.ts
Labels: Build, Components, Packages, needs feedback, status: ready to merge

#6894 Remote Payments Feature Flag: change to false
  config/development.json
Labels: needs changelog entry

#6723 Get currency from `CurrencyContext`
  client/profile-wizard/steps/business-details/data/revenue-options.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  readme.txt
Labels: status: ready to merge

#6886 Tweak: change MailPoet's title and description in Store Profiler
  client/profile-wizard/steps/business-details/data/extension-benefits.js
  readme.txt
Labels: feature: onboarding, status: ready to merge

#6829 Setup Checklist: Update PayU logo
  client/task-list/tasks/payments/images/payu-india.js
  readme.txt
Labels: feature: setup checklist, status: ready to merge

#6901 Revert WCPay international support for bundled package
  config/core.json
  readme.txt
Labels: needs changelog entry, status: ready to merge

#6891 Redirect to WC Home after setting up a payment method
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/LocalPayments.js
  readme.txt
Labels: status: ready to merge

#6889 Remove allowed keys list for adding woocommerce_meta data
  packages/data/CHANGELOG.md
  packages/data/src/user/test/use-user-preferences.js
  packages/data/src/user/use-user-preferences.js
  readme.txt
Labels: Packages, category: extensibility, status: ready to merge

#6869 Expand / collapse list items component
  packages/components/CHANGELOG.md
  packages/components/src/index.js
  packages/components/src/list/collapsible-list/index.tsx
  packages/components/src/list/collapsible-list/style.scss
  packages/components/src/list/experimental-list.tsx
  packages/components/src/list/index.js
  packages/components/src/list/stories/index.js
  packages/components/src/list/test/index.js
  packages/components/src/style.scss
Labels: Build, Components, Packages, status: ready to merge

#6905 Un-skip product import test, delete all products in the setup
  readme.txt
  tests/api/onboarding-tasks.php
Labels: status: ready to merge

#6902 Add disabled prop to SelectControl
  packages/components/src/select-control/control.js
  packages/components/src/select-control/index.js
  packages/components/src/select-control/style.scss
  packages/components/src/select-control/test/index.js
  readme.txt
Labels: Components, Packages, status: ready to merge, type: enhancement
