Repository woocommerce/woocommerce-admin, pull requests merged in 2021-02, with the labels that each got.

#6164 Migrate the Travis unit test suite to Github actions
  .github/workflows/e2e.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-test-js.yml
  .github/workflows/test-php.yml
  .travis.yml
  bin/ci/gh-install-wp-tests.sh
  bin/js_lint_test.sh
  bin/phpcs.sh
Labels: Build, status: in progress

#6119 Add WooCommerce Version Selection to Docker PHP Test Suite
  docker/wc-admin-php-test-suite/docker-compose.yml
  docker/wc-admin-php-test-suite/entrypoint.sh
  docker/wc-admin-php-test-suite/readme.md
Labels: status: needs review

#6226 Adding checkbox role to chart legend component to make it compatible with screen readers
  packages/components/src/chart/d3chart/legend.js
  packages/components/src/chart/d3chart/test/legend.js
Labels: Components, Packages, category: accessibility, status: ready to merge

#6225 Landmark link display is cut off when new navigation is enabled
  client/navigation/style.scss
Labels: category: accessibility, feature: navigation, status: ready to merge

#6234 Changing headings on report tables to use semantic tags
  client/analytics/components/leaderboard/test/__snapshots__/index.js.snap
  packages/components/src/table/index.js
Labels: Components, Packages, category: accessibility, status: ready to merge

#6183 Update README.md spelling
  docs/examples/extensions/README.md
Labels: Build, needs feedback, status: ready to merge

#6224 Adding text labels to elements that were previously invisible to screen readers
  client/dashboard/dashboard-charts/index.js
  client/navigation/components/header/index.js
Labels: category: accessibility, status: ready to merge

#6232 Addressing 'sort by undefined' issue with screen readers in reports t…
  packages/components/CHANGELOG.md
  packages/components/src/table/table.js
Labels: Components, Packages, category: accessibility, status: ready to merge

#6227 Adding role to focusable elements in analytics charts for screen reader accessibility
  packages/components/src/chart/d3chart/utils/line-chart.js
Labels: Components, Packages, category: accessibility, needs feedback

#6198 Remove header height
  client/stylesheets/shared/_embed.scss
Labels: needs feedback, status: ready to merge

#6167 Check current user's install plugin capability before rendering
  client/homescreen/stats-overview/install-jetpack-cta.js
  src/Loader.php
Labels: status: needs review

#6260 Fixed the Add First Product email note checks
  images/admin_notes/img-product-light.png
  images/admin_notes/openbox+purple.png
  includes/emails/html-merchant-notification.php
  readme.txt
  src/Notes/AddFirstProduct.php
Labels: needs cherry picking, status: ready to merge

#6238 Add settings menu items on non-settings pages
  src/Features/Navigation/CoreMenu.php
Labels: feature: navigation, priority: high, status: ready to merge

#6228 Dependency Extraction Webpack Plugin: Add Woo Blocks packages
  .gitignore
  bin/packages/build.js
  packages/README.md
  packages/dependency-extraction-webpack-plugin/README.md
  packages/dependency-extraction-webpack-plugin/assets/packages.js
  packages/dependency-extraction-webpack-plugin/src/index.js
Labels: Build, Packages, status: ready to merge

#6217 Refactor WCA plugin outdated version check to run on 'woocommerce_init' hook
  src/Composer/Package.php
Labels: status: ready to merge

#6259 Added extended task list refactor to readme.txt
  readme.txt
Labels: status: ready to merge

#6165 Add WooCommerce flyout menu
  packages/navigation/src/style.scss
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Init.php
  src/Features/Navigation/Menu.php
Labels: Packages, feature: navigation, needs feedback

#6271 Onboarding - Fixed "Business Details" error
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  readme.txt
Labels: needs cherry picking, status: ready to merge, type: bug

#6273 Skip intermittent failing test
  tests/api/onboarding-tasks.php
Labels: status: ready to merge

#6256 Add/testing instructions
  .github/PULL_REQUEST_TEMPLATE.md
  TESTING-INSTRUCTIONS.md
Labels: Build, status: ready to merge

#6278 Skip extensions in navigation flyout menu
  src/Features/Navigation/CoreMenu.php
Labels: feature: navigation, status: ready to merge

#6257 Add the Mollie payment provider setup task
  .github/workflows/lint-test-js.yml
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/images/mollie.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/mollie.js
  client/task-list/test/payments.js
  package-lock.json
  packages/components/package.json
  packages/data/src/plugins/actions.js
  readme.txt
  src/API/Plugins.php
  src/Features/Onboarding.php
Labels: Build, Components, Packages, status: ready to merge

#6090 Change from MenuGroup to label
  packages/components/CHANGELOG.md
  packages/components/src/search-list-control/icons/checkbox-checked.js
  packages/components/src/search-list-control/icons/checkbox-unchecked.js
  packages/components/src/search-list-control/icons/index.js
  packages/components/src/search-list-control/icons/radio-selected.js
  packages/components/src/search-list-control/icons/radio-unselected.js
  packages/components/src/search-list-control/index.js
  packages/components/src/search-list-control/item.js
  packages/components/src/search-list-control/stories/index.js
  packages/components/src/search-list-control/style.scss
  packages/components/src/search-list-control/test/__snapshots__/index.js.snap
Labels: Components, Packages, needs feedback

#6261 Add paypal commerce obw integration
  TESTING-INSTRUCTIONS.md
  client/header/activity-panel/panels/help.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/paypal.js
  client/task-list/test/payments.js
  docs/features/onboarding.md
  packages/data/src/plugins/action-types.js
  packages/data/src/plugins/actions.js
  packages/data/src/plugins/constants.js
  packages/data/src/plugins/reducer.js
  packages/data/src/plugins/resolvers.js
  packages/data/src/plugins/selectors.js
  readme.txt
  src/API/Options.php
  src/API/Plugins.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks.php
Labels: Packages, feature: onboarding, status: needs review

#6270 Adding Favorite API Class to Navigation Feature
  src/Features/Navigation/Favorites.php
Labels: feature: navigation, status: needs review

#6253 Separate secondary items into separate menu in navigation
  client/navigation/components/container/index.js
  client/navigation/components/container/style.scss
  client/navigation/style.scss
Labels: feature: navigation, status: ready to merge

#6245 Add WordPress Version Selection to Docker PHP Test Suite
  bin/install-wp-tests.sh
  docker/wc-admin-php-test-suite/docker-compose.yml
  docker/wc-admin-php-test-suite/entrypoint.sh
  docker/wc-admin-php-test-suite/readme.md
Labels: Build, status: ready to merge

#6254 Navigation: Add temp override to fix Gutenberg item CSS
  client/navigation/components/container/style.scss
Labels: feature: navigation, needs cherry picking, status: ready to merge

#6268 Dependency Extraction Webpack Plugin: bump version to 1.2
  bin/starter-pack/_package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
Labels: Build, Packages, status: ready to merge

#6294 Navigation: Return $menu when no child items exist
  src/Features/Navigation/Menu.php
Labels: feature: navigation, needs cherry picking, status: needs review

#6281 Make sure that industry is defined in payment methods
  client/task-list/tasks/payments/methods.js
Labels: needs cherry picking, status: ready to merge, type: bug

#6286 Fix the react state update error on homescreen
  client/header/activity-panel/unread-indicators.js
  client/inbox-panel/index.js
  client/layout/store-alerts/index.js
  client/layout/store-alerts/test/index.js
  client/layout/transient-notices/index.js
  client/layout/transient-notices/test/index.js
  package-lock.json
  packages/data/package.json
  packages/data/src/notes/selectors.js
  packages/data/src/notes/test/selectors.js
Labels: Build, Packages, status: needs review, type: bug

#6083 Adjust the timing of the Marketing.php note to 5 days.
  readme.txt
  src/Notes/Marketing.php
  tests/notes/class-wc-marketing.php
Labels: feature: inbox

#6277 Add a new note with a link to the downloadable product doc
  src/Events.php
  src/Notes/FirstDownlaodableProduct.php
Labels: feature: inbox, status: ready to merge

#6295 Fixes for @woocommerce/dependency-extraction-webpack-plugin
  bin/starter-pack/_package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/README.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/dependency-extraction-webpack-plugin/src/index.js
Labels: Build, Packages, status: needs review

#6282 Adding Navigation Favorites REST API Endpoints
  src/API/Init.php
  src/API/NavigationFavorites.php
  src/Features/Navigation/Favorites.php
Labels: feature: navigation, feature: rest api, needs feedback, status: ready to merge

#6291 Show management links when main task list is hidden
  client/homescreen/layout.js
  client/homescreen/test/index.js
  readme.txt
Labels: needs cherry picking, status: needs review, type: bug

#6275 Add navigation favorites data store
  packages/data/src/navigation/action-types.js
  packages/data/src/navigation/actions.js
  packages/data/src/navigation/index.js
  packages/data/src/navigation/reducer.js
  packages/data/src/navigation/resolvers.js
  packages/data/src/navigation/selectors.js
  packages/data/src/navigation/test/reducer.js
Labels: Packages, feature: navigation, status: ready to merge

#6309 Update highlight tooltip to make use of anchor logic
  client/header/activity-panel/highlight-tooltip/index.js
  client/header/activity-panel/index.js
  readme.txt
Labels: status: ready to merge

#6240 Change `siteUrl` to `homeUrl` on navigation site title
  client/navigation/components/header/index.js
  src/Loader.php
Labels: status: ready to merge

#6298 Updated copy in task lists
  client/homescreen/activity-panel/stock/card.js
  client/homescreen/welcome-from-calypso-modal/welcome-from-calypso-modal.js
  client/homescreen/welcome-modal/index.js
  client/inbox-panel/action.js
  client/profile-wizard/index.js
  client/profile-wizard/steps/benefits/index.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/industry.js
  client/profile-wizard/steps/product-types/index.js
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/theme/index.js
  client/profile-wizard/steps/usage-modal.js
  client/task-list/index.js
  client/task-list/tasks.js
  client/task-list/tasks/appearance.js
  client/task-list/tasks/connect.js
  client/task-list/tasks/products/products.js
  client/task-list/tasks/shipping/index.js
  client/task-list/tasks/shipping/rates.js
  client/task-list/tasks/steps/location.js
  client/task-list/tasks/tax.js
  client/task-list/test/index.js
  client/task-list/test/products.js
  composer.lock
  src/API/OnboardingTasks.php
Labels: status: ready to merge

#6310 Move admin menu manipulation from admin_head to admin_menu
  src/Features/Homescreen.php
Labels: needs cherry picking

#6320 Fix a bug where the incorrect index was set for alerts.
  client/layout/store-alerts/index.js
Labels: status: needs review, type: bug

#6321 Bump versions to 2.1.0-dev
  TESTING-INSTRUCTIONS.md
  composer.json
  package-lock.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: ready to merge

#6328 Fix removal of core settings pages
  src/Features/Navigation/Menu.php
Labels: feature: navigation, needs cherry picking, priority: critical, status: ready to merge, type: bug

#6325 Build: Update Jetpack Autoloader dependency.
  composer.json
  composer.lock
Labels: Build, needs cherry picking, status: ready to merge

#6330 Bump minimum WP version to 5.4
  woocommerce-admin.php
Labels: status: ready to merge

#6247 Try: Refactor head and body heights
  client/header/activity-panel/style.scss
  client/header/index.js
  client/header/style.scss
  client/header/test/index.js
  client/index.js
  client/layout/style.scss
  client/navigation/components/container/index.js
  client/navigation/components/container/style.scss
  client/navigation/style.scss
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_reset.scss
  src/Features/Navigation/Init.php
Labels: needs feedback

#6287 Add favoriting extensions client UI
  client/navigation/components/category-title/index.js
  client/navigation/components/category-title/style.scss
  client/navigation/components/container/index.js
  client/navigation/components/container/style.scss
Labels: feature: navigation, status: in progress, status: ready to merge

#6089 Try: Add the settings feature and pages
  config/core.json
  config/development.json
  config/plugin.json
  src/Features/Features.php
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
  src/Features/Settings.php
Labels: feature: settings, status: ready to merge

#6092 Add settings client pages and plumbing
  client/analytics/report/get-reports.js
  client/layout/controller.js
  client/settings/index.js
  client/wc-admin-settings/index.js
  docs/examples/extensions/examples.config.js
  src/Features/Settings.php
  tests/js/jest.config.json
  webpack.config.js
Labels: Build, feature: settings, status: ready to merge

#6336 Fix navigation priority settings conflict
  client/header/index.js
  client/navigation/components/container/index.js
  client/navigation/style.scss
  src/Features/Navigation/Menu.php
Labels: feature: navigation, status: needs review, type: bug

#6091 Add core settings redirection to new settings pages
  src/Features/Settings.php
Labels: feature: settings, status: ready to merge

#6331 Dependency Extraction Webpack Plugin: Add @woocommerce/settings to list of packages
  bin/starter-pack/_package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/assets/packages.js
  packages/dependency-extraction-webpack-plugin/package.json
Labels: Build, Packages, status: needs review

#5236 Shell script to release a tagged version to wordpress.org
  bin/release-plugin-to-dot-org.sh
Labels: Build, needs feedback

#6318 Stalebot: Update label exclusion list.
  .github/workflows/stale.yml
Labels: Build, status: ready to merge

#6329 Remove categories without menu items
  client/navigation/components/Item/index.js
  docs/features/navigation.md
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
Labels: feature: navigation, status: ready to merge

#6173 Small documentation fix
  src/Features/Navigation/Screen.php
Labels: needs feedback

#6335 Use box sizing and padding to fix nav and admin menu styling
  client/layout/style.scss
  client/navigation/style.scss
  client/stylesheets/shared/_embed.scss
  client/stylesheets/shared/_reset.scss
Labels: status: needs review, type: bug

#6290 Move favorited menu items to primary menu
  client/navigation/components/category-title/index.js
  client/navigation/components/container/index.js
  packages/data/src/navigation/reducer.js
  packages/data/src/navigation/test/reducer.js
  src/Features/Navigation/Menu.php
Labels: Build, Components, Packages, feature: navigation, status: ready to merge

#6233 Refactor panel with withFocusOutside
  client/header/activity-panel/index.js
  client/header/activity-panel/panel.js
  client/hooks/useFocusOnMount.js
  client/hooks/useFocusOutside.js
  package-lock.json
  package.json
Labels: Build, status: needs review

#6332 Implement the PayU payment task and fix a bug
  client/task-list/tasks/payments/images/payu-india.js
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/methods.js
  client/task-list/tasks/payments/payu-india.js
  client/task-list/test/payments.js
  readme.txt
  src/Features/Onboarding.php
Labels: status: ready to merge

#6347 Fix Markdown formatting in page-controller.md
  docs/page-controller.md
Labels: status: ready to merge

#6355 Remove CES actions for adding and editing a product and editing an order
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
Labels: status: needs review

#6312 Add the favorites tooltip to the navigation
  client/navigation/components/category-title/index.js
  client/navigation/components/category-title/style.scss
  client/navigation/components/favorite-button/index.js
  client/navigation/components/favorite-button/style.scss
  client/navigation/components/favorites-tooltip/index.js
Labels: Packages, feature: navigation, status: ready to merge

#6343 Remove googlefonts/material icons. Migrate to @wordpress/icons and gridicons
  client/header/activity-panel/index.js
  client/profile-wizard/steps/business-details/flows/bundle/index.js
  client/profile-wizard/steps/product-types/label.js
  client/profile-wizard/steps/product-types/product-type.js
  client/profile-wizard/steps/product-types/test/__snapshots__/index.js.snap
  client/profile-wizard/steps/product-types/test/__snapshots__/product-type.js.snap
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/theme/preview.js
  client/profile-wizard/style.scss
  client/task-list/tasks/products/products.js
  client/task-list/tasks/shipping/rates.js
  packages/components/package.json
  packages/components/src/list/style.scss
  packages/components/src/search/style.scss
  packages/components/src/select-control/control.js
  readme.txt
  src/Loader.php
Labels: Build, Components, Packages, status: ready to merge

#6348 New Settings: Turn off in dev mode
  config/development.json
Labels: status: ready to merge

#6322 Set `is_deleted` from the database when instantiating a `Note`
  src/Notes/DataStore.php
Labels: status: ready to merge

#6356 Refactor test:php npm script to use a post script
  package.json
Labels: Build, status: ready to merge

#6246 Cache initial read time
  client/inbox-panel/index.js
Labels: status: ready to merge

#6229 Check if tax was successfully added before notice
  client/wp-admin-scripts/onboarding-tax-notice/index.js
  package.json
Labels: Build, status: ready to merge

#6354 override wpbody styles when nav present
  client/layout/style.scss
Labels: status: ready to merge

#6366 Fix empty nav menu
  client/navigation/components/container/index.js
Labels: feature: navigation, status: ready to merge

#6344 Navigation: Add test to container component
  client/navigation/components/container/index.js
  client/navigation/components/container/test/index.js
  package-lock.json
  readme.txt
Labels: feature: navigation, needs feedback, status: ready to merge

#6358 Enqueue beta features scripts on enqueue_scripts action instead of filter
  readme.txt
  src/Features/Features.php
Labels: needs feedback, type: bug

#6342 Update Minimum version in docs and test configs
  .github/workflows/test-php.yml
  README.md
  docker/wc-admin-php-test-suite/docker-compose.yml
  docs/README.md
  readme.txt
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: needs review

#6378 Add missing testing instructions
  TESTING-INSTRUCTIONS.md
Labels: status: needs review

#6371 Add filter to allow the wp toolbar in navigation
  client/header/style.scss
  client/layout/style.scss
  client/navigation/style.scss
  client/profile-wizard/index.js
  docs/features/navigation.md
  readme.txt
  src/Features/Navigation/Screen.php
Labels: feature: navigation, status: ready to merge

#6365 Move capability checks to client
  TESTING-INSTRUCTIONS.md
  client/header/activity-panel/index.js
  client/header/activity-panel/test/index.js
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/layout/controller.js
  client/layout/index.js
  packages/data/src/index.js
  packages/data/src/user/constants.js
  packages/data/src/user/index.js
  packages/data/src/user/test/use-user-preferences.js
  packages/data/src/user/use-user-preferences.js
  packages/data/src/user/use-user.js
  packages/data/src/user/with-current-user-hydration.js
  src/Features/Features.php
  src/Features/Homescreen.php
  src/Loader.php
Labels: Packages, status: ready to merge

#6374 Removed @woocommerce/components/card from OBW
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/style.scss
  client/profile-wizard/steps/business-details/style.scss
  client/profile-wizard/steps/product-types/style.scss
  readme.txt
Labels: status: ready to merge

#6324 Email notes now are turned off by default
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Events.php
Labels: status: ready to merge

#6373 Order and styles updates to nav footer
  client/navigation/components/container/style.scss
  src/Features/Navigation/CoreMenu.php
Labels: needs feedback, status: ready to merge

#6375 Update overflow visible on card media
  client/task-list/tasks/payments/index.js
Labels: status: ready to merge

#6297 update single column home screen width to 680px
  client/homescreen/style.scss
Labels: Trash Pickup, needs feedback, status: ready to merge

#6368 Add CES track settings tab on updating settings
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/CustomerEffortScoreTracks.php
  tests/features/class-wc-tests-ces-tracks.php
Labels: feature: customer effort score, status: ready to merge

#6142 Hide tooltip in welcome modal
  client/layout/style.scss
Labels: status: needs review

#6292 Apply responsive header style to all pages
  client/header/style.scss
  client/stylesheets/shared/_reset.scss
Labels: status: needs review

#6367 Add navigation intro modal
  TESTING-INSTRUCTIONS.md
  client/homescreen/constants.js
  client/homescreen/layout.js
  client/navigation/components/intro-modal/index.js
  client/navigation/components/intro-modal/style.scss
  readme.txt
Labels: feature: navigation, needs feedback, status: needs review, status: ready to merge

#6382 Refactor menu item mapping and sorting
  TESTING-INSTRUCTIONS.md
  client/navigation/components/container/index.js
  client/navigation/components/container/primary-menu.js
  client/navigation/components/container/secondary-menu.js
  client/navigation/components/container/test/index.js
  client/navigation/test/utils.js
  client/navigation/utils.js
  src/Features/Navigation/CoreMenu.php
  src/Features/Navigation/Menu.php
Labels: feature: navigation, needs feedback, status: ready to merge

#6403 Add missing changelog entries for 2.1 release
  readme.txt
Labels: status: needs review

#6410 Update Testing Instructions for 2.1.0
  TESTING-INSTRUCTIONS.md
Labels: status: needs review

#6396 Navigation: Reset submenu before making Flyout
  TESTING-INSTRUCTIONS.md
  package.json
  readme.txt
  src/Features/Navigation/Menu.php
Labels: Build, feature: navigation, status: needs review

#6285 Add tracks event for WooCommerce Payments install via tasklist and inbox note
  client/task-list/tasks/payments/methods.js
  src/Notes/WooCommercePayments.php
Labels: needs feedback

#6408 Move the shipping input and text 1px lower
  client/task-list/style.scss
  readme.txt
Labels: status: ready to merge

#6411 Allow for use of Array.flat in wc-admin client / packages
  bin/packages/get-babel-config.js
  package-lock.json
  package.json
  readme.txt
  webpack.config.js
Labels: Build, status: ready to merge

#6414 Add a changelog lint check and auto-labelling
  .github/actions/pr-labeler/README.md
  .github/actions/pr-labeler/action.yml
  .github/actions/pr-labeler/dist/index.js
  .github/actions/pr-labeler/index.js
  .github/actions/pr-labeler/package-lock.json
  .github/actions/pr-labeler/package.json
  .github/workflows/lint-changelog.yml
  .gitignore
  bin/ci/lint-changelog.sh
  readme.txt
Labels: Build, status: needs review

#6412 Remove 1 global from main file
  readme.txt
  woocommerce-admin.php
Labels: needs changelog entry, needs feedback

#6421 Add navigation screen unit tests
  tests/navigation/class-wc-screen.php
Labels: cooldown period, feature: navigation, status: ready to merge

#6443 Improve changelog linting automation
  .github/workflows/lint-changelog.yml
Labels: Build, status: needs review

#6440 Correct the Klarna slug
  TESTING-INSTRUCTIONS.md
  client/task-list/tasks/payments/index.js
  client/task-list/tasks/payments/klarna.js
  readme.txt
Labels: needs cherry picking, status: ready to merge

#6432 Fix the onTransitionEnd callback
  client/header/activity-panel/index.js
  client/header/activity-panel/panel.js
  client/header/activity-panel/test/index.js
Labels: needs changelog entry, needs cherry picking, status: ready to merge, type: bug

#6417 Bump Version to 2.2.0-dev
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: Build, status: needs review

#6455 Update Broken Link Anchors to Online Support
  client/header/activity-panel/panels/help.js
  readme.txt
Labels: needs cherry picking, status: needs review

#6401 Deprecate Onboarding::has_woocommerce_support
  TESTING-INSTRUCTIONS.md
  readme.txt
  src/Features/Onboarding.php
Labels: status: ready to merge

#6462 Checking if navigation is in the process of being enabled while initializing
  TESTING-INSTRUCTIONS.md
  package-lock.json
  readme.txt
  src/Features/Navigation/Init.php
Labels: needs feedback, priority: high, status: ready to merge

#5762 Add Dependency Extraction Webpack Plugin
  bin/make-zip.sh
  client/layout/index.js
  package-lock.json
  package.json
  packages/data/src/index.js
  packages/notices/src/index.js
  readme.txt
  src/Features/Coupons.php
  src/Features/Navigation/Init.php
  src/Features/OnboardingTasks.php
  src/Features/ShippingLabelBanner.php
  src/Loader.php
  webpack.config.js
Labels: Build, Packages, status: ready to merge
