Repository woocommerce/woocommerce-admin, pull requests merged in 2022-03, with the labels that each got.

#8372 Enable Typescript checking on ./client folder
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  changelogs/chore-enable-ts-for-client
  client/homescreen/stats-overview/install-jetpack-cta.js
  client/jest.config.js
  client/jest.config.json
  client/tsconfig.json
  client/tsconfig.test.json
  package-lock.json
  package.json
  packages/admin-e2e-tests/tsconfig.json
  packages/components/tsconfig.json
  packages/data/src/constants.ts
  packages/explat/package.json
  packages/explat/tsconfig.json
  packages/js-tests/package.json
  packages/js-tests/tsconfig-cjs.json
  packages/js-tests/tsconfig.json
  packages/tsconfig.json
  patches/@automattic+explat-client-react-helpers+0.0.3.patch
  tsconfig.json
Labels: status: ready to merge, Build, Packages, Components

#8391 Fix view logic for Setup additional payment providers task
  changelogs/fix-extended-payments
  src/Features/OnboardingTasks/Tasks/AdditionalPayments.php
Labels: status: ready to merge

#8380 Remove the use of preloaded countries
  changelogs/fix-8373_dataendpoints_countries
  client/analytics/report/customers/config.js
  client/analytics/report/customers/table.js
  client/dashboard/components/settings/general/store-address.tsx
  client/profile-wizard/steps/store-details/index.js
  client/tasks/fills/shipping/index.js
  client/tasks/fills/steps/location.js
  packages/data/src/countries/action-types.ts
  packages/data/src/countries/actions.ts
  packages/data/src/countries/reducer.ts
  packages/data/src/countries/resolvers.ts
  packages/data/src/countries/selectors.ts
  packages/data/src/countries/types.ts
  packages/data/src/index.ts
  packages/js-tests/src/setup-globals.js
  src-internal/Admin/Analytics.php
  src/Features/Onboarding.php
Labels: status: ready to merge, Packages

#8394 Stop showing actioned inbox items
  changelogs/fix-hide-actioned-notifications
  client/inbox-panel/index.js
Labels: status: needs review, feature: inbox

#8389 Redirect customers back to the payment task after enabling an offline gateway
  changelogs/update-8242-tweak-flow-after-setting-up-offline-payments
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  client/tasks/task.tsx
Labels: status: ready to merge

#8395 Update/version 3.4.0 dev
  TESTING-INSTRUCTIONS.md
  composer.json
  package-lock.json
  package.json
  readme.txt
  src-internal/Admin/FeaturePlugin.php
  src/Composer/Package.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#8404 Fix inbox letters truncator to support multi characters
  changelogs/fix-8005-multi-characters-inbox-letters-truncator
  client/inbox-panel/index.js
  client/inbox-panel/test/utils.js
  client/inbox-panel/utils.js
  package.json
  pnpm-lock.yaml
Labels: status: needs review, Build

#8410 Fix build "docs"
  package.json
Labels: status: needs review, Build

#8399 Use integers for add_menu_page priority
  changelogs/fix-82910-add-menu-page-invalid-parameter
  src-internal/Admin/Analytics.php
  src-internal/Admin/WcPayWelcomePage.php
  src/PageController.php
Labels: status: needs review

#8411 Reintroduce emphasis on inbox note action button
  changelogs/fix-84080-reintroduce-emphasis-on-inbox-note-action-button
  packages/experimental/src/inbox-note/action.tsx
  packages/experimental/src/inbox-note/inbox-note.tsx
  packages/experimental/src/inbox-note/style.scss
Labels: status: needs review, Packages

#8421 Use update_option instead of delete_option + add_option
  src-internal/Admin/Install.php
Labels: status: ready to merge

#8392 Update all js packages with minor/patch version changes
  changelogs/update-js-deps
  package.json
  packages/admin-e2e-tests/CHANGELOG.md
  packages/admin-e2e-tests/package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/csv-export/CHANGELOG.md
  packages/csv-export/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/customer-effort-score/CHANGELOG.md
  packages/customer-effort-score/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/data/src/countries/actions.ts
  packages/data/src/countries/resolvers.ts
  packages/data/src/payment-gateways/actions.ts
  packages/data/src/payment-gateways/resolvers.ts
  packages/data/src/payment-gateways/selectors.ts
  packages/data/src/payment-gateways/types.ts
  packages/data/src/plugins/actions.ts
  packages/data/src/plugins/resolvers.ts
  packages/data/src/plugins/test/actions.ts
  packages/data/src/types/api.ts
  packages/data/src/types/index.ts
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/explat/CHANGELOG.md
  packages/explat/package.json
  packages/js-tests/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/notices/CHANGELOG.md
  packages/notices/package.json
  packages/number/CHANGELOG.md
  packages/number/package.json
  packages/onboarding/package.json
  packages/style-build/package.json
  packages/tracks/CHANGELOG.md
  packages/tracks/package.json
  pnpm-lock.yaml
Labels: status: ready to merge, Build, Packages, Components

#8423 Run woocommerce_admin_updated as a scheduled action
  src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php
Labels: status: ready to merge

#8401 Fix long notes are not replaced with shorter notes
  changelogs/fix-8008-long-notes-are-not-replaced-with-shorter-notes
  src-internal/Admin/Events.php
  src/Notes/NoteTraits.php
  tests/notes/class-wc-tests-note-traits.php
Labels: status: ready to merge

#8416 Cleanup Loader.php and move it to Internal namespace
  bin/starter-pack/_main.php
  changelogs/update-8268_loader
  docs/examples/extensions/add-abbreviated-notification/woocommerce-admin-add-abbreviated-notification-example.php
  docs/examples/extensions/add-report/woocommerce-admin-add-report-example.php
  docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php
  docs/examples/extensions/dashboard-section/woocommerce-admin-dashboard-section.php
  docs/examples/extensions/important-admin-notice/woocommerce-admin-important-admin-notice-example.php
  docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php
  docs/examples/extensions/table-column/woocommerce-admin-table-column.php
  includes/core-functions.php
  src-internal/Admin/ActivityPanels.php
  src-internal/Admin/CategoryLookup.php
  src-internal/Admin/Coupons.php
  src-internal/Admin/FeaturePlugin.php
  src-internal/Admin/Homescreen.php
  src-internal/Admin/Loader.php
  src-internal/Admin/Marketing.php
  src-internal/Admin/ShippingLabelBanner.php
  src-internal/Admin/Translations.php
  src-internal/Admin/WCAdminAssets.php
  src-internal/Admin/WCAdminUser.php
  src-internal/Admin/WCPayPromotion/Init.php
  src/API/Init.php
  src/Features/Features.php
  src/Features/Navigation/Favorites.php
  src/Features/Navigation/Init.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks/Init.php
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/Appearance.php
  src/Features/OnboardingTasks/Tasks/Products.php
  src/Features/OnboardingTasks/Tasks/Tax.php
  src/Features/TransientNotices.php
  src/Loader.php
  src/Marketing/InstalledExtensions.php
  src/PageController.php
  tests/wc-admin-assets.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#8432 Fixing home item appearing in extensions menu on Woo Navigation
  src/Features/Navigation/CoreMenu.php
Labels: status: ready to merge

#8442 Fix legend item width
  TESTING-INSTRUCTIONS.md
  changelogs/fix-8442
  packages/components/src/chart/d3chart/legend.scss
Labels: status: ready to merge, Packages, needs cherry picking, Components

#8455 Fix error possibly_update_note call to get_content() on null
  src/Notes/NoteTraits.php
Labels: status: ready to merge

#8456 Fix failing `test_cancel_import` and `WC_Tests_API_Reports_Variations` php tests
  tests/api/reports-import.php
  tests/api/reports-variations.php
Labels: status: ready to merge, Build

#8206 Avoid get_notes() in Notes::possibly_delete_survey_notes()
  changelogs/fix-7987-avoid-get_notes-in-possibly-delete-survey-note
  src/Notes/DataStore.php
  src/Notes/Notes.php
Labels: status: ready to merge

#8446 Removed not used `OnboardingEmailMarketing` reference
  src-internal/Admin/Events.php
Labels: status: ready to merge

#8458 Add `moment-timezone` to `@woocommerce/components` package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  pnpm-lock.yaml
Labels: status: ready to merge, Build, Packages, Components

#8466 Add `:preserveSemverRanges` to renovate.json
  renovate.json
Labels: status: ready to merge

#8445 Display WCPay task when installed via subscriptions option on profiler
  TESTING-INSTRUCTIONS.md
  changelogs/update-8240
  src/Features/OnboardingTasks/Tasks/WooCommercePayments.php
Labels: status: ready to merge

#8412 Fix paid themes
  changelogs/fix-8397_fix_paid_themes
  src/Features/OnboardingTasks/Tasks/Purchase.php
  tests/features/onboarding-tasks/tasks/purchase.php
Labels: status: ready to merge, needs cherry picking

#8462 Experimental: Add filters to allow simple products to be included in Variations analytics report
  client/analytics/report/variations/table.js
  src/API/Reports/Variations/Controller.php
  src/API/Reports/Variations/DataStore.php
  src/API/Reports/Variations/Stats/Controller.php
  src/API/Reports/Variations/Stats/DataStore.php
Labels: status: ready to merge, feature: analytics

#8451 Use constant to construct image URLs
  client/payments-welcome/style.scss
  client/payments-welcome/wcpay-banner.png
  client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js
  src-internal/Admin/FeaturePlugin.php
  src-internal/Admin/Loader.php
  src-internal/Admin/Notes/MarketingJetpack.php
  src/API/OnboardingTasks.php
  src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
  src/Marketing/InstalledExtensions.php
Labels: status: ready to merge

#8436 Add required dependencies for pnpm nx build {package} command
  package.json
  packages/admin-e2e-tests/package.json
  packages/components/package.json
  packages/components/src/advanced-filters/test/advanced-filters.test.js
  packages/components/src/compare-filter/stories/index.js
  packages/components/src/filter-picker/stories/index.js
  packages/csv-export/package.json
  packages/currency/package.json
  packages/customer-effort-score/package.json
  packages/data/package.json
  packages/date/package.json
  packages/dependency-extraction-webpack-plugin/package.json
  packages/eslint-plugin/package.json
  packages/experimental/package.json
  packages/explat/package.json
  packages/js-tests/package.json
  packages/navigation/package.json
  packages/notices/package.json
  packages/number/package.json
  packages/onboarding/package.json
  packages/style-build/package.json
  packages/tracks/package.json
  pnpm-lock.yaml
Labels: status: ready to merge, Build, Packages, Components

#8465 Update `@woocommerce/date` documentation
  packages/date/README.md
Labels: status: ready to merge, Packages

#8464 Update @types/wordpress__notices version to fix type error
  package.json
  pnpm-lock.yaml
Labels: status: ready to merge, Build

#8461 Remove class `ExtendedPayments`.
  changelogs/fix-8414
  src/Features/OnboardingTasks/TaskLists.php
  src/Features/OnboardingTasks/Tasks/AdditionalPayments.php
  src/Features/OnboardingTasks/Tasks/ExtendedPayments.php
Labels: status: ready to merge, needs cherry picking

#8428 Add capability for ExPlat integration to authenticate WPCOM users
  changelogs/add-8071-add-wpcom-authentication-for-explat
  includes/class-experimental-abtest.php
  packages/explat/CHANGELOG.md
  packages/explat/README.md
  packages/explat/package.json
  packages/explat/src/assignment.ts
  packages/explat/src/index.ts
  packages/explat/src/test/assignment-test.js
  pnpm-lock.yaml
  src/API/Experiments.php
  src/API/Init.php
  tests/api/experiments.php
  tests/includes/class-experimental-abtest-test.php
Labels: status: ready to merge, Build, Packages

#8429 Add/8269 rest api docs
  changelogs/add-8269_rest_api_docs
  src/API/Coupons.php
  src/API/CustomAttributeTraits.php
  src/API/Customers.php
  src/API/Data.php
  src/API/DataCountries.php
  src/API/DataDownloadIPs.php
  src/API/Features.php
  src/API/Init.php
  src/API/Leaderboards.php
  src/API/Marketing.php
  src/API/MarketingOverview.php
  src/API/NavigationFavorites.php
  src/API/NoteActions.php
  src/API/Notes.php
  src/API/OnboardingFreeExtensions.php
  src/API/OnboardingProductTypes.php
  src/API/OnboardingProfile.php
  src/API/OnboardingTasks.php
  src/API/OnboardingThemes.php
  src/API/Orders.php
  src/API/PaymentGatewaySuggestions.php
  src/API/Plugins.php
  src/API/ProductAttributeTerms.php
  src/API/ProductAttributes.php
  src/API/ProductCategories.php
  src/API/ProductReviews.php
  src/API/ProductVariations.php
  src/API/Products.php
  src/API/ProductsLowInStock.php
  src/API/Reports/Categories/Controller.php
  src/API/Reports/Controller.php
  src/API/Reports/Coupons/Controller.php
  src/API/Reports/Coupons/Stats/Controller.php
  src/API/Reports/Customers/Controller.php
  src/API/Reports/Customers/Stats/Controller.php
  src/API/Reports/Downloads/Controller.php
  src/API/Reports/Downloads/Files/Controller.php
  src/API/Reports/Downloads/Stats/Controller.php
  src/API/Reports/Export/Controller.php
  src/API/Reports/Import/Controller.php
  src/API/Reports/Orders/Controller.php
  src/API/Reports/Orders/Stats/Controller.php
  src/API/Reports/PerformanceIndicators/Controller.php
  src/API/Reports/Products/Controller.php
  src/API/Reports/Products/Stats/Controller.php
  src/API/Reports/Revenue/Stats/Controller.php
  src/API/Reports/Stock/Controller.php
  src/API/Reports/Stock/Stats/Controller.php
  src/API/Reports/Taxes/Controller.php
  src/API/Reports/Taxes/Stats/Controller.php
  src/API/Reports/Variations/Controller.php
  src/API/Reports/Variations/Stats/Controller.php
  src/API/SettingOptions.php
  src/API/Taxes.php
  src/API/Themes.php
Labels: status: ready to merge

#8426 Translate dates in NewSalesRecord note
  changelogs/update-8419-translate-dates-in-new-sales-record-note
  src-internal/Admin/Notes/NewSalesRecord.php
  tests/notes/class-wc-tests-newsalesrecord-note.php
Labels: status: ready to merge, Build

#8020 Suppress `lint:js` warnings in CI and GitHub PRs
  changelogs/fix-lint-js-types
  packages/admin-e2e-tests/CHANGELOG.md
  packages/admin-e2e-tests/src/elements/DropdownField.ts
  packages/admin-e2e-tests/src/elements/DropdownTypeaheadField.ts
  packages/admin-e2e-tests/src/elements/FormToggle.ts
  packages/admin-e2e-tests/src/elements/HelpMenu.ts
  packages/admin-e2e-tests/src/fixtures/options.ts
  packages/admin-e2e-tests/src/fixtures/orders.ts
  packages/admin-e2e-tests/src/pages/Analytics.ts
  packages/admin-e2e-tests/src/pages/AnalyticsOverview.ts
  packages/admin-e2e-tests/src/pages/BasePage.ts
  packages/admin-e2e-tests/src/pages/Coupons.ts
  packages/admin-e2e-tests/src/pages/Login.ts
  packages/admin-e2e-tests/src/pages/OnboardingWizard.ts
  packages/admin-e2e-tests/src/pages/PaymentsSetup.ts
  packages/admin-e2e-tests/src/pages/ProductsSetup.ts
  packages/admin-e2e-tests/src/pages/WcSettings.ts
  packages/admin-e2e-tests/src/pages/WpSettings.ts
  packages/admin-e2e-tests/src/sections/onboarding/BusinessSection.ts
  packages/admin-e2e-tests/src/sections/onboarding/IndustrySection.ts
  packages/admin-e2e-tests/src/sections/onboarding/ProductTypesSection.ts
  packages/admin-e2e-tests/src/sections/onboarding/StoreDetailsSection.ts
  packages/admin-e2e-tests/src/sections/onboarding/ThemeSection.ts
  packages/admin-e2e-tests/src/sections/payment-setup/BankAccountTransferSetup.ts
  packages/admin-e2e-tests/src/utils/actions.ts
Labels: type: technical debt

#8459 Refactor the `onFilterChange` method in the `AdvancedFilters` component
  packages/components/CHANGELOG.md
  packages/components/src/advanced-filters/attribute-filter.js
  packages/components/src/advanced-filters/date-filter.js
  packages/components/src/advanced-filters/index.js
  packages/components/src/advanced-filters/number-filter.js
  packages/components/src/advanced-filters/search-filter.js
  packages/components/src/advanced-filters/select-filter.js
  packages/components/src/advanced-filters/stories/index.js
Labels: @woocommerce/components, Packages, Components

#8488 Allow CLI environments to run the install routines
  src-internal/Admin/Install.php
Labels: priority: high

#8476 Update webpack 4 to webpack 5
  changelogs/dev-webpack5
  package.json
  packages/components/package.json
  packages/customer-effort-score/package.json
  packages/dependency-extraction-webpack-plugin/CHANGELOG.md
  packages/dependency-extraction-webpack-plugin/package.json
  packages/experimental/package.json
  packages/onboarding/package.json
  packages/style-build/index.js
  packages/style-build/package.json
  pnpm-lock.yaml
  storybook/.storybook/main.js
  storybook/webpack.config.js
  unminify.js
  webpack.config.js
Labels: tool: monorepo infrastructure, needs: author feedback, @woocommerce/components, Packages, Components, Build

#8493 Fix php notice when selecting paid theme
  changelogs/fix-8478_php_notice_purchase_task
  client/profile-wizard/steps/theme/index.js
  packages/admin-e2e-tests/src/pages/OnboardingWizard.ts
  packages/admin-e2e-tests/src/sections/onboarding/StoreDetailsSection.ts
  packages/admin-e2e-tests/src/sections/onboarding/ThemeSection.ts
  packages/admin-e2e-tests/src/specs/index.ts
  packages/admin-e2e-tests/src/specs/tasks/purchase.ts
  src-internal/Admin/Onboarding/OnboardingThemes.php
  src/Features/OnboardingTasks/Tasks/Purchase.php
  tests/features/onboarding-tasks/tasks/purchase.php
Labels: release: cherry-pick, Packages

#8497 Block Merges to main
  .github/workflows/block-merge-to-main.yml
Labels: needs changelog entry, Build
