Repository woocommerce/woocommerce-admin, pull requests merged in 2022-01, with the labels that each got.

#8100 Reset "install_timestamp" if it's not numeric to avoid TypeError
  changelogs/fix-7891-uncaught-typeError-int-string
  src/WCAdminHelper.php
  tests/wc-admin-helper.php
Labels: status: ready to merge

#8094 Skip opening the dropdown if the click event is from the error message
  changelogs/fix-7906-click-error-message-open-select-control
  packages/components/CHANGELOG.md
  packages/components/src/select-control/control.js
Labels: status: ready to merge, Packages, Components

#8099 OBW: Fix free extensions list isn't updated after store location or industry is changed
  changelogs/fix-8007-update-free-extensions-when-country-industry-changed
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/test/index.js
Labels: status: ready to merge

#8104 Activate promo note after WC Pay is activated
  changelogs/add-8067-activate-promo-note
  client/payments-welcome/index.tsx
  src/API/Notes.php
Labels: status: ready to merge

#8108 Fix CI php unit tests for woocommerce >= 6.0.0
  bin/ci/gh-install-wp-tests.sh
Labels: status: ready to merge, Build

#8105 Replace all docs.woocommerce.com links with woocommerce.com's
  changelogs/fix-8096-doc-links
  client/activity-panel/panels/help.js
  client/tasks/fills/tax/manual-configuration/configure.tsx
  docs/features/onboarding.md
  docs/woocommerce.com/activity-panels.md
  packages/components/src/dynamic-form/README.md
  readme.txt
  src/Marketing/InstalledExtensions.php
  src/Notes/AddFirstProduct.php
  src/Notes/AddingAndManangingProducts.php
  src/Notes/CustomizingProductCatalog.php
  src/Notes/FirstDownlaodableProduct.php
  src/Notes/ManageStoreActivityFromHomeScreen.php
  src/Notes/OrderMilestones.php
  src/Notes/UnsecuredReportFiles.php
Labels: status: ready to merge, Packages, Components

#8091 Add MailPoet to Installed marketing extensions
  changelogs/enhancement-8091-mailpoet-in-installed-extensions
  images/marketing/mailpoet.svg
  src/Marketing/InstalledExtensions.php
Labels: status: ready to merge

#8112 Truncate the site title with an ellipses on the second line
  changelogs/fix-8011-truncate-long-site-title
  client/navigation/components/header/index.js
  client/navigation/components/header/style.scss
Labels: status: ready to merge

#8113 Fix misaligned rows per page dropdown
  changelogs/fix-7863-misaligned-rows-per-page-dropdown
  packages/components/CHANGELOG.md
  packages/components/src/pagination/index.js
Labels: status: ready to merge, Packages, Components

#8114 Add resolution check to ensure setup-wizard redirection on homescreen is stable
  changelogs/fix-8029-ensure-redirect-to-setup-wizard-stably
  client/homescreen/index.tsx
Labels: status: ready to merge

#8117 Make use of the woocommerce_allow_marketplace_suggestions filter
  changelogs/add-wc-pay-promotion-allow-suggestion-filter
  src/Features/WcPayPromotion/Init.php
Labels: status: ready to merge, needs cherry picking

#8118 Adding changelogs from 3.0.2 release
  changelog.txt
Labels: status: ready to merge

#8122 Check if WC Pay is supported before adding gateway
  changelogs/fix-wcpay-promotion-non-supported-country
  src/Features/WcPayPromotion/Init.php
Labels: status: ready to merge

#8115 Use ExPlat to render the WC Pay menu conditionally
  src/Features/WcPayWelcomePage.php
Labels: status: ready to merge, feature: wcpay

#8121 Fix misaligned status column on orders report
  changelogs/fix-7623-misaligned-status-column-on-orders-report
  client/analytics/report/orders/style.scss
  client/analytics/report/orders/table.js
  packages/components/CHANGELOG.md
  packages/components/src/order-status/index.js
  packages/components/src/order-status/style.scss
Labels: status: needs review, Packages, Components

#8120 Fix variations table product filter
  changelogs/fix-7768-variations-table-filter
  client/analytics/report/variations/table.js
Labels: status: ready to merge

#8128 Fix storybook cannot resolve '@woocommerce/settings' error
  storybook/setting.mock.js
  storybook/webpack.config.js
Labels: status: ready to merge, Build

#8124 Enable wc-pay-welcome-page feature in the core config
  config/core.json
Labels: status: ready to merge

#8130 Update changelog with 3.0.3 changes
  changelog.txt
  changelogs/add-wc-pay-promotion-allow-suggestion-filter
  changelogs/fix-wcpay-promotion-non-supported-country
Labels: status: ready to merge

#8021 Improve Customers Sync Performance
  changelogs/fix-26452-customers-sync-performance
  src/API/Reports/Customers/DataStore.php
  src/API/Reports/Orders/Stats/DataStore.php
  src/Overrides/Order.php
  src/Overrides/OrderRefund.php
Labels: status: ready to merge, feature: analytics, category: performance

#8138 Fix duplicated back button with two-cols experiment
  client/homescreen/layout.js
  client/two-column-tasks/extended-task.tsx
Labels: status: ready to merge, needs feedback, needs cherry picking

#8139 Adding allowed plugins to composer configuration
  changelogs/update-composer-add-allow-plugins
  composer.json
Labels: status: ready to merge, Build, needs feedback

#8141 Fix PHP ExPlat warning
  includes/class-experimental-abtest.php
Labels: status: ready to merge

#8142 Change WCPay menu experiment check ordering
  src/Features/WcPayWelcomePage.php
Labels: status: ready to merge, needs changelog entry

#8143 Change WCPay menu experiment pageview track
  client/payments-welcome/index.tsx
Labels: status: ready to merge

#8083 Move WC Pay welcome page from wc-calypso-bridge
  changelogs/add-8064-add-wc-pay-welcome-screen
  changelogs/add-8067-activate-promo-note
  changelogs/add-8077-wcpay-payments-remind-me-later-note
  client/layout/controller.js
  client/payments-welcome/banner.tsx
  client/payments-welcome/cards/amex.js
  client/payments-welcome/cards/applepay.js
  client/payments-welcome/cards/cb.js
  client/payments-welcome/cards/diners.js
  client/payments-welcome/cards/discover.js
  client/payments-welcome/cards/gpay.js
  client/payments-welcome/cards/jcb.js
  client/payments-welcome/cards/maestro.js
  client/payments-welcome/cards/mastercard.js
  client/payments-welcome/cards/unionpay.js
  client/payments-welcome/cards/visa.js
  client/payments-welcome/exit-survey-modal.tsx
  client/payments-welcome/faq.tsx
  client/payments-welcome/flag.js
  client/payments-welcome/index.tsx
  client/payments-welcome/strings.tsx
  client/payments-welcome/style.scss
  config/core.json
  config/development.json
  config/plugin.json
  images/wc_pay_welcome_page/wcpay-banner.png
  includes/class-experimental-abtest.php
  src/API/Notes.php
  src/Events.php
  src/Features/WcPayWelcomePage.php
  src/Loader.php
  src/Notes/PaymentsRemindMeLater.php
Labels: status: ready to merge

#8151 Move WC Pay welcome page from wc-calypso-bridge
  changelogs/add-8064-add-wc-pay-welcome-screen
  changelogs/add-8067-activate-promo-note
  changelogs/add-8077-wcpay-payments-remind-me-later-note
  client/layout/controller.js
  client/payments-welcome/banner.tsx
  client/payments-welcome/cards/amex.js
  client/payments-welcome/cards/applepay.js
  client/payments-welcome/cards/cb.js
  client/payments-welcome/cards/diners.js
  client/payments-welcome/cards/discover.js
  client/payments-welcome/cards/gpay.js
  client/payments-welcome/cards/jcb.js
  client/payments-welcome/cards/maestro.js
  client/payments-welcome/cards/mastercard.js
  client/payments-welcome/cards/unionpay.js
  client/payments-welcome/cards/visa.js
  client/payments-welcome/exit-survey-modal.tsx
  client/payments-welcome/faq.tsx
  client/payments-welcome/flag.js
  client/payments-welcome/index.tsx
  client/payments-welcome/strings.tsx
  client/payments-welcome/style.scss
  config/core.json
  config/development.json
  config/plugin.json
  images/wc_pay_welcome_page/wcpay-banner.png
  includes/class-experimental-abtest.php
  src/API/Notes.php
  src/Events.php
  src/Features/WcPayWelcomePage.php
  src/Loader.php
  src/Notes/PaymentsRemindMeLater.php
Labels: status: ready to merge

#8133 Make sure WP_ENVIRONMENT_TYPE is defined before checking the value
  src/Schedulers/MailchimpScheduler.php
Labels: status: ready to merge, needs cherry picking

#8116 Add REST endpoint to retrieve address locales
  changelogs/update-7782
  src/API/DataCountries.php
Labels: status: ready to merge

#8145 Add Magento migration note
  changelogs/add-7971
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/MagentoMigration.php
Labels: status: ready to merge

#8148 OBW: Move newsletter signup checkbox inside the same Card as the rest of the Store Details form inputs.
  changelogs/fix-8033-obw-no-border-between-email-and-newsletter-checkbox
  client/profile-wizard/steps/store-details/index.js
Labels: status: ready to merge

#8137 Fix incorrectly selected column type in two-cols experiment
  client/two-column-tasks/extended-task.tsx
Labels: status: ready to merge, needs cherry picking

#8150 Fix marketing task not displaying on Atomic sites.
  changelogs/fix-8149
  src/RemoteInboxNotifications/RuleEvaluator.php
Labels: status: ready to merge, needs cherry picking

#8152 Make activity panel badges margin consistent
  changelogs/tweak-8035-activity-panel-badges-margin
  client/homescreen/style.scss
  client/inbox-panel/index.scss
  client/tasks/tasks.scss
Labels: status: ready to merge

#8153 Fix category report query returns invalid net sales
  TESTING-INSTRUCTIONS.md
  changelogs/fix-7710-overview-category-report-query-invalid-net-sales
  src/API/Reports/Categories/DataStore.php
Labels: status: ready to merge

#8119 Add countries data store
  changelogs/update-7782-data-store
  packages/data/src/countries/action-types.ts
  packages/data/src/countries/actions.ts
  packages/data/src/countries/constants.ts
  packages/data/src/countries/index.ts
  packages/data/src/countries/reducer.ts
  packages/data/src/countries/resolvers.ts
  packages/data/src/countries/selectors.ts
  packages/data/src/countries/types.ts
  packages/data/src/index.ts
Labels: status: ready to merge, Packages

#8166 Update changelog and testing instructions with 3.1.0-rc.1 release
  TESTING-INSTRUCTIONS.md
  changelog.txt
  changelogs/add-8064-add-wc-pay-welcome-screen
  changelogs/add-8067-activate-promo-note
  changelogs/add-8077-wcpay-payments-remind-me-later-note
  changelogs/fix-8149
Labels: status: ready to merge

#8123 Add localized validation to store address
  changelogs/update-7782-store-details
  client/dashboard/components/settings/general/store-address.tsx
  client/profile-wizard/steps/store-details/index.js
  client/tasks/fills/steps/location.js
  packages/data/src/countries/selectors.ts
Labels: status: ready to merge, Packages

#8169 Fix setup wizard free features checkbox re-check itself
  changelogs/fix-8163-setup-wizard-features-checkbox-recheck-itself
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
Labels: status: ready to merge, needs cherry picking

#8165 Fix shipping rate error message overlaps with the 'Proceed' button
  changelogs/fix-6389-shipping-error-message-overlaps
  client/tasks/fills/shipping/rates.js
Labels: status: ready to merge

#8162 Fix php unit test "test_deleted_coupons" for wc >= 6.1.0
  bin/install-wp-tests.sh
  tests/reports/class-wc-tests-reports-coupons.php
Labels: status: ready to merge, Build

#8181 Fix incorrect reader text generated for data points on charts table
  changelogs/fix-6255-screen-reader-text-on-chart-table
  packages/components/CHANGELOG.md
  packages/components/src/chart/d3chart/utils/line-chart.js
Labels: status: ready to merge, Packages, Components

#8179 Fix incorrectly displayed note created date
  changelogs/fix-2006-notes-time-zone
  packages/experimental/CHANGELOG.md
  packages/experimental/src/inbox-note/inbox-note.tsx
Labels: status: ready to merge, Packages

#8180 Fix get_automated_tax_supported_countries doesn't include UK
  changelogs/fix-5836-automated-tax-supported-countries-uk
  src/Features/OnboardingTasks/Tasks/Tax.php
Labels: status: ready to merge

#8182 Fix incorrect total count of downloads on the analytics download report
  changelogs/2022-01-17-08-56-31-701552
  src/API/Reports/Downloads/Stats/DataStore.php
Labels: status: ready to merge

#8081 OBW - Business Details - Consolidate selling options
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
Labels: status: ready to merge

#8178 Rename some constants
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/test/index.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/stock/index.js
  client/homescreen/activity-panel/stock/test/index.js
  client/homescreen/activity-panel/test/panels.js
Labels: status: ready to merge

#8187 Adding tooltip to describe the lack of refund deductions from revenue summaries
  changelogs/add-7997-add-tooltip
  client/analytics/components/report-summary/index.js
  client/analytics/report/revenue/config.js
  packages/components/src/summary/number.js
  packages/components/src/summary/style.scss
Labels: Packages, needs feedback, Components

#8185 Fix task ID class check and add tests around tracking
  changelogs/fix-8183
  src/Features/OnboardingTasks/TaskTraits.php
  tests/features/onboarding-tasks/task-list.php
  tests/features/onboarding-tasks/task.php
Labels: status: ready to merge, priority: high, needs cherry picking

#8189 Fix incorrect date options when the "Default Date Range" is set from Analytics settings
  changelogs/fix-7639-by-hour-option-not-displayed
  client/analytics/components/report-chart/index.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/index.js
  client/dashboard/store-performance/index.js
  packages/data/src/reports/utils.js
  packages/date/CHANGELOG.md
  packages/date/src/index.js
  packages/date/src/test/index.js
Labels: status: ready to merge, Packages

#8172 Hide store address fields in regions that specify hidden
  changelogs/add-store-address-hidden
  client/dashboard/components/settings/general/store-address.tsx
Labels: status: ready to merge

#8147 Change the reviews empty state panels logic
  changelogs/add-8074
  client/homescreen/activity-panel/index.js
  client/homescreen/activity-panel/orders/index.js
  client/homescreen/activity-panel/orders/test/index.js
  client/homescreen/activity-panel/panels.js
  client/homescreen/activity-panel/stock/index.js
  client/homescreen/activity-panel/stock/test/index.js
  client/homescreen/activity-panel/test/panels.js
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/admin-e2e-tests/src/utils/actions.ts
Labels: status: ready to merge, Packages, feature: home screen

#8193 Fix undefined derived_currency value for the track 'wcadmin_storeprofiler_store_details_continue'
  changelogs/fix-7569-undefined-currency-code
  client/profile-wizard/steps/store-details/index.js
Labels: status: ready to merge

#8129 Enhance report chart i18n support
  changelogs/enhancement-7827-report-i18n-translate
  client/analytics/components/report-chart/index.js
  client/analytics/components/report-chart/utils.js
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/date/src/index.js
  packages/date/src/test/index.js
Labels: status: ready to merge, Build, Packages

#8197 Updated frontend email validation to use @wordpress/url
  changelogs/fix-8155-improve-frontend-email-validation
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/store-details/test/__snapshots__/index.js.snap
  client/profile-wizard/steps/store-details/test/index.js
  package-lock.json
Labels: type: bug, status: ready to merge, has tests

#8171 Reduce padding around plugin list titles for marketing tools page.
  changelogs/fix-8164-padding-reduction-reach-out-to-customers
  client/tasks/fills/Marketing/PluginList.scss
Labels: status: ready to merge

#8168 Fix/7174 dismiss button alignment
  changelogs/fix-7174-dismiss-button-alignment
  client/tasks/tasks.scss
  packages/components/CHANGELOG.md
  packages/components/src/ellipsis-menu/style.scss
Labels: status: ready to merge, Packages, Components

#8203 Update readme.txt to update plugin's description in WordPress.org
  readme.txt
Labels: status: ready to merge

#8042 Add performance tracks to onboarding flow
  changelogs/add-7919_performance_tracks
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
  client/profile-wizard/steps/product-types/index.js
  client/tasks/fills/Marketing/index.tsx
  client/tasks/fills/PaymentGatewaySuggestions/components/List/Item.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/Suggestion.js
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  client/utils/index.js
  client/utils/plugins.ts
  packages/data/src/plugins/actions.ts
  src/API/Plugins.php
Labels: status: ready to merge, Packages

#8212 Update changelog with 3.1.0-rc.1 release
  changelog.txt
  changelogs/fix-8163-setup-wizard-features-checkbox-recheck-itself
  changelogs/fix-8183
Labels: status: ready to merge

#8214 Bump versions for multiple WooCommerce packages
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/explat/CHANGELOG.md
  packages/explat/package.json
Labels: status: ready to merge, Build, Packages, Components

#8173 Task List: Personalize your store / Import products - error message is not formatted correctly
  changelogs/fix-4314-import-products-error-message-formatting
  client/layout/transient-notices/snackbar/index.js
  client/tasks/fills/appearance.js
Labels: status: ready to merge

#8146 Add tasklist_payment_setup track for WooCommerce Payments
  changelogs/fix-7881_wcpay_setup_tracks
  client/tasks/fills/PaymentGatewaySuggestions/components/Action.js
  client/tasks/fills/PaymentGatewaySuggestions/components/List/Item.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/Suggestion.js
Labels: status: needs review

#8217 Bump version to 3.3.0-dev and sync changelog from 3.2.0-beta.1
  TESTING-INSTRUCTIONS.md
  changelog.txt
  changelogs/2022-01-17-08-56-31-701552
  changelogs/add-7919_performance_tracks
  changelogs/add-7971
  changelogs/add-7997-add-tooltip
  changelogs/add-8074
  changelogs/add-store-address-hidden
  changelogs/dev-wc-admin-settings
  changelogs/enhancement-7827-report-i18n-translate
  changelogs/enhancement-8091-mailpoet-in-installed-extensions
  changelogs/fix-2006-notes-time-zone
  changelogs/fix-26452-customers-sync-performance
  changelogs/fix-4314-import-products-error-message-formatting
  changelogs/fix-5836-automated-tax-supported-countries-uk
  changelogs/fix-6255-screen-reader-text-on-chart-table
  changelogs/fix-6389-shipping-error-message-overlaps
  changelogs/fix-7174-dismiss-button-alignment
  changelogs/fix-7569-undefined-currency-code
  changelogs/fix-7623-misaligned-status-column-on-orders-report
  changelogs/fix-7639-by-hour-option-not-displayed
  changelogs/fix-7710-overview-category-report-query-invalid-net-sales
  changelogs/fix-7768-variations-table-filter
  changelogs/fix-7863-misaligned-rows-per-page-dropdown
  changelogs/fix-7891-uncaught-typeError-int-string
  changelogs/fix-7906-click-error-message-open-select-control
  changelogs/fix-7907-disallow-white-space-platform-name-input
  changelogs/fix-8006-hide-header-if-no-plugin
  changelogs/fix-8007-update-free-extensions-when-country-industry-changed
  changelogs/fix-8011-truncate-long-site-title
  changelogs/fix-8029-ensure-redirect-to-setup-wizard-stably
  changelogs/fix-8033-obw-no-border-between-email-and-newsletter-checkbox
  changelogs/fix-8096-doc-links
  changelogs/fix-8155-improve-frontend-email-validation
  changelogs/fix-8164-padding-reduction-reach-out-to-customers
  changelogs/tweak-8035-activity-panel-badges-margin
  changelogs/update-7782
  changelogs/update-7782-data-store
  changelogs/update-7782-store-details
  changelogs/update-7923
  changelogs/update-composer-add-allow-plugins
  composer.json
  package.json
  readme.txt
  src/Composer/Package.php
  src/FeaturePlugin.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#8213 Fix Uncaught TypeError count(NULL) for php8+ in Marketing.php
  changelogs/fix-8211-marketing-overview-type-error
  src/Features/Marketing.php
Labels: status: ready to merge, needs cherry picking

#8201 Fix setup wizard title and flash of content
  changelogs/fix-6598
  client/layout/controller.js
  src/Features/Onboarding.php
Labels: status: ready to merge

#8222 fix: onboarding wizard checkmarks go missing sometimes
  changelogs/fix-8156-obw-checkmarks-go-missing
  packages/components/CHANGELOG.md
  packages/components/src/stepper/check-icon.js
Labels: status: ready to merge, Packages, Components

#8220 Replace mysql image with mariadb
  changelogs/update-docker-compose-mysql-for-arm64
  docker/wc-admin-php-test-suite/docker-compose.yml
  readme.txt
Labels: status: ready to merge

#8079 Add asynchronous plugin install and activation endpoints
  changelogs/update-as-plugin-install
  src/API/Plugins.php
  src/FeaturePlugin.php
  src/Notes/InstallJPAndWCSPlugins.php
  src/PluginsHelper.php
  tests/api/plugins.php
Labels: status: ready to merge

#8186 Fix distorted Country/Region label at some zoom levels
  changelogs/fix-7893-country-input-label-distorted
  packages/components/CHANGELOG.md
  packages/components/src/select-control/style.scss
Labels: status: ready to merge, Packages, Components
