Repository woocommerce/woocommerce-admin, pull requests merged in 2022-02, with the labels that each got.

#8231 Make ExPlat request URL args filterable
  changelogs/update-8227-add-install-timestamp-to-explat
  includes/class-experimental-abtest.php
  packages/explat/CHANGELOG.md
  packages/explat/jest.config.json
  packages/explat/package.json
  packages/explat/src/assignment.ts
  packages/explat/src/test/assignment-test.js
  tests/includes/class-experimental-abtest-test.php
Labels: status: ready to merge, has tests, Build, Packages

#8238 Reintroduce CES
  changelogs/update-8170-reintroduce-the-ces
  src/Features/CustomerEffortScoreTracks.php
Labels: status: ready to merge

#8219 Dev/e2e reset
  changelogs/dev-e2e-reset
  package-lock.json
  package.json
  packages/admin-e2e-tests/package.json
  packages/admin-e2e-tests/src/fixtures/action-scheduler.ts
  packages/admin-e2e-tests/src/fixtures/index.ts
  packages/admin-e2e-tests/src/fixtures/plugins.ts
  packages/admin-e2e-tests/src/fixtures/reset.ts
  packages/admin-e2e-tests/src/pages/AnalyticsOverview.ts
  packages/admin-e2e-tests/src/specs/activate-and-setup/complete-onboarding-wizard.ts
  packages/admin-e2e-tests/src/specs/homescreen/activity-panel.ts
  packages/admin-e2e-tests/src/specs/homescreen/task-list.ts
  packages/admin-e2e-tests/src/utils/actions.ts
  tests/e2e/config/default.json
  tests/e2e/docker/initialize.sh
Labels: status: ready to merge, Build, Packages

#8243 Update changelog from the 3.2.0 beta 2 release
  changelog.txt
  changelogs/add-8198-include-square-in-spain
  changelogs/fix-7881_wcpay_setup_tracks
  changelogs/fix-8211-marketing-overview-type-error
  changelogs/fix-8225-country-region-not-preserved
  changelogs/update-8227-add-install-timestamp-to-explat
Labels: status: ready to merge

#8247 Add additional testing instructions for 3.2 release
  TESTING-INSTRUCTIONS.md
Labels: status: ready to merge, needs cherry picking

#8202 Avoid `get_notes` call in `CouponPageMoved`
  changelogs/fix-7986-avoid-get_notes-in-CouponPageMoved
  src/Notes/CouponPageMoved.php
  src/Notes/Notes.php
Labels: status: ready to merge

#8256 Add support for filtering by changelog type for testing instructions
  bin/changelogger/WCAdminFormatter.php
  bin/test-instruction-logger/README.md
  bin/test-instruction-logger/WriteCommand.php
  changelogs/update-testing-instructions-script
Labels: status: ready to merge, Build

#8235 Only add product data on REST requests and task list
  changelogs/fix-7884
  src/API/OnboardingProductTypes.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks/Tasks/Purchase.php
Labels: status: ready to merge

#8234 Remove unused task styling classes
  changelogs/fix-7693
  client/inbox-panel/dismiss-all-modal.js
  client/inbox-panel/index.js
  client/profile-wizard/index.js
  client/two-column-tasks/dismiss-modal.js
  client/two-column-tasks/index.js
  client/two-column-tasks/style.scss
  client/two-column-tasks/task-list.js
Labels: status: ready to merge

#8233 Update headercard to use filter to add ExPlat parameter
  changelogs/update-8227-add-headercard-experiment-hook
  client/homescreen/constants.js
  client/homescreen/hooks/test/use-headercard-experiment-hook.test.js
  client/homescreen/hooks/use-headercard-experiment-hook.js
  client/homescreen/layout.js
  client/two-column-tasks/extended-task.tsx
  client/two-column-tasks/headers/appearance.js
  client/two-column-tasks/headers/marketing.js
  client/two-column-tasks/headers/products.js
  client/two-column-tasks/headers/shipping.js
  client/two-column-tasks/headers/tax.js
  client/two-column-tasks/headers/woocommerce-payments.js
  src/Features/Homescreen.php
Labels: status: ready to merge

#8255 Fix/8191 deleting products adds blank space to analytics data
  changelogs/fix-8191-deleting-products-adds-blank-space-to-analytics-data
  client/analytics/report/variations/table.js
  src/API/Reports/Variations/DataStore.php
Labels: status: ready to merge

#8260 Fix shipping task step when store location isn't filled out
  changelogs/fix-8239_shipping_task
  client/tasks/fills/shipping/index.js
Labels: status: ready to merge, needs cherry picking

#8250 Make sure hidden fields are cleared when definition changes
  client/dashboard/components/settings/general/store-address.tsx
Labels: status: ready to merge, needs cherry picking

#8263 Made email in OBW optional again
  changelogs/fix-optional-email
  client/profile-wizard/steps/store-details/index.js
  client/profile-wizard/steps/store-details/test/index.js
Labels: status: ready to merge, needs cherry picking

#8265 Add business-details step complete track
  changelogs/add-7919_business_details_track
  client/profile-wizard/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/style.scss
  client/profile-wizard/steps/business-details/style.scss
Labels: needs feedback, needs cherry picking

#8279 Fix minor process issues
  client/marketing/coupons/index.js
  client/marketing/overview/index.js
  src/API/Marketing.php
  src/API/NavigationFavorites.php
  src/API/OnboardingThemes.php
  src/API/Options.php
  src/API/Reports/DataStore.php
  src/API/Taxes.php
  src/Features/Homescreen.php
  src/Features/Navigation/Favorites.php
  src/Features/Navigation/Menu.php
  src/Features/Onboarding.php
  src/Features/OnboardingTasks/TaskLists.php
  src/PageController.php
  tests/navigation/class-wc-favorites.php
Labels: status: ready to merge, needs changelog entry

#8262 Replace "any" type with an explicit type
  client/dashboard/components/settings/general/store-address.tsx
  client/utils/types.ts
Labels: status: ready to merge, needs feedback

#8232 Fix payments extensions displayed below the offline payments options
  changelogs/fix-8230-display-offline-payment-options-below
  client/tasks/fills/PaymentGatewaySuggestions/index.js
  client/tasks/fills/PaymentGatewaySuggestions/test/index.js
Labels: status: ready to merge, has tests

#8285 Fix a lot of pending "run_remote_notifications" scheduled actions
  changelogs/fix-pending-run-remote-notifications-actions
  src/RemoteInboxNotifications/StoredStateSetupForProducts.php
Labels: status: ready to merge

#8282 Enable type definitions output for @woocommerce/components
  .gitignore
  changelogs/enhancement-8282-enable-typedefs-woocommerce-components
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/tsconfig.json
  packages/tsconfig.json
Labels: status: ready to merge, Build, Packages, Components

#8290 Add wc_version to store profiler view and complete tracks
  changelogs/add-7919_wc_version_to_storeprofiler_tracks
  client/profile-wizard/index.js
  client/profile-wizard/steps/business-details/flows/selective-bundle/index.js
Labels: status: ready to merge, needs cherry picking

#8004 Add hook reference generator README and documentation
  .eslintrc.js
  bin/hook-reference/README.md
  bin/hook-reference/data.js
  bin/hook-reference/data.json
  changelogs/add-hook-reference-readme
  client/activity-panel/panels/help.js
  client/analytics/components/report-table/index.js
  client/analytics/report/categories/config.js
  client/analytics/report/coupons/config.js
  client/analytics/report/customers/config.js
  client/analytics/report/downloads/config.js
  client/analytics/report/get-reports.js
  client/analytics/report/index.js
  client/analytics/report/orders/config.js
  client/analytics/report/products/config.js
  client/analytics/report/revenue/config.js
  client/analytics/report/stock/config.js
  client/analytics/report/taxes/config.js
  client/analytics/report/variations/config.js
  client/analytics/settings/config.js
  client/analytics/settings/historical-data/status.js
  client/dashboard/customizable.js
  client/dashboard/dashboard-charts/config.js
  client/dashboard/default-sections.js
  client/embedded-body-layout/embedded-body-layout.tsx
  client/header/utils.js
  client/homescreen/stats-overview/defaults.js
  client/layout/controller.js
  client/layout/transient-notices/index.js
  client/lib/currency-context.js
  client/navigation/components/container/primary-menu.js
  client/profile-wizard/index.js
  client/store-management-links/index.js
  client/tasks/fills/products/product-template-modal.js
  packages/data/src/navigation/selectors.js
  packages/data/src/onboarding/deprecated-tasks.js
  packages/navigation/src/index.js
  packages/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js
  packages/onboarding/src/components/WooOnboardingTaskListItem/WooOnboardingTaskListItem.js
  packages/onboarding/src/components/WooPaymentGatewayConfigure/WooPaymentGatewayConfigure.js
  packages/onboarding/src/components/WooPaymentGatewaySetup/WooPaymentGatewaySetup.js
Labels: status: needs review, Build, Packages

#8293 Jetpack Backup note - change time range and add an image
  changelogs/update-jetpack-note-update-date-add-image
  images/admin_notes/marketing-jetpack-2x.png
  src/Notes/MarketingJetpack.php
Labels: status: ready to merge

#8306 Added tracks test for PaymentGatewaySuggestions
  changelogs/dev-add-tracks-test-payment
  client/tasks/fills/PaymentGatewaySuggestions/test/index.js
Labels: status: ready to merge

#8311 Make src/Features/RemoteFreeExtensions/* internal
  src-internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php
  src-internal/Admin/RemoteFreeExtensions/EvaluateExtension.php
  src-internal/Admin/RemoteFreeExtensions/Init.php
  src-internal/Admin/RemoteFreeExtensions/RemoteFreeExtensionsDataSourcePoller.php
  src/API/OnboardingFreeExtensions.php
  src/Features/Features.php
  src/Features/OnboardingTasks/Tasks/Marketing.php
Labels: status: ready to merge

#8296 Fix WCPay in core texts and promo slug
  changelogs/fix-wcpay-experiment-fix-text-and-promo-slug
  client/payments-welcome/index.tsx
  client/payments-welcome/strings.tsx
  src/API/Notes.php
  src/Notes/PaymentsRemindMeLater.php
Labels: status: ready to merge, needs cherry picking

#8307 Move src/Features/WcPayPromotion to /src-internal/Admin/WcPayPromotion
  bin/make-zip.sh
  composer.json
  phpcs.xml.dist
  src-internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php
  src-internal/Admin/RemoteFreeExtensions/EvaluateExtension.php
  src-internal/Admin/RemoteFreeExtensions/Init.php
  src-internal/Admin/RemoteFreeExtensions/RemoteFreeExtensionsDataSourcePoller.php
  src-internal/Admin/WCPayPromotion/Init.php
  src-internal/Admin/WCPayPromotion/WCPayPromotionDataSourcePoller.php
  src-internal/Admin/WCPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php
  src/API/OnboardingFreeExtensions.php
  src/Features/Features.php
  src/Features/OnboardingTasks/Tasks/Marketing.php
Labels: status: ready to merge, Build

#8319 Small change to WCPay welcome page banner
  client/payments-welcome/strings.tsx
Labels: status: ready to merge, needs cherry picking

#8304 Refactor `MerchantEmailNotifications`
  changelogs/dev-8275
  src-internal/Admin/Notes/MerchantEmailNotifications.php
  src/Events.php
  src/FeaturePlugin.php
  src/Notes/EmailNotification.php
  tests/notes/class-wc-tests-email-notes.php
Labels: status: ready to merge

#8316 Move src/Schedulers/* to src-internal/Admin/Schedulers
  src-internal/Admin/Schedulers/CustomersScheduler.php
  src-internal/Admin/Schedulers/ImportInterface.php
  src-internal/Admin/Schedulers/ImportScheduler.php
  src-internal/Admin/Schedulers/MailchimpScheduler.php
  src-internal/Admin/Schedulers/OrdersScheduler.php
  src/Events.php
  src/Features/Onboarding.php
  src/ReportsSync.php
  tests/api-init.php
  tests/api/onboarding-profile.php
  tests/batch-queue.php
  tests/schedulers/class-wc-tests-mailchimp-scheduler.php
Labels: status: ready to merge, Build

#8317 Make classes in src internal
  includes/wc-admin-update-functions.php
  src-internal/Admin/CategoryLookup.php
  src-internal/Admin/Events.php
  src-internal/Admin/FeaturePlugin.php
  src-internal/Admin/Install.php
  src-internal/Admin/Survey.php
  src-internal/Admin/WCAdminSharedSettings.php
  src/Composer/Package.php
  src/Features/Navigation/Init.php
  src/Features/OnboardingTasks/DeprecatedOptions.php
  src/Loader.php
  src/Notes/GivingFeedbackNotes.php
  tests/api/reports-categories.php
  tests/bootstrap.php
  tests/category-lookup.php
  tests/framework/helpers/class-wc-helper-reports.php
  tests/install.php
  tests/plugin-version.php
  uninstall.php
  woocommerce-admin.php
Labels: status: ready to merge, Build

#8333 Packages: Bump versions for release
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/currency/CHANGELOG.md
  packages/currency/package.json
  packages/customer-effort-score/CHANGELOG.md
  packages/customer-effort-score/package.json
  packages/data/CHANGELOG.md
  packages/data/package.json
  packages/date/CHANGELOG.md
  packages/date/package.json
  packages/experimental/CHANGELOG.md
  packages/experimental/package.json
  packages/explat/CHANGELOG.md
  packages/explat/package.json
  packages/navigation/CHANGELOG.md
  packages/navigation/package.json
  packages/notices/CHANGELOG.md
  packages/notices/package.json
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: status: ready to merge, Build, Packages, Components

#8334 Add build-types to .eslintignore
  .eslintignore
Labels: Build

#8330 Fix Google Listings plugin is always shown in free features despite already activated
  changelogs/fix-8327-google-listings-plugin-is-always-shown-in-free-features
  src-internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php
Labels: status: ready to merge

#8318 Make src/Features/* internal except for Features.php, Onboarding.php and TransientNotices.php
  src-internal/Admin/ActivityPanels.php
  src-internal/Admin/Analytics.php
  src-internal/Admin/Coupons.php
  src-internal/Admin/CouponsMovedTrait.php
  src-internal/Admin/CustomerEffortScoreTracks.php
  src-internal/Admin/Homescreen.php
  src-internal/Admin/Marketing.php
  src-internal/Admin/MobileAppBanner.php
  src-internal/Admin/RemoteInboxNotifications.php
  src-internal/Admin/Settings.php
  src-internal/Admin/ShippingLabelBanner.php
  src-internal/Admin/ShippingLabelBannerDisplayRules.php
  src-internal/Admin/WcPayWelcomePage.php
  src/API/Marketing.php
  src/API/Options.php
  src/Features/Features.php
  src/Features/Navigation/CoreMenu.php
  src/Notes/CouponPageMoved.php
  tests/features/class-wc-tests-ces-tracks.php
  tests/features/class-wc-tests-shipping-label-banner-display-rules.php
Labels: status: ready to merge

#8258 Increase chart selection to 10 and allow color overriding
  TESTING-INSTRUCTIONS.md
  changelogs/add-chart-color-filter
  changelogs/update-increase-chart-selection-to-10
  packages/components/src/chart/README.md
  packages/components/src/chart/constants.js
  packages/components/src/chart/d3chart/legend.scss
  packages/components/src/chart/d3chart/utils/color.js
  packages/components/src/chart/stories/index.js
Labels: status: ready to merge, Packages, Components

#8308 Use WC_VERSION as cache buster for assets
  changelogs/update-8294-use-wc-version-as-cache-buster
  src/Features/OnboardingTasks/Tasks/Appearance.php
  src/Features/OnboardingTasks/Tasks/Products.php
  src/Features/OnboardingTasks/Tasks/Tax.php
  src/Loader.php
Labels: status: ready to merge

#8338 Replace deprecated wp.compose.withState with wp.element.useState
  packages/components/CHANGELOG.md
  packages/components/src/calendar/stories/date-picker.js
  packages/components/src/calendar/stories/date-range.js
  packages/components/src/ellipsis-menu/stories/index.js
  packages/components/src/image-upload/stories/index.js
  packages/components/src/search-list-control/index.js
  packages/components/src/search-list-control/stories/index.js
  packages/components/src/search-list-control/test/index.js
  packages/components/src/search/stories/index.js
  packages/components/src/segmented-selection/stories/index.js
  packages/components/src/select-control/stories/index.js
  packages/components/src/stepper/stories/index.js
  packages/components/src/table/stories/table-card.js
  packages/components/src/tag/index.js
  packages/components/src/tag/test/index.js
  packages/components/src/text-control-with-affixes/stories/index.js
  packages/components/src/text-control/stories/index.js
Labels: status: ready to merge, Packages, Components

#8342 Implement MailChimp API request threshold for MailchimpScheduler
  changelogs/fix-8322-mailchimp-too-many-request
  src-internal/Admin/Schedulers/MailchimpScheduler.php
  src/Features/Onboarding.php
  tests/api/onboarding-profile.php
  tests/schedulers/class-wc-tests-mailchimp-scheduler.php
Labels: status: ready to merge, has tests

#8184 Fix Notice in RuleEvaluator
  src/RemoteInboxNotifications/RuleEvaluator.php
Labels: needs feedback

#8347 Updated changelog from 3.2.0 release
  changelog.txt
  changelogs/add-7919_wc_version_to_storeprofiler_tracks
  changelogs/fix-8251_wc_pay_task_list_logic
  changelogs/fix-8320_subscription_should_be_hidden_with_cbd_industry
  changelogs/fix-wcpay-experiment-fix-text-and-promo-slug
Labels: status: ready to merge

#8371 Make $customer_id public again
  src/Overrides/Order.php
  src/Overrides/OrderRefund.php
Labels: status: ready to merge

#8328 Fix hidden notes in `admin/notes` when the user is not in tasklist experiment
  changelogs/fix-admin_notes_tasklist_experiment
  src/API/Notes.php
  src/Notes/DataStore.php
  tests/api/admin-notes.php
  tests/framework/helpers/class-wc-helper-admin-notes.php
Labels: status: ready to merge

#8366 Update WooCommerce Payment note action callback logic
  src/Notes/Note.php
  src/Notes/WooCommercePayments.php
Labels: status: ready to merge

#8378 Add missing dependency to onboarding package
  packages/onboarding/CHANGELOG.md
  packages/onboarding/package.json
Labels: status: ready to merge, Build, Packages

#8324 OBW: fix copy on Business Details when "WooCommerce Shipping" is not listed
  changelogs/fix-6860
  client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js
  client/profile-wizard/steps/business-details/test/index.js
Labels: status: ready to merge

#8384 Only run the version check for an admin request
  src-internal/Admin/Install.php
Labels: status: ready to merge

#8376 Remove inbox_action_click event from onclick event
  client/inbox-panel/index.js
Labels: status: ready to merge

#8367 Redirect to the WC Pay onboarding when WC Pay is installed
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/Suggestion.js
  client/tasks/fills/PaymentGatewaySuggestions/components/WCPay/utils.js
Labels: status: ready to merge

#8379 Remove unused data endpoints param
  changelogs/fix-8373_dataendpoints_wc_v3_settings
  src/Loader.php
Labels: status: ready to merge
